src/carriers/portmonitor_carrier/examples/simple_qos/qos.lua, src/libYARP_OS/include/yarp/os/OutputStream.h, src/libYARP_OS/include/yarp/os/RateThread.h, src/libYARP_OS/include/yarp/os/impl/DgramTwoWayStream.h, src/libYARP_OS/include/yarp/os/impl/PortCore.h, src/libYARP_OS/include/yarp/os/impl/PortCoreOutputUnit.h, src/libYARP_OS/include/yarp/os/impl/SocketTwoWayStream.h, src/libYARP_OS/src/DgramTwoWayStream.cpp, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/RateThread.cpp, src/libYARP_OS/src/SocketTwoWayStream.cpp
=> qos for yarp

conf/CMakeLists.txt
Fix https://github.com/robotology/icub-main/issues/86
=> [cmake] Properly install YarpPluginPath.cmake

bindings/yarp.i
=> A[C# bindings] Add ImageMono16 and PixelMono16 stuff

src/libYARP_dev/include/yarp/dev/DataSource.h
This PR adds statistics on acquisition rate, it helps debugging recent glitches in framegrabber acquisition rate.
@apaikan
=> added acquisition statistics and report for framegrabber

src/libYARP_dev/include/yarp/dev/CanBusInterface.h, src/libYARP_dev/include/yarp/dev/IControlLimits2Impl.h, src/libYARP_dev/include/yarp/dev/IInteractionModeImpl.h, src/libYARP_dev/include/yarp/dev/IVelocityControl2Impl.h, src/libYARP_dev/include/yarp/dev/ServerSoundGrabber.h, src/libYARP_dev/src/ControlBoardInterfacesImpl.cpp, src/libYARP_dev/src/ControlCalibrationImpl.cpp, src/libYARP_dev/src/IPositionControl2Impl.cpp, src/libYARP_dev/src/IPositionDirectImpl.cpp, src/libYARP_dev/src/ServerControlBoard.cpp, src/libYARP_dev/src/ServerFrameGrabber.cpp, src/libYARP_dev/src/ServerSerial.cpp, src/libYARP_dev/src/modules/AnalogSensorClient/AnalogSensorClient.cpp, src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/modules/ControlBoardWrapper/RPCMessagesParser.cpp, src/libYARP_dev/src/modules/RemoteControlBoard/RemoteControlBoard.cpp, src/libYARP_dev/src/modules/ServerInertial/ServerInertial.cpp, src/modules/serial/SerialDeviceDriver.cpp, src/yarpdatadumper/main.cpp, src/yarpdataplayer-qt/src/mainwindow.cpp, src/yarphear/yarphear.cpp
tested with win32 msvc12, using Travis CI  to check for typos on different target platforms
=> removed some printfs, replaced with proper logging functions

doc/yarpmanager.dox, src/libYARP_manager/include/yarp/manager/broker.h, src/libYARP_manager/include/yarp/manager/localbroker.h, src/libYARP_manager/src/localbroker.cpp, src/yarpmanager-gtk/application_window.cpp, src/yarpmanager-qt/applicationviewwidget.cpp
This PR adds support to create process that start visible, invisible, or minimized. Implemented for Windows with localhost. Useful for console applications.
Examples:
\<display>--minimized\</display> 
\<display>--hidden\</display> 
...
=> Console with localbroker

src/libYARP_OS/include/yarp/os/Network.h, src/libYARP_OS/include/yarp/os/OutputStream.h, src/libYARP_OS/include/yarp/os/impl/DgramTwoWayStream.h, src/libYARP_OS/include/yarp/os/impl/PortCore.h, src/libYARP_OS/include/yarp/os/impl/SocketTwoWayStream.h, src/libYARP_OS/src/DgramTwoWayStream.cpp, src/libYARP_OS/src/Network.cpp, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/SocketTwoWayStream.cpp
Here is the example: 
```c++
getConnectionQos(src, dest, srcStyle, desStlye)
```
=> implements getConnectionQos to returns the actual QoS configuration of a connection 

src/libYARP_OS/src/Property.cpp, tests/libYARP_OS/PropertyTest.cpp
A group in a ini was not correctly saved if it was closed by a `[include ...]` statement. 
This PR introduces a regression test and a fix. 
Fixes issue https://github.com/robotology/yarp/issues/459 .
=> Fix issue #459

src/libYARP_OS/src/NetworkClock.cpp
=> Fixed memory access in NetworkClock

src/libYARP_dev/include/yarp/dev/ControlBoardHelper.h, src/libYARP_dev/include/yarp/dev/ControlBoardInterfaces.h, src/libYARP_dev/include/yarp/dev/ControlBoardInterfacesImpl.inl, src/libYARP_dev/include/yarp/dev/ImplementControlBoardInterfaces.h, src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.h, src/libYARP_dev/src/modules/ControlBoardWrapper/RPCMessagesParser.cpp, src/libYARP_dev/src/modules/ControlBoardWrapper/RPCMessagesParser.h, src/libYARP_dev/src/modules/RemoteControlBoard/RemoteControlBoard.cpp, src/modules/fakeMotionControl/fakeMotionControl.cpp, src/modules/fakeMotionControl/fakeMotionControl.h, src/modules/fakeMotionControl/fakeMotionControl.ini
new methods for iAmplifier interface:
* getNominalCurrent
* setPeakCurrent
* getPWM
* getPWMLimit
* getPowerSupplyVoltage
=> Update Iamplifier interface

src/carriers/portmonitor_carrier/CMakeLists.txt, src/carriers/portmonitor_carrier/MonitorBinding.cpp, src/carriers/portmonitor_carrier/lua/MonitorLua.cpp
@drdanz would you please check? :p
=> build the portmonitor DLL plugin even if lua is not installed

tests/libYARP_math/MathTest.cpp
Unit tests on [libYarp_math](http://yarp.it/Math_8h.html) are completed.
All tests are passed, except for the one about [eigenValues()](http://yarp.it/namespaceyarp_1_1math.html#a4b03c7c2ba2459d811789ede54306bfc).
=> [tests] Complete tests on libYarp_math()

src/libYARP_OS/include/yarp/os/SystemInfo.h, tests/libYARP_OS/SystemInfoTest.cpp, tests/libYARP_OS/TestList.h
Added a test for the _SystemInfo_ class (has 0% coverage according to coveralls.io) of libYARP_OS.
Corrected a typo in the SystemInfo.h doc.
=> [Test] libYARP_OS

src/libYARP_OS/src/ThreadImpl.cpp
=> YARP_OS: fix race condition in setting thread id

tests/libYARP_OS/EventTest.cpp
Test pull request to check coveralls integration.
Please do not merge.
=> [tests] Improve EventTest

doc/changes.dox, doc/cmd_yarp.dox, src/libYARP_OS/include/yarp/os/ResourceFinder.h, src/libYARP_OS/src/Companion.cpp, src/libYARP_OS/src/ResourceFinder.cpp
fixed "yarp resource" command
@pattacini not sure why I can create the PR.
=> RF::configure() extended with third optional param

scripts/admin/generate-cmake-options.sh, src/libYARP_dev/CMakeLists.txt, src/libYARP_dev/src/Drivers.cpp, src/libYARP_dev/src/PopulateDrivers.cpp, src/libYARP_dev/src/modules/ControlBoardRemapper/ControlBoardRemapper.cpp, src/libYARP_dev/src/modules/ControlBoardRemapper/ControlBoardRemapper.h, src/libYARP_dev/src/modules/ControlBoardRemapper/ControlBoardRemapperHelpers.cpp, src/libYARP_dev/src/modules/ControlBoardRemapper/ControlBoardRemapperHelpers.h, src/modules/fakeMotionControl/fakeMotionControl.cpp, src/modules/fakeMotionControl/fakeMotionControl.h, tests/CMakeLists.txt, tests/YarpBuildLocation.h.in, tests/libYARP_dev/ControlBoardRemapperTest.cpp, tests/libYARP_dev/TestList.h, tests/libYARP_dev/harness.cpp
3rd take on actually doing the PR, after https://github.com/robotology/yarp/pull/746 and https://github.com/robotology/yarp/pull/757 .
=> Control board remapper

src/libYARP_OS/src/Network.cpp, src/libYARP_OS/src/PortCore.cpp, src/libYARP_manager/include/yarp/manager/broker.h, src/libYARP_manager/include/yarp/manager/localbroker.h, src/libYARP_manager/include/yarp/manager/yarpbroker.h, src/libYARP_manager/src/execstate.cpp, src/libYARP_manager/src/executable.cpp, src/libYARP_manager/src/localbroker.cpp, src/libYARP_manager/src/manager.cpp, src/libYARP_manager/src/yarpbroker.cpp
See #736
<a href='https://www.codereviewhub.com/robotology/yarp/pull/760?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/760'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix some issues with yarp connections and yarpmanager

src/yarpmanager++/src-builder/arrow.cpp, src/yarpmanager++/src-builder/builderitem.cpp, src/yarpmanager++/src-builder/builderitem.h, src/yarpmanager++/src-builder/builderwindow.cpp, src/yarpmanager++/src-builder/propertiestable.cpp, src/yarpmanager++/src-builder/propertiestable.h
fixed #761
fixed #751
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/drdanz%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/764%23issuecomment-220599652%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-05-20T13%3A03%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/robotology …
=> fixed #761

.travis.yml
<a href='https://www.codereviewhub.com/robotology/yarp/pull/765?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/765'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> .travis.yml: Enable ccache

src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/modules/ControlBoardWrapper/SubDevice.cpp
Fix errors on ROS topic message, in particular:
- measurement unit for linear joints: They were converted into radiants by mistake. Fixed
- timeStamps fot joint message: now uses time from getEncoderTime. This fixes issue on ROS TF while using Gazebo simulator. In this case both YARP & ROS clock plugin have to be instantiated.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/barbalberto%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4061020%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/drdanz%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/7 …
=> Fix cbw2 ros topic

conf/StandardFindModule.cmake, src/modules/opencv/CMakeLists.txt
<a href='https://www.codereviewhub.com/robotology/yarp/pull/766?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/766'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix warnings

src/modules/laserHokuyo/laserHokuyo.cpp
This commit fixes a critical bug preventing laserHokuyo module to operate correctly
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/771%23issuecomment-221815471%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/771%23issuecomment-221815471%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22One%20of%20the%20AppVeyor%20faiiled%20for%20some%20issues%20with%20%60git%20clone%60%2C%20since%20the%20other%20AppVeyor%20build%20succeeded%20I%27m%20abusing%20my%20administrator%20privileges%20and%20merging%20this%20anyway...%22%2C%20%22created_at%22%3A%20%222016-05-26T08%3A57%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.gi …
=> critical bugfix for laserHokuyo

src/libYARP_dev/src/modules/AnalogSensorClient/AnalogSensorClient.cpp, src/libYARP_dev/src/modules/AnalogSensorClient/AnalogSensorClient.h
It is a documentation bugfix, so I think it is ok to merge it in master.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/776%23issuecomment-222073172%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/776%23issuecomment-222073172%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222016-05-27T06%3A50%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4061020%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/barbalberto%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img …
=> [libYARP_dev] Fix AnalogSensorClient documentation, as period is not used at all.

src/libYARP_OS/include/yarp/os/impl/PlatformThread.h
Can any apple user (ping @traversaro @francesco-romano) test it and confirm that it works, or at least that it builds and that the tests pass?
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/792%23issuecomment-224332672%22%2C%20%22https%3A//github.com/robotology/yarp/pull/792%23issuecomment-224372809%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/792%23issuecomment-224332672%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%7E%7E%7E%5Cr%5Cn100%25%20tests%20passed%2C%200%20tests%20failed%20out%20of%2052%5Cr%5Cn%7E%7E%7E%22%2C%20%22created_at%22%3A%20%222016-06-07T16%3A16%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A/ …
=> YARP_OS: Fix PlatformThread for OSX, no ACE, no c++11

doc/installation/install_windows.dox, doc/installation/installation_downloads.dox
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/796%23issuecomment-225198027%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/796%23issuecomment-225198027%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Appveyor%20is%20failing%20because%20for%20some%20inexplicable%20reasons%20it%20is%20building%20on%20paulfitz/yarp%20instead%20of%20robotology/yarp.%5Cr%5CnActually%20there%20are%202%20different%20webhooks%2C%20but%20I%20have%20no%20idea%20which%20one%20is%20which%2C%20I%20disabled%20one%2C%20we%27ll%20see.%5Cr%5CnAnyway%2C%20this%20is%20not%20related%20to%20the%20patch...%20merging%20thanks.%22%2C%20%22created_at%22%3A%20%222016-06-10T14% …
=> [doc] Polish windows installation tutorial

doc/release/v2_3_66_1.md, src/yarpscope-qt/CMakeLists.txt, src/yarpscope-qt/plugin/CMakeLists.txt, src/yarpscope-qt/src/CMakeLists.txt, src/yarpview-qt/CMakeLists.txt, src/yarpview-qt/plugin/CMakeLists.txt, src/yarpview-qt/src/CMakeLists.txt
Embedded in .app bundle plugins' .so and qmldir file
Fixes #457 
Thanks @drdanz
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/806%23issuecomment-227195156%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/806%23issuecomment-227195156%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22cc%20%40claudiofantacci%20%20%40vtikha%20%22%2C%20%22created_at%22%3A%20%222016-06-20T16%3A30%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2189180%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/francesco-romano%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a …
=> Fixed macOS .app bundle for YARPView and YARPScope

src/libYARP_OS/src/SharedLibrary.cpp, src/libYARP_dev/src/TorqueControlImpl.cpp
<a href='https://www.codereviewhub.com/robotology/yarp/pull/816?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/816'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix some memory leaks

doc/yarpscope.dox
Hi all, this is a small yarpscope documentation fix. Before merging, please confirm that the first point of https://github.com/robotology/yarp/issues/812 is correct.
I based the PR on the master branch because it's documentation, let me know if that is the correct procedure.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/pattacini%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/813%23issuecomment-229489846%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-06-29T21%3A10%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_ur …
=> yarpscope min/max param documentation fix

src/yarpscope-qt/plugin/xmlloader.cpp
Fixes #812
cc @gsaponaro
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/819%23issuecomment-230738534%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/819%23issuecomment-230738534%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Confirmed%20working%2C%20thanks.%22%2C%20%22created_at%22%3A%20%222016-07-06T10%3A41%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6716962%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gsaponaro%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'><img …
=> yarpscope: Fix reading minval and maxval from xml

scripts/admin/generate-cmake-options.sh
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/mbrunettini%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4234840%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/810%23issuecomment-228772963%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-06-27T15%3A03%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4234840%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/mbrunettini%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/8 …
=> Removed VALGRIND TEST on linux

src/libYARP_dev/src/modules/AnalogWrapper/AnalogWrapper.cpp, src/libYARP_dev/src/modules/RGBDSensorWrapper/RGBDSensorWrapper.cpp, src/libYARP_dev/src/modules/Rangefinder2DWrapper/Rangefinder2DWrapper.cpp, src/libYARP_dev/src/modules/ServerInertial/ServerInertial.cpp
As otherwise port is not closed
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/814%23issuecomment-229437940%22%2C%20%22https%3A//github.com/robotology/yarp/pull/814%23issuecomment-229992098%22%2C%20%22https%3A//github.com/robotology/yarp/pull/814%23issuecomment-230253910%22%2C%20%22https%3A//github.com/robotology/yarp/pull/814%23issuecomment-231426246%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/814%23issuecomment-229437940%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20%40randaz81%20%40drdanz%2C%5Cr%5CnWould%20be%20great%20if%20you%20review%20and%20merge.%5Cr%5CnThanks%2C%20Tobi%22%2C%20%22created_at%22%3A%20%222016-06-29T18% …
=> [libYARP_dev Modules] Call interrupt and destructor of rosNode

src/yarpmotorgui-qt/main.cpp, src/yarpmotorgui-qt/partitem.cpp, src/yarpmotorgui-qt/partitem.h, src/yarpmotorgui-qt/yarpmotorgui.h
Tested on CER01 (number of joints = 28)
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/pattacini%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/821%23issuecomment-232146489%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-07-12T19%3A03%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3 …
=> Max number of joints was fixed to 16. Now memory is dynamically allocated.

src/yarpmotorgui-qt/partitem.cpp, src/yarpmotorgui-qt/sequencewindow.cpp
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/825%23issuecomment-232607355%22%2C%20%22https%3A//github.com/robotology/yarp/pull/825%23issuecomment-232607552%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/825%23issuecomment-232607355%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Technically%2C%20new%20features%20belong%20to%20the%20devel%20branch...%20Anyway%20this%20is%20almost%20a%20bugfix%20therefore%20I%27ll%20allow%20it%21%20%3Asanta%3A%22%2C%20%22created_at%22%3A%20%222016-07-14T08%3A58%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A% …
=> Yarpmotorgui fix

src/libYARP_OS/src/Contact.cpp
Was broken due to recent changes.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/829%23issuecomment-233029170%22%2C%20%22https%3A//github.com/robotology/yarp/pull/829%23issuecomment-233029587%22%2C%20%22https%3A//github.com/robotology/yarp/pull/829%23issuecomment-233030025%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/829%23issuecomment-233029170%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40drdanz%20%22%2C%20%22created_at%22%3A%20%222016-07-15T18%3A22%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Tobias-Fisc …
=> Fix contact compilation

src/libYARP_dev/include/yarp/dev/ControlBoardInterfaces.h, src/libYARP_dev/include/yarp/dev/Wrapper.h, tests/libYARP_dev/PolyDriverTest.cpp
Solves the issue in https://github.com/robotology/gazebo-yarp-plugins/issues/254
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232632795%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232636584%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232649137%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232662091%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232664695%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232665181%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-232923659%22%2C%20%22https%3A//github.com/robotology/yarp/pull/824%23issuecomment-233296203% …
=> Export as public symbols IWrapper, IMultipleWrapper and other widely used interfaces

doc/installation/install_mac.dox
[ci skip]
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/834%23issuecomment-234546161%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/834%23issuecomment-234546161%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40drdanz%20I%20put%20%5Bci%20skip%5D%20but%20it%20does%20not%20seem%20to%20have%20any%20effects..%22%2C%20%22created_at%22%3A%20%222016-07-22T13%3A38%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2189180%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/francesco-romano%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a …
=> Updated macOS installation

src/yarpdataplayer-qt/src/main.cpp, src/yarplogger-qt/main.cpp, src/yarpmanager-qt/main.cpp, src/yarpmotorgui-qt/main.cpp, src/yarpscope-qt/src/main.cpp, src/yarpview-qt/src/main.cpp
<a href='https://www.codereviewhub.com/robotology/yarp/pull/838?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/838'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> fixing issue #837

doc/release/v2_3_66_1.md, src/libYARP_OS/src/SystemInfo.cpp
I open the PR to track the work, otherwise it gets lost in the various branches.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/799%23issuecomment-227176154%22%2C%20%22https%3A//github.com/robotology/yarp/pull/799%23issuecomment-227247914%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/799%23issuecomment-227176154%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Ready%20to%20merge.%5Cr%5Cn%40apaikan%20can%20you%20check%20this%20PR%3F%22%2C%20%22created_at%22%3A%20%222016-06-20T15%3A26%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2189180%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3 …
=> Added SystemInfo implementation for macOS

src/libYARP_OS/src/NameConfig.cpp
<a href='https://www.codereviewhub.com/robotology/yarp/pull/847?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/847'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Move delete[] outside of the loop

doc/installation/install_mac.dox
Worked on issue https://github.com/robotology/yarp/issues/848.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/856%23issuecomment-237807020%22%2C%20%22https%3A//github.com/robotology/yarp/pull/856%23discussion_r73669094%22%2C%20%22https%3A//github.com/robotology/yarp/pull/856%23issuecomment-237813185%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/856%23issuecomment-237807020%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cud83d%5Cudc4d%20%5Cr%5CnFor%20me%20is%20ok%22%2C%20%22created_at%22%3A%20%222016-08-05T09%3A36%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2189180%3Fv%3D3%22% …
=> improve documentation for YARP installation for macOS

src/yarplogger-qt/mainwindow.cpp, src/yarplogger-qt/yarprunPortSorting.cpp
yarplogger: this commit fixes issue #648 "yarplogger not taking in acccount the date"
<a href='https://www.codereviewhub.com/robotology/yarp/pull/855?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/855'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> 648_logger_gui_fix

src/idls/rosmsg/src/RosType.cpp
<a href='https://www.codereviewhub.com/robotology/yarp/pull/863?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/863'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> idl/rosmsg: Improve output on failure and add some debug messages

src/libYARP_OS/include/yarp/os/impl/Logger.h
CC @francesco-romano
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/francesco-romano%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2189180%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/864%23issuecomment-238844221%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-08-10T11%3A52%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2189180%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/francesco-romano%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//gi …
=> OS/impl/Logger: Use the same enum values when ACE is disabled

.travis.yml, conf/YarpDescribe.cmake, src/idls/rosmsg/tests/CMakeLists.txt, src/idls/thrift/tests/CMakeLists.txt
Thanks to @drdanz  for the correct cmake commands. This should fix https://github.com/robotology/yarp/issues/872
If it all works, we should not allow the failure of the corresponding test in Travis anymore.
I also increased the `travis_wait` time for the tests, even 30 minutes might not be long enough.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/874%23issuecomment-240425486%22%2C%20%22https%3A//github.com/robotology/yarp/pull/874%23issuecomment-240426277%22%2C%20%22https%3A//github.com/robotology/yarp/pull/874%23issuecomment-240471500%22%2C%20%22https%3A//github.com/robotology/yarp/pull/874%23issuecomment-240651410%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github …
=> Fix yarp IDL for Xcode

doc/release/v2_3_66_1.md, src/yarpdataplayer-qt/src/utils.cpp
By default `std::stream` opens a file in read and write mode.
I changed the `fstream` to open the file in read mode. Alternatively we can keep the old constructor but change the stream to `ifstream`.
cc @ChiaraBartolozzi 
@vtikha There was a reason why the file is opened in write mode?
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/vtikha%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4537987%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/875%23issuecomment-240681876%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-08-18T10%3A12%3A11Z%22%2C%20%22user%22%3A%20%7B%22a …
=> Fixed issue on yarpdataplayer when opening readonly files

src/libYARP_OS/src/Carriers.cpp
Fixes #403
<a href='https://www.codereviewhub.com/robotology/yarp/pull/879?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/879'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> List carriers in plugins with "yarp connect --list-carriers"

src/modules/portaudio/PortAudioDeviceDriver.cpp
Number of samples was multiplied by channels number twice, recording double samples then required in stereo mode.
Change default parameters to stream chunks of 1 second of data. Before the default was 30 seconds (1 minute due to the other bug), so there were 30 seconds (1min) of delay before receiving the first yarp message.
This gave the feeling that the device was not working, while it actually was storing data but not responding in the meantime.
Using 1 sec as default make the device more responsive. It can changed using --samples option as usual
<a href='https://www.codereviewhub.com/robotology/yarp/pull/890?approve …
=> portaudio device: fixes

src/modules/imuBosch_BNO055/imuBosch_BNO055.cpp, src/modules/imuBosch_BNO055/imuBosch_BNO055.h
Improved errors handling and removed useless code.
=> Cleanup imuBosch module

src/yarpdataplayer-qt/include/UI/mainwindow.ui, src/yarpdataplayer-qt/include/mainwindow.h, src/yarpdataplayer-qt/include/utils.h, src/yarpdataplayer-qt/include/worker.h, src/yarpdataplayer-qt/src/mainwindow.cpp, src/yarpdataplayer-qt/src/utils.cpp, src/yarpdataplayer-qt/src/worker.cpp
Added a `time taken` column and fixed synchronisation issue
see https://github.com/robotology/QA/issues/138
=> fixing synchronisation in yarpdataplayer

cmake/YarpFindDependencies.cmake
See https://github.com/robotology/yarp/issues/840#issuecomment-259072222 .
=> Enable Eigen backend of libYARP_math by default

src/libYARP_dev/src/devices/FrameTransformClient/FrameTransformClient.cpp, src/libYARP_math/include/yarp/math/FrameTransform.h, src/libYARP_math/include/yarp/math/Math.h, src/libYARP_math/src/math.cpp, tests/libYARP_dev/FrameTransformClientTest.cpp
As discussed in https://github.com/robotology/yarp/issues/786 .
=> [WIP] Fix quaternion handling functions 

src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp, src/devices/imuBosch_BNO055/imuBosch_BNO055.h, src/libYARP_dev/include/yarp/dev/IFrameTransform.h, src/libYARP_dev/src/devices/FrameTransformClient/FrameTransformClient.cpp, src/libYARP_dev/src/devices/FrameTransformClient/FrameTransformClient.h, src/libYARP_dev/src/devices/FrameTransformServer/FrameTransformServer.cpp, src/libYARP_dev/src/devices/LocationsServer/LocationsServer.cpp, src/libYARP_dev/src/devices/LocationsServer/LocationsServer.h, src/libYARP_eigen/include/yarp/eigen/Eigen.h, src/libYARP_math/CMakeLists.txt, src/libYARP_math/include/yarp/math/FrameTransform.h, src/libYARP_math/include/yarp/math/Math.h, src/libYARP_math/include/yarp/math/Quaternion.h, src/libYARP_math/src/FrameTransform.cpp, src/libYARP_math/src/Quaternion.cpp, src/libYARP_math/src/math.cpp, tests/libYARP_dev/FrameTransformClientTest.cpp, tests/libYARP_math/MathTest.cpp
This PR subsumes #958. 
See also #910
Can you please give it a look? Thanks!
@francesco-romano  @traversaro @barbalberto @drdanz @aerydna @pattacini
=> [WIP] Quaternion class

.travis.yml, tests/CMakeLists.txt, tests/libYARP_OS/PortTest.cpp
new already broken test added along with a related cmake flag and a travis dedicated failure-allowed build
=> added broken tests

src/libYARP_OS/include/yarp/os/impl/BottleImpl.h
Fix https://github.com/robotology/yarp/issues/956
=> Fix infinite recursion in storable tostring

src/libYARP_sig/include/yarp/sig/Matrix.h, src/libYARP_sig/include/yarp/sig/Vector.h
Remove some leftover of the gsl --> Eigen migration.
=> Cleanup YARP sig Vector and Matrix

doc/release/v2_3_66_2.md, src/yarplogger-qt/mainwindow.cpp, src/yarplogger-qt/mainwindow.h
to make opening files a bit faster I added drag'n'drop
=> YarpLoggerQT: open logs by drag'n'drop

src/libYARP_OS/src/SystemInfo.cpp
This pull request also fixes crashing yarpview on windows while using yarpviz!
=> fixes: yarpview on windows was crashing on prop get command from admin rpc port

src/libYARP_dev/src/devices/ControlBoardRemapper/ControlBoardRemapper.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp
This fix allows to set remote variables which do not belong to the first set of joints. e.g. (0 1 2) (0 1 HERE 3 4)
=> fix bug in setRemoteVariable

src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/devices/RemoteControlBoard/RemoteControlBoard.cpp, src/libYARP_dev/src/devices/RemoteControlBoard/stateExtendedReader.cpp, src/libYARP_dev/src/devices/RemoteControlBoard/stateExtendedReader.hpp
These very important commits from @barbalberto fix an insidious race condition causing segfault of a remoteControlBoard client. Currently under testing.
=> Remote cb fix get data

doc/release/v2_3_66_2.md, src/modules/serial/SerialDeviceDriver.cpp
=> serial: Print error when the device cannot be opened

src/devices/fakeMotionControl/fakeMotionControl.cpp
Fix issue #983. The fakemotioncontrol was not opening correctly if 'Encoder' parameter was used in the config file
=> Fix fake motion control open - issue #983

src/devices/depthCamera/depthCameraDriver.h
=> depthCamera: fix doxygen

src/yarpmotorgui/jointitem.cpp, src/yarpmotorgui/main.cpp, src/yarpmotorgui/mainwindow.cpp, src/yarpmotorgui/mainwindow.h, src/yarpmotorgui/partitem.cpp, src/yarpmotorgui/partitem.h, src/yarpmotorgui/startdlg.cpp, src/yarpmotorgui/startdlg.h, src/yarpmotorgui/yarpmotorgui.h
no more hardcoded limit on the number of parts. only the check has been removed and everything seems to work.
however the code is messy at the moment and his behaviour is not obvious. @barbalberto had informed me that this gui has been converted to Qt from a previous gtk version so i presume that some things are survived phantoms of the previous version (and the main suspect is that limiting the number of part was one of them).
=> no more hardcoded number of parts

src/devices/depthCamera/depthCameraDriver.cpp, src/devices/depthCamera/depthCameraDriver.h, src/libYARP_dev/src/devices/Rangefinder2DWrapper/Rangefinder2DWrapper.cpp
message error of Rangefinder2D fixed and segfault due to incorrect configuration file of depthCameraDriver avoided
=> Devices bugfix

src/devices/laserFromDepth/laserFromDepth.cpp
horizontal flip and RGBD like distortion added
=> laserFromDepth fix

doc/release/v2_3_70.md, src/libYARP_dev/src/devices/AnalogWrapper/AnalogWrapper.cpp, src/libYARP_dev/src/devices/AnalogWrapper/AnalogWrapper.h
=> Deprecation of AnalogWrapper constructors with arguments

doc/release/v2_3_68_1.md, src/libYARP_dev/src/devices/AnalogWrapper/AnalogWrapper.cpp, src/libYARP_dev/src/devices/AnalogWrapper/AnalogWrapper.h, tests/CMakeLists.txt, tests/libYARP_dev/AnalogWrapperTest.cpp, tests/libYARP_dev/TestList.h
=> Bug Fixing AnalogWrapper class and addition of relative yarp tests

cmake/YarpFindDependencies.cmake, src/carriers/zfp_portmonitor/CMakeLists.txt
=> Move find_package(ZFP) from CMakeLists.txt to cmake/YarpFindDependencies.cmake

src/devices/depthCamera/depthCameraDriver.cpp
=> depthCameraDriver bugfix

src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.cpp, src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.h
added option for forcing rosmessage sync between image and info topics
=> RGBDSensorWrapper

doc/release/v2_3_70.md, src/yarpview/plugin/VideoSurface.qml, src/yarpview/plugin/qtyarpview.cpp, src/yarpview/plugin/qtyarpview.h
left-click on the image and keep left button pressed: yarpview starts to draw a line.
When the left button is released, the coordinates of the initial and the final point are sent to the 'out' yarp port.
=> Implemented dragvector function on yarpview.

src/carriers/zfp_portmonitor/CMakeLists.txt
Compilation error of zfpcarrier fixed.
=> Fixed CMakeLists for zfpPortmonitor

src/devices/depthCamera/depthCameraDriver.cpp, src/devices/depthCamera/depthCameraDriver.h
added depth on rgb image registration via openni2
=> added hardware image registration

src/rtf-plugins/fixture-managers/yarpplugin/YarpPluginFixture.cpp, src/rtf-plugins/fixture-managers/yarpplugin/YarpPluginFixture.h
=> YarpPluginFixture: add the check among available carriers

src/libYARP_dev/src/IVisualParamsImpl.cpp
Fixed the comunication of mirroring and intrinsic parameter through sender and parser.
=> IVisualParamsImpl: Bug fixing

src/rtf-plugins/fixture-managers/yarpplugin/YarpPluginFixture.cpp, src/rtf-plugins/fixture-managers/yarpplugin/YarpPluginFixture.h
=> YarpPluginFixture:Add the check for the available portmonitors

src/libYARP_dev/include/yarp/dev/ControlBoardPid.h, src/libYARP_dev/src/ControlBoardPid.cpp
Added overloading of == operator in class Pid.
=> Pid class: added operetor == overloading

doc/release/v2_3_70.md, src/devices/depthCamera/depthCameraDriver.cpp, src/devices/depthCamera/depthCameraDriver.h, src/devices/test_grabber/TestFrameGrabber.cpp, src/devices/test_grabber/TestFrameGrabber.h, src/libYARP_dev/include/yarp/dev/IRGBDSensor.h, src/libYARP_dev/include/yarp/dev/IVisualParams.h, src/libYARP_dev/include/yarp/dev/IVisualParamsImpl.h, src/libYARP_dev/include/yarp/dev/RemoteFrameGrabber.h, src/libYARP_dev/src/IVisualParamsImpl.cpp, src/libYARP_dev/src/devices/RGBDSensorClient/RGBDSensorClient.cpp, src/libYARP_dev/src/devices/RGBDSensorClient/RGBDSensorClient.h, src/libYARP_sig/include/yarp/sig/Image.h
It introduce to the interface `IVisualParams`:
- `getRgbResolution`
- `getRgbSupportedConfigurations` that gives the possible configuration of a camera in terms of `width`, `height`, `framerate` and `pixelCoding`.
=> IVisualParams improvement

src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp
small change in error messages.
=> imu bosh: improve human readable error messages

src/idls/rosmsg/src/RosType.cpp, src/idls/rosmsg/src/main.cpp
fixes an issues when working with custom, nested ros messages
=> fixes an issues when working with custom, nested ros messages

src/libYARP_OS/include/yarp/os/Subscriber.h
yarp subscriber class: added the following methods:
- virtual void onRead (T &datum)
- void useCallback (TypedReaderCallback< T > &callback)
- void useCallback()
- void disableCallback()
=> Subscriber with callback

src/devices/CMakeLists.txt, src/devices/SDLJoypad/CMakeLists.txt, src/devices/SDLJoypad/SDLJoypad.cpp, src/devices/SDLJoypad/SDLJoypad.h, src/devices/SDLJoypad/SDLJoypad.ini, src/libYARP_dev/CMakeLists.txt, src/libYARP_dev/include/yarp/dev/IJoypadController.h, src/libYARP_dev/src/PopulateDrivers.cpp, src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.cpp, src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.h, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlNetUtils.h, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlServer.cpp, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlServer.h
new Joypad interface/server/client/device suite for joypad management with yarp.
@randaz81 @barbalberto @drdanz
=> JoypadControl suite

doc/release/v2_3_70.md, src/libYARP_math/include/yarp/math/Math.h, src/libYARP_math/include/yarp/math/Quaternion.h, src/libYARP_math/src/Quaternion.cpp, src/libYARP_math/src/math.cpp, tests/libYARP_math/MathTest.cpp
Added operator* overload for quaternion multiplication along with a corresponding math test.
=> Quaternion multiplication

src/libYARP_dev/include/yarp/dev/IJoypadController.h, src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.cpp, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlServer.cpp
Sticks bug fixed and todo list updated. some error message added.
=> Joypad control suite update

src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlServer.cpp
JoypadControlServer yarp::math dependency eliminated
=> JoypadControlServer yarp::math dependency eliminated

cmake/template/placeGeneratedYarpIdlFiles.cmake.in
=> YarpIDL: Fix yarp_idl_to_dir for path containing spaces

src/devices/ovrheadset/OVRHeadset.cpp, src/devices/ovrheadset/OVRHeadset.h
Implementation of the IJoypadController interface for teleoperation purpose
=> Oculus touch IJoypadController implementation

src/libYARP_dev/src/devices/FrameTransformClient/FrameTransformClient.cpp, src/libYARP_dev/src/devices/FrameTransformClient/FrameTransformClient.h, src/libYARP_dev/src/devices/FrameTransformServer/FrameTransformServer.cpp, src/libYARP_dev/src/devices/FrameTransformServer/FrameTransformServer.h, tests/libYARP_dev/FrameTransformClientTest.cpp
adds timed transforms on frameTransform suite
=> Transform client update

src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.cpp, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlServer.cpp
various fixes to the JoypadControl client and server
=> [WIP] Joypad control fix

src/libYARP_OS/include/yarp/os/Subscriber.h
Added setStrict() method to yarp::os::Subscriber.
=> Subscriber strict

src/libYARP_dev/include/yarp/dev/IJoypadController.h
=> IJoypadController.h: fix #1191

src/devices/ovrheadset/CMakeLists.txt, src/devices/ovrheadset/OVRHeadset.cpp, src/devices/ovrheadset/OVRHeadset.h
position and rotation tracking via tf.
=> Oculus touch tracking

src/yarpdataplayer/src/main.cpp, src/yarpmotorgui/main.cpp, src/yarpview/src/main.cpp
This PR introduces changes to solve #837, #1122, #1038.
=> Substitution of QT_DEVICE_RATIO(deprecated)

src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.cpp
JoypadControlClient: comma operator bugfix
=> JoypadControlClient: comma operator bugfix

doc/cmd_yarp-config.dox, doc/cmd_yarpmanager.dox, doc/port_expert.dox, doc/resource_finder_spec.dox, doc/yarp_data_dirs.dox, src/libYARP_OS/src/Port.cpp
Fix https://github.com/robotology/yarp/issues/1202
=> fixed documentation in Port class (and not only)

src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/mainwindow.cpp, src/yarpmanager/src-manager/mainwindow.h
This PR restore changes introduced by @Tobias-Fischer  in #1053, accidentally reverted by #1206 
=> yarpmanager: restore changes introduced in PR #1053 accidentally reverted by #1206

tests/libYARP_OS/PortTest.cpp
This PR add a `BROKEN_TEST` that reproduces the close deadlock of a device after a `prepare()` on a closed port (#1236).
=> Add deadlock device

src/libYARP_manager/src/kbase.cpp
This PR fix a possible security issue using `strcpy`
=> libYARP_manager: fix possible security issue about strcpy

src/rtf-plugins/fixture-managers/yarpmanager/YarpFixManager.cpp
This pr updates the `yarpmanager` fixture after the recent changes in `lib_YARP_manager`
=> YarpFixManager: update call to addApplication after recent changes to manager.h

src/libYARP_manager/include/yarp/manager/kbase.h, src/libYARP_manager/include/yarp/manager/manager.h, src/libYARP_manager/src/kbase.cpp, src/libYARP_manager/src/manager.cpp, src/yarpmanager/src-manager/mainwindow.cpp
This PR introduce changes for fixing robotology/gazebo-yarp-plugins#299 (TESTED)
Ready to be merged
=> [WIP] yarpmanager: add changes to make it compatible with yarpFixManager

doc/release/v2_3_68_1.md, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp
Still to be tested on the robot
=> Fix ROS only option in ControlBoardWrapper

doc/release/v2_3_68_1.md, src/yarpmanager/src-manager/applicationviewwidget.cpp
=> yarpmanager: Fix Refresh button

src/libYARP_dev/src/devices/FrameTransformServer/FrameTransformServer.cpp, src/libYARP_dev/src/devices/FrameTransformServer/FrameTransformServer.h
transformServer can now read tf from his configuration file and publish them as static tf
=> transformServer new feature: Static transform from config file

src/libYARP_dev/src/devices/FrameTransformServer/FrameTransformServer.cpp
- deleted c++11 keyword "or" in favor of the classic || for visual studio incompatibility
- added the parsing of 4x4 matrix as tf description in configuration file
=> transformServer visual studio fix

src/devices/SDLJoypad/SDLJoypad.cpp, src/devices/SDLJoypad/SDLJoypad.h, src/libYARP_dev/CMakeLists.txt, src/libYARP_dev/include/yarp/dev/IJoypadController.h, src/libYARP_dev/src/IJoypadController.cpp, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlServer.cpp, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlServer.h
added sticks management in the SDLJoypad (including axis reverse). added script execution as partial implementation of the IJoypadController interface for it to be activated in the desired device. added various utility e fix
=> JoypadControlSuite pre-release patch

src/devices/SDLJoypad/SDLJoypad.cpp
Visual studio patch for SDLJoypad
=> SDLJoypad vs patch

doc/release/v2_3_70.md, src/libYARP_dev/CMakeLists.txt, src/libYARP_dev/include/yarp/dev/IHapticDevice.h
imported the IHapticDevice interface from https://github.com/robotology/haptic-devices.
=> IHapticDevice interface added

src/yarpview/plugin/qtyarpview.cpp
Add check in yarpview to verify yarpserver is running at startup, it was missing.
=> yarpview: add check yarpserver is running

src/libYARP_OS/src/YarpPlugin.cpp
=> libYARP_OS-YarpPlugin: change Time::now() with SystemClock::nowSystem()

doc/main.dox, doc/yarp_env_variables.md
Fix https://github.com/robotology/yarp/issues/1118
=> Add documentation on YARP environmental variables

doc/release/v2_3_70_1.md, src/libYARP_OS/src/DgramTwoWayStream.cpp
This PR fixes mcast without ACE on macOS.
=> Fix mcast on macOS

src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/applicationviewwidget.h
The changes introduced by this PR fix the refresh/disconnect after introducing the combobox
TESTED on r1 setup
=> yarpmanager: fix refresh and disconnect after introducing the combobox

src/devices/ovrheadset/OVRHeadset.cpp, src/devices/ovrheadset/OVRHeadset.h
OVRDevice Cleanupped and updated
=> Ovr device updates

src/libYARP_dev/CMakeLists.txt, src/libYARP_dev/include/yarp/dev/IVisualServoing.h
This PR is to add a new interface called IVisualServoing which can be used to implement visual servoing-based devices.
=> Add IVisualServoing device interface

doc/release/v2_3_72.md
IVisualServoing.h has been added in YARP_dev.
Bonus round: my editor ✨ automagically ✨ deleted a trailing space!
=> Update release documentation mentionig IVisualServoing

src/devices/rpLidar2/rpLidar2.cpp, src/devices/rpLidar2/rpLidar2.h, src/libYARP_dev/src/devices/Rangefinder2DClient/Rangefinder2DClient.cpp
this PR improves rpLidar2 device driver and rangefinder2DClient.
=> Laser fix on undefined value

src/libYARP_dev/src/devices/Map2DServer/Map2DServer.cpp
added options mapCollectionFile mapCollectionContext
=> Fix map2d server

src/devices/ovrheadset/OVRHeadset.cpp, src/devices/ovrheadset/OVRHeadset.h
- small fix on ovrdevice frames
- added absolute tracking mode (opposed to head-relative)
=> OVRDevice: small fix

src/devices/ovrheadset/OVRHeadset.cpp
small bugfix for correctly compiling ovrDevice
=> compile error fix of ovrDevice

doc/release/v2_3_72.md, src/devices/ovrheadset/OVRHeadset.cpp, src/devices/ovrheadset/OVRHeadset.h, src/devices/ovrheadset/TextureBuffer.cpp, src/devices/ovrheadset/TextureBuffer.h
OVRDevice can now visualize hud feeding directly from yarp image ports.
=> Ovr huds from port

src/libYARP_dev/include/yarp/dev/IVisualServoing.h
This PR is to update the IVisualServoing interface.
There is still WIP, but the overall is at a good dev stage.
=> Update IVisualServoing interface

src/libYARP_dev/src/devices/FrameTransformClient/FrameTransformClient.cpp
=> FrameTransformServer small fix

src/libYARP_dev/include/yarp/dev/IJoypadController.h, src/libYARP_dev/src/IJoypadController.cpp, src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.cpp, src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.h, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlNetUtils.h
added a network watchdog to the JoypadControlClient to prevent wrong input in case of network issues
=> Joypad control watchdog

src/rtf-plugins/fixture-managers/yarpmanager/YarpFixManager.cpp
yarpfixmanager search the fixture file with the absolute path if the relative path failed
=> yarpfixmanager RTF plugin fix

src/libYARP_dev/include/yarp/dev/IVisualServoing.h
=> Update IVisualServoing documentation

src/yarpmanager/src-manager/mainwindow.cpp, src/yarpmanager/src-manager/mainwindow.ui
=> yarpmanager: fix template ordering

src/libYARP_serversql/src/yarpserver.cpp
=> libYARP_serversql: adds to the help the write option

doc/release/v2_3_70_1.md, src/yarpview/src/main.cpp
This PR introduces signal handler in yarpview.
Fixes #356.
=> Fix yarpview SIGINT/SIGTERM handling

example/port_power/ex0001_sender.cpp, example/port_power/ex0101_sender.cpp, example/port_power/ex0400_expect_reply.cpp, example/port_power/ex0401_give_reply.cpp, example/port_power/ex0402_port_callback_reply.cpp, example/port_power/ex0403_bufferedport_callback_reply.cpp
Fixes #1337 compilation problem due to the removal of Value(const char*) on devel branch. 
=> example:fix port_power compilation issue

doc/release/v2_3_72.md, src/libYARP_OS/CMakeLists.txt, src/libYARP_OS/include/yarp/os/Os.h, src/libYARP_OS/include/yarp/os/impl/MacOSAPI.h, src/libYARP_OS/src/MacOSAPI.mm, src/libYARP_OS/src/Os.cpp, src/yarpdataplayer/src/main.cpp
=> Macos AppNap support

doc/release/v2_3_72.md, src/rtf-plugins/fixture-managers/CMakeLists.txt, src/rtf-plugins/fixture-managers/yarpmanager/CMakeLists.txt, src/rtf-plugins/fixture-managers/yarpplugin/CMakeLists.txt, src/rtf-plugins/fixture-managers/yarpserver/CMakeLists.txt, src/rtf-plugins/fixture-managers/yarpserver/yarpserverfixture.cpp
RTF plugin for running yarpserver as a fixture directly from the tests
=> Rtf yarpserver plugin

src/libYARP_dev/src/MapGrid2D.cpp, src/libYARP_dev/src/PolyDriver.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/RPCMessagesParser.cpp, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlServer.cpp, src/libYARP_dev/src/devices/Map2DServer/Map2DServer.cpp, tests/libYARP_dev/TestFrameGrabberTest.cpp
libYARP_dev - fix file by file
- after the assignment the var is never read
- possible access to null pointer
=> Fix Clang warnings - libYARP_dev

doc/release/v2_3_72.md, src/rtf-plugins/fixture-managers/yarpserver/yarpserverfixture.cpp
small codacy fix on yarpserver fixture + changelog fix
=> Yarpserver fixture small codacy fix

src/libYARP_serversql/src/yarpserver.cpp
added an option for not printing messages. this is useful when using yarp server as a plugin.
=> Yarpserver silent

src/libYARP_OS/include/yarp/os/impl/BufferedConnectionWriter.h, src/libYARP_OS/include/yarp/os/impl/Companion.h, src/libYARP_OS/include/yarp/os/impl/DgramTwoWayStream.h, src/libYARP_OS/include/yarp/os/impl/Dispatcher.h, src/libYARP_OS/include/yarp/os/impl/Logger.h, src/libYARP_OS/include/yarp/os/impl/ShmemInputStream.h, src/libYARP_OS/include/yarp/os/impl/StreamConnectionReader.h, src/libYARP_OS/src/BottleImpl.cpp, src/libYARP_OS/src/Companion.cpp, src/libYARP_OS/src/HttpCarrier.cpp, src/libYARP_OS/src/InputStream.cpp, src/libYARP_OS/src/NameClient.cpp, src/libYARP_OS/src/NetworkClock.cpp, src/libYARP_OS/src/Port.cpp, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/PortReaderBuffer.cpp, src/libYARP_OS/src/Property.cpp, src/libYARP_OS/src/QosStyle.cpp, src/libYARP_OS/src/RunProcManager.cpp, src/libYARP_OS/src/SplitString.cpp, src/libYARP_OS/src/SystemInfo.cpp, src/libYARP_OS/src/Terminator.cpp, src/libYARP_OS/src/Thread.cpp, src/libYARP_OS/src/ThreadImpl.cpp, src/libYARP_OS/src/WireReader.cpp
Fix file by file of some of the issues raised by Coverity Static Analyzer on OS component.
=> Coverity fix libYARP_OS

src/libYARP_dev/src/devices/FrameTransformServer/FrameTransformServer.cpp
=> transform server fix

src/libYARP_OS/include/yarp/os/impl/DgramTwoWayStream.h, src/libYARP_OS/src/PortCoreInputUnit.cpp, src/libYARP_OS/src/RosNameSpace.cpp
fix submitted for some other issues raised by Coverity static analyzer libYARP_OS
=> Coverity fix - libYARP_OS #2

src/libYARP_manager/include/yarp/manager/application.h, src/libYARP_manager/include/yarp/manager/binexparser.h, src/libYARP_manager/include/yarp/manager/impl/textparser.h, src/libYARP_manager/include/yarp/manager/localbroker.h, src/libYARP_manager/src/application.cpp, src/libYARP_manager/src/execstate.cpp, src/libYARP_manager/src/executable.cpp, src/libYARP_manager/src/localbroker.cpp, src/libYARP_manager/src/manager.cpp, src/libYARP_manager/src/primresource.cpp, src/libYARP_manager/src/yarpbroker.cpp
Fix file by file of issues raised by Coverity static analyzer on libYARP_manager.
=> Coverity fix - libYARP_manager

tests/libYARP_sig/ImageTest.cpp
added a broken test in the harness_sig::ImageTest suite.
see issue #1408
=> added an image broken test

src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/devices/Rangefinder2DWrapper/Rangefinder2DWrapper.cpp, src/libYARP_dev/src/devices/ServerInertial/ServerInertial.cpp
Commits left out from https://github.com/robotology/yarp/pull/1387
=> Coverity fix - libYARP_dev #2

src/carriers/bayer_carrier/BayerCarrier.h, src/carriers/mpi_carrier/include/yarp/os/MpiBcastCarrier.h, src/carriers/mpi_carrier/src/MpiBcastCarrier.cpp, src/carriers/portmonitor_carrier/PortMonitor.h, src/carriers/priority_carrier/PriorityCarrier.h, src/carriers/tcpros_carrier/RosLookup.h, src/carriers/tcpros_carrier/RosSlave.h, src/carriers/tcpros_carrier/yarpros.cpp, src/libYARP_OS/include/yarp/os/SharedLibraryClassApi.h
Fix file by file of issues raised by Coverity static analyzer over carriers
=> Coverity fix - carriers

example/game/game_clientmt/main.cpp, example/stressTests/callback.cpp, example/stressTests/stressrpc.cpp, example/stressTests/stressrpcMD.cpp, src/devices/fakebot/FakeBot.cpp, src/devices/test_grabber/TestFrameGrabber.cpp, src/yarpviz/src/MainWindow.cpp
Substituted all usages of `yarp::os::Random` API with utilities from C++11's `<random>` library.
=> Replace yarp::os::Random

src/libYARP_dev/include/yarp/dev/DataSource.h, src/libYARP_dev/src/ControlBoardPid.cpp, src/libYARP_dev/src/DeviceDriver.cpp, src/libYARP_dev/src/IEncodersTimedImpl.cpp, src/libYARP_dev/src/IMotorEncodersImpl.cpp, src/libYARP_dev/src/IMotorImpl.cpp, src/libYARP_dev/src/MapGrid2D.cpp, src/libYARP_dev/src/PWMControlImpl.cpp, src/libYARP_dev/src/PolyDriver.cpp, src/libYARP_dev/src/devices/AnalogWrapper/AnalogWrapper.cpp, src/libYARP_dev/src/devices/ControlBoardRemapper/ControlBoardRemapper.cpp, src/libYARP_dev/src/devices/ControlBoardRemapper/ControlBoardRemapperHelpers.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.h, src/libYARP_dev/src/devices/ControlBoardWrapper/RPCMessagesParser.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/SubDevice.cpp, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlServer.cpp, src/libYARP_dev/src/devices/RGBDSensorClient/RGBDSensorClient.cpp, src/libYARP_dev/src/devices/RGBDSensorClient/RGBDSensorClient_StreamingMsgParser.cpp, src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.cpp, src/libYARP_dev/src/devices/Rangefinder2DClient/Rangefinder2DClient.cpp, src/libYARP_dev/src/devices/ServerGrabber/ServerGrabber.cpp, src/libYARP_dev/src/devices/ServerInertial/ServerInertial.cpp, src/libYARP_dev/src/devices/VirtualAnalogWrapper/VirtualAnalogWrapper.cpp
Fix file by file of the majority of issues raised by Coverity static analyzer on libYARP_dev
=> Coverity fix - libYARP_dev

doc/release/v2_3_72.md, src/libYARP_OS/include/yarp/os/Publisher.h
For symmetry with BufferedPort
=> Added unprepare method to Publisher

src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.cpp
oversight fix in joypadControlClient
=> bugfix on joypadControlClient

example/idl/thrift/generated/CMakeLists.txt, example/matrix/CMakeLists.txt, example/matrix/gsl_example.cpp
It fixes #1395 .
It fixes #1338.
=> Fixes gsl and thrift example compilation issue

doc/main.dox, doc/rtf_plugins.md
=> Add Rtf plugins documentation

src/devices/SDLJoypad/SDLJoypad.h
added doxygen documentation on SDLJoypad.
=> SDLJoypad doxygen

src/devices/SDLJoypad/SDLJoypad.h, src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.cpp, src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.h
doxygen documentation added to joypadControlClient + minor cleanup
=> Jp control client doxygen

doc/release/v2_3_72.md, src/libYARP_OS/src/Stamp.cpp
This PR optimize `Stamp::write()` and `Stamp::read()` in textMode.
=> Optimize yarp::os::Stamp

example/web/web_test.cpp
- Contact(name) -> Contact contact(name)
- ConstString::toString -> std::stringstream implementation
=> Fix web example issues.

src/devices/fakeAnalogSensor/fakeAnalogSensor.cpp, src/devices/fakeLaser/fakeLaser.h, src/devices/ffmpeg/FfmpegGrabber.cpp, src/devices/ffmpeg/FfmpegGrabber.h, src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp, src/devices/laserFromDepth/laserFromDepth.h, src/devices/laserHokuyo/laserHokuyo.h, src/devices/microphone/LinuxMicrophoneDeviceDriver.cpp, src/devices/opencv/OpenCVGrabber.cpp, src/devices/opencv/OpenCVGrabber.h, src/devices/openni2/OpenNI2DeviceDriverClient.cpp, src/devices/openni2/OpenNI2SkeletonData.cpp, src/devices/openni2/OpenNI2SkeletonTracker.cpp, src/devices/rpLidar/rpLidar.h, src/devices/test_grabber/TestFrameGrabber.cpp, src/devices/test_grabber/TestFrameGrabber.h
Fix file by file of some of the issues raised by Coverity static analyzer on devices component.
=> Coverity fix - devices

src/yarpdataplayer/src/loadingwidget.cpp, src/yarpdataplayer/src/utils.cpp, src/yarpdataplayer/src/worker.cpp, src/yarplogger-console/main.cpp, src/yarpmotorgui/partitem.cpp, src/yarprobotinterface/Action.cpp, src/yarprobotinterface/CalibratorThread.cpp, src/yarprobotinterface/Param.cpp, src/yarprobotinterface/Robot.cpp, src/yarprobotinterface/XMLReader.cpp, src/yarpscope/plugin/plotter.cpp, src/yarpscope/plugin/qtyarpscope.cpp, src/yarpscope/plugin/xmlloader.cpp
Affect components
- yarplogger-console
- yarpdataplayer
- yarpmotorgui
- yarprobotinterface
- yarpscope
Commits are grouped by component.
=> Coverity fixes - initializations_4

src/libYARP_manager/include/yarp/manager/kbase.h, src/libYARP_manager/src/application.cpp, src/yarpmanager/src-builder/arrow.cpp, src/yarpmanager/src-builder/builderitem.h, src/yarpmanager/src-builder/builderscene.cpp, src/yarpmanager/src-builder/builderwindow.cpp, src/yarpmanager/src-builder/itemsignalhandler.cpp, src/yarpmanager/src-builder/moduleitem.cpp, src/yarpmanager/src-builder/propertiestable.cpp, src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/genericviewwidget.cpp, src/yarpmanager/src-manager/safe_manager.cpp
Affect components
- YARP_manager
- yarpmanager
=> Coverity fixes - initializations_3

doc/release/v2_3_72.md, src/libYARP_serversql/CMakeLists.txt, src/libYARP_serversql/include/yarp/serversql/Server.h, src/libYARP_serversql/include/yarp/serversql/api.h, src/libYARP_serversql/include/yarp/serversql/yarpserversql.h, src/libYARP_serversql/src/yarpserver.cpp, src/rtf-plugins/fixture-managers/yarpserver/yarpserverfixture.cpp
`YarpServerThread` class created in order to use yarpserver as a standard executable or in a plugin (example: yarpserverfixture)
=> yarpserver class created + yarpserver_main updated

src/devices/SDLJoypad/SDLJoypad.cpp
updated help output of SDLJoypad device
=> SDLJoypad help updated

doc/release/v2_3_70_2.md, src/carriers/portmonitor_carrier/CMakeLists.txt, src/carriers/tcpros_carrier/CMakeLists.txt, src/carriers/xmlrpc_carrier/CMakeLists.txt
=> Remove unused ACE dependencies on carriers

bindings/yarp.i
I have added some bindings for IFrameGrabberControls2, including some helper functions to deal with reference-based arguments.
PS: sorry for the mess, I pressed the enter key by accident and had to edit the PR afterwards :sweat_smile:
=> Add bindings for IFrameGrabberControls2

src/yarpdatadumper/main.cpp
=> fix bug introduced by initialization in yarpdatadumper

doc/release/v2_3_70_2.md, src/libYARP_dev/include/yarp/dev/FrameGrabberInterfaces.h, src/libYARP_dev/include/yarp/dev/RemoteFrameGrabber.h, src/libYARP_dev/src/devices/ServerGrabber/ServerGrabber.cpp, tests/libYARP_dev/TestFrameGrabberTest.cpp
This PR add an RPC command to get a crop of the image.
The server ask the device to crop, if fails (not implemented) the server crop the image by his own (less optimized).
Right now only the server crop is implemented.
Under testing
=> Add request for cropped image over RPC

src/libYARP_OS/src/AuthHMAC.cpp, src/libYARP_OS/src/DgramTwoWayStream.cpp, src/libYARP_OS/src/NestedContact.cpp, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/Run.cpp, src/libYARP_dev/src/MapGrid2D.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.cpp
Some fixes for Coverity analyzer in 
* `libYARP_OS`
* `libYARP_dev`
=> Coverity fix

src/devices/ServerSoundGrabber/ServerSoundGrabber.h, src/devices/jrkerr/JrkerrMotionControl.cpp, src/devices/jrkerr/JrkerrMotionControl.h, src/devices/jrkerr/README.TXT, src/devices/jrkerr/nmccom.cpp, src/devices/jrkerr/nmccom.h, src/devices/jrkerr/picservo.cpp, src/devices/jrkerr/picservo.h, src/devices/microphone/WindowsMicrophoneDeviceDriver.cpp, src/devices/openni2/CMakeLists.txt, src/devices/openni2/OpenNI2DeviceDriverClient.cpp, src/devices/openni2/OpenNI2DeviceDriverClient.h, src/devices/openni2/OpenNI2DeviceDriverServer.cpp, src/devices/openni2/OpenNI2DeviceDriverServer.h, src/devices/openni2/OpenNI2SkeletonData.cpp, src/devices/openni2/OpenNI2SkeletonData.h, src/devices/openni2/OpenNI2SkeletonTracker.cpp, src/devices/openni2/OpenNI2SkeletonTracker.h, src/devices/openni2/README, src/devices/openni2/include/yarp/dev/IOpenNI2DeviceDriver.h, src/devices/vfw/VfwGrabber.cpp, src/libYARP_sig/include/yarp/sig/IplImage.h
=> Re-license part2

src/devices/serialport/README.TXT, src/devices/serialport/SerialDeviceDriver.h
=> devices/serialport: Re-license BSD

doc/release/v2_3_72_1.md, src/libYARP_sig/src/Sound.cpp, tests/libYARP_sig/SoundTest.cpp
+= operator was not working correctly, this PR fix it.
A test is also been added in harness_sig
=> Fix bug in yarp::sig::Sound append (+= operator)

doc/release/v3_0_0.md, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp
Add error code in attaching subdevices
@traversaro
=> Add error code in attaching subdevices

example/os/rateThreadTiming.cpp, example/os/ratethread.cpp, example/os/threads.cpp
Fix segfault in the rateThread example
=> Fix rateThread example

doc/release/v3_0_0.md, src/libYARP_OS/include/yarp/os/Nodes.h, src/libYARP_OS/src/Nodes.cpp
* Refactor the whole class implementation using c++11
* Make the critical sections as small as possible
* Cleanup
(I'm testing the git-hub command line tool to create this PR, so please
forgive me if I mess this up)
=> OS: Fix race condition in Nodes

src/libYARP_OS/include/yarp/os/NestedContact.h, src/libYARP_OS/src/NestedContact.cpp
* Use PIMPL
* Move implementation in .cpp
* Cleanup
=> OS/NestedContact: Cleanup

src/libYARP_dev/src/devices/ServerFrameGrabber/ServerFrameGrabber.cpp
Fix a copy-paste error while refactoring in commit 16d8ad3
=> ServerFrameGrabber: fix default wrapper

src/devices/realsense2/realsense2Driver.cpp
Fix an error on a return value.
=> RealSense device: fix error in return value

.gitignore
Add `CMakeSettings.json` file and `.vs` folder.
=> Update gitignore including VS2017 files

doc/release/v2_3_72_1.md, src/libYARP_profiler/src/NetworkProfiler.cpp, src/yarpmanager/src-manager/clusterWidget.cpp
Minor fixes to the `ClusterWidget`.
It fixes #1536 .
Tested on `iCubGenova01` setup.
=> Fix yarpmanager

doc/release/v2_3_72_1.md, src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/applicationviewwidget.h
This PR fixes #964 .
Moreover it fixes the same bug in the resources list.
please review code
=> Fix yarpmanager res/conn list

src/devices/multipleanalogsensorsclient/MultipleAnalogSensorsClient.cpp, src/devices/multipleanalogsensorsremapper/MultipleAnalogSensorsRemapper.cpp, src/devices/multipleanalogsensorsremapper/MultipleAnalogSensorsRemapper.h, src/libYARP_dev/include/yarp/dev/MultipleAnalogSensorsInterfaces.h
Furthermore, fix https://github.com/robotology/yarp/issues/1666 .
=>  Improve MultipleAnalogSensorInterfaces docs 

doc/release/v3_0_0.md, doc/yarp_env_variables.md, src/libYARP_OS/include/yarp/os/Bottle.h, src/libYARP_OS/include/yarp/os/SharedLibraryFactory.h, src/libYARP_OS/include/yarp/os/Thread.h, src/libYARP_OS/include/yarp/os/impl/BottleImpl.h, src/libYARP_OS/include/yarp/os/impl/ThreadImpl.h, src/libYARP_OS/src/Bottle.cpp, src/libYARP_OS/src/BottleImpl.cpp, src/libYARP_OS/src/Carriers.cpp, src/libYARP_OS/src/Network.cpp, src/libYARP_OS/src/Thread.cpp, src/libYARP_OS/src/ThreadImpl.cpp, src/libYARP_OS/src/Time.cpp
This PR c11-fy `Bottle`, `BottleImpl` and `MultiNameSpace` singletons.
demoRedball tested successfully on the simulator.
=> Cleanup singleton part2

cmake/YarpFindDependencies.cmake, doc/release/v3_0_0.md
=> YARP_math enabled if eigen is found

doc/cmd_yarpdatadumper.dox, doc/release/v3_0_0.md, src/libYARP_sig/CMakeLists.txt, src/libYARP_sig/include/yarp/sig/ImageFile.h, src/libYARP_sig/src/ImageFile.cpp, src/yarpdatadumper/main.cpp
Added support to save files in jpg format. 
Requires libjpeg.
yarpdatadumper updated (--type image_jpg)
=> Support for jpg file

src/yarpdatadumper/main.cpp
This PR fixes the storing of float images that has been affected by #1712.
=> Fix yarpdatadumper when storing float images

doc/release/v3_0_1.md, src/carriers/CMakeLists.txt, src/devices/CMakeLists.txt
=> Cmake: fix configuration when CARRIER and DEVICES are OFF

doc/release/v3_0_1.md, src/yarpscope/plugin/plotter.cpp, src/yarpscope/plugin/plotter.h, src/yarpscope/plugin/qtyarpscope.cpp
=> Fix yarpscope double free

src/libYARP_dev/include/yarp/dev/Drivers.h, src/libYARP_dev/src/Drivers.cpp
=> Drivers: c++11-fy singleton

doc/release/v3_0_1.md, src/libYARP_sig/include/yarp/sig/Image.h
This PR fixes #1749.
It will break probably the ABI compatibility but I didn't find another way to fix it.
=> Fix negative vocab

src/libYARP_OS/include/yarp/os/impl/NameClient.h, src/libYARP_OS/src/NameClient.cpp, src/libYARP_OS/src/YarpNameSpace.cpp
added timeout parameter when writing to nameserver.
=> added timeout parameter  to YarpNameSpace::writeToNameServer()

doc/release/v3_1_0.md, src/libYARP_serversql/include/yarp/serversql/impl/NameServiceOnTriples.h, src/libYARP_serversql/src/NameServiceOnTriples.cpp
allows to list only the ports opened by yarprun executables
=> update yarp name help and add list of yarprun ports command

src/carriers/tcpros_carrier/yarpros.cpp, src/devices/depthCamera/depthCameraDriver.cpp, src/devices/ffmpeg/FfmpegGrabber.cpp, src/idls/rosmsg/src/RosType.cpp, src/yarplogger/mainwindow.cpp, src/yarpmanager/src-builder/builderwindow.cpp, src/yarpmanager/src-builder/propertiestable.cpp, src/yarpmanager/src-manager/entitiestreewidget.cpp, src/yarpmanager/src-manager/mainwindow.cpp, src/yarprobotinterface/XMLReader.cpp
Fixes some problems reported by Coverity static analyzer
=> Coverity fixes

src/libYARP_OS/include/yarp/os/Contactables.h, src/libYARP_OS/include/yarp/os/Node.h, src/libYARP_OS/include/yarp/os/Nodes.h, src/libYARP_OS/src/Nodes.cpp
Fixes #1501 
Still there is work to do to fully understand how this classes are expected to work and how they actually works.
=> add documentation to Node, Nodes, Contactables

src/yarpmotorgui/jointitem.cpp, src/yarpmotorgui/jointitem.h, src/yarpmotorgui/jointitem.ui, src/yarpmotorgui/mainwindow.cpp, src/yarpmotorgui/mainwindow.h, src/yarpmotorgui/partitem.cpp, src/yarpmotorgui/partitem.h
major changes to yarpmotorgui application
=> yarpmotorgui improvements

src/devices/ovrheadset/OVRHeadset.h
ovrheadset parameters documented
=> update ovrheadset parameters documentation

doc/release/v3_1_1.md, src/libYARP_dev/include/yarp/dev/IControlLimits.h
=> Fix IControlLimits.h not being a self-sufficient header

src/libYARP_OS/include/yarp/os/impl/NameConfig.h, src/libYARP_OS/src/NameConfig.cpp, src/libYARP_OS/src/Os.cpp, src/libYARP_OS/src/ResourceFinder.cpp, src/libYARP_companion/src/Companion.cpp
Also cleanup some nonsense implementations.
=> Fix "Unable to create directory" error

src/devices/CMakeLists.txt, src/devices/navigation2DServer/CMakeLists.txt
Broken by: 48c4dfdf2fbc532bfc703a308a8078f359389878
Moreover some cleanup has been done, please @randaz81 check it.
=> Fix devel builds without math

doc/release/v3_2_0.md, src/devices/CMakeLists.txt, src/devices/localization2DClient/Localization2DClient.cpp, src/devices/localization2DClient/Localization2DClient.h, src/devices/localization2DServer/CMakeLists.txt, src/devices/localization2DServer/Localization2DServer.cpp, src/devices/localization2DServer/Localization2DServer.h, src/devices/localization2DServer/localization2DServer.ini, src/devices/navigation2DClient/Navigation2DClient.cpp, src/devices/navigation2DClient/Navigation2DClient.h, src/devices/navigation2DServer/navigation2DServer.cpp, src/libYARP_dev/include/yarp/dev/ILocalization2D.h
* Added `localization2DServer `device, previously belonging to https://github.com/robotology/navigation repository.
* `yarp::dev::ILocalization2D `added the new two following methods:
` bool   getLocalizationStatus(LocalizationStatusEnum& status)`
`  bool   getEstimatedPoses(std::vector<yarp::dev::Map2DLocation>& poses)`
* `yarp::dev::ILocalization2D` added the new type: `LocalizationStatusEnum`
=> Add localizationServer device

doc/release/v3_1_1.md, src/devices/ffmpeg/FfmpegGrabber.cpp, src/devices/ffmpeg/FfmpegWriter.cpp, src/devices/ffmpeg/README.TXT, src/devices/ffmpeg/avpreamble.h, src/devices/ffmpeg/ffmpeg_api.cpp, src/devices/ffmpeg/ffmpeg_api.h
It fixes #1849
Moreover it some replaces deprecated functions and some cleanup.                                                                                                                                          
=> Ffmpeg fix debian testing compilation and replace some deprecated functions

src/libYARP_dev/include/yarp/dev/ControlBoardPid.h, src/libYARP_dev/include/yarp/dev/IRobotDescription.h, src/libYARP_dev/src/ControlBoardPid.cpp, src/libYARP_logger/include/yarp/logger/YarpLogger.h, src/libYARP_manager/include/yarp/manager/application.h, src/libYARP_manager/include/yarp/manager/arbitrator.h, src/libYARP_manager/include/yarp/manager/data.h, src/libYARP_manager/include/yarp/manager/graph.h, src/libYARP_manager/include/yarp/manager/module.h, src/libYARP_manager/include/yarp/manager/resource.h, src/libYARP_math/include/yarp/math/Vec2D.h, src/libYARP_math/src/Vec2D.cpp
This is an ABI break and therefore it should probably be in devel, but I don't care since I consider this an important bug. Also API is 100% compatible.
=> Make comparison operator const

src/carriers/h264_carrier/H264Decoder.cpp
Hi @randaz81,
as you required, I create the pull request to make available the feature of jitter removing in h264 client.
Asap I'll make optional this feature by a carrier's parameter.
=> h264: added jitter buffer plugin

doc/release/v3_1_1.md, src/libYARP_OS/src/Port.cpp, tests/libYARP_OS/PortTest.cpp
=> check if port is interrupted before resuming

.travis.yml
This should fix current issues with osx builds
=> .travis.yml: Use homebrew addon for osx

.travis.yml, cmake/YarpFindDependencies.cmake, doc/release/v3_2_0.md, src/libYARP_sig/CMakeLists.txt, src/libYARP_sig/include/yarp/sig/ImageFile.h, src/libYARP_sig/src/ImageFile.cpp
It is now possible to save image files into .png format
=> png support

doc/release/v3_2_0.md, src/yarpview/plugin/VideoSurface.qml, src/yarpview/plugin/YARPViewStatusBar.qml
added size (w,h) info for:
-the image received on the yarp port
-the image currently displayed in yarpview
=> Yarpview with size

src/devices/localization2DClient/Localization2DClient.cpp, src/devices/localization2DServer/Localization2DServer.cpp, src/devices/navigation2DClient/Navigation2DClient.cpp
Urgent fix for method getEstimatedPoses() in both Localization/Navigation clients and servers.
=> getEstimatedPoses() fix

doc/release/v3_2_0.md, src/devices/CMakeLists.txt, src/devices/batteryClient/BatteryClient.cpp, src/devices/batteryClient/BatteryClient.h, src/devices/batteryWrapper/BatteryWrapper.cpp, src/devices/batteryWrapper/BatteryWrapper.h, src/devices/batteryWrapper/CMakeLists.txt, src/devices/batteryWrapper/batteryWrapper.ini, src/devices/fakeBattery/CMakeLists.txt, src/devices/fakeBattery/fakeBattery.cpp, src/devices/fakeBattery/fakeBattery.h, src/devices/fakeBattery/fakeBattery.ini, src/libYARP_dev/include/yarp/dev/IBattery.h, src/yarpbatterygui/display.cpp, src/yarpbatterygui/display.h, src/yarpbatterygui/main.cpp
* added fakebattery device for testing purposes
* IBattery::getBatteryStatus() now uses enum instead of int
* Improved batteryWrapper device
=> Fake battery device

doc/release/v3_1_1.md, src/libYARP_OS/src/Network.cpp, src/libYARP_OS/src/NetworkClock.cpp
Re-doing PR 'cause I mess up the previous one. Sorry
=> Add Network clock initialization value that was missing in some cases.

src/carriers/h264_carrier/H264Carrier.cpp, src/carriers/h264_carrier/H264Carrier.h, src/carriers/h264_carrier/H264Decoder.cpp, src/carriers/h264_carrier/H264Decoder.h, src/carriers/h264_carrier/H264Stream.cpp, src/carriers/h264_carrier/H264Stream.h
In this pr I made removeJitter optional; before, it was the default behaviour.
Since this element could add some delay, I preferred to make it optional in order to perform some tests about it.
=> make removeJitter feature optional

src/devices/ovrheadset/TextureBattery.cpp
=> Fix yarp_ovrheadset build

doc/release/v3_2_0.md, src/devices/localization2DServer/Localization2DServer.cpp, src/devices/localization2DServer/Localization2DServer.h, src/devices/map2DServer/Map2DServer.cpp, src/devices/navigation2DClient/Navigation2DClient.cpp, src/devices/navigation2DClient/Navigation2DClient.h, src/devices/navigation2DServer/navigation2DServer.cpp, src/devices/navigation2DServer/navigation2DServer.h, src/libYARP_dev/CMakeLists.txt, src/libYARP_dev/include/yarp/dev/INavigation2D.h, src/libYARP_dev/src/INavigation2D.cpp
* added streaming port to Localization2DServer
* Navigation2DClient: added handler for rpc string commands. By default the port is called <client_name>/user_commands/rpc. Help command provided. Implemented new method getNameOfCurrentTarget()
* Navigation2DServer: cleanup, various rpc handlers moved to Navigation2DClient.
* INavigation2D: added helper static methods INavigation2DHelpers::statusToString(), stringToStatus()
* INavigation2D: added method getNameOfCurrentTarget() to the interface.
* Localization2DServer: added retrieve_position_periodically option + cleanup + added documentation banner.
=> Streaming localizer

doc/release/v3_2_0.md, src/devices/map2DClient/Map2DClient.cpp, src/devices/map2DClient/Map2DClient.h, src/devices/map2DServer/Map2DServer.cpp, src/devices/map2DServer/Map2DServer.h, src/devices/navigation2DClient/Navigation2DClient.cpp, src/devices/navigation2DClient/Navigation2DClient.h, src/libYARP_dev/CMakeLists.txt, src/libYARP_dev/include/yarp/dev/ILocalization2D.h, src/libYARP_dev/include/yarp/dev/IMap2D.h, src/libYARP_dev/include/yarp/dev/INavigation2D.h, src/libYARP_dev/include/yarp/dev/Map2DArea.h, src/libYARP_dev/src/Map2DArea.cpp, src/libYARP_dev/src/MapGrid2D.cpp, tests/libYARP_dev/MapGrid2DTest.cpp
added new class yarp::dev::Map2DArea
=> Map2d Area 

src/carriers/zfp_portmonitor/README.md
Update environment variable name to use to match the cmake find_package
[ci skip]
=> Update zfp portmonitor README.md

bindings/python/examples/example_enc.py
=> Fix python Examples

src/libYARP_OS/include/yarp/os/Timer.h
leftover in timer documentation removed. thanks to @barbalberto
=> timer documentation fix

doc/release/v3_2_0.md, src/libYARP_dev/src/devices/AnalogWrapper/AnalogWrapper.cpp, src/libYARP_dev/src/devices/AnalogWrapper/AnalogWrapper.h
This PR add the feature of opening multiple ros topics by AnalogWrapper for the case of wrenchStamped ros msg type
=> Update AnalogWrapper to handle multiple ros topics for wrenchStamped

src/devices/localization2DServer/Localization2DServer.cpp, src/devices/navigation2DServer/navigation2DServer.cpp
fixed critical race conditions during navigation2DServer and Localization2DServer opening
=> navigation server fix

doc/release/v3_2_0.md, src/devices/fakeLaser/fakeLaser.cpp, src/devices/fakeLaser/fakeLaser.h
added parameters for range configuration
=> improvements to fakeLaser device 

bindings/python/examples/yarpImage_py2.py, bindings/python/examples/yarpImage_py3.py
These are python examples for python2 and python3 on how to deal with a stream of yarp images
=> adding python examples to treat yarp images

src/libYARP_dev/src/devices/RemoteControlBoard/RemoteControlBoard.cpp
Add interrupt while closing ports and remove legacy code
=> RemoteControlBoard fix

src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp
=> imuBosch: fix conversion factor for gyro and magnetometer

src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp
:warning: WAIT #2041  BEFORE MERGING.
=> imuBosch: fix unit measure in ThreeAxis interface

example/portaudio/sound_loopback.cpp, example/portaudio/sound_receiver.cpp, example/portaudio/sound_sender_mic.cpp
=> Fix portaudio examples

doc/release/master/fix-yarpdataplayer.md, src/yarpdataplayer/include/worker.h, src/yarpdataplayer/src/worker.cpp
This PR fixes the issues where timestamps were not consistent as reported in #2049 #2052.
=> adding timing changes to yarpdataplayer

doc/release/devel/Property_refactor.md, src/libYARP_OS/include/yarp/os/Bottle.h, src/libYARP_OS/include/yarp/os/impl/BottleImpl.h, src/libYARP_OS/src/Bottle.cpp, src/libYARP_OS/src/Property.cpp
Fixes #2084 should also address comments in #2079
=> Add move ctor and copy operator to Bottle and fix property issues

src/devices/ovrheadset/OVRHeadset.cpp, src/devices/ovrheadset/OVRHeadset.h
This PR fixes the bug described in #2103 
@drdanz @aerydna
=> Add the hands_relative parameter in the ovr headset device

cmake/YarpIDL.cmake
Fixed syntax error of  issue  https://github.com/robotology/yarp/issues/2107
=> fixed regex replace syntax error

doc/release/master/yarpdataplayer_fixslider, src/yarpdataplayer/src/worker.cpp
This PR adds the missing slider functionality in the ```yarpdataplayer``` as reported in #2126
=> yarpdataplayer adding missing slider functionality

doc/release/yarp_3_3/fixYarpdataplayerPause.md, src/yarpdataplayer/include/worker.h, src/yarpdataplayer/src/worker.cpp
It fixes #2139 
Tested on my laptop.
=> Fix yarpdataplayer clock drifting when pressing pause for a long time

.travis.yml, cmake/YarpFindDependencies.cmake, doc/release/yarp_3_3/supportOpenCV4.md, src/devices/opencv/OpenCVGrabber.cpp, src/libYARP_cv/src/yarp/cv/Cv.h, src/yarpdatadumper/main.cpp, src/yarpdataplayer/src/worker.cpp, src/yarplaserscannergui/main.cpp
It fixes #1672.
It compiles also with OpenCV 3
=> Support OpenCV 4

doc/release/yarp_3_3/fixYarpdataplayerPartMismatch.md, src/yarpdataplayer/include/mainwindow.h, src/yarpdataplayer/include/utils.h, src/yarpdataplayer/src/mainwindow.cpp, src/yarpdataplayer/src/utils.cpp
It fixes #2173 .
cc @vtikha @xEnVrE
=> Fix yarpdataplayer part mismatch

doc/release/master/introduce_begin_end_for_const_iterator.md, src/libYARP_sig/src/yarp/sig/Vector.h
This PR is related to issue #2179 
@Nicogene
=> Introduce const_iterator begin() and const_iterator end() methods in yarp::sig::VectorBase class

doc/release/yarp_3_3/fixYarpatadumperVideo.md, src/yarpdatadumper/main.cpp
This PR addresses and solves #2193.
I've tested it successfully running the following:
- `yarpdev --device test_grabber`
- `yarpdatadumper --type video --connect /grabber`
=> Fix video generation in yarpdatadumper

CMakeLists.txt, doc/release/master/featureGetEstimatedOdometry.md, src/devices/fakeLaser/fakeLaser.h, src/devices/fakeLocalizerDevice/fakeLocalizerDev.cpp, src/devices/fakeLocalizerDevice/fakeLocalizerDev.h, src/devices/fakeNavigationDevice/fakeNavigationDev.cpp, src/devices/fakeNavigationDevice/fakeNavigationDev.h, src/devices/localization2DClient/Localization2DClient.cpp, src/devices/localization2DClient/Localization2DClient.h, src/devices/localization2DServer/Localization2DServer.cpp, src/devices/localization2DServer/Localization2DServer.h, src/devices/map2DClient/Map2DClient.h, src/devices/navigation2DClient/Navigation2DClient.cpp, src/devices/navigation2DClient/Navigation2DClient.h, src/devices/navigation2DServer/navigation2DServer.cpp, src/devices/navigation2DServer/navigation2DServer.h, src/libYARP_dev/src/yarp/dev/ILocalization2D.h, src/libYARP_dev/src/yarp/dev/IMap2D.cpp, src/libYARP_dev/src/yarp/dev/IMap2D.h, src/libYARP_dev/src/yarp/dev/INavigation2D.cpp, src/libYARP_dev/src/yarp/dev/INavigation2D.h
* added method yarp::dev::Nav2D::ILocalization2D::getEstimatedOdometry() to the interface.
* all devices using interface ILocalization2D updated accordingly.
* added Nav2D namespace where missing.
* added missing ROS initialization in Localization2DServer
=> Get estimated odometry

src/libYARP_sig/src/yarp/sig/Vector.h
=> YARP_sig: fix vector iterators

doc/release/yarp_3_3/fixUsbCamera.md, src/devices/usbCamera/linux/V4L_camera.cpp, src/devices/usbCamera/linux/V4L_camera.h
=> Fix usbCamera device

doc/release/master/featureLaserFromExternalPort.md, src/devices/CMakeLists.txt, src/devices/laserFromDepth/laserFromDepth.cpp, src/devices/laserFromDepth/laserFromDepth.h, src/devices/laserFromExternalPort/CMakeLists.txt, src/devices/laserFromExternalPort/laserFromExternalPort.cpp, src/devices/laserFromExternalPort/laserFromExternalPort.h, src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/yarp/dev/Lidar2DDeviceBase.cpp, src/libYARP_dev/src/yarp/dev/Lidar2DDeviceBase.h
added device driver laserFromExternalPort
=> devicedriver LaserFromExternalPort

src/devices/RGBDSensorClient/RGBDSensorClient.cpp, src/devices/RGBDSensorClient/RGBDSensorClient.h
Added parameters to set the carrier type used by RGBDSensorClient
=> Carrier for RGBDSensorClient

doc/release/master/featureBuilderTab.md, src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/applicationviewwidget.h, src/yarpmanager/src-manager/applicationviewwidget.ui, src/yarpmanager/src-manager/mainwindow.cpp, src/yarpmanager/src-manager/mainwindow.h
Moved the builder, from the hidden place to a tab in the application view.
=> Improve builder integration

doc/release/master/yarp_pray.md, src/libYARP_companion/src/yarp/companion/impl/Companion.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.h, src/libYARP_os/src/yarp/os/impl/PortCore.cpp
* Fix any issues by entrusting a Superior Entity.
* When logic fails, it's time to `yarp pray`. Watch out for palindrome mode.
=> Fix any issue (including hardware problems)

doc/release/master/featureLoadPNG.md, src/libYARP_sig/src/yarp/sig/ImageFile.cpp
Added support to load a PNG file into a `ImageOf<PixelRgb>`
=> Load PNG file

doc/release/master/isNetworkInitialized.md, src/libYARP_os/src/yarp/os/Network.cpp, src/libYARP_os/src/yarp/os/Network.h, src/libYARP_os/src/yarp/os/Time.cpp, src/libYARP_os/src/yarp/os/Time.h
* Added `bool isClockInitialized()` method
* Added `bool isNetworkInitialized()` method
=> os: Add Clock::isClockInitialized and Network::isNetworkInitialized methods

doc/release/master/log_refactor_2.md, src/libYARP_logger/src/yarp/logger/YarpLogger.cpp, src/libYARP_logger/src/yarp/logger/YarpLogger.h
* Interpret the new message format containing extra info.
Depends on #2256
=> logger: Interpret the new message format containing extra info

doc/release/master/log_refactor_3.md, src/yarplogger/logmodel.cpp, src/yarplogger/logmodel.h, src/yarplogger/logtab.cpp, src/yarplogger/logtab.h, src/yarplogger/logtab.ui, src/yarplogger/main.cpp, src/yarplogger/mainwindow.cpp, src/yarplogger/mainwindow.h, src/yarplogger/mainwindow.ui
=> Refactor to display the new info from tags and to use a custom log model

src/libYARP_os/src/yarp/os/impl/PortCore.cpp, src/libYARP_os/src/yarp/os/impl/PortCore.h
Depends on #2268 
Depends on #2266
=> os/impl/PortCore: Port to the new logging system

doc/release/master/laserDevicesRefactored.md, doc/release/master/laserDevicesRefactored2.md, src/devices/fakeLaser/fakeLaser.cpp, src/devices/fakeLaser/fakeLaser.h, src/devices/laserFromDepth/laserFromDepth.cpp, src/devices/laserFromDepth/laserFromDepth.h, src/devices/laserFromExternalPort/laserFromExternalPort.cpp, src/devices/laserFromExternalPort/laserFromExternalPort.h, src/devices/laserFromPointCloud/laserFromPointCloud.cpp, src/devices/laserFromPointCloud/laserFromPointCloud.h, src/devices/rpLidar2/rpLidar2.cpp, src/devices/rpLidar2/rpLidar2.h, src/libYARP_dev/src/yarp/dev/Lidar2DDeviceBase.cpp, src/libYARP_dev/src/yarp/dev/Lidar2DDeviceBase.h, src/yarplaserscannergui/main.cpp
*rpLidar2  now derives from Lidar2DDeviceTemplate.
Should be merged after #2205
=> rpLidar2 refactored

src/devices/ovrheadset/OVRHeadset.cpp
This fixes #2301 
@aerydna @drdanz
=> Fix includes in OVRHeadset.cpp

src/devices/ovrheadset/CMakeLists.txt, src/devices/ovrheadset/GLDebug.cpp, src/devices/ovrheadset/InputCallback.cpp, src/devices/ovrheadset/OVRHeadset.cpp, src/devices/ovrheadset/OVRHeadsetLogComponent.cpp, src/devices/ovrheadset/OVRHeadsetLogComponent.h, src/devices/ovrheadset/TextureBattery.cpp, src/devices/ovrheadset/TextureBuffer.cpp, src/devices/ovrheadset/TextureLogo.cpp, src/devices/ovrheadset/TextureStatic.cpp
Unfortunately at the moment I don't have a way to check if this compiles and works
Can anyone with an oculus and a windows machine try this? Perhaps @GiulioRomualdi?
=> devices/ovrheadset: Port to the new logging system

doc/release/master/featureLaserFromPointCloudAndMore.md, src/devices/fakeLaser/fakeLaser.cpp, src/devices/fakeLaser/fakeLaser.h, src/devices/laserFromExternalPort/laserFromExternalPort.cpp, src/devices/laserFromExternalPort/laserFromExternalPort.h, src/devices/laserFromPointCloud/laserFromPointCloud.cpp, src/devices/laserFromPointCloud/laserFromPointCloud.h, src/devices/transformClient/FrameTransformClient.cpp, src/devices/transformClient/FrameTransformClient.h, src/devices/transformServer/FrameTransformServer.cpp, src/libYARP_dev/src/yarp/dev/Lidar2DDeviceBase.cpp, src/yarplaserscannergui/main.cpp, tests/libYARP_dev/FrameTransformClientTest.cpp
This PR also includes some improvements to:
* yarplaserscannergui
* laserFromExternalPort
* fakeLaser
* frameTransformClient/frameTransformServer
=> Improvements to LaserFromPointCloud (and more)

bindings/python/CMakeLists.txt, doc/release/master/drop_python2.md
=> Drop support for python 2

src/libYARP_logger/src/yarp/logger/YarpLogger.cpp, src/libYARP_logger/src/yarp/logger/YarpLogger.h, src/yarplogger/logmodel.cpp, src/yarplogger/logmodel.h, src/yarplogger/logtab.cpp, src/yarplogger/logtab.h, src/yarplogger/mainwindow.cpp, src/yarplogger/mainwindow.h, src/yarplogger/mainwindow.ui
This PR implements necessary changes to yarplogger and yarplogger GUI to read and print the custom time implemented in a previous PR.
=> Add custom time to yarplogger and yarplogger-GUI

src/yarplogger/logmodel.cpp, src/yarplogger/messageWidget.cpp, src/yarpmanager/src-builder/applicationitem.cpp, src/yarpmanager/src-builder/arrow.cpp, src/yarpmanager/src-builder/destinationportitem.cpp, src/yarpmanager/src-builder/moduleitem.cpp, src/yarpmanager/src-builder/sourceportitem.cpp, src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/mainwindow.cpp, src/yarpmotorgui/mainwindow.cpp, src/yarpmotorgui/sequencewindow.cpp, src/yarpviz/src/portloggerdialog.cpp, src/yarpviz/src/portloggerdialog.h
=> guis: Do not make use of deprecated Qt methods

doc/release/master/featureLaserFromRosTopic.md, src/devices/CMakeLists.txt, src/devices/laserFromRosTopic/CMakeLists.txt, src/devices/laserFromRosTopic/laserFromRosTopic.cpp, src/devices/laserFromRosTopic/laserFromRosTopic.h
added `LaserFromRosTopic` device, which exposes on Yarp a lidar ROS topic (dataype `sensor_msgs::LaserScan`)
using yarp `IRangefinder2D` interface.
=> LaserFromRosTopic

doc/release/yarp_3_4/fix_depthToPC.md, src/libYARP_sig/src/yarp/sig/PointCloudUtils.cpp
Fixed bug in methods `depthToPC()` which was not properly decimating the pointcloud given in input
=> PointcloudUtils fix

cmake/YarpFindDependencies.cmake, doc/release/master/drop_opencv_2.md, src/devices/opencv/OpenCVGrabber.cpp, src/devices/usbCamera/linux/V4L_camera.cpp, src/libYARP_cv/src/yarp/cv/Cv.h, src/yarpdatadumper/main.cpp, src/yarpdataplayer/src/worker.cpp, src/yarplaserscannergui/main.cpp
As discussed in #2360 
CC @pattacini, @PeterBowman, @Nicogene
=> Drop support for OpenCV < 3

src/libYARP_os/src/yarp/os/NestedContact.cpp, src/libYARP_os/src/yarp/os/SystemInfo.cpp, src/libYARP_os/src/yarp/os/YarpNameSpace.cpp, src/libYARP_os/src/yarp/os/impl/DgramTwoWayStream.cpp, src/libYARP_os/src/yarp/os/impl/NameClient.cpp, src/libYARP_os/src/yarp/os/impl/NameConfig.cpp, src/libYARP_os/src/yarp/os/impl/PortCore.cpp, src/libYARP_os/src/yarp/os/impl/Protocol.cpp, src/libYARP_os/src/yarp/os/impl/SocketTwoWayStream.cpp, src/libYARP_os/src/yarp/os/impl/TcpFace.cpp, src/libYARP_os/src/yarp/os/impl/posix/TcpAcceptor.cpp, src/libYARP_os/src/yarp/os/impl/posix/TcpConnector.cpp, src/libYARP_os/src/yarp/os/impl/posix/TcpStream.cpp
Also add some other useful debug lines.
=> os: Log system errors using yCError instead of perror

tests/libYARP_os/PortTest.cpp
Add an unit test for `yarp::os::ModifyingCarrier`
As it is possible to see from the test, it is not possible to modify the reply on the receiver side. (See also #2379)
=> tests/Port: Add unit test for ModifyingCarrier

tests/libYARP_os/PortTest.cpp
When a port uses `enableBackgroundWrite`, block on a condition variable and use the callback from the write to wake up the process, so that we can be sure that the write-read-reply process is actually over.
Fixes #2392
Fixes #2395
=> tests: Fix ModifyingCarrier tests

doc/release/master/location_is_near_to.md, src/devices/navigation2DClient/Navigation2DClient.cpp, src/devices/navigation2DClient/Navigation2DClient.h, src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/yarp/dev/Map2DLocation.cpp, src/libYARP_dev/src/yarp/dev/Map2DLocation.h
Added method Map2DLocation::is_near_to()
=> Map2DLocation::is_near_to

doc/release/master/fake_laser_obstacle.md, src/devices/fakeLaser/fakeLaser.cpp, src/devices/fakeLaser/fakeLaser.h, src/libYARP_dev/src/yarp/dev/NavTypes.h
- added rpc port to device fakeLaser
- through the rpc is possible to dynamically create obstacles in the map.
- Use the rpc command 'help' to get additional information
=> Improvements to device fake_laser

src/libYARP_os/src/yarp/os/impl/PortCore.cpp, src/libYARP_os/src/yarp/os/impl/PortCore.h
As the comment says... "This should be using a condition variable once we have them" :smile:
=> os/impl/PortCore: Refactor connection change semaphore

bindings/yarp.i, doc/release/master/bindings_extension.md
Improvement to easily export yarp sounds to python
=> Bindings: Add extensions to the yarp::sig::Sound class

doc/release/yarp_3_4/yarpmobilebasegui_fix.md, src/yarpmobilebasegui/display.cpp
Fixed gui buttons when the value of max linear/angular velocity is < 0
=> fixed buttons of yarpmobilebasegui

src/libYARP_os/src/yarp/os/ResourceFinder.cpp, src/libYARP_os/src/yarp/os/ResourceFinder.h
Some variables have been renamed for improve code clarity. No functional changes.
=> ResourceFinder cleanup

doc/release/master/yarp_latency-test.md, src/libYARP_companion/src/CMakeLists.txt, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdLatencyTest.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.h
Added new companion command: `yarp latency-test`
=> yarp latency-test

doc/release/master/getNameOfCurrentTarget_fix.md, src/devices/fakeNavigationDevice/fakeNavigationDev.cpp, src/devices/fakeNavigationDevice/fakeNavigationDev.h, src/devices/navigation2DClient/Navigation2DClient.cpp, src/devices/navigation2DClient/Navigation2DClient.h, src/devices/navigation2DServer/navigation2DServer.cpp, src/devices/navigation2DServer/navigation2DServer.h, src/libYARP_dev/src/yarp/dev/ILocalization2D.h, tests/libYARP_dev/Navigation2DClientTest.cpp
* improved `fakeNavigationDev` for testing purposes
* fixed `getNameOfCurrentTarget()` method moving logic from `Navigation2DClient` to `navigation2DServer`
* added new tests to `Navigation2DClientTest.cpp`
=> Navigation: Fixed method getNameOfCurrentTarget()

cmake/YarpOptions.cmake, extern/catch2/README.txt, extern/catch2/catch.hpp, tests/CMakeLists.txt, tests/carriers/CMakeLists.txt, tests/devices/CMakeLists.txt, tests/libYARP_dev/CMakeLists.txt, tests/libYARP_math/CMakeLists.txt, tests/libYARP_os/CMakeLists.txt, tests/libYARP_os/impl/CMakeLists.txt, tests/libYARP_robotinterface/CMakeLists.txt, tests/libYARP_rosmsg/CMakeLists.txt, tests/libYARP_run/CMakeLists.txt, tests/libYARP_serversql/CMakeLists.txt, tests/libYARP_sig/CMakeLists.txt, tests/libYARP_wire_rep_utils/CMakeLists.txt, tests/yarpidl_rosmsg/demo/CMakeLists.txt, tests/yarpidl_thrift/demo/CMakeLists.txt
* Import catch2 2.13.4
* Port to Catch.cmake (ParseAndAddCatchTests.cmake is deprecated)
=> Catch update

cmake/YarpSystemCheck.cmake, doc/release/yarp_3_4/fix_float128_t.md
* Fixed float128_t where long double is 64 bit.
=> conf: Fix float128_t where long double is 64 bit

doc/release/master/jpg_support.md, src/devices/fakeFrameGrabber/FakeFrameGrabber.cpp, src/devices/fakeFrameGrabber/FakeFrameGrabber.h, src/libYARP_sig/src/yarp/sig/ImageFile.cpp, tests/conf/contexts/fakeFrameGrabberTest/left_test.ini, tests/conf/contexts/fakeFrameGrabberTest/right_test.ini
* yarp::sig::ImageFile.cpp Added support to read .jpg files
* added rpc port to FakeFrameGrabber, to change its mode at runtime
=> .jpg support

tests/libYARP_dev/MapGrid2DTest.cpp
Added new tests to MapGrid2DTest.cpp
=> MapGrid2DTest

cmake/YarpFindDependencies.cmake, doc/release/master/qt_5_4.md, src/yarpview/plugin/ImagePort.cpp
* Qt 5.4 or later is now requred
=> Drop support for Qt < 5.4

src/libYARP_math/src/yarp/math/Vec2D.cpp, src/libYARP_math/src/yarp/math/Vec2D.h
I'm not sure if this will work on all platforms, but it is worth a try
=> math/Vec2D: Fix -Wattributes warning 

doc/release/yarp_3_4/getEstimatedOdometryFix.md, src/devices/localization2DClient/Localization2DClient.cpp, src/devices/localization2DServer/Localization2DServer.cpp, src/devices/navigation2DClient/Navigation2DClient.cpp, src/libYARP_dev/src/yarp/dev/ILocalization2D.h, tests/libYARP_dev/Navigation2DClientTest.cpp
Fixed missing implementation for method `getEstimatedOdometry()` in `localization2DClient`, `navigation2DClient` etc.
=> fixed for method getEstimatedOdometry()

doc/release/master/pointcloudutils.md, src/libYARP_sig/src/yarp/sig/PointCloudUtils-inl.h, src/libYARP_sig/src/yarp/sig/PointCloudUtils.h
added unordered point cloud generation to remove zero points
=> sig: pointcloudutils added ordered and unordered pointcloud generation

src/libYARP_sig/src/yarp/sig/Image.cpp
=> sig/Image: Simplify move constructor and assigment operator

cmake/YarpSystemCheck.cmake
Added /zC:__cplusplus to obtain the correct cplusplus version with macro __cplusplus
=> added /zC:__cplusplus option to makefile

src/devices/frameTransformClient/frameTransformClient.cpp, src/devices/frameTransformStorage/FrameTransformStorage.cpp, src/devices/frameTransformUtils/frameTransformContainer.cpp, src/libYARP_dev/src/yarp/dev/IJoypadController.cpp, src/libYARP_sig/src/yarp/sig/SoundFileWav.cpp
Removed some warnings that where showing up during compilation.
=> Devices compilation warnings removed

doc/main.dox, doc/nws_and_nwc_architecture.md
added the documentation already present in https://github.com/robotology/yarp/discussions/2441 to yarp doxgen
=> added nws and nwc section to documentation

doc/release/master/refactor_frameTransformStorage.md, src/devices/frameTransformStorage/FrameTransformStorage.cpp, src/devices/frameTransformStorage/FrameTransformStorage.h
Changed `FrameTransformStorage` inherited class. It now inherits from `WrapperSingle`
=> Refactor FrameTransformStorage

tests/libYARP_dev/CMakeLists.txt, tests/libYARP_dev/newFrameTransformClientTest.cpp
Added tests for the new frametransformclient local only.
=> added tests for frametransformclient

src/libYARP_companion/src/yarp/companion/impl/Companion.cmdLatencyTest.cpp
* Use "write-reply" on a single connection, instead of "write-write" on
two separate connections if the carrier allows it.
* Add "--no-reply" option to disable the above behaviour and always use
two separate connections
* Add missing options to help
* Fix a few minor issues
Apparently on some setups, using a single channel has a significant impact on the latency, this PR makes `yarp latency-test` use a single connection whenever the carrier allows it, and it adds a `--no-reply` option to disable this behaviour`
=> yarp latency-test: A few enhancements

doc/audio_doc.dox, src/libYARP_dev/src/yarp/dev/AudioRecorderDeviceBase.cpp
=> Doc audio fix

.reuse/dep5, doc/release/master/rplidar_sdk_udate.md, extern/rplidar/README.txt, extern/rplidar/sdk/include/rplidar.h, extern/rplidar/sdk/include/rplidar_cmd.h, extern/rplidar/sdk/include/rplidar_driver.h, extern/rplidar/sdk/include/rplidar_protocol.h, extern/rplidar/sdk/include/rptypes.h, extern/rplidar/sdk/src/arch/macOS/net_serial.cpp, extern/rplidar/sdk/src/arch/win32/arch_win32.h, extern/rplidar/sdk/src/arch/win32/net_serial.cpp, extern/rplidar/sdk/src/arch/win32/net_serial.h, extern/rplidar/sdk/src/arch/win32/timer.cpp, extern/rplidar/sdk/src/arch/win32/timer.h, extern/rplidar/sdk/src/arch/win32/winthread.hpp, extern/rplidar/sdk/src/hal/abs_rxtx.h, extern/rplidar/sdk/src/hal/event.h, extern/rplidar/sdk/src/hal/locker.h, extern/rplidar/sdk/src/hal/thread.cpp, extern/rplidar/sdk/src/hal/thread.h, extern/rplidar/sdk/src/hal/types.h, extern/rplidar/sdk/src/hal/util.h, extern/rplidar/sdk/src/rplidar_driver.cpp, extern/rplidar/sdk/src/rplidar_driver_TCP.h, extern/rplidar/sdk/src/rplidar_driver_impl.h, extern/rplidar/sdk/src/rplidar_driver_serial.h, extern/rplidar/sdk/src/sdkcommon.h
* `extern/rplidar` updated to the latest version from https://github.com/Slamtec/rplidar_sdk
* affects yarp device `rplidar2`
=> rplidar sdk update

doc/release/yarp_3_5/fix_map2D_nws.md, src/devices/map2DServer/Map2D_nws_yarp.cpp
Fixed three little error/typos which prevented Map2D_nws_yarp::parse_vocab_command from working correctly.
=> Fixed little errors in Map2D_nws_yarp::parse_vocab_command

src/devices/rpLidar2/rpLidar2.cpp, src/devices/rpLidar3/rpLidar3.cpp, src/devices/rpLidar3/rpLidar3.h, src/yarplaserscannergui/main.cpp
Improvements to device rplidar3
continuation of : https://github.com/robotology/yarp/pull/2675
=> Rplidar3 improv (cont)

doc/release/yarp_3_5/fix_frameTransformSet_nwc_ros.md, src/devices/frameTransformSet/FrameTransformSet_nwc_ros.cpp
Fixed bug in `frameTransformSet_nwc_ros::publishFrameTransforms`.
=> Fix frameTransformSet_nwc_ros

doc/release/master/getCentroid.md, src/libYARP_dev/src/yarp/dev/Map2DArea.cpp, src/libYARP_dev/src/yarp/dev/Map2DArea.h
`Map2DArea` : added new method `Map2DArea::getCentroid()`
=> Map2DArea::getCentroid

doc/release/yarp_3_5/fix_period_RGBDSensor_nws_ros.md, src/devices/RGBDSensorWrapper/RgbdSensor_nws_ros.cpp, src/devices/RGBDSensorWrapper/RgbdSensor_nws_ros.h
The period was still in milliseconds
=> Fixed bug in rgbdSensor_nws::open

doc/release/master/fakeLaser_with_localization2D_nwc_yarp.md, src/devices/fakeLaser/fakeLaser.cpp, src/devices/fakeLaser/fakeLaser.h
fakeLaser device extended to connect to localization2D_nwc_yarp instead of localization2DClient
=> fakeLaser improvements

doc/release/master/yarploggerfix_ap5_ap6.md, src/libYARP_logger/src/CMakeLists.txt, src/libYARP_logger/src/yarp/logger/YarpLogger.cpp, src/libYARP_logger/src/yarp/logger/YarpLogger.h, src/libYARP_logger/src/yarp/logger/YarpLoggerFiles.cpp, src/yarplogger/mainwindow.cpp
for points 5 and 6 discussed in https://github.com/robotology/community/discussions/558
=> improvements to yarplogger

doc/release/master/yarpmotogui_slider.md, src/yarpmotorgui/jointitem.cpp, src/yarpmotorgui/jointitem.h, src/yarpmotorgui/mainwindow.cpp, src/yarpmotorgui/mainwindow.h, src/yarpmotorgui/partitem.cpp, src/yarpmotorgui/partitem.h, src/yarpmotorgui/sliderWithTarget.cpp, src/yarpmotorgui/sliderWithTarget.h
yarpmotorgui: improved slider graphics, with the displayed reference value (optional, enabled from the menu, default off)
=> yarpmotorgui improved slider

tests/libYARP_os/TimeTest.cpp
=> improved libYARP_os TimeTest

src/yarpmotorgui/jointitem.cpp, src/yarpmotorgui/jointitem.ui, src/yarpmotorgui/mainwindow.cpp, src/yarpmotorgui/partitem.cpp, src/yarpmotorgui/partitem.h
It also changes the default messages shown in the HF tab to ``UNKNOWN``.
=> Fix some yarpmotorgui memory leaks and warnings

src/devices/ILocalization2DMsgs/idl_generated_code/return_get_estimated_poses.cpp, src/devices/IMap2DMsgs/idl_generated_code/return_get_all_areas.cpp, src/devices/IMap2DMsgs/idl_generated_code/return_get_all_locations.cpp, src/devices/IMap2DMsgs/idl_generated_code/return_get_all_paths.cpp, src/devices/IMap2DMsgs/idl_generated_code/return_get_areas_list.cpp, src/devices/IMap2DMsgs/idl_generated_code/return_get_locations_list.cpp, src/devices/IMap2DMsgs/idl_generated_code/return_get_map_names.cpp, src/devices/IMap2DMsgs/idl_generated_code/return_get_paths_list.cpp, src/devices/frameTransformStorageMsgs/idl_generated_code/FrameTransformStorageSetRPC.cpp, src/devices/frameTransformStorageMsgs/idl_generated_code/return_getAllTransforms.cpp, src/devices/multipleAnalogSensorsMsgs/idl_generated_code/SensorMeasurements.cpp, src/devices/multipleAnalogSensorsMsgs/idl_generated_code/SensorRPCData.cpp, src/libYARP_dev/src/idl_generated_code/yarp/dev/Map2DAreaData.cpp, src/libYARP_dev/src/idl_generated_code/yarp/dev/Map2DPathData.cpp, src/yarpdataplayer-console/idl_generated_code/yarpdataplayer_console_IDL.cpp, src/yarpidl_thrift/src/t_yarp_generator.cc, tests/yarpidl_thrift/demo/CMakeLists.txt, tests/yarpidl_thrift/demo/mapOfLists.thrift
=> yarpidl_thrift: Fix regression in map of lists serialization

doc/release/yarp_3_6/catch2_v2.13.8.md, extern/catch2/README.txt, extern/catch2/catch.hpp
The old version (v2.13.4) fails to build on some configurations with c++17 enabled.
=> Import catch2 v2.13.8

doc/release/master/topic-test.md, src/libYARP_companion/src/CMakeLists.txt, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdLatencyTest.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdStats.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdTopicTest.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.h
* added new companion command `yarp topic-test`
* minor improvements to companion command `yarp latency-test`
=> yarp topic-test

doc/install_linux.md, doc/main.dox, doc/yarp-doxygen-header.html, doc/yarpdataplayer_example.dox
move all istances of icub.org to icub.eu
=> from icub.org to icub.eu

src/carriers/mjpeg_carrier/MjpegCarrier.cpp
Fix https://github.com/robotology/yarp/issues/2353 .
=> Fix compilation when using plain libjpeg

doc/release/master/sound-marker.md, src/devices/audioToFileDevice/audioToFileDevice.cpp, src/devices/audioToFileDevice/audioToFileDevice.h, src/portmonitors/CMakeLists.txt, src/portmonitors/sound_marker/CMakeLists.txt, src/portmonitors/sound_marker/README.md, src/portmonitors/sound_marker/Sound_marker.cpp, src/portmonitors/sound_marker/Sound_marker.h
* added new portmonitor `sound_marker`
* `audioToFileDevice` added new option: `--save_mode break_file`
=> Sound marker

src/devices/ControlBoardWrapper/ControlBoard_nws_ros.cpp, src/devices/ControlBoardWrapper/ControlBoard_nws_yarp.cpp
Check if the encoders timestamps are consistent
=> CB_NWS encoder check

src/libYARP_robotinterface/src/yarp/robotinterface/impl/XMLReaderFileV3.cpp
fixes issue https://github.com/robotology/yarp/issues/2812 about parsing lists in extern-name parameter of yarprobotinterface.
=> yarprobotinterface extern-name fix

doc/release/master/audioToFileDeviceMarked.md, src/devices/audioToFileDevice/audioToFileDevice.cpp, src/devices/audioToFileDevice/audioToFileDevice.h
`audioToFileDevice`: added option --add_marker
=> audioToFileDevice: audio marker

src/devices/odometry2D_nws_ros/Odometry2D_nws_ros.cpp, src/devices/odometry2D_nws_yarp/Odometry2D_nws_yarp.cpp
fixed issue with std::isnan from cmath on macos
=> fixed issue with std::isnan from cmath on macos

src/libYARP_conf/src/yarp/conf/string.h, src/libYARP_os/src/yarp/os/Header.cpp, src/libYARP_sig/src/yarp/sig/Image.cpp
As per the title, this PR adds missing includes as per #2863
=> Add missing includes

doc/release/yarp_3_7/improved_integration_tests.md, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdPlugin.cpp, tests/integration/CMakeLists.txt
Added integration tests to check the correct execution of the following commands:
yarp --version
yarpdev --list
yarp plugin --all
=> Improved integration tests in CI

cmake/YarpPlugin.cmake, src/devices/odometry2D_nws_ros/CMakeLists.txt, src/devices/odometry2D_nws_yarp/CMakeLists.txt, tests/integration/CMakeLists.txt
Improved CI to catch some undetected issues on plugins. Integration tests are expected to fail.
=> Improved plugins CI

doc/release/master/rangefinder2D_nwc_yarp.md, src/devices/CMakeLists.txt, src/devices/Rangefinder2DClient/CMakeLists.txt, src/devices/Rangefinder2DClient/Rangefinder2DClient.cpp, src/devices/Rangefinder2DClient/tests/CMakeLists.txt, src/devices/Rangefinder2DClient/tests/Rangefinder2DClientTest.cpp, src/devices/Rangefinder2D_nwc_yarp/CMakeLists.txt, src/devices/Rangefinder2D_nwc_yarp/Rangefinder2D_nwc_yarp.cpp, src/devices/Rangefinder2D_nwc_yarp/Rangefinder2D_nwc_yarp.h, src/devices/Rangefinder2D_nwc_yarp/tests/CMakeLists.txt, src/devices/Rangefinder2D_nwc_yarp/tests/Rangefinder2D_nwc_yarpTest.cpp, src/devices/Rangefinder2D_nws_yarp/CMakeLists.txt, src/devices/Rangefinder2D_nws_yarp/tests/CMakeLists.txt, src/devices/Rangefinder2D_nws_yarp/tests/Rangefinder2D_nws_yarpTest.cpp, src/devices/fakeLaser/CMakeLists.txt, src/devices/fakeLaser/fakeLaser.h, src/devices/fakeLaser/tests/CMakeLists.txt, src/devices/fakeLaser/tests/fakeLaserTest.cpp, src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/yarp/dev/tests/IRangefinder2DTest.cpp, src/libYARP_dev/src/yarp/dev/tests/IRangefinder2DTest.h
added new device rangefinder2D_nwc_yarp
=> Rangefinder2D_nwc_yarp

doc/release/master/yarpmotorgui_hwfault_motorpos.md, src/devices/fakeMotionControl/fakeMotionControl.cpp, src/yarpmotorgui/jointitem.cpp, src/yarpmotorgui/jointitem.ui
Added visualization of motor position when a joint is in hardware fault
=> Yarpmotorgui hwfault motorpos

.github/workflows/ci.yml, CMakeLists.txt, doc/release/master/ycm_0_15_1.md
ycm 0.15.1 is now used on github CI.
ycm 0.15.1 is now required by Yarp.
=> YCM 0.15.1 now used in Yarp

.github/workflows/ci.yml
* removed `nick-invision/retry@v2.2.0` retry actions
* fixed deprecated set-output commands
* fixed node.js warnings
=> Improvement to Yarp CI

tests/misc/check_license.pl
=> License update 2023

.github/workflows/ci.yml, tests/misc/CMakeLists.txt, tests/misc/check_tests.py, tests/misc/check_tests_skip.txt
Added check_tests.py script to verify that each device has a corresponding test
=> Check tests

src/devices/frameTransformGet/FrameTransformGet_nws_yarp.cpp, src/devices/frameTransformStorage/FrameTransformStorage.cpp, src/devices/frameTransformStorage/FrameTransformStorage.h
fixed some devices' segfaults on closure
=> fixed some devices' segfaults on closure

doc/release/yarp_3_8/master.md, src/devices/navigation2D_nws_yarp/navigation2D_nws_yarp.cpp, src/devices/navigation2D_nws_yarp/navigation2D_nws_yarp.h
Added status port to navigation2d_nws to help with the sensor network integration
=> Added status port to navigation2d_nws

src/devices/serialPort_nws_yarp/serialPort_nws_yarp.cpp
fixed segfault of serialPort_nws_yarp, added debug messages
=> fix for serialPort_nws_yarp

doc/release/yarp_3_8/wav_files_fix.md, src/libYARP_sig/src/yarp/sig/SoundFileWav.cpp
Fixed segfault when reading a mono .wav file from disk
=> wav files fix

doc/release/yarp_3_8/feature_device_speechTranscription_nwc_yarp.md, src/devices/CMakeLists.txt, src/devices/speechTranscription_nwc_yarp/CMakeLists.txt, src/devices/speechTranscription_nwc_yarp/SpeechTranscription_nwc_yarp.cpp, src/devices/speechTranscription_nwc_yarp/SpeechTranscription_nwc_yarp.h, src/devices/speechTranscription_nwc_yarp/tests/CMakeLists.txt, src/devices/speechTranscription_nwc_yarp/tests/speechTranscription_nwc_yarp_test.cpp
* Added a `yarp` `nwc` for the `ISpeechTranscription` interface and the corresponding test
=> Feature: speechTranscription_nwc_yarp

cmake/YarpFindDependencies.cmake, doc/release/yarp_3_9_master/yarpaudiocontrolgui.md, src/CMakeLists.txt, src/yarpaudiocontrolgui/CMakeLists.txt, src/yarpaudiocontrolgui/main.cpp
Added new gui `yarpaudiocontrolgui` to start/stop an `audioRecorder_nwc_yarp` or an `audioPlayer_nwc_yarp` device
=> yarpaudiocontrolgui

doc/release/yarp_3_8/feature_device_speechSynthesizer_nwc_yarp.md, src/devices/CMakeLists.txt, src/devices/speechSynthesizer_nwc_yarp/CMakeLists.txt, src/devices/speechSynthesizer_nwc_yarp/SpeechSynthesizer_nwc_yarp.cpp, src/devices/speechSynthesizer_nwc_yarp/SpeechSynthesizer_nwc_yarp.h, src/devices/speechSynthesizer_nwc_yarp/tests/CMakeLists.txt, src/devices/speechSynthesizer_nwc_yarp/tests/speechSynthesizer_nwc_yarp_test.cpp
* Added a `yarp` `nwc` for the `ISpeechSynthesizer` interface and the corresponding test
=> Feature: speechSynthesizer_nwc_yarp

doc/release/yarp_3_8/audioRecorderBase_fix.md, src/libYARP_dev/src/yarp/dev/AudioRecorderDeviceBase.cpp
Fixed segfault in audioRecorderDeviceBase
=> Fixed segfault in audioRecorderDeviceBase

src/devices/audioRecorder_nws_yarp/tests/audioRecorder_nws_yarp_test.cpp, src/devices/fakeMicrophone/fakeMicrophone.cpp, src/libYARP_dev/src/yarp/dev/AudioRecorderDeviceBase.cpp
improved audioRecorder_nws_test.
Used to detect https://github.com/robotology/yarp/pull/3021
=> improved audioRecorder_nws_test

doc/module_devices/frametransform.dox, doc/release/yarp_3_8/fix_dox_frameTransformServer.md
* Fixed a couple of lines in the `frameTransformServer` usage documentation page
=> Fix frameTransformServer

src/libYARP_os/src/yarp/os/Log.cpp
=> log.cpp fix

extern/catch2/README.txt, extern/catch2/catch2/catch_amalgamated.cpp, extern/catch2/catch2/catch_amalgamated.hpp
Catch library updated from Version: 3.2.1 to Version: 3.4.0
=> Catch library 3.4.0 update

extern/thrift/thrift/compiler/cpp/src/thrift/generate/t_generator.h, src/libYARP_math/src/yarp/math/Vec2D.h, src/libYARP_os/src/yarp/os/SystemInfo.cpp
A set of changes that make Yarp compatible both on cpp17 and cpp20 standards.
In this PR only cpp17 is tested.
=> CPP20 fixes cumulative pack

.github/workflows/ci.yml
- added cmake 3.26, 3.27
- added macos13, removed macos11
- added windows 2022 - VS2022
=> Updated CI

src/devices/audioToFileDevice/CMakeLists.txt, src/devices/audioToFileDevice/audioToFileDevice.cpp, src/devices/audioToFileDevice/audioToFileDevice.h, src/devices/audioToFileDevice/audioToFileDeviceParams.cpp, src/devices/audioToFileDevice/audioToFileDeviceParams.h, src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/yarp/dev/IDeviceDriverParams.cpp, src/libYARP_dev/src/yarp/dev/IDeviceDriverParams.h
added new interface `IDeviceDriverParams` of Device Driver parameters handling.
Example applied to device `audioToFileDeviceParams.h`
=> IDeviceDriverParams 

src/libYARP_os/src/yarp/os/Network.h
See https://github.com/orgs/robotology/discussions/680 . @Nicogene @paliasgh
=> Fix documentation of isConnected method

doc/release/master.md, docker/Dockerfile
* Added two parameters to yarp `Dockerfile`:
* `base_img` to allow starting from different parent images
* `yarp_branch` to set the yarp version the users might need in their image
=> Parameters for Dockerfile

src/libYARP_sig/src/CMakeLists.txt
Tiny follow-up to https://github.com/robotology/yarp/pull/3137, see my unanswered comments there.
=> Populate CMake property with IDL impl headers

src/yarplaserscannergui/main.cpp
improvements to yarplaserscannergui: 
- opencv C -> C++
- fix fo client -> nwc
=> yarplaserscannergui improvements

src/libYARP_sig/src/CMakeLists.txt, src/libYARP_sig/src/yarp/sig/PointCloud.cpp, src/libYARP_sig/src/yarp/sig/PointCloud.h, src/libYARP_sig/tests/PointCloudTest.cpp
Pointcloud template now splitted in .cpp and .h files
Added method pointcloud::sortDataZ to order points from 0 to inf 
Added method pointcloud::filterDataZ to keep zmin<points<zmax
=> Pointcloud sorting

.github/workflows/ci.yml
just edited `.github/workflows/ci.yml` to add CI for Ubuntu 24.04
=> Added CI for Ubuntu24.04

doc/release/master.md, src/libYARP_sig/src/yarp/sig/PointCloudUtils-inl.h, src/libYARP_sig/src/yarp/sig/PointCloudUtils.cpp, src/libYARP_sig/src/yarp/sig/PointCloudUtils.h, src/libYARP_sig/tests/PointCloudTest.cpp
Added new functionalities to pointCloud library.
=> Added new functionalities to pointCloud library

src/devices/audioFromFileDevice/AudioFromFileDevice.cpp, src/libYARP_dev/src/yarp/dev/ReturnValue.cpp, src/libYARP_dev/src/yarp/dev/ReturnValue.h, src/libYARP_dev/tests/ReturnValueTest.cpp
Improvements to the macros controlling the behaviour of yarp::dev::ReturnValue
=> ReturnValue improvements

cmake/YarpIDL.cmake
Rosmsg tool is deprecated. Removed leftovers in cmake fiile
=> Removed references to rosmsg from YarpIDL.cmake

src/devices/networkWrappers/RGBDSensorClient/RGBDSensorClient.cpp
=> RGBDSensorClient: fix setRgbFov

src/guis/yarpmanager/src-manager/main.cpp, src/guis/yarpmanager/src-manager/mainwindow.cpp
this PR adds an option (--load_application) to automatically load an application inside the main window
=> add option to load a default application in yarpmanager in the main window

bindings/python/CMakeLists.txt
Fix https://github.com/robotology/yarp/issues/3246#issue-3195448803
=> Fix sysconfig import for python version >=3.12

.github/workflows/ci.yml, CMakeLists.txt
YCM 0.18.0 now required
CI update
=> YCM 0.18.0 now required
