src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.cpp
Minimize number of parameters if only one subdevice is used. 
See https://github.com/robotology/yarp/issues/310#issuecomment-62872910 .
=> Simplify use of controlboardwrapper2

src/libYARP_dev/include/yarp/dev/ControlBoardInterfaces.h, src/libYARP_dev/src/modules/ControlBoardWrapper/StreamingMessagesParser.cpp, src/libYARP_dev/src/modules/ControlBoardWrapper/StreamingMessagesParser.h, src/libYARP_dev/src/modules/RemoteControlBoard/RemoteControlBoard.cpp
This PR should change how the `setRefTorque` and `setRefTorques` handle the request passing from RPC to streaming.
=> setRefTorque/s implemented using streaming instead of RPC

doc/yarp_swig.dox
Two small changes related to compilation and installation of SWIG bindings:
1. remove "good for Python" comment from the "sudo make install" line;
2. add a paragraph describing the PYTHONPATH option to use the bindings without superuser privileges.
See also https://github.com/robotology/yarp/issues/357
=> Update yarp_swig.dox tutorial: PYTHONPATH

src/libYARP_dev/src/modules/RemoteControlBoard/RemoteControlBoard.cpp
The current version of extendedIntputStatePort is not thread safe.
Examining the two following lines, the contents of the shared vector last_wholePart may be modified by another thread before the std::copy(), or maybe during the copy.
bool ret = extendedIntputStatePort.getLast(last_wholePart, lastStamp, localArrivalTime);
std::copy(last_wholePart.jointVelocity.begin(), last_wholePart.jointVelocity.end(), spds);
In the proposed patch, i added a mutex to ensure multi-thread safety.
=> added mutex to ensure multi-thread safety

src/libYARP_OS/CMakeLists.txt, src/libYARP_OS/harness/TestList.h, src/libYARP_OS/harness/UnitTestTest.cpp, src/libYARP_OS/include/yarp/os/impl/UnitTest.h, src/libYARP_OS/src/UnitTest.cpp
This is some support for memory checks I'll be adding in later PRs, basically adding tests that yarp does not allocate memory during performance-sensitive operations.
It relies on overriding new/delete.  This appears to conflict with something ACE is doing.  Reserving these tests for a no-ace build is fine for my purposes.  None of this code will be run unless YARP is compiled with a special `YARP_TEST_HEAP` flag (marked as advanced).
=> [YARP_OS] add hooks for checking heap allocation in regression tests

src/libYARP_dev/include/yarp/dev/ControlBoardInterfaces.h, src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.h, src/libYARP_dev/src/modules/ControlBoardWrapper/RPCMessagesParser.cpp, src/libYARP_dev/src/modules/ControlBoardWrapper/RPCMessagesParser.h, src/libYARP_dev/src/modules/RemoteControlBoard/RemoteControlBoard.cpp
Implement protocol check for emotecontrolboard and controlboardwrapper2. The check only issues a warning. In the future we can make it a strict check (however, the option --ignoreProtocolCheck can be added for debugging, uncomment line RemoteControlBoard.cpp:1073)
=> added version check for remotecontrolboard and controlboardwrapper2

.travis.yml, src/libYARP_OS/harness/BufferedConnectionWriterTest.cpp, src/libYARP_OS/include/yarp/os/ManagedBytes.h, src/libYARP_OS/include/yarp/os/impl/BufferedConnectionWriter.h, src/libYARP_OS/include/yarp/os/impl/PortCore.h, src/libYARP_OS/src/BufferedConnectionWriter.cpp, src/libYARP_OS/src/PortCore.cpp
This eliminates one set of unnecessary memory allocations associated with sending envelope messages (e.g. timestamps), see #353. There's more to do for that issue, this is just one piece.  The PR also adds a bunch of documentation to the `BufferedConnectionWriter` class, since I needed to upgrade it a bit.
=> [YARP_OS] reduce memory churn for envelope messages 

src/libYARP_OS/include/yarp/os/impl/Logger.h
The yarp library has a lot of internal debug messages which are
hidden by default but can be shown by setting the YARP_VERBOSE
environment variable.  This commit strips the code generating these
messages from the release build, in order to improve performance.
Debug builds are untouched.
=> [YARP_OS] make yarp-internal debug messages evaporate in release mode

bindings/tests/csharp/TestStamp.cs, bindings/tests/csharp/run.sh, bindings/yarp.i
This method expects a PortWriter. Users will typically pass a Portable
which is both a PortReader and a PortWriter. Swig has a tough time
translating multiple inheritance (for good reason), so translations
may not know that Portables are PortWriters (see #372 for example).
We can help out by explicitly accepting Portables.
=> [swig] fix translation of Contactable::setEnvelope, fixes #372

.travis.yml, src/libYARP_OS/src/SocketTwoWayStream.cpp, tests/integration/CMakeLists.txt, tests/integration/check-http.sh
This is a test for the problem described in #341. I wasn't able to replicate it with a yarp-to-yarp connection, I think yarp is too forgiving, so I show it here against `curl`. This test currently fails for me when compiling without ACE. /cc @drdanz
=> [test] add integration test for http protocol against curl

src/yarpdataplayer-gtk/CMakeLists.txt
Fixes #388
@paulfitz I cannot test the fix right now (working with the smartphone) Can you please test it and eventually merge it?
If it works, I think that the same needs to be done for the qt version...
=> [yarpdataplayer-gtk] Do not build without opencv

bindings/yarp.i, conf/template/yarp_config_system.h.in, doc/port_expert.dox, example/port_power/TargetVer1.h, example/port_power/TargetVer1b.h, src/carriers/wire_rep_utils/BlobNetworkHeader.h, src/carriers/wire_rep_utils/WireImage.h, src/libYARP_OS/CMakeLists.txt, src/libYARP_OS/harness/BinPortableTest.cpp, src/libYARP_OS/include/yarp/os/SharedLibraryClassApi.h, src/libYARP_OS/include/yarp/os/begin_pack_for_net.h, src/libYARP_OS/include/yarp/os/end_pack_for_net.h, src/libYARP_sig/include/yarp/sig/Image.h, src/libYARP_sig/include/yarp/sig/ImageNetworkHeader.h, src/libYARP_sig/src/Matrix.cpp, src/libYARP_sig/src/SoundFile.cpp, src/libYARP_sig/src/Vector.cpp
Using headers for packing the structures is risky since headers might end up being moved away from the structure.
This patch replaces the ``begin_pack_for_net.h`` and ``end_pack_from_net.h`` headers with two macros: ``YARP_BEGIN_PACK`` and ``YARP_END_PACK``.
The first commit adds some macro to generate portable errors and warnings at build time, this is here because I needed it in order to cause a deprecated warning when ``begin_pack_for_net.h`` and ``end_pack_from_net.h`` are used, but since I think it is an useful feature, therefore I made it "public"
I'm not sure if ``yarp/conf/system.h`` is the right place for these things, though, @paulfitz what do you think?
=> Pack macros

src/libYARP_OS/include/yarp/os/Contact.h, src/libYARP_OS/include/yarp/os/Network.h, src/libYARP_OS/src/Contact.cpp, src/libYARP_OS/src/Network.cpp
It is now possible to explicitly set the server address without using the detect method.
This addresses https://github.com/robotology/yarp/issues/394
=> Added a setNameServerContact 

bindings/yarp.i, conf/template/yarp_config_system.h.in, doc/port_expert.dox, example/port_power/TargetVer1.h, example/port_power/TargetVer1b.h, src/carriers/wire_rep_utils/BlobNetworkHeader.h, src/carriers/wire_rep_utils/WireImage.h, src/libYARP_OS/harness/BinPortableTest.cpp, src/libYARP_OS/include/yarp/os/begin_pack_for_net.h, src/libYARP_sig/include/yarp/sig/Image.h, src/libYARP_sig/include/yarp/sig/ImageNetworkHeader.h, src/libYARP_sig/src/Matrix.cpp, src/libYARP_sig/src/SoundFile.cpp, src/libYARP_sig/src/Vector.cpp
It looks like that this macro is useless, perhaps something left from before the introduction of the ``#pragma``s
I moved the definition of the macro in ``yarp/os/begin_pack_for_net.h`` in order to keep compatibility with the old code and removed all occurrences.
=> Remove useless PACKED_FOR_NET macro

src/carriers/bayer_carrier/CMakeLists.txt, src/carriers/mjpeg_carrier/CMakeLists.txt, src/carriers/mpi_carrier/CMakeLists.txt, src/carriers/portmonitor_carrier/CMakeLists.txt, src/carriers/priority_carrier/CMakeLists.txt, src/carriers/tcpros_carrier/CMakeLists.txt, src/carriers/xmlrpc_carrier/CMakeLists.txt, src/modules/PumaCalibrator/CMakeLists.txt, src/modules/dimax_u2c/CMakeLists.txt, src/modules/fakebot/CMakeLists.txt, src/modules/ffmpeg/CMakeLists.txt, src/modules/firewirecamera/CMakeLists.txt, src/modules/jrkerr/CMakeLists.txt, src/modules/kinect/OpenNI/CMakeLists.txt, src/modules/kinect/freenect/CMakeLists.txt, src/modules/meiMotionControl/CMakeLists.txt, src/modules/microphone/CMakeLists.txt, src/modules/opencv/CMakeLists.txt, src/modules/openni2/CMakeLists.txt, src/modules/portaudio/CMakeLists.txt, src/modules/serial/CMakeLists.txt, src/modules/stage/CMakeLists.txt, src/modules/urbtc/CMakeLists.txt, src/modules/vfw/CMakeLists.txt, src/modules/wxsdl/CMakeLists.txt
At the moment this works only because we add "using namespace"s in generated files but I believe that we should not endorse this. Using the full name of the class is more correct and makes it easier to understand what we are passing to the macro.
Also in order to be sure that the class name is always full, one day I would like to remove the "using namespace" from the generated files. Even though this will break some compatibility, it will make it more robust and less error prone.
=> Do not omit namespace when preparing carriers and devices

src/libYARP_dev/src/modules/AnalogWrapper/AnalogWrapper.cpp
And remove two trailing whitespaces. 
cc @barbalberto
=> [yarpdev][analogWrapper] improve verbosity when reporting error

.travis.yml, scripts/admin/check-bindings.sh, tests/integration/CMakeLists.txt, tests/integration/ros/index.sh, tests/integration/test-helper.sh
This runs the various integration tests on travis using the regular ctest machinery, resulting in some simplification.  For now it seems necessary to run those tests only under clang, since some swig targets are now too bulky for gcc with the memory travis provides. Example run: https://travis-ci.org/robotology/yarp/builds/51133895
=> [test] run integration tests via ctest

src/libYARP_OS/include/yarp/os/SharedLibraryFactory.h, src/libYARP_OS/include/yarp/os/YarpPlugin.h, src/libYARP_OS/include/yarp/os/YarpPluginSettings.h, src/libYARP_OS/src/SharedLibraryFactory.cpp, src/libYARP_dev/src/Drivers.cpp
This info is already available in the library, but it is not exposed for
use.
There are probably not many reasons for exposing this information, but
without this, the plugin factory ignores the name of the class for the
plugins, and therefore the documentation generated by harness_dev is
different.
=> Make class name available for plugin devices

src/libYARP_OS/src/BottleImpl.cpp
It defines LC_NUMERIC and other functions and types
I don't know which of the `SKIP_ACE=True` and `YARP_USE_READLINE=False` is causing this, but I could not compile without including `#include <clocale>`
=> Added inclusion of locale.h.

src/modules/openni2/OpenNI2DeviceDriverServer.cpp, src/modules/openni2/OpenNI2DeviceDriverServer.h, src/modules/openni2/OpenNI2SkeletonTracker.cpp, src/modules/openni2/OpenNI2SkeletonTracker.h
With this PR:
- Sensors with no RGB cameras are correctly initialised and RGB functionality is disabled
- The ``--noCameras`` option has been replaced with ``--noRGB``. This disables all RGB-related functionality
- Removed a warning during compilation
- Some general cleaning of white lines etc.
Commits squashed and rebased :)
Documentation will update shortly.
Many thanks to @David-Estevez for his work and testing!
=> OpenNI2 device detects and handles RGB-less sensors

src/modules/opencv/OpenCVGrabber.cpp
Without this addition, upon:
`yarpdev --device opencv_grabber --framerate 15 --verbose`
the framerate argument is only passed to the grabber wrapper:
`grabber.framerate=15 [0]
maximum rate in Hz to read from subdevice`
With this addition, opencv_grabber actually sets the framerate on the device:
`opencv_grabber.framerate=15 [-1]
if present, specifies desired camera device framerate`
Tested and works. My only concern is that I have seen some cases in the past in which an exception can be thrown when lacking certain operating system permissions on the device. A solution for that would be setting this as a separate flag, such as --opencv_framerate, but the resulting syntax would be way too long, and I additionally haven't been able to replicate the exception (*chmod 444 /dev/video** breaks …
=> make opencv_grabber attend to --framerate flag, not only the wrapper

src/libYARP_OS/include/yarp/os/SharedLibraryClassApi.h, src/libYARP_OS/src/SharedLibraryFactory.cpp
When deleting a device/carrier from a plugin, if the
yarp::dev::DeviceDriver/yarp::os::Carrier class is not the first
inherited class, instead of the destructor of the class a complete
different function was called by delete.
The double cast in the _create() and _destroy() functions are required
to ensure that everything works when `basename` is not the first
inherited class:
*  _create() will return a valid `basename` or a null pointer if
`classname` does not inherit from `basename`.
* _destroy() will ensure that we are calling `classname` destructor
even if `basename` is not the first inherited class. If the
dynamic_cast fails, it will not delete the object (that is probably
leaked), but it is less dangerous than executing some other random
function.
Also bump plugin system version an …
=> [YARP_OS] Properly cast the object in plugin create and destroy functions

src/idls/thrift/src/t_yarp_generator.cc, src/libYARP_OS/include/yarp/os/idl/WireTypes.h
Thrift auto-generated files will employ `yError()` and no longer `fprintf()` in order to stream the messages throughout the network and make them be displayed by means of `yarplogger`.
see #462
=> thrift generated files will use yError() in place of fprintf()

src/idls/rosmsg/src/RosTypeCodeGenYarp.cpp, src/libYARP_OS/harness/BottleTest.cpp, src/libYARP_OS/src/BottleImpl.cpp, src/libYARP_OS/src/WireReader.cpp, src/libYARP_OS/src/WireWriter.cpp
For compatibility with an ancient version of yarp, strings have been up to now transmitted with a null character included. More recent versions of yarp will accept either a string with or without a null termination. This commit stops transmitting that null termination, but preserves the ability to receive a null terminated string for compatibility between programs using different versions of yarp.
The motivation for this change is for ROS compatibility, see #452, but it will also be a step towards removing an awkward corner case where yarp will not faithfully transmit a non-null-terminated string that happens to have a null character embedded as its last character [as opposed to a null-terminated string :-)].
=> [ros] omit final null character when sending strings, fixes #452

scripts/yarp_completion, src/libYARP_OS/include/yarp/os/Property.h, src/libYARP_OS/src/Companion.cpp, src/libYARP_OS/src/Property.cpp, src/libYARP_OS/src/YarpPlugin.cpp
* Add method "Property::fromConfigDir" to save the name of the .ini file that generated a part of the config
* Use it to retrieve the name of the .ini file that imports a plugin
* Improve plugin command. It is now able to detect broken plugins and shows a better output. Also improve the help and implement the following commands:
* yarp plugin --help
* yarp plugin --list
* yarp plugin --all
* yarp plugin --search-path
* Update bash completion for "yarp plugin"
Examples:
```
$ yarp plugin --help
Print information about installed plugins
Usage:
* Test a specific plugin:
yarp plugin <pluginname>
yarp plugin /path/to/plugin/<libraryname>.(so|dll|dylib) <pluginpart>
* Test all the plugins:
yarp plugin --all
* Print a list of plugins:
yarp plugin --list
* Print plugin search path:
yarp plugin …
```
=> Improvements to "yarp plugin"

doc/yarp_swig.dox
Add documentation on how to compile bindings while compiling YARP. For the time being left also the "old" way of compiling, until we remove it from CMake .
ref: https://github.com/robotology/yarp/issues/318
=> [doc][swig] update compilation instructions

conf/doxygen/Doxyfile.part.template, src/libYARP_OS/include/yarp/os/ConstString.h, src/libYARP_OS/src/ConstString.cpp
Several methods are still missing, but this is a step towards having the same API as `std::string` that may cause confusion when `YARP_WRAP_STL_STRING` is disabled
=> Implement several of the std::string methods missing in ConstString

src/libYARP_OS/include/yarp/os/Os.h, src/libYARP_OS/src/Os.cpp, src/libYARP_OS/src/RFModule.cpp
Add yarp::os::abort to wrap ace::abort.
Use abort to kill RFmodule at 4th CRTL+C, because exit is not recommended for multithread process according to http://www.cplusplus.com/reference/cstdlib/exit and causes random segfaults when used.
=> Use ACE::abort instead of ACE::exit to kill RFModule

src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/modules/RemoteControlBoard/RemoteControlBoard.cpp, src/libYARP_dev/src/modules/RemoteControlBoard/stateExtendedReader.cpp, src/libYARP_dev/src/modules/msgs/stateExt.thrift, src/libYARP_dev/src/modules/msgs/yarp/include/jointData.h, src/libYARP_dev/src/modules/msgs/yarp/src/jointData.cpp
Each value broadcasted inside the stateExt port is paired with a boolean flag telling if the value is valid or not.
The flag will be set to true if the corresponding getXXX function in the remote device driver was succesful or false otherwise.
In this way if the user application tries a getMotorAcceleration and the robot/simulator does not implement this function (or it fails somehow) the return value in the user application will be false.
Right now, since all broadcasted values are always available the return value was always true but I think this is not correct.
This will re-establish the same behaviour of the former version of yarp without the stateExt.
=> Propagate return values alongside the data

src/yarpdatadumper/main.cpp, src/yarpdataplayer-qt/src/worker.cpp
- The constructor `cv::Mat(IplImage*)` disappeared and can be thus replaced by `cv::cvarrtoMat()`
- `cvCopy()` takes over `cvCopyImage()`
Hopefully, these changes are back-compatible.
=> fixes for compatibility with opencv 3.0.0

src/libYARP_OS/src/Network.cpp
When `setNameServerContact` was called the properties were correctly saved to the configuration file, but it was not reloaded (until next run of yarp).
I forced the reload by calling `activate` with the `true` flag.
I don't know if this is the most correct way.
cc @lornat75 
PS:
I think that nobody (but me) uses this function, so I think I'll not break any compatibility
PPS:
@lornat75 the fact that all configurations passes through file writing causes some issues in some configuration, e.g. read-only filesystem, etc.. I think this is quite old yarp code, but maybe we can open a (low priority) issue on making optional the writing, and/or allowing yarp to be configured also in-memory. cc @alecive
=> Forced the refresh of the nameserver properties (host, port)

doc/installation/install_mac.dox
Updated the OS X documentation to better reflect the updated YARP formula.
Specifically:
- Broadly divided in 3 major section: Installing prerequisites, installing YARP from Homebrew, installing YARP from source (and its dependencies from Homebrew)
- Removed references to installing X11 (and subsequently the PKG_CONFIG env variable. All gtk-related homebrew packages are X11-free now (and with a better Quartz theme!).
See also: #510 
@vtikha, could you please review the PR and change things that you think could be confusing to the user? I kept your writing style as much as I could, so that the instructions appear more uniform. Thanks!
All commits squashed and rebased :)
=> Update OS X YARP install docs

doc/installation/install_mac.dox
Just a simple addition, regarding the instructions for enabling bash completion in OS X.
The commit was rebased :)
=> Update docs about bash completion on OS X

doc/installation/install_mac.dox
Python support was broken in OS X ( #508 ). Now that it is fixed, I have updated the yarp homebrew formula to provide a ''--with-python'' option. 
This commit is the update to the installation docs to reflect the added option.
Commit rebased :)
=> Update OS X docs

conf/YarpOptions.cmake, src/CMakeLists.txt, tests/CMakeLists.txt
Added `YARP_BUILD_LIBRARIES_ONLY`, by default to NO.
If set to YES only libraries will be build: no `add_executable` cmake command will be called.
I could have missed something, so double check is welcome.
The rationale behind this is to allow the compilation only of yarp libraries
cc: @lornat75 @drdanz @vtikha @alecive
=> Added option to skip binaries compilation

doc/carrier_expert.dox, src/carriers/mjpeg_carrier/MjpegCarrier.cpp, src/carriers/mjpeg_carrier/MjpegCarrier.h, src/carriers/mjpeg_carrier/MjpegDecompression.cpp, src/carriers/mjpeg_carrier/MjpegDecompression.h, src/carriers/mjpeg_carrier/MjpegStream.cpp, src/carriers/mjpeg_carrier/MjpegStream.h, src/libYARP_OS/include/yarp/os/Carrier.h, src/libYARP_OS/include/yarp/os/Connection.h, src/libYARP_OS/include/yarp/os/InputStream.h, src/libYARP_OS/include/yarp/os/impl/PortCoreInputUnit.h, src/libYARP_OS/src/Network.cpp, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/PortCoreInputUnit.cpp, src/libYARP_OS/src/PortCoreOutputUnit.cpp
Allow envelope to be carried inside the stream instead of by administrative messages, and use the new methods to allow mjpeg to carry the envelope inside its stream.
The carrier will have to overload the ``yarp::os::Carrier::handleEnvelope`` method (that by default does nothing). This method will be called by the ``PortCoreOutputUnit`` for non-escapable ``Carriers`` (like the mjpeg carrier) instead of sending the administrative command containing the envelope.
On the receiving side, the ``PortCoreInputUnit`` will install a callback using the ``yarp::os::InputStream::setReadEnvelopeCallback`` method (that should be overloaded by non-escapable carriers that want to handle the envelope). The input stream must then execute the callback as soon as the envelope is ready. This is necessary, …
=> Add methods to send envelope with the stream and send envelope with mjpeg

src/yarpmanager-qt/applicationviewwidget.cpp, src/yarpmanager-qt/main.cpp
This PR re-enables inspection of connections. Created consoles are detached from the manager and are not closed when the manager closes. however this is the same behavior that we had previously and in linux so let's keep it and improve later. #542
=> Console with localbroker

src/libYARP_OS/include/yarp/os/Property.h, src/libYARP_OS/src/Property.cpp
This modification adds Property.fromCommand(char* param, bool wipe) method to the Property class to parse the command line arguments given as a string.  For example:
```c++
yarp::os::Property prop;
prop.fromCommand("--verbose --show --from test.config");
cout<<"prop.toString()"<<endl;
...
```
Result: 
```
(show) (from test.config) (verbose)
```
=> implementing Property.fromCommand() for command line arguments given as a string

doc/installation/install_mac.dox
With current version, brew tap homebrew/x11 results in a Error: Invalid tap name in OS X Yosemite.
=> [dox] [osx] fix tap name in installation doc

bindings/yarp.i, src/libYARP_OS/CMakeLists.txt, src/libYARP_OS/include/yarp/os/Network.h, src/libYARP_OS/include/yarp/os/QosStyle.h, src/libYARP_OS/src/Network.cpp, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/QosStyle.cpp, tests/libYARP_OS/NetworkTest.cpp
This pull-request implements a new API `Networkbase::setConnectionQos()` to adjust the QoS preferences of a connection. The QoS preferences are applied to the both side of a connection. That adjusts the communication's thread real-time properties (the thread which handles asynchronous read/write within a port object) and the IPV4/6 packets DSCP value. These features had already been implemented in YARP but now have been made available using the  `setConnectionQos()` API.  
Here is an example: 
```c++
yarp::os::QosStyle qos;
qos.threadPriority = 10;
qos.threadPolicy = 1;  // SCHED_FIFO on Unix
qos.packetPriority = yarp::os::QosStyle::HIGH; // DSCP 36
Network::setConnectionQos("/output", "/input", qos, qos);
```
The above example adjust the communication thread's (if available) real-time …
=> implements Networkbase::setConnectionQos() API

example/dev/fake_motor.cpp, src/libYARP_dev/CMakeLists.txt, src/libYARP_dev/include/yarp/dev/TestMotor.h, src/libYARP_dev/src/ClientControlBoard.cpp, src/libYARP_dev/src/PopulateDrivers.cpp, src/libYARP_dev/src/modules/RemoteControlBoard/RemoteControlBoard.cpp, tests/libYARP_dev/PolyDriverTest.cpp
This new device is a copy of the `remote_controlboard` freezed and it is meant to be used as a backward compatibility for the controlboard device (legacy wrapper).
In this way we can add new features to the `controlBoardWrapper2` and  only keep `remote_controlboard` updated, while leaving the couple of devices controlboard & clientcontrolboard as they are.
`Harness_dev` has been updated with an "open" test for the 2 couples
=> Add Client control board

src/libYARP_OS/src/ResourceFinder.cpp
This deadlock was caused by PR https://github.com/robotology/yarp/pull/546 .
Basically until now all yarp basic utilities and functions were not calling `Time` functions, so they could work perfectly even if yarp was using a network clock that was not publishing any data. 
After https://github.com/robotology/yarp/pull/546 , any call to `Connect` (at least with tcp carrier I guess) will cause the invocation of the ResourceFinder, that invoked the `Time::now()` call, that itself was trying to call `Connect` if used with a Network Clock:
This PR solve the issue by always using the SystemClock (instead of the NetworkClock) in the ResourceFinder (even because the time information is only used for a local cache. 
@drdanz beside this issue, don't you think that invoking the ResourceFinder just …
=> Fix deadlock while using network clock

src/libYARP_OS/include/yarp/os/SystemInfo.h, src/libYARP_OS/include/yarp/os/impl/ThreadImpl.h, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/SystemInfo.cpp, src/libYARP_OS/src/ThreadImpl.cpp
This pull request add new functionality to the port admin commands (i.e., `prop get` ) to retrieve the process ID of the port's owner and the thread ID of the connection's owner (if exist).  The thread ID equal to -1, indicates that there is not any dedicated thread for the corresponding connections. 
Example: 
`/sender`  --->  `/receiver`
```
$ yarp admin rpc /sender
>> prop get /receiver 
Response: (sched ((priority 0) (pid 24192) (tid 24221) (policy 0))) (qos ((tos 0)))
```
If `/sender` does not have a dedicated thread for the corresponding connection then 
```
>> prop get /receiver
Response: (sched ((priority 0) (pid 24192) (tid -1) (policy 0))) (qos ((tos 0)))
```
=> Getting the port's owner process and thread ID using port admin commands  

doc/installation/install_mac.dox
Furthermore installing dependencies in this way ensures that dependencies are installed with the desired options.
=> [doc] [osx] streamline installation of yarp deps

src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.h, src/libYARP_dev/src/modules/ControlBoardWrapper/SubDevice.cpp
Right now, if axisname is not available in the subdevice, the one inside [ROS] group will be used
=> ControlBoardWrapper2 get axis names for ROS topic from motionControl device

src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.h
Use dynamic allocation only once at the beginning
Add mutex to take care of concurrency problem between multiple client connected to RPC port
=> ControlBoardWrapper2: change static allocation to dynamic

src/carriers/wire_rep_utils/WireTwiddler.cpp, src/libYARP_sig/CMakeLists.txt, src/libYARP_sig/include/yarp/sig/Image.h, src/libYARP_sig/include/yarp/sig/impl/DeBayer.h, src/libYARP_sig/src/DeBayer.cpp, src/libYARP_sig/src/Image.cpp
implemented automatic debayering when reading a bayer channel from ROS; when reading from a ImageOf<PixelMono> no debayering is performed leaving freedom to the user to do what he prefers. If the channel is read from a color image it performs debayering. Current implementations are very basic and do nearest neighbor interpolation. Implemented only debayer from 8 bit GRBG to RGB, RGBA, BGR, BGRA. Better functions could be used, for example by taking from the Bayer Carrier.
=> Ros bayer (cleaned)

src/libYARP_OS/CMakeLists.txt, src/libYARP_OS/include/yarp/os/MonitorObject.h
Fixed a documentation issue on MonitorObject.h
**Rewrote header guard macro**
I put in bold the reason why I opened a PR.
In particular, as this [link](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier) states, macro starting with a single or double underscore are reserved.
I modified only one for now, but I think we should change also the others.
@drdanz @lornat75 @traversaro
=> MonitorObject.h is now installed

src/libYARP_sig/src/ImageFile.cpp
This patch fixes these 2 logical operation warnings:
```
[ 26%] Building CXX object src/libYARP_sig/CMakeFiles/YARP_sig.dir/src/ImageFile.cpp.o
/opt/iit/src/yarp/src/libYARP_sig/src/ImageFile.cpp: In function ‘bool ReadHeader(FILE*, int*, int*, int*)’:
/opt/iit/src/yarp/src/libYARP_sig/src/ImageFile.cpp:211:17: warning: logical ‘and’ of mutually exclusive tests is always false [-Wlogical-op]
while(ch<'0'&&ch>'9'&&ch!=-1)
^
/opt/iit/src/yarp/src/libYARP_sig/src/ImageFile.cpp:216:15: warning: logical ‘and’ of mutually exclusive tests is always false [-Wlogical-op]
if (ch<'0'&&ch>'9')
^
```
I *think* that the goal of the author was to jump at the first character that is a number, therefore this patch just fixes the warnings. The old conditions made it impossible to enter these 2 `if` blocks. …
=> Fix logical ‘and’ of mutually exclusive tests is always false [-Wlogical-op] warnings

src/libYARP_OS/include/yarp/os/Value.h, src/libYARP_OS/src/Value.cpp, tests/libYARP_OS/ValueTest.cpp
warning C4717: 'yarp::os::Value::operator==' : recursive on all control
paths, function will cause runtime stack overflow
This warning was introduced by ef31735
Use a ``yarp::os::impl::Storable`` instead of another ``Value`` as proxy. The proxy was already guaranteed to be a Storable (i.e. a class derived by ``Value``), but it was saved as a ``Value`` pointer, probably to hide the existence of the ``Storable`` class.
The ``Storable`` is nonetheless hidden, since it just needs to be forward-declared in the class declaration.
At some point it should disappear again, and should be hidden using the PIMPL idiom.
This change simplifies a lot understanding how the ``Value`` class works.
I also added some unit tests to check the ``Value::operator==()`` operator
CC @pattacini
=> Fix value C4717 warning

src/yarplogger-console/main.cpp
~~~
error: cannot pass non-POD object of type 'yarp::yarpLogger::LogLevel' to variadic function;
expected type from format string was 'int' [-Wnon-pod-varargs]
~~~
PR open to see if this fix the Travis build.
=> [yarplogger-console] Fix compilation in clang

src/modules/openni2/OpenNI2DeviceDriverServer.cpp, src/modules/openni2/OpenNI2DeviceDriverServer.h, src/modules/openni2/OpenNI2SkeletonTracker.cpp, src/modules/openni2/OpenNI2SkeletonTracker.h
This commit fixes the mirroring behaviour and introduces individual parameters for the mirroring of the RGB and Depth streams:
Specifically:
- Default mirroring behaviour for both streams is ``ON``
- ``--noRGBMirror`` to turn off mirroring for the RGB stream
- ``--noDepthMirror`` to turn off mirroring for the Depth stream
See also https://github.com/robotology/yarp/issues/683
All commits squashed and rebased :)
=> OpenNI2: Individual mirroring options for depth and RGB streams (thanks    to Juan Victores for the corrections)

conf/YarpInstallationHelpers.cmake, doc/yarpdatadumper.dox, src/yarpdatadumper/CMakeLists.txt, src/yarpdatadumper/yarpdatadumperAppGenerator.py
Script to automatically generate yarpmanager applications.
It is installed only if python is found in the OS.
It should run fine also on Windows, but I did not test it.
Documentation of yarpdatadumper was also updated.
I don't know what is the policy for python scripts in yarp, but this script is definitely useful and it may be helpful for all yarp users, feel free to reject PR if we prefer not to pollute yarp with script in interpreted languages. @drdanz 
Script for helping @fjandrad data collection.
=> [yarpdatadumper] Add small python helper script to yarpdatadumper

src/libYARP_dev/CMakeLists.txt, src/libYARP_dev/include/yarp/dev/DeviceDriver.h, src/libYARP_dev/src/ClientControlBoard.cpp, src/libYARP_dev/src/PolyDriver.cpp, src/libYARP_dev/src/PopulateDrivers.cpp, src/libYARP_dev/src/ServerControlBoard.cpp, src/yarprobotinterface/Module.cpp, src/yarprobotinterface/Robot.cpp, src/yarprobotinterface/Robot.h, tests/libYARP_dev/PolyDriverTest.cpp
This patch adds a generic method to deprecate devices. Since devices are "plugins" and therefore the compiler does not see them, the check must necessarily be at run time.
In order to deprecate a device, the user just needs to inherit from `yarp::dev::DeprecatedDeviceDriver` instead of `yarp::dev::DeviceDriver` and possibly add a warning in the `open(Searchable& config)` method.
```diff
- class foo : public yarp::dev::DeviceDriver
+ class foo : public yarp::dev::DeprecatedDeviceDriver
```
(In yarp compilation should also be disabled when `YARP_NO_DEPRECATED` is enabled).
When a deprecated device is opened as a `PolyDriver` it will refuse to open unless the `allow-deprecated-devices` option is passed. Please note that it can be still used from the source code by explicitly opening the …
=> Add runtime check for deprecated devices and deprecate controlboard and clientcontrolboard devices

bindings/yarp.i
yarp::sig::Matrix was not included in bindings.
Now all bindings include also Matrix, and in particular the python bindings allow to access elements with the same semantic as cpp, e.g.:
```
import yarp
m = yarp.Matrix(3,3)
m[2,2] = 1.0
```
=> [bindings] added yarp::sig::Matrix in bindings

.travis.yml, doc/yarp_cmake_hello.dox, example/os/image_process_module.cpp
- in yarp/example/os/image_process_module.cpp the input of module.runModule() has been modified according to what is required by the RFmodule.cpp (which substitutes the deprecated code Module.cpp) 
- in yarp/doc/yarp_cmake_hello.dox it has been added the suggestion to create a build directory inside the source folder and launch cmake from it
=> Cleanup of tutorials

src/carriers/portmonitor_carrier/PortMonitor.cpp, src/carriers/portmonitor_carrier/PortMonitor.h, src/libYARP_OS/include/yarp/os/Carrier.h, src/libYARP_OS/include/yarp/os/ModifyingCarrier.h, src/libYARP_OS/include/yarp/os/impl/PortCore.h, src/libYARP_OS/src/ModifyingCarrier.cpp, src/libYARP_OS/src/Network.cpp, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/PortCoreInputUnit.cpp
**This pull-request allows attaching directly a pmonitor plug-in to a Yarp port.**
Motivation
-------------
Up to now, a portmonitor plug-in could be attach to a specific connection either in the sender or receiver side. This could be useful if the user is interested in filtering/modifying data only within a specific connection. However, if the result of a plug-in is needed to be used by two different modules, the plug-in must be replicated twice for each connection. Thus it would be useful to have the plug-in attached directly to a port which process the outgoing data from the port before passing it to the connection's carriers. 
Usage
--------
Plug-ins (written in C++ or Lua) can be directly attached to a port using the Yarp admin port's commands. See the example below: 
| …
=> attaching portmonitor plug-ins directly to the port using Yarp admin commands

example/portmonitor/depth_image/DepthImage.cpp
@barbalberto
<a href='https://www.codereviewhub.com/robotology/yarp/pull/756?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/756'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> DepthImage PortMonitor example: invert scale

src/libYARP_dev/include/yarp/dev/IPositionDirectImpl.h
This was causing a linker error in `icub-main` in Ubuntu 16.04 . Fixing in master because it is a bug fix.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/traversaro%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1857049%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/drdanz%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/762%23issuecomment-220285750%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-05-19T10%3A24%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.g …
=> [YARP_dev] Add missing YARP_dev_API export symbol to StubImplPositionDirectRaw

doc/installation/dependencies.dox
In recent versions of doxygen the \code command generates line
numbers, that are really unconvenient when the code is meant to be
copy pasted (as in the case of bash commands).
Once https://bugzilla.gnome.org/show_bug.cgi?id=737472 is fixed we can
revert this modification.
See http://www.yarp.it/dependencies.html for the current version. Long lines such as the packages necessary to install qt5 in particular are quite cumbersome.
=> [doc] Substitute \code with \verbatim in dependencies tutorial

src/libYARP_OS/include/yarp/os/Property.h
Add documentation about the behaviour of `yarp::os::Property` when a duplicate value is added.
General cleanup and improvement of the documentation
<a href='https://www.codereviewhub.com/robotology/yarp/pull/775?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/775'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Docs: Improve yarp::os::Property documentation

.mailmap, conf/YarpDoc.cmake, conf/template/Doxyfile.in, doc/changes.dox, doc/main.dox, doc/release/v2_3_65.md, doc/release/v2_3_65_1.md
Add release notes for v2.3.65 and v2.3.65.1
Improve format of the changelog page.
The release notes are written using markdown instead of doxygen, so that
they can be copy-pasted in the release page on github.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/777%23issuecomment-221902302%22%2C%20%22https%3A//github.com/robotology/yarp/pull/777%23issuecomment-222082433%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/777%23issuecomment-221902302%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22The%20%5C%22changelog%5C%22%20page%20will%20contain%20only%20a%20link%20to%20the%20release%20notes%20for%20all%20the%20releases.%5Cr%5Cn%40lornat75%20 …
=> Release notes

src/yarpmanager++/CMakeLists.txt
It was missing part of the relative path from the yarpmanager++ source folder to the AppIcon.icns location.
The compilation process was failing on MacOSX systems if CREATE_YARPMANAGER_PP was set to ON.
Fixes #758
<a href='https://www.codereviewhub.com/robotology/yarp/pull/778?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/778'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix the cmake path to MacOS yarpmanager++ icon

src/libYARP_dev/src/modules/Rangefinder2DWrapper/Rangefinder2DWrapper.cpp, src/libYARP_dev/src/modules/Rangefinder2DWrapper/Rangefinder2DWrapper.h, src/modules/laserHokuyo/laserHokuyo.cpp, src/modules/laserHokuyo/laserHokuyo.h
angle_increment is now obtained from the hardware device. Before it was fixed to 1, preventing correct operation of laserHokuyo device (which has angle_increment=0.25)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/788%23issuecomment-224272011%22%2C%20%22https%3A//github.com/robotology/yarp/pull/788%23discussion_r66088521%22%2C%20%22https%3A//github.com/robotology/yarp/pull/788%23issuecomment-224309790%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/788%23issuecomment-224272011%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22One%20of%20the%20travis%20build%20failed%2C%20but%20it%20seems%20yet%20another%20random%20failure%2C%20since%20i …
=> crtical bugfix for laser wrapper

conf/YarpOSXUtilities.cmake
<a href='https://www.codereviewhub.com/robotology/yarp/pull/791?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/791'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> YarpOSXUtilities.cmake: Fix name when TARGET_DEST is not defined

src/modules/imuBosch_BNO055/imuBosch_BNO055.cpp, src/modules/imuBosch_BNO055/imuBosch_BNO055.h
The use of char (a signed type) for the byte buffer was corrupting
positive measures when converting from 2 bytes to a single 16 bit value.
The same bug is affecting the driver present in the cer repository.
cc @barbalberto
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/801%23issuecomment-226465854%22%2C%20%22https%3A//github.com/robotology/yarp/pull/801%23issuecomment-226481937%22%2C%20%22https%3A//github.com/robotology/yarp/pull/801%23issuecomment-226497746%22%2C%20%22https%3A//github.com/robotology/yarp/pull/801%23issuecomment-226797582%22%2C%20%22https%3A//github.com/robotology/yarp/pull/801%23issuecomment-227115109%22%2C%20%22https%3A//github.com/robotology/yarp/pull/801%23issuecomment-227119303%22%2C%20%22https%3A// …
=> [modules] Fix imuBosch_BNO055

src/libYARP_OS/src/Property.cpp
`szarg` was allocated twice.
<a href='https://www.codereviewhub.com/robotology/yarp/pull/818?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/818'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> [YARP_OS] Fix memory leak in Property::fromArgs

src/libYARP_dev/src/modules/AnalogWrapper/AnalogWrapper.cpp, src/libYARP_dev/src/modules/AnalogWrapper/AnalogWrapper.h
Now analogWrapper is able to publish ROS sensor_msgs/JointState messages. 
Tested on CER01 hands.
<a href='https://www.codereviewhub.com/robotology/yarp/pull/820?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/820'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Analog wrapper with joints

bindings/yarp.i, doc/release/v2_3_66_1.md
Fixes TypedReaderCallbackImageMono redefinition.
<a href='https://www.codereviewhub.com/robotology/yarp/pull/830?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/830'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Bindings: Properly define TypedReaderCallbackSound

src/libYARP_OS/src/NameConfig.cpp, src/libYARP_OS/src/SocketTwoWayStream.cpp
Fixes several race conditions reported by valgrind.
<a href='https://www.codereviewhub.com/robotology/yarp/pull/831?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/831'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Use reentrant version of get_host_addr

src/yarpdataplayer-qt/src/main.cpp, src/yarpmotorgui-qt/main.cpp, src/yarpview-qt/src/main.cpp
Not touching yarpscope because it already works fine and yarpmanager++ because this settings badly affects the graphical representation of the applications.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/pattacini%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/839%23issuecomment-236445698%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-07-31T17%3A54%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github. …
=> fixing #837 setting QT_DEVICE_PIXEL_RATIO = auto for some guis. 

doc/release/v2_3_68.md, src/carriers/tcpros_carrier/TcpRosCarrier.cpp, src/libYARP_OS/include/yarp/os/AbstractContactable.h, src/libYARP_OS/include/yarp/os/BufferedPort.h, src/libYARP_OS/include/yarp/os/Contactable.h, src/libYARP_OS/include/yarp/os/Port.h, src/libYARP_OS/include/yarp/os/impl/PortCore.h, src/libYARP_OS/src/Contact.cpp, src/libYARP_OS/src/Node.cpp, src/libYARP_OS/src/Port.cpp, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/PortCoreInputUnit.cpp, src/libYARP_OS/src/RosNameSpace.cpp, tests/libYARP_OS/ContactTest.cpp
See #826
Main contribution is the proper implementation of getBusInfo, which provides a connection list to ROS. It's not yet implemented for services.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/828%23issuecomment-233291252%22%2C%20%22https%3A//github.com/robotology/yarp/pull/828%23issuecomment-233294365%22%2C%20%22https%3A//github.com/robotology/yarp/pull/828%23issuecomment-233294536%22%2C%20%22https%3A//github.com/robotology/yarp/pull/828%23issuecomment-233296950%22%2C%20%22https%3A//github.com/robotology/yarp/pull/828%23issuecomment-233302452%22%2C%20%22https%3A//github.com/robotology/yarp/pull/828%23issuecomment-233307189%22%2C%20%22https%3A//github.com/robotology/yarp/pull/828%23issuecomment-233308153%22%2C%20%22h …
=> Several Improvements for ROS Compatibility

src/libYARP_OS/src/NameConfig.cpp
When looking at the Travis output for https://github.com/robotology/yarp/pull/828, I noticed that the `serversql::server_test::Valgrind::MemCheck` is failing when ACE is not used. This should fix it.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/841%23issuecomment-236968147%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/841%23issuecomment-236968147%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40Tobias-Fischer%20The%20patch%20looks%20good%20to%20me%2C%20Thanks%21%5Cr%5CnThis%20kind%20of%20patches%20belong%20to%20the%20%60master%60%20branch%20%28small%20bugfix%2C%20no%20API/ABI%20change%29...%20I%27m%20merging%20this%20and%20then%2 …
=> Fix valgrind test when ACE is not used

doc/release/v2_3_66_1.md, src/libYARP_OS/src/SocketTwoWayStream.cpp
Fixed "Conditional jump or move depends on uninitialised value" issues reported by `valgrind --memcheck` in SocketTwoWayStream.
<a href='https://www.codereviewhub.com/robotology/yarp/pull/842?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/842'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> YARP_OS/SocketTwoWayStream: Initialize sockaddr structures when SKIP_ACE is enabled

src/libYARP_OS/src/NameConfig.cpp
See https://github.com/robotology/yarp/pull/844 (https://github.com/robotology/yarp/pull/843 can't be reopened as branch was force-pushed).
<a href='https://www.codereviewhub.com/robotology/yarp/pull/846?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/846'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Fix valgrind issues in NameConfig.cpp

src/libYARP_dev/include/yarp/dev/ControlBoardHelper.h, src/libYARP_dev/src/ControlMode2Impl.cpp, src/libYARP_dev/src/ControlModeImpl.cpp, src/libYARP_dev/src/IEncodersTimedImpl.cpp, src/libYARP_dev/src/IInteractionModeImpl.cpp, src/libYARP_dev/src/IMotorEncodersImpl.cpp, src/libYARP_dev/src/IMotorImpl.cpp, src/libYARP_dev/src/IPositionControl2Impl.cpp, src/libYARP_dev/src/IPositionDirectImpl.cpp, src/libYARP_dev/src/IVelocityControl2Impl.cpp, src/libYARP_dev/src/ImpedanceControlImpl.cpp, src/libYARP_dev/src/OpenLoopControlImpl.cpp, src/libYARP_dev/src/TorqueControlImpl.cpp, src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.cpp
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/845%23discussion_r73398075%22%2C%20%22https%3A//github.com/robotology/yarp/pull/845%23discussion_r73477945%22%2C%20%22https%3A//github.com/robotology/yarp/pull/845%23discussion_r73479875%22%2C%20%22https%3A//github.com/robotology/yarp/pull/845%23discussion_r73483347%22%2C%20%22https%3A//github.com/robotology/yarp/pull/845%23discussion_r73486888%22%2C%20%22https%3A//github.com/robotology/yarp/pull/845%23discussion_r73490120%22%5D%2C%20%22comments%22%3A%20%7B%22Pull%201cb2164c2e107aa529a8fa227764b4b5d13999f9%20src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.cpp%205%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/845%23discussion_r …
=> Jointidcheck

src/yarpmotorgui-qt/jointitem.cpp, src/yarpmotorgui-qt/jointitem.ui
This fixes issue #630
<a href='https://www.codereviewhub.com/robotology/yarp/pull/851?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/851'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> yarpmotorgui: Added QlineEdit box to display openloop output.

src/libYARP_serversql/src/NameServiceOnTriples.cpp, src/libYARP_serversql/src/NameServiceOnTriples.h
`YARP_serversql/NameServiceOnTriples`: Protect concurrent access to internal variables using a mutex
Fixes several race conditions reported by valgrind
Might fix #374 
CC @Tobias-Fischer
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/860%23discussion_r73843846%22%2C%20%22https%3A//github.com/robotology/yarp/pull/860%23issuecomment-238182507%22%2C%20%22https%3A//github.com/robotology/yarp/pull/860%23discussion_r73850323%22%2C%20%22https%3A//github.com/robotology/yarp/pull/860%23issuecomment-238213020%22%2C%20%22https%3A//github.com/robotology/yarp/pull/860%23issuecomment-238221280%22%2C%20%22https%3A//github.com/robotology/yarp/pull/860%23issuecomment-238221454%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%2 …
=> Try to fix NodeTest race condition

src/libYARP_OS/src/PortCoreOutputUnit.cpp
This fixes #621. The addition of `op!=NULL` is the actual fix; moving `if(done) { ... }` up in the other protected area is just clean-up (and does not change the logic). 
I've written a small comment in the code, as just moving the `if(replied ...)` up in the other protected area is not enough. The call to `closeBasic` might set `op=NULL`, and thus there is another check required whether `op!=NULL`.
I had this running for ~16 hours without crash.
Would be great if you could merge @drdanz.
<a href='https://www.codereviewhub.com/robotology/yarp/pull/866?approve=1'><img …
=> Fixes #621: Add check for NULL to fix potential segfault

src/libYARP_dev/CMakeLists.txt, src/libYARP_dev/src/PopulateDrivers.cpp, src/libYARP_dev/src/modules/ControlBoardRemapper/RemoteControlBoardRemapper.cpp, src/libYARP_dev/src/modules/ControlBoardRemapper/RemoteControlBoardRemapper.h, src/libYARP_dev/src/modules/RemoteControlBoard/RemoteControlBoard.cpp, src/modules/fakeMotionControl/fakeMotionControl.cpp, src/modules/fakeMotionControl/fakeMotionControl.h, tests/libYARP_OS/PropertyTest.cpp, tests/libYARP_dev/ControlBoardRemapperTest.cpp
Add the new `remotecontrolboardremapper` device, rationale for its use can be found in the class documentation https://github.com/robotology/yarp/compare/devel...traversaro:RemoteControlBoardRemapper?expand=1#diff-2ce8be34020e8c21cfd98d56050157a4R22 and in https://github.com/robotology/yarp/pull/746 .
Tests of the `controlboardremapper` device have been modified to test also the `remotecontorlboardmapper`  . 
Documentation of the `remote_controlboard` has been also added for consistency : https://github.com/robotology/yarp/commit/f5e88f2b1c7be0862f747f9d9ba68635d92dad53 .
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/861%23issuecomment-238487668%22%2C%20%22https%3A//github.com/robotology/yarp/pull/861%23issuecomment-2388 …
=> Remote control board remapper

src/libYARP_OS/src/PortCoreOutputUnit.cpp
* Move variable declaration inside the if where it is used (see [#866](https://github.com/robotology/yarp/pull/866#issuecomment-240074850)).
* Modify reply right after receiving it instead of (CC @apaikan). The extra `op!=NULL` check added by #866 was removed, since it makes no sense here (CC @Tobias-Fischer).
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Tobias-Fischer%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5497832%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/yarp/pull/871%23issuecomment-240111268%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-08-16T14%3A03%3A14 …
=> YARP_OS/PortCoreOutputUnit: small fixes

doc/release/v2_3_66_1.md, src/libYARP_OS/include/yarp/os/impl/RunProcManager.h, src/libYARP_OS/src/Run.cpp
Symptom  of the problem was the following uncaught exception:
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
```
Details of the problem:
> The problem is that the join was called on a thread object in a process different from the one which created it.
> This happened because of calls to `fork()`.
> 
> In particular we have to be careful when we call `fork()`: all the memory is duplicated but only one thread (the one calling `fork()`) survives.
> In general it can be very dangerous to fork in a multithread application. It is only safe to call exec* as soon as possible after the fork. At that point the whole memory is substituted with the executed process.
> 
> To fix this issue I decided to completely remove the …
=> Fixes yarprun (at least on macOS)

conf/template/yarp_plugin_carrier.cpp.in, doc/carrier_expert.dox, doc/release/v2_3_68.md, doc/yarp_build_structure.dox, example/carrier/carrier_human.cpp, example/carrier/carrier_stub.cpp, src/carriers/CMakeLists.txt, src/libYARP_OS/CMakeLists.txt, src/libYARP_OS/include/yarp/os/Carriers.h, src/libYARP_OS/include/yarp/os/impl/PortCore.h, src/libYARP_OS/include/yarp/os/impl/Protocol.h, src/libYARP_OS/src/Carriers.cpp, src/libYARP_OS/src/Companion.cpp, src/libYARP_OS/src/NameSpace.cpp, src/libYARP_OS/src/Network.cpp, tests/libYARP_OS/PortCoreTest.cpp
Fixes #402
This will allow to create carriers as plugins in separate packages.
<a href='https://www.codereviewhub.com/robotology/yarp/pull/877?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/877'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> YARP_OS: Move Carriers out of the impl namespace

src/libYARP_dev/src/modules/AnalogWrapper/AnalogWrapper.h
To avoid the missing "More..." link in http://www.yarp.it/classyarp_1_1dev_1_1AnalogWrapper.html .
<a href='https://www.codereviewhub.com/robotology/yarp/pull/883?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/883'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> Add a brief doxygen doc to AnalogWrapper

src/modules/imuBosch_BNO055/CMakeLists.txt
Cleanup in CMakeListss removed YARP_math from linking but it is required by this module to work.
YARP_math is used to convert data into dcm.
Maybe to cleanup this dependency this device should be removed from compilation if YARP_math is off?
To fix the error, now it has been re-introduced, cleanup will follow.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/yarp/pull/884%23issuecomment-242035408%22%2C%20%22https%3A//github.com/robotology/yarp/pull/884%23issuecomment-242035777%22%2C%20%22https%3A//github.com/robotology/yarp/pull/884%23issuecomment-242059835%22%2C%20%22https%3A//github.com/robotology/yarp/pull/884%23issuecomment-242059987%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A …
=> Fix linking issue due to recent changes in CMakeFiles.

src/modules/imuBosch_BNO055/CMakeLists.txt
<a href='https://www.codereviewhub.com/robotology/yarp/pull/887?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/robotology/yarp/pull/887'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>
=> imuBosch_BNO055: Disable when YARP_math is not available and fix include dirs

doc/release/v2_3_66_1.md, src/libYARP_OS/src/DgramTwoWayStream.cpp
Fixes #637 
This PR fixes UDP and MCAST on macOS.
**UDP**
Currently the updated code is included in an `#ifdef __APPLE__` so other OSes should not see any changes in UDP.
Anyway, as discussed with @apaikan probably we should trust more the kernel engineers of the various OSes and their choice for socket buffers.
In the current macOS implementation thus, the default for the socket buffers are taken from the operating system configuration. Nevertheless they can be overwritten by environment variables.
What about a test (both of compilation and performance) also on other OSes (i.e. Linux and Windows). In this case a manual intervention is needed as the `#ifdef` block should be substituted the older block
**MCAST**
[Related issue on ACE](https://github.com/DOCGroup/ACE_TAO/issues/281)
It …
=> Fix UDP and MCAST on macOS

doc/release/v2_3_66_1.md, src/libYARP_dev/src/modules/AnalogWrapper/AnalogWrapper.cpp, src/libYARP_dev/src/modules/ControlBoardWrapper/ControlBoardWrapper.cpp
The removal of some parameters deprecated for a long time is causing some confusion when updating some robots simulated in Gazebo. Reformulated the error message to be clearer and update the release notes (the 2.3.66.1 one because we already released 2.3.66).
=> libYARP_dev : document clearly the removal of two deprecated parameters

doc/release/v2_3_68.md, src/libYARP_OS/include/yarp/os/impl/PortCore.h, src/libYARP_OS/include/yarp/os/impl/PortCoreAdapter.h, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/PortCoreAdapter.cpp
This allows to query the port and to get information about the type of the port (whether it is an input, output or rpc port) and the message type accepted/produced by the port (if set). For example:
```
>>prop get /yarp/bar+@/foo process
Response: (sched ((policy -1) (priority -1) (tid 19689))) (process ((arguments foo) (name "./test-yarp-node") (pid 19647) (policy 0) (priority 0))) (platform ((hostname "xxx.xxx.xxx.xxx") (os Linux))) (port ((is_input 0) (is_output 1) (is_rpc 0) (type "std_msgs/String")))
```
Now contains this information `(port ((is_input 0) (is_output 1) (is_rpc 0) (type "std_msgs/String")))`
@apaikan I think it would be nice to have this information in `yarpviz`
=> Port core port info

src/libYARP_OS/src/ThreadImpl.cpp
* **Fix scheduling priority methods on UNIX without ACE**
These methods are currently implemented in an `#if defined(UNIX)` that is actually never built (and this is obvious because the code inside is missing an `=` and therefore it is broken. The correct macro is `__unix__`.
* **Implement scheduling priority methods for C++11**
These methods are at the moment not implemented without C++11. Using [std::thread::native_handle](http://en.cppreference.com/w/cpp/thread/thread/native_handle) allow us to get a handle depending on the implementation and to use it either with ACE or with pthread.
Note: this is currently untested on windows with `YARP_EXPERIMENTAL_CXX11` enabled + ACE. It would be really useful if someone could at least try and see if it builds, since I'm not sure if the native …
=> Implement scheduling priority methods for C++11

doc/release/v2_3_66_1.md, src/libYARP_OS/src/PortCore.cpp, tests/libYARP_OS/NetworkTest.cpp
* **OS/PortCore: do not interrupt input unit in closeMain**
When an input port is deleted, all the ports connected to this port should be disconnected first. Therefore a message is sent to these ports, and these perform the actual disconnection. The real disconnection is executed after sending a final message on the socket.
The interrupt() call removed by this patch closes the socket internally, therefore when the final message is sent by the output port, the output socket is broken, hence the SIGPIPE.
Removing the interrupt here does not seem to have side effects, since the socket is closed later, when the message arrives.
* **NetworkTest: Interrupt and close the port when the SlowResponder thread is stopped**
This fixes the SIGPIPE crash with gdb
=> Fix SIGPIPE errors when running tests with gdb

doc/release/v2_3_68.md, src/libYARP_OS/src/PortCoreInputUnit.cpp, src/libYARP_OS/src/PortCoreOutputUnit.cpp
YARP 2.1.2 is now a "long time ago"...
I'm not sure about this, but this might break compatibility at protocol level between `master` and `devel` because by default, the output part, still writes using the old protocol.
I believe it is time to get rid of this part of the code, but if you think it is not ok to do so I can probably change the `PortCoreOutputUnit` now (so that `devel` "writes" using the new protocol but "reads" both), that should keep the compatibility with `master`, and  later remove the `PortCoreInputUnit` part.
=> Drop compatibility with YARP 2.1.2

cmake/YarpOSXUtilities.cmake, src/yarpbatterygui/CMakeLists.txt, src/yarpdataplayer/CMakeLists.txt, src/yarplaserscannergui/CMakeLists.txt, src/yarplogger/CMakeLists.txt, src/yarpmanager++/CMakeLists.txt, src/yarpmanager/CMakeLists.txt, src/yarpmotorgui/CMakeLists.txt, src/yarpscope/src/CMakeLists.txt, src/yarpview/src/CMakeLists.txt
After removing the GTK guis, also the code setting the `OUTPUT_NAME` property for gui targets was removed.
This code was setting the output name for the target `yarpfoo-qt` to `yarpfoo`.
This property was then copied to the bundle copy of the target, i.e. `yarpfoo.app` target had `OUTPUT_NAME` set to `yarpfoo`.
If `OUTPUT_NAME` is not set, it uses the name of the target as the output name, i.e. `yarpfoo.app`
CMake adds automatically `.app` to this name, therefore if `OUTPUT_NAME` is not set, `yarpfoo` copy target gerates a bundle `yarpfoo.app.app`
In this patch, if `OUTPUT_NAME` is not set, it is forced to the name of the original target.
Also the `TARGET_DEST` and `TARGET_ORIG` options are removed and replaced by the `TARGET` option
=> Fix the bundle folder to be named "<target>.app.app"

src/libYARP_math/include/yarp/math/NormRand.h
This class is for a normal (Gaussian) probability distribution. The documentation was referring to a uniform distribution (which is in yarp::math::Rand).
=> yarp::math::NormRand documentation fix

doc/release/v2_3_66_2.md, src/libYARP_OS/include/yarp/os/impl/PlatformThread.h, tests/libYARP_OS/ThreadTest.cpp
This is a dedicated PR that follows PR #943.
The 3 commits address 2 issues:
- Fix/Align the join() return value of YARP threads when C++11 compilation is activated. In particular, the return value is aligned with the one used by ACE and pthread threads (even though, as pointed out by @drdanz, `EINVAL` should be used as return value in place of -1, but the requirement is a value different from 0 and -1 is the same used by ACE.)
- Improve tests for YARP thread. The return values of join() calls are now tested.
=> Fix thread return value when C++11 compilation is activated

scripts/admin/README_RELEASE.md
Fix https://github.com/robotology/yarp/issues/878 . 
Committing just to `devel` because they are just developers' instructions.
=> Update release instructions

src/libYARP_OS/include/yarp/os/impl/BottleImpl.h, src/libYARP_OS/src/BottleImpl.cpp
The yarp::os::impl::String class no longer exist, and these methods are
now duplicated of the non-flex ones.
=> OS/impl/BottleImpl: Remove internal "StringFlex" methods

src/libYARP_OS/include/yarp/os/impl/LogForwarder.h, src/libYARP_OS/src/LogForwarder.cpp, src/libYARP_init/src/CustomInit.cpp
This issue fix the destruction of logForwarder causing segfault in closure of any yarp application.
=> Fix segfault while closing yarp modules

src/yarpmanager++/src-manager/applicationviewwidget.cpp, src/yarpmanager++/src-manager/applicationviewwidget.h, src/yarpmanager++/src-manager/mainwindow.cpp, src/yarpmanager++/src-manager/mainwindow.h, src/yarpmanager++/src-manager/mainwindow.ui
This pull request adds the show/hide menu to the yarpmanager++ to enable/disable the builder or manager windows. 
By default the builder windows is set to hidden.
=> Show/Hide window menu  for Yarpmanager++ 

example/carrier/carrier_human.cpp, example/carrier/carrier_stub.cpp
I corrected yarp carriers tutorial (located in `yarp/example/carrier`) so that it is now possible to compile it without errors (see issue https://github.com/robotology/yarp/issues/734)
=> corrected yarp carriers tutorial

src/libYARP_OS/src/Run.cpp, src/libYARP_manager/include/yarp/manager/application.h, src/libYARP_manager/include/yarp/manager/module.h, src/libYARP_manager/src/application.cpp, src/libYARP_manager/src/kbase.cpp, src/libYARP_manager/src/localbroker.cpp, src/libYARP_manager/src/manager.cpp, src/libYARP_manager/src/module.cpp, src/libYARP_manager/src/xmlapploader.cpp
This pull request  (as requested by  :notes: @randaz81) allows to set the multiple environment variables for each single module within the application xml file. example below: 
```xml
<module>
<name>mymodule</name>
<node>localhost</node>
<prefix>/test</prefix>
<environment>VAR1=value1;VAR2=value2</environment>
</module>
```
the `mymodule` will receive the flowing variables in its local environment-variables set: 
```ini
...
YARP_PORT_PREFIX=/test
VAR1=value1
VAR2=value2
```
=> Setting modules' environment variables within application XML file

src/libYARP_manager/src/manager.cpp
=> double checking enviornment variable and port prefix for \';\'

bindings/CMakeLists.txt
Following up the discussion in https://github.com/robotology/yarp/commit/86b118c91fa3c84b22a43597db5c2ebde4dd362f this PR sets the RPATH to the python bindings.
Would be great if you have a look @drdanz
=> Set RPATH for Python bindings

src/devices/depthCamera/depthCameraDriver.cpp, src/devices/depthCamera/depthCameraDriver.h, src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.cpp, src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.h
-
-camInfo params for ros interoperation
-typo correction
-yarp::os::Node add "/" at the beginning of the name if not present.
=> RGBDbugfix

src/libYARP_dev/include/yarp/dev/ImplementTorqueControl.h, src/libYARP_dev/src/TorqueControlImpl.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.h, src/libYARP_dev/src/devices/ControlBoardWrapper/SubDevice.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/SubDevice.h
removed unused variable
propagate device name to ControlBoardWrapper2 subdevices to have more meaningful error messages
=> ControlBoardWrapper2 cleanup and small improvment

src/yarpview/plugin/VideoSurface.qml, src/yarpview/plugin/YARPViewMenu.qml, src/yarpview/plugin/qtyarpview.cpp, src/yarpview/plugin/qtyarpview.h, src/yarpview/plugin/signalhandler.cpp, src/yarpview/plugin/signalhandler.h, src/yarpview/plugin/videoproducer.cpp, src/yarpview/plugin/videoproducer.h, src/yarpview/src/qml/QtYARPView/main.qml, src/yarpview/src/qml/QtYARPView/mainCompact.qml
added --autosize option
added menu item which allows the main yarpview window to automatically resize to the new frame size when a video stream width/height is time-variant.  
tested with:
yarpdev --device test_grabber -mode size
=> Yarp view autosize

src/libYARP_dev/src/devices/AnalogWrapper/AnalogWrapper.cpp
-Change ROS param from `joint_names` to `jointNames` like the controlBoardWrapper. Old name is deprecated, but still accepted. A warning message will be displayed.
- Add call to subdevice close
=> Analog wrapper harmonize params

doc/release/v2_3_70.md, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.h, src/libYARP_dev/src/devices/RemoteControlBoard/RemoteControlBoard.cpp, src/libYARP_dev/src/devices/RemoteControlBoard/stateExtendedReader.hpp
This PR remove the backward compatibility of the remote control board with wrapper that has ONLY the state:o port.
This device is therefore expecting the wrapper to have the stateExt:o port, which was introduced in 30/07/2014.
=> Remote control board: remove single port compatibility

src/libYARP_dev/src/PolyDriver.cpp, src/yarprobotinterface/Device.cpp, src/yarprobotinterface/Param.cpp
I made the following changes:
- With respect to the issue #832, now a warning is printed if parenthesis are not balanced.
- I noticed that, in a parameter's value, when parenthesis are not balanced (or in general when the syntax of the value is not respected), also other parameters may be affected (that is they might not be stored in the `Property` object). This is due to the fact that before creating the `Property `object an intermediate string representation is used. I got rid of this (apparently useless) intermediate step, so that when the syntax of a value is not respected, only the related parameter will be corrupted.
-  In `PolyDriver.cpp` I added a warning when in a `Property` object there are two 'device' parameters nested one in the other (one is part of the value of the other). …
=> Fix for issue #832 and further related improvements

cmake/YarpIDL.cmake, doc/release/v2_3_68_1.md
* When generating ROS idls for paths containing ".." the files are no
longer generated every time make is executed.
* When path contains something like ".." the temporary files are no
longer generated outside current build directory.
* Mark the generated files as generated.
* Force cmake to re-run when the file is modified, even if the previous
version had no output files.
=> CMake: Fixes to yarp_add_idl()

src/libYARP_dev/src/devices/Rangefinder2DWrapper/Rangefinder2DWrapper.cpp, src/libYARP_dev/src/devices/Rangefinder2DWrapper/Rangefinder2DWrapper.h
RangeFinder2DWrapper can now create his own device trough the --subdevice parameter
=> RangeFinder2DWrapper: added internal subdevice spawn and attach

src/yarpmanager/src-manager/main.cpp
I found myself more comfortable having `yarpmanager` to load applications also from sub-folders **by default**.
This way, the usual path `~/.local/share/yarp/applications` can have a tree of sub-folders without impacting `yarpmanager`.
As of now, in fact, to make `yarpmanager` deal with the above configuration, we have to create a context containing the proper option.
cc @Tobias-Fischer @clement-moulin-frier
=> Yarpmanager to load sub-folders by default

src/devices/depthCamera/CMakeLists.txt
This change is necessary for fixing [ycm/#111](https://github.com/robotology/ycm/pull/111).
=> CMakeLists.txt ported to new OpenNI2 variables

tests/libYARP_OS/NodeTest.cpp
adds a broken test regarding wrong effect misleading port name after ros node creation. see issue #1037
=> New broken test

src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.h, src/libYARP_dev/src/devices/RemoteControlBoard/RemoteControlBoard.cpp, src/libYARP_dev/src/devices/RemoteControlBoard/stateExtendedReader.cpp, src/libYARP_dev/src/devices/msgs/yarp/include/jointData.h, src/libYARP_dev/src/devices/msgs/yarp/src/jointData.cpp
Reduce message size of controlboardwrapper stateExt:o of nearly 30% and
writing time by nearly half by using yarp vector instead of std::vector in idl.
btw idl shall generate optimized code also when using std::vector... but that's another matter.
=> Control board message Optimization - Update protocol number

cmake/YarpFindDependencies.cmake
(sorry for the YARP branch instead of the branch on the fork)
=> Add a workaround to avoid CMake pollution from OpenCV 2.4

src/libYARP_OS/src/AbstractCarrier.cpp
Fixes the following error on Jetson TK1 (arm64 architecture):
`/usr/local/src/robot/yarp/src/libYARP_OS/src/AbstractCarrier.cpp:222:36: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]`
=> fixes narrowing conversion error

src/libYARP_OS/include/yarp/os/Value.h, tests/libYARP_OS/ValueTest.cpp
fixes #1028.
`<yarp::os::Value> == <literal integer>` calls the `const char*` comparison overload (often resulting in a segfault). new `int` comparison overload has been added with relative test.
=> Deprecate yarp::os::Value::operator==(const char *alt)

src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.cpp
prevent RGBDSensorWrapper from posting camera_info with different sequence number but same time stamp on rostopic.
=> RGBDSensorWrapper time stamp' dt == 0 fixed

doc/release/v2_3_68_1.md, src/libYARP_sig/include/yarp/sig/Vector.h
The `yarp::sig::VectorOf<T>::resize()` allocates memory for new objects, but the constructor is never called.
This means that one can resize a vector, and then access the new elements, that are not initialized, but it cannot call the constructor on them leading to several types of errors (for example the valgrind errors on `devel` are caused by this).
=> Ensure that after yarp::sig::VectorOf<T>::resize(), the constructor operator for the new objects is called

src/libYARP_math/include/yarp/math/SVD.h, src/libYARP_math/src/eigen/eigen_SVD.cpp, tests/libYARP_math/svdTest.cpp
Fix https://github.com/robotology/yarp/issues/1062 .
@drdanz What is the best strategy to bring this to devel? The file containing the fix has been merged with another fail, so probably merging forward will fail.
=> Fix resizing of output matrices in SVD

src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.cpp, src/yarpmotorgui/mainwindow.cpp, tests/libYARP_dev/robotDescriptionTest.cpp
Various warnings fixed (unused variable, parenthesis for forcing operator precendence, unsigned int vs int comparison)
=> various Warning Fixed

src/libYARP_dev/src/devices/ControlBoardRemapper/ControlBoardRemapper.cpp, tests/libYARP_dev/ControlBoardRemapperTest.cpp
If axesNames contains a name of an axis that is not contained in the controlboards passed to attachAll,
attachAll did not return any error. It will now with this bugfix. The PR also includes test that will catch similar bugs in the future.
=>  Fix bug in ControlBoardRemapper on malformed axesNames

bindings/yarp.i
Here's a small patch to include the `IAnalogSensor` interface in the bindings (via `yarp.i`).
A small working example using `getChannel()` and `read()` is [here](https://github.com/roboticslab-uc3m/teo-body/blob/0ca3b9fb55d868f972ddfa562f6fcca140d844ae/example/python/exampleRemoteJr3.py), tested with:
- One of the four 6 channel ports of a [Jr3 F/T sensor](https://github.com/roboticslab-uc3m/teo-body/tree/0ca3b9fb55d868f972ddfa562f6fcca140d844ae/libraries/BodyYarp/Jr3) device.
- An instance of: `yarpdev --device fakeAnalogSensor --period 20 --name /jr3/ch0:o`
=> Add viewIAnalogSensor and IAnalogSensor.h to bindings (yarp.i)

cmake/YarpDescribe.cmake, cmake/YarpFindDependencies.cmake, cmake/YarpOptions.cmake, doc/release/v2_3_70.md, src/CMakeLists.txt, src/libYARP_rtf/CMakeLists.txt, src/libYARP_rtf/include/yarp/rtf/JointsPosMotion.h, src/libYARP_rtf/include/yarp/rtf/TestAsserter.h, src/libYARP_rtf/include/yarp/rtf/TestCase.h, src/libYARP_rtf/include/yarp/rtf/api.h, src/libYARP_rtf/src/JointsPosMotion.cpp, src/libYARP_rtf/src/TestAsserter.cpp, src/libYARP_rtf/src/TestCase.cpp, src/middleware/yarp/include/YarpTestCase.h, src/rtf-plugins/CMakeLists.txt, src/rtf-plugins/fixture-managers/CMakeLists.txt, src/rtf-plugins/fixture-managers/yarpmanager/CMakeLists.txt, src/rtf-plugins/fixture-managers/yarpmanager/YarpFixManager.cpp, src/rtf-plugins/fixture-managers/yarpmanager/YarpFixManager.h, src/rtf-plugins/fixture-managers/yarpplugin/CMakeLists.txt, src/rtf-plugins/fixture-managers/yarpplugin/YarpPluginFixture.cpp, src/rtf-plugins/fixture-managers/yarpplugin/YarpPluginFixture.h
* New library `libYARP_rtf` to simplify the creation of unit tests using the [Robot Testing Framework (RTF)](https://github.com/robotology/robot-testing/) and YARP. This is a slightly modified version of the `RTF_YARP_utilities` library in RTF 1.0.
* The `yarpmanager` RTF Fixture Managers was imported from robotology/robot-testing, and allows one to start a fixture using yarpmanager.
* The `yarpplugin` RTF Fixture Managers was imported from robotology/icub-tests (Originally YarpPluginFixture), and allows one to check if a yarp plugin is available.
All these can be enabled with the option `YARP_COMPILE_RTF_ADDONS` and require RTF from `devel` branch
=> Import RTF-YARP library and fixture managers from RTF

src/devices/test_grabber/TestFrameGrabber.cpp, tests/libYARP_dev/TestFrameGrabberTest.cpp
This PR updates the `TestFrameGrabberTest` for testing the new functionalities introduced in `IRgbVisualParams` .
These changes triggers a non-deterministic uninitialised memory valgrind error : 
```
==18615== Thread 7:
==18615== Syscall param write(buf) points to uninitialised byte(s)
==18615== at 0x62DB72D: ??? (/build/eglibc-oGUzwX/eglibc-2.19/io/../sysdeps/unix/syscall-template.S:81)
==18615== by 0x6652D08: ACE::send_n_i(int, void const*, unsigned long, unsigned long*) (in /usr/lib/libACE-6.0.3.so)
==18615== by 0x4EDD17C: yarp::os::impl::SocketTwoWayStream::write(yarp::os::Bytes const&) (in /home/travis/build/robotology/yarp/build/lib/libYARP_OS.so.2.3.69.5)
==18615== by 0x4EA2AE3: yarp::os::impl::BufferedConnectionWriter::write(yarp::os::OutputStream&) (in …
```
=> TestFrameGrabberTest: update for testing new functionalities

src/libYARP_dev/src/IVisualParamsImpl.cpp
The bug was that if asked width or height through rpc, the response was always false (`VOCAB_FAILED`).
=> IVisualParamsImpl: fixes a bug in `respond()`

src/yarprobotinterface/Robot.cpp
It is usually a good practice to free resources in the reverse order of the one used to acquired them.
Probably this code won't affect any devices, but I think it may avoid future issues.
cc @drdanz @randaz81 @traversaro
=> [yarprobotinterface] closeDevices reversed order

src/libYARP_dev/include/yarp/dev/IControlLimits2.h
`IControlLimits2Raw` inherit publicly from `IControlLimitsRaw`, similar to other interfaces; allows b/w compatibility viewing `IControlLimitsRaw`.
Default `private`inheritance looked more like a bug/typo than something really intentional.
=> IControlLimits2Raw inherit publicly from IControlLimitsRaw

doc/release/v2_3_68_1.md, src/libYARP_dev/include/yarp/dev/IEncoders.h
If somebody includes only `IEncoders.h` than  `YARP_dev_API` is not defined.
Thanks @claudia-lat
=> Fixed missing include in IEncoders.h

doc/release/v2_3_68_1.md, src/idls/rosmsg/src/RosTypeCodeGenYarp.cpp
fixes an out-of-bounds error if an array contained in a ros message has size ==0
=> RosTypeMsg_bounds_fix

src/devices/opencv/OpenCVGrabber.cpp, src/devices/opencv/OpenCVGrabber.h
This PR was motivated by recent experiments with opencv_grabber on my PC - unfruitful as the device was constantly producing empty ("black") images when acquired through the onboard webcam. Further tests focusing on the data acquisition part (no YARP involved, just a simple main routine) revealed that the webcam actually works with OpenCV, but its interface had to be upgraded to C++. This changeset aims to replace the obsolete C API (see 85ef904). Thanks to @jgvictores for his help in identifying the problem.
Tested on:
* Windows 10, OpenCV 3.2.0 (VS 2015 x32)
* Windows 10, OpenCV 2.3.1 (VS 2015 x32)
* Ubuntu 16.04 x64, OpenCV 3.2.0
* Ubuntu 16.04 x64, OpenCV 2.3.1: compiles successfully, although the camera cannot be opened (neither could it with current C API)
OpenCV 2.3.1 is the …
=> Implement OpenCV C++ API in opencv_grabber device

src/idls/rosmsg/src/RosTypeCodeGenYarp.cpp
fixes segfault when publishing a ros message including a null vector
=> fixes segfault when publishing a ros message including a null vector

src/libYARP_math/include/yarp/math/Math.h, src/libYARP_math/src/math.cpp
Added conversion from/to rotation matrix <-> yaw-pitch-roll angles (Rx*Ry*Rz order), to be used with R1 Gazebo equivalent model.
=> Added conversion from/to rotation matrix <-> yaw-pitch-roll angles.

doc/release/v2_3_70.md, src/libYARP_OS/include/yarp/os/ResourceFinder.h, tests/libYARP_OS/ResourceFinderTest.cpp
This PR add an overload function of `ResourceFinder::setDefaultContext()` which now accepts a `yarp::os::ConstString` as input type parameter.
As a plus, this PR adds:
1. `YARP_DEPRECATED` suffix to `ResourceFinder::setContext()` which is documented as deprecated, but wasn't properly appointed in the code;
2. proper **documentation** for each implementation of `ResourceFinder::setDefaultContext()`;
3. **two new test** to cover all the above-mentioned modifications.
=> Add overload function of ResourceFinder::setDefaultContext()

src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlNetUtils.h
@aerydna I'm not sure whether you prefer to keep them as `struct`s and therefore change the forward declaration like I did in this path, or if you'd prefer to change them to `class`...
=> JoypadControlServer: Fix -Wmismatched-tags warnings

src/carriers/tcpros_carrier/TcpRosCarrier.cpp
This commit fixes a critical issue in TcpRosCarrier causing a severe slowdown of yarp::os::publisher when multiple ros clients are connected to the same topic.
=> TcpRosCarrier fix

doc/cmd_yarp.dox, doc/name_server.dox, doc/release/v2_3_70.md, example/external/c/yarpmin.c, example/external/python/find_name_server.py, example/profiling/local.sh, example/profiling/remote.sh, src/libYARP_OS/src/NameConfig.cpp, src/yarp/yarp.1, src/yarp/yarpconfig.cpp, tests/integration/check-runtime.sh
The `YARP_CONF` environment variable has been deprecated for a long time (since April 2013) and it is no longer used. Since there was not a proper warning, the warning is printed now at runtime when the variable
is set. See [`ResourceFinder::getConfigHome()` documentation](http://yarp.it/classyarp_1_1os_1_1ResourceFinder.html) for informations about paths used by YARP to detect the	configuration files.
If you still need to use the `YARP_CONF` for some reason, you can use the `YARP_CONFIG_HOME` environment variable instead.
=> OS/NameConfig: Disable YARP_CONF environment variable

doc/cmd_yarpmotorgui.dox, doc/release/v2_3_70.md, src/yarpmotorgui/main.cpp, src/yarpmotorgui/mainwindow.cpp, src/yarpmotorgui/mainwindow.h, src/yarpmotorgui/partitem.cpp, src/yarpmotorgui/partitem.h
Changed custom positions support in the motorgui.
To implement this change I needed to change the .ini syntax regarding the custom positions (which was anyway new and never pushed to master).
The proposed changes have the following impact on the use of the motorgui:
- the number of custom positions is no more hardcoded. This means that it is possible to not specify any custom positions (and no options are shown in the menus) or to add a variable number of positions.
- the custom positions are now named instead of numbered. This simplifies the executions of custom positions if more then one are specified in the ini file.
- Added also the menu option in the single part menubar menu.
For @robotology/codyco-developers this means that it is now possible to have a single ini file with the most …
=> Improved Custom positions support for yarpmotorgui

src/libYARP_dev/src/devices/FrameTransformClient/FrameTransformClient.cpp
The method was blocking until a transform was **not** possible, rather then the contrary.
=> Bug fix for FrameTransformClient::waitForTransform

src/libYARP_dev/src/devices/ServerGrabber/ServerGrabber.cpp, src/libYARP_dev/src/devices/ServerGrabber/ServerGrabber.h, tests/libYARP_dev/TestFrameGrabberTest.cpp
This PR introduces:
- The possibility to set `--split true` also if the server open one device(e.g leopard_python), the image will be splitted and sent on two separate ports. This feature has been introduced for `iCub Purple` users (cc @vvasco @arrenglover @Iaxama) 
- Description of the parameter for `yarpdev --verbose`
- Code refactoring
PR ready to be merged :+1:
=> ServerGrabber enhancement

src/libYARP_rtf/CMakeLists.txt
Installing `rtf/api.h` fixes https://github.com/robotology/icub-tests/issues/34
=> Install missing rtf/api.h header

cmake/YarpInstallationHelpers.cmake
From the commit description:
> `yarp_configure_external_installation` requires that certain variables are defined on each call (e.g. the ones introduced by [GNUInstallDirs](https://cmake.org/cmake/help/git-master/module/GNUInstallDirs.html)). Keep in mind that CMake macros and functions are visible in the global scope once defined; therefore, one may have included this module in a previous section of the CMake project tree and, as a result, fail to load the entire file due to the presence of the if-guard. If this is the case, and variables like `CMAKE_INSTALL_DATADIR` haven't been set in the cache, `yarp_configure_external_installation` sees empty strings instead and produces absolute paths.
In other words, there is an inconsistency in the expected behaviour of this module. The following …
=> Set and export CMake variables before entering if-guard in YarpInstallationHelpers

README.md
Should fix badges on root `README.md`: latest release, travis, appveyor
PR directly to `master` because it is set as the default branch.
=> [README.md] fix badges: release, travis, appveyor

README.md
No need to tap and install separately. This command will do both.
Related, that repo has a confusing name. Opened https://github.com/robotology/homebrew-cask/issues/7 to discuss that.
=> README.md: macOS: tap and install in a single command

doc/release/v2_3_68_1.md, src/libYARP_dev/include/yarp/dev/IControlMode.h
VOCAB3 and VOCAB4 are defined in yarp/os/Vocab.h
=> Added missing include in IControlMode.h

bindings/yarp.i
Hi,
This adds bindings for yarp/os/Log.h and yarp/os/LogStream.h. It allows the following:
```
import yarp
logger = yarp.Log()
logger.debug('See how cool this is')
```
=> Add bindings for yarp/os/Log.h and yarp/os/LogStream.h

doc/main.dox
This link is broken, and anyhow it seems that Urbi is not maintained anymore (see https://github.com/aldebaran/urbi)
=> [doc] Remove link to Urbi

doc/release/v2_3_68_1.md, src/libYARP_manager/include/yarp/manager/application.h, src/libYARP_manager/include/yarp/manager/kbase.h, src/libYARP_manager/include/yarp/manager/manager.h, src/libYARP_manager/src/kbase.cpp, src/libYARP_manager/src/manager.cpp, src/yarpmanager/src-builder/builderwindow.cpp, src/yarpmanager/src-builder/builderwindow.h, src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/applicationviewwidget.h, src/yarpmanager/src-manager/entitiestreewidget.cpp, src/yarpmanager/src-manager/entitiestreewidget.h, src/yarpmanager/src-manager/genericviewwidget.cpp, src/yarpmanager/src-manager/genericviewwidget.h, src/yarpmanager/src-manager/mainwindow.cpp, src/yarpmanager/src-manager/mainwindow.h, src/yarpmanager/src-manager/mainwindow.ui, src/yarpmanager/src-manager/newapplicationwizard.cpp, src/yarpmanager/src-manager/newapplicationwizard.h
The changes introduced by this PR fix #755:
TODO before merging
Ready to be merged :+1:
=> yarpmanager: fix SaveAs button, before it doesn't do anything

doc/resource_finder_basic.dox
While reading [The ResourceFinder Class (basic)](http://www.yarp.it/master/yarp_resource_finder_basic.html) tutorial I noticed that there is NO "random_motion" in the examples directory, BUT the correct file is "rf_basic". So I modified the tutorial accordingly.
=> The ResourceFinder Class (basic) tutorial is misleading

src/libYARP_dev/src/devices/FrameTransformClient/FrameTransformClient.cpp, src/libYARP_dev/src/devices/FrameTransformClient/FrameTransformClient.h
Added the following command to FrameTransformClient
* list_frames: print all the available refence frames
* list_ports: print all the opened ports for tranform broadcasting
* publish_transform <src> <dst> <portname> <format>: opens a port to publish transform from src to dst
* unpublish_transform <portname>: closes a previously opened port to publish a transform
* unpublish_all <portname>: closes a all previously opened ports to publish a transform
=> Transform client with ports

cmake/YarpFindDependencies.cmake, cmake/ycm-0.3.1/find-modules/FindZFP.cmake, src/carriers/zfp_portmonitor/CMakeLists.txt, src/carriers/zfp_portmonitor/README.md, src/carriers/zfp_portmonitor/zfpPortmonitor.cpp
From zfp library version 0.5.1 the library providers start using CMake as a build system.
Some function API changed, so our find package and code has been updated.
=> ZFP carrier: update find package and code to the latest library version

doc/yarp_cluster.dox
Update yarp_cluster tutorial to link to the latest Iperf website.
=> doc: update iperf url in yarp_cluster tutorial

src/libYARP_manager/src/kbase.cpp
This PR fixes the possible double free (issue robotology/gazebo-yarp-plugins#299)
please review code.
=> libYARP_manager: add check for avoiding double free

src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp, src/devices/imuBosch_BNO055/imuBosch_BNO055.h
Referring to https://github.com/robotology/yarp/issues/1229, these commits should fix the sharing of  data between the `run()` and `read()` methods.
I still have to test this branch on the robot, in the meantime please let me know if you have any feedback.
Particularly, I changed the behavior when a sensor fails to read a measure. Before the missing measure was set to zero, I think it has more sense setting its value to the previous measurement.
cc @barbalberto @traversaro @francesco-romano
=> Fix Mutex behavior in yarp::dev::BoschIMU

doc/release/v2_3_70.md, src/carriers/human_carrier/HumanCarrier.h, src/carriers/mpi_carrier/src/MpiCarrier.cpp, src/carriers/tcpros_carrier/TcpRosCarrier.cpp, src/carriers/xmlrpc_carrier/XmlRpcCarrier.cpp, src/libYARP_OS/CMakeLists.txt, src/libYARP_OS/include/yarp/os/Route.h, src/libYARP_OS/src/AbstractCarrier.cpp, src/libYARP_OS/src/HttpCarrier.cpp, src/libYARP_OS/src/LocalCarrier.cpp, src/libYARP_OS/src/NameserCarrier.cpp, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/PortCoreInputUnit.cpp, src/libYARP_OS/src/Protocol.cpp, src/libYARP_OS/src/Route.cpp, src/libYARP_OS/src/TextCarrier.cpp
* The following methods were deprecated:
- `addFromName()`
- `addToName()`
- `addCarrierName()`
- `addToContact()`
* The following methods were added:
- `setFromName()`
- `setToName()`
- `setCarrierName()`
- `setToContact()`
- `swapNames()`
* Added move constructors and copy and move assignment operators
* Use PIMPL idiom
* Update everything to the new API.
Even though it takes more lines to do the same thing, this saves several copies of the `Route` object.
I don't think this is used anywhere outside YARP.
=> OS: Refactor yarp::os::Route

src/rtf-plugins/fixture-managers/yarpmanager/YarpFixManager.cpp
This PR introduces changes in `YarpFixManager` to make it compatible with recent changes in `libYARP_manager`, fixes robotology/gazebo-yarp-plugins#299 (TESTED) 
MERGE AFTER robotology/yarp#1244
=> YarpFixManager: fix yarp fixture for compatibility with recent changes in libYARP_manager

doc/release/v2_3_68_1.md, src/libYARP_OS/src/NameClient.cpp
This PR Fix #1197.
Now it actually check the available carriers in the machine.
=> NameClient: fix yarp name /port accepts

cmake/YarpOSXUtilities.cmake, cmake/ycm-0.3.1/modules/GetAllCMakeProperties.cmake
This commit, if applied, enforces the new [CMP0054](https://cmake.org/cmake/help/v3.8/policy/CMP0054.html) behavior, if available in the current CMake version.
Fixes #1187 
Integrates [robotology/ycm#116](https://github.com/robotology/ycm/issues/116)
=> Fix CMake policy CMP0054

src/libYARP_dev/src/devices/FrameTransformClient/FrameTransformClient.cpp, tests/libYARP_dev/FrameTransformClientTest.cpp
- fixed an on-closure segfault in transformClient (if without the transformServer)
- added a check in the correlated test to prevent a segfaul in the opening failure case of the trasformClient
=> Frametransform fix

doc/release/v2_3_70.md, src/devices/fakeMotionControl/fakeMotionControl.cpp, src/devices/fakeMotionControl/fakeMotionControl.h, src/libYARP_dev/include/yarp/dev/IControlMode.h, src/libYARP_dev/include/yarp/dev/IControlMode2.h, src/libYARP_dev/include/yarp/dev/ImplementControlMode.h, src/libYARP_dev/include/yarp/dev/ImplementControlMode2.h, src/libYARP_dev/src/ControlMode2Impl.cpp, src/libYARP_dev/src/ControlModeImpl.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.h, src/libYARP_dev/src/devices/ControlBoardWrapper/RPCMessagesParser.cpp, src/libYARP_dev/src/devices/RemoteControlBoard/RemoteControlBoard.cpp
Unused, doesn't belong to any controlboard interface, leads to confusion due to the recent deletion of `IPositionDirect::setPositionDirectMode`.
=> Deprecate IControlMode::setXXXMode(int) methods

tests/libYARP_OS/PortTest.cpp
=> BufferedPort: add check if the port is closed before calling write()

doc/release/v2_3_68_1.md, src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/entitiestreewidget.cpp, src/yarpmanager/src-manager/entitiestreewidget.h, src/yarpmanager/src-manager/mainwindow.cpp, src/yarpmanager/src-manager/mainwindow.h
This PR introduces:
- Load of the application tab when you open an application from disk.
- Remove of auto select all after `RUN ALL` `STOP ALL` `REFRESH ALL`  `KILL ALL`
- Automatic refresh on application load
please review code.
=> Fix yarpmanager

data/icons/512x512/action_connect_all.svg, data/icons/512x512/action_disconnect_all.svg, data/icons/512x512/action_kill_all.svg, data/icons/512x512/action_play_all.svg, data/icons/512x512/action_stop_all.svg, doc/release/v2_3_68_1.md, src/yarpmanager/res.qrc, src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/applicationviewwidget.h, src/yarpmanager/src-manager/mainwindow.cpp, src/yarpmanager/src-manager/mainwindow.h, src/yarpmanager/src-manager/mainwindow.ui
This PR introduce the differentiation between `run/stop/kill/connect/disconnect_all` actions and `run/stop/kill/connect/disconnect_selected` action.
Now `yarpmanager` looks like:
The *old* run/stop/kill/connect/disconnect buttons now acts only on selected items.
On the left side a new toolbar has been added, it contains the action that acts on all the item of the current application.
Ready to be merged :+1:
=> Enhance yarp manager

doc/release/v2_3_68_1.md, src/libYARP_OS/src/Node.cpp
Apparently, `rosnode info` (ROS Python utility) always expects a `XMLRPCLegalValue` (see Slave API, output parameter `busInfo`) even if it's empty. Not doing so results in a `ValueError` caused by attempting to unpack three variables from a tuple of two values.
* http://wiki.ros.org/ROS/Slave_API#line-33
* https://github.com/ros/ros_comm/blob/ac9f45f/tools/rosnode/src/rosnode/__init__.py#L528
* https://github.com/ros/ros_comm/blob/ac9f45f/tools/rosnode/src/rosnode/__init__.py#L79
This bug was encountered when a CBW2 configured with `useROS true` (or `only`) was queried by `rosnode info /nameOfNode`. Moreover, `rostopic echo /nameOfTopic` hung the terminal (no output). Tested on ROS Kinetic, Ubuntu 16.04. Please review, should this entail any further implications.
=> Return empty list as getBusInfo's reply if no connections available

bindings/yarp.i
Currently the MATLAB-specific part are ignored by the yarp cmake
build, but they are useful for yarp-matlab-bindings to use
the upstream yarp.i instead of having a separate copy
=> Port changes to yarp.i from https://github.com/robotology-playground/yarp-matlab-bindings

doc/release/v2_3_70_1.md, src/libYARP_OS/src/Route.cpp
This PR fixes the `yarp::os::Route::swapNames()` segfault in Windows, and MacOS (@francesco-romano ?).
=> Fix yarp::os::Route

doc/release/v2_3_72.md, src/libYARP_OS/src/Run.cpp, src/libYARP_manager/src/manager.cpp
This PR introduces:
- add the property "yarprun" to the ports opened throgh `yarp run` or `yarprun`
- add the check for "Computers" if the corresponding port has been opened through `yarprun`
TODO:
=> YarpManager: Fix "Computer" resource check

doc/release/v2_3_72.md, src/libYARP_manager/include/yarp/manager/manager.h, src/libYARP_manager/src/manager.cpp, src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/applicationviewwidget.h, src/yarpmanager/src-manager/applicationviewwidget.ui, src/yarpmanager/src-manager/safe_manager.cpp, src/yarpmanager/src-manager/safe_manager.h
=> yarpmanager: add the scan of available carriers before performing connect and disconnect

src/libYARP_OS/src/Run.cpp
This PR add the *yarprun* property to ports opened through `yarprun` also on `Win32`
=> Fix yarprun win32

src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.cpp
rpc handshake now prints the name of the remote port
=> joypadControlClient: rpc connection message verbosed

src/libYARP_OS/src/DgramTwoWayStream.cpp
This PR remove the use of `inet_addr` (deprecated) for mcast carrier no ace.
=> [WIP] libYARP_OS: remove deprecated 'inet_addr' for mcast carrier NO ACE

doc/release/v2_3_70_1.md, src/libYARP_OS/include/yarp/os/impl/McastCarrier.h, src/libYARP_OS/src/McastCarrier.cpp
This PR fixes `MCastCarrier`, if you connected multiple ports through mcast to the same sender and if you disconnected the first receiver, the other carriers didn't have the buffers where actually write.
TESTED also on macOS.
please review code.
Thanks for the assist @barbalberto :+1:
=> Fix mcast issue if you close the first connection

src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/safe_manager.cpp
This PR *undo* the changes about the automatic refresh of the connections after `start`, `stop`, `kill`.
It will be introduced using a dedicated thread.
sorry for the inconvenience.
This is the patch used on `iCubGenova01` setup.
please review code
=> yarpmanager: temporary undo for the automatic refresh

cmake/YarpInstallationHelpers.cmake, doc/release/v2_3_70_1.md
Instantaneous regression caused by 3e4a85c, suppressing 3dc9e91 just a few minutes after it was committed (both were bundled within #400).
=> Actually export absolute paths from YARP_CONFIGURE_EXTERNAL_INSTALLATION

src/libYARP_dev/include/yarp/dev/IVisualServoing.h, src/libYARP_dev/include/yarp/dev/all.h
The overloaded method accepts two `yarp::sig::Vectors`.
One vector is for Cartesian position, the other is for the axis-angle orientation.
Also add `yarp/dev/IVisualServoing.h` to `yarp/dev/all.h`.
=> Add goToGoal method overload

src/devices/SDLJoypad/SDLJoypad.cpp, src/devices/SDLJoypad/SDLJoypad.h, src/libYARP_dev/include/yarp/dev/IJoypadController.h, src/libYARP_dev/src/IJoypadController.cpp, src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.cpp, src/libYARP_dev/src/devices/JoypadControlClient/JoypadControlClient.h, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlNetUtils.h, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlServer.h
The Joypad EventDriven mode can be activated when using the `IJoypadController` interface by providing a valid pointer to a `IJoypadEvent` object. A thread will start and will call the `IJoypadEvent::action` method containing the detected events at every `RateThread::run`.
=> Event driven joypad

doc/release/v2_3_72.md, src/libYARP_serversql/src/yarpserver.cpp
This PR add the property *nameserver* to the port of the nameserver. 
It will be useful to check if exist a `yarpserver` launched with a certain namespace.
=> Add name server property

doc/release/v2_3_72.md, src/libYARP_manager/CMakeLists.txt, src/libYARP_manager/include/yarp/manager/xmlclusterloader.h, src/libYARP_manager/src/xmlclusterloader.cpp, src/yarpmanager/CMakeLists.txt, src/yarpmanager/src-manager/clusterWidget.cpp, src/yarpmanager/src-manager/clusterWidget.h, src/yarpmanager/src-manager/clusterWidget.ui, src/yarpmanager/src-manager/main.cpp, src/yarpmanager/src-manager/mainwindow.cpp, src/yarpmanager/src-manager/mainwindow.h, src/yarpmanager/src-manager/mainwindow.ui
This PR import iCubCluster inside yarpmanager that looks like: 
It has been successfully tested on `iCubGenova01` setup and it has (for now) the same functionalities of `icub-cluster.py`.
on `WIN32` the iCubCluster panel is for now disabled (sorry @randaz81 , @pattacini  and @lornat75 :sweat_smile: ).
@traversaro you owe me a beer :stuck_out_tongue:.
We should discuss about the cross dependency with icub-main( it needs only the `cluster-config.xml`) and about the deployer for windows.
We could keep it as it is for now and try to figure out later how to launch commands from and to windows machines.
@claudiofantacci @barbalberto @vtikha 
Fixes #730.
=> Add iCubCluster functionality to yarpmanager

doc/release/v2_3_70_1.md, src/libYARP_OS/include/yarp/os/impl/LocalCarrier.h, src/libYARP_OS/src/LocalCarrier.cpp
This PR removes the inheritance from `SocketTwoWayStream` in `LocalCarrierStream` and fixes `setConnectionQos()` for `local` carrier.
=> Fix local carrier

doc/release/v2_3_70_1.md, src/libYARP_dev/src/devices/ControlBoardRemapper/ControlBoardRemapper.cpp, src/libYARP_dev/src/devices/ControlBoardRemapper/ControlBoardRemapper.h, src/libYARP_dev/src/devices/ControlBoardRemapper/ControlBoardRemapperHelpers.cpp, src/libYARP_dev/src/devices/ControlBoardRemapper/ControlBoardRemapperHelpers.h
This change was triggered by the issue https://github.com/robotology/yarp/issues/1309. It implements the `IPWMControl` class methods in the control board re-mapper as follows:
- inheritance and implementation of `IPWMControl` methods in `ControlBoardRemapper` class. For now, only `setRefDutyCycle` has been implentented **\*** (sets the PWM for a single joint), the others only return a `false` status.
- handle the sub-device driver pointer `iPwm` in the `ControlBoardRemapperHelpers` class: initialisation, setting in the `attach` and `detach` methods, warning if sub-device driver is not attached.
(**\***)We track here the implemented methods:
=> Implement IPWMControl and ICurrentControl in ControlBoardRemapper

src/libYARP_OS/include/yarp/os/Network.h, src/libYARP_OS/include/yarp/os/Time.h, src/libYARP_OS/include/yarp/os/impl/TimeImpl.h, src/libYARP_OS/src/Network.cpp, src/libYARP_OS/src/Time.cpp
In case yarp::os::Time()/delay() are used without prior Network initialization a warning message is printed to warn the user.
If YARP_NO_DEPRECATED is set, the program terminates with error instead.
=> Clock refactoring update

src/libYARP_OS/include/yarp/os/impl/BottleImpl.h, tests/libYARP_OS/PortCoreTest.cpp
`BottleImpl` is the private implementation for the `Bottle` class.
There is no need to be a `Portable`, it's never written on a port (it was used in the `PortCoreTest`, but it makes no sense, and it is changed here to use `Bottle` instead).
=> OS/impl/BottleImpl: There is no need for the Bottle implementation to be a Portable itself

bindings/yarp.i
Fix bug introduced by https://github.com/robotology/yarp/pull/1317 .
Fix https://github.com/robotology/yarp/issues/1325 . 
@drdanz I remember that we used to have Travis checking at least the bindings compilation, something happened and we don't have it anymore?
=> [bindings] Fix included headers

CMakeLists.txt, cmake/YarpOptions.cmake, cmake/ycm-0.4.0/modules/AddInstallRPATHSupport.cmake
Added a new variable INSTALL_NAME_DIR to specify the absolute installation path of the libraries.
This variable will be used if RPATH is disabled either for the full project or for the installation
=> Updated RPATH macro

doc/release/v2_3_70_1.md, src/libYARP_OS/src/AbstractCarrier.cpp
This pr add `proto.os().flush()` at the end of `writeYarpInt()` to finalize the write, that for some carriers is necessary.
=> Fix abstract carrier

doc/release/v2_3_70_1.md, src/libYARP_OS/src/Network.cpp, tests/libYARP_OS/NetworkTest.cpp
The changes introduced by this PR add the check of the presence of spaces in dst and src port name in Network::metaConnect().
It fixes #1211.
=> Fix Network::connect()

doc/release/v2_3_70_2.md, src/libYARP_OS/src/BottleImpl.cpp, src/libYARP_OS/src/Property.cpp, tests/libYARP_OS/PropertyTest.cpp
This PR fixes double truncation in `Property::fromString()`, and it substitutes in `Property::putBottle()` the inefficient  `a.fromString(b.toString())` with `a = b`.
Fixes #1057 . 
=> Fix double truncation in Property::fromString()

doc/rostypes_tutorial_continued.dox
[ci skip]
I think they are not "recent" anymore.
=> [rostypes_tutorial_continued] Remove reference to recent YARP fixes

src/libYARP_math/src/Quaternion.cpp, src/libYARP_math/src/RandnScalar.cpp, src/libYARP_math/src/Vec2D.cpp
libYARP_math - fix file by file
- missing initialization, the content content could be garbage
=> Fix Clang warnings - libYARP_math

doc/release/v2_3_70_2.md, src/libYARP_OS/src/FallbackNameServer.cpp, src/libYARP_name/src/BootstrapServer.cpp, src/libYARP_serversql/src/yarpserver.cpp
Since `v2_3_70` we support mcast also without ACE.
This PR add the open of the `fallback` port also if `yarp` is compiled with `SKIP_ACE`.
=> Fix mcast yarpserver

src/libYARP_sig/include/yarp/sig/ImageNetworkHeader.h, src/libYARP_sig/src/Matrix.cpp, src/libYARP_sig/src/SoundFile.cpp, src/libYARP_sig/src/Vector.cpp, tests/libYARP_sig/MatrixTest.cpp
libYARP_sig - fix file by file
- after the assignment the var is never read
- possible access to null pointer
- missing initialization, the content content could be garbage
=> Fix Clang warnings - libYARP_sig

src/libYARP_manager/include/yarp/manager/impl/textparser.h, src/libYARP_manager/src/binexparser.cpp, src/libYARP_name/include/yarp/name/NameServerConnectionHandler.h, src/yarpmanager/src-builder/propertiestable.cpp, src/yarpmotorgui/jointitem.cpp, src/yarpmotorgui/mainwindow.cpp
libYARP_name, libYARP_manager, yarpmanager, yarpmotorgui - fix file by file
- after the assignment the var is never read
- possible access to null pointer
- missing initialization, the content content could be garbage
- shift operator with undefined behaviour
=> Fix Clang warnings - other libraries

doc/yarp_swig.dox
Fix https://github.com/robotology/yarp/issues/1380 .
=> [doc] Mention that we need swig3.0 in Debian Jessie

src/libYARP_OS/src/ThreadImpl.cpp
Fix initialization of ThreadImpl id field
=> Fix ThreadImpl.cpp for OSX

doc/release/v2_3_70_2.md, src/libYARP_OS/include/yarp/os/impl/DgramTwoWayStream.h, src/libYARP_OS/src/DgramTwoWayStream.cpp
This PR unifies the code in `DGramTwoWayStream` and deletes a useless `while()` in `flush()`, the packet is already divided in packets in the `write()` function in order to be sent through datagrams.
It fixes #899.
TODO:
All tests passed, ready to be merged.
=> Unification of DGramTwoWayStream

src/idls/rosmsg/src/RosType.cpp, src/idls/rosmsg/src/RosType.h, src/idls/rosmsg/src/RosTypeCodeGenYarp.cpp, src/idls/rosmsg/src/RosTypeCodeGenYarp.h, src/libYARP_dev/src/devices/msgs/ros/include/TickDuration.h, src/libYARP_dev/src/devices/msgs/ros/include/TickTime.h, src/libYARP_dev/src/devices/msgs/ros/include/geometry_msgs_Point.h, src/libYARP_dev/src/devices/msgs/ros/include/geometry_msgs_Pose.h, src/libYARP_dev/src/devices/msgs/ros/include/geometry_msgs_Quaternion.h, src/libYARP_dev/src/devices/msgs/ros/include/geometry_msgs_Transform.h, src/libYARP_dev/src/devices/msgs/ros/include/geometry_msgs_TransformStamped.h, src/libYARP_dev/src/devices/msgs/ros/include/geometry_msgs_Vector3.h, src/libYARP_dev/src/devices/msgs/ros/include/geometry_msgs_Wrench.h, src/libYARP_dev/src/devices/msgs/ros/include/geometry_msgs_WrenchStamped.h, src/libYARP_dev/src/devices/msgs/ros/include/nav_msgs_MapMetaData.h, src/libYARP_dev/src/devices/msgs/ros/include/nav_msgs_OccupancyGrid.h, src/libYARP_dev/src/devices/msgs/ros/include/sensor_msgs_CameraInfo.h, src/libYARP_dev/src/devices/msgs/ros/include/sensor_msgs_Image.h, src/libYARP_dev/src/devices/msgs/ros/include/sensor_msgs_Imu.h, src/libYARP_dev/src/devices/msgs/ros/include/sensor_msgs_JointState.h, src/libYARP_dev/src/devices/msgs/ros/include/sensor_msgs_LaserScan.h, src/libYARP_dev/src/devices/msgs/ros/include/sensor_msgs_RegionOfInterest.h, src/libYARP_dev/src/devices/msgs/ros/include/std_msgs_ColorRGBA.h, src/libYARP_dev/src/devices/msgs/ros/include/std_msgs_Header.h, src/libYARP_dev/src/devices/msgs/ros/include/tf2_msgs_TFMessage.h, src/libYARP_dev/src/devices/msgs/ros/include/tf_tfMessage.h, src/libYARP_dev/src/devices/msgs/ros/include/visualization_msgs_Marker.h, src/libYARP_dev/src/devices/msgs/ros/include/visualization_msgs_MarkerArray.h
Change the code to complete autogenerated ROS msgs types with initialization lists, in order to fix the 'uninitialized scalar | pointer field' issues raised by Coverity static analyzer.
The pull also includes ROS types filled with initialization lists.
=> rosmsgs autogeneration fix

src/libYARP_dev/src/IJoypadController.cpp
fixed a wrong typo-caused recursive call on JoypadControl
=> joypadControlClient: recursive call fix

src/idls/rosmsg/src/RosType.cpp, src/idls/rosmsg/src/RosType.h, src/idls/rosmsg/src/RosTypeCodeGenYarp.cpp, src/idls/rosmsg/src/RosTypeCodeGenYarp.h
Previous code was generating problems when the message had constant fields declared as last fields.
This fix provides support for this case and also for void messages or messages with only constant fields.
=> ros msgs autogeneration bug fix

.travis.yml, cmake/YarpFindDependencies.cmake, cmake/ycm-0.5.1/3rdparty/COPYING.qt-gstreamer, cmake/ycm-0.5.1/3rdparty/FindGLIB2.cmake, cmake/ycm-0.5.1/3rdparty/FindGStreamer.cmake, cmake/ycm-0.5.1/3rdparty/FindGStreamerPluginsBase.cmake, cmake/ycm-0.5.1/3rdparty/MacroFindGStreamerLibrary.cmake, cmake/ycm-0.5.1/3rdparty/README.qt-gstreamer, doc/release/v2_3_72.md, src/carriers/CMakeLists.txt, src/carriers/h264_carrier/CMakeLists.txt, src/carriers/h264_carrier/H264Carrier.cpp, src/carriers/h264_carrier/H264Carrier.h, src/carriers/h264_carrier/H264Decoder.cpp, src/carriers/h264_carrier/H264Decoder.h, src/carriers/h264_carrier/H264Stream.cpp, src/carriers/h264_carrier/H264Stream.h, src/carriers/h264_carrier/h264.ini, src/libYARP_OS/CMakeLists.txt, src/libYARP_OS/include/yarp/os/Carrier.h, src/libYARP_OS/include/yarp/os/impl/FakeFace.h, src/libYARP_OS/src/Carrier.cpp, src/libYARP_OS/src/Carriers.cpp, src/libYARP_OS/src/Network.cpp
Here is implemented the H264 carrier. 
It can be used to read and decode a h264 stream published by Gstreamer.
In order to accomplished it, I needed to add method `yarp::os::carrier::createFace()`,  that returns the needed face of the carrier. This method is used in `yarp::os::carriers::listen` and in `yarp::os::carriers::connect `  in order to open new connection using the correct face.
=> H264 encoding

src/libYARP_logger/include/yarp/logger/YarpLogger.h, src/libYARP_logger/src/YarpLogger.cpp, src/libYARP_math/src/RandScalar.cpp, src/libYARP_math/src/math.cpp, src/libYARP_wire_rep_utils/WireImage.h, src/libYARP_wire_rep_utils/WireTwiddler.h
fix submitted for issues raised by Coverity static analyzer in these YARP components
libYARP_math 
YARP_wire_rep_utils
YARP_serversql
YARP_logger
=> Coverity fix - other libraries

cmake/YarpOptions.cmake, doc/release/v2_3_72.md
This variables makes ConstString a typedef to std::string when set to OFF.
Please note that for existing builds the value is not updated.
Please let me know what you think about this change.
=> [WIP] Change YARP_WRAP_STL_STRING default value on non-MSVC platforms

cmake/YarpFindDependencies.cmake, doc/release/v2_3_72.md, src/libYARP_rtf/src/JointsPosMotion.cpp, src/libYARP_rtf/src/TestCase.cpp, src/rtf-plugins/fixture-managers/yarpmanager/CMakeLists.txt, src/rtf-plugins/fixture-managers/yarpmanager/YarpFixManager.cpp, src/rtf-plugins/fixture-managers/yarpplugin/CMakeLists.txt, src/rtf-plugins/fixture-managers/yarpserver/CMakeLists.txt
This PR increases the `RTF` required version to 1.3.2 and cleans up the rtf plugins after recent changes on devel branch of `RTF`.
Plugins tested, it can be merged.
=> Clean up rtf fixtures

doc/release/v2_3_70_2.md, src/libYARP_OS/src/Random.cpp
libYARP_OS:
Random.cpp and Random.h files modified to fix coverity issue: calling risky function rand()
=> Coverity fix - Random.cpp

cmake/template/YARPConfig.cmake.in
Only if YARP_rtf is created, fixes https://github.com/robotology/yarp/issues/1430 .
=> Add find_package(RTF QUIET) in YarpConfig.cmake

doc/release/v2_3_70_2.md, src/libYARP_OS/include/yarp/os/ConstString.h
Fix `yarp::os::ConstString::getline(...)` to work fine with Windows.
It fixes #1357.
=> Bugfix for yarpdev on Windows

src/libYARP_sig/include/yarp/sig/Image.h
Solves #1433 for me , but it is not clear to me why it is working on all other  people's and Travis configurations.
=> Fix problem of template specialization in a different namespace in gcc 5.4

src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/applicationviewwidget.h, src/yarpmanager/src-manager/entitiestreewidget.cpp, src/yarpmanager/src-manager/entitiestreewidget.h, src/yarpmanager/src-manager/mainwindow.cpp
This PR introduces some small enhancements:
- If `<node>` and  `<protocol>` are not specified in the xml file, `localhost` and `tcp` will be added respectively while loading the application.
- Added ip details of the port nodes: 
- Remove duplication of resources, before if two(or more modules) had the same `<dependencies>` the resource was diplayed twice:
=> Small improvements in yarpmanager

src/libYARP_sig/include/yarp/sig/Image.h
@traversaro please test on ubuntu 16.04
=> sig/ImageOf: Remove redundant namespaces in specializations

src/libYARP_OS/src/Network.cpp
Currently, if source or destination port is not competent (ie it can't perform yarp handshaking), carrier's paramters given in connect command are lost.
Since could be usefull to specify some resize paramters for h264 carrier in connect command, I needed to change how the parameters are passed to the carrier.
now if user gives following commands:
```
yarp name register /srcPort MyCarrier+param1.value1 IP PORTNUM
yarp name register /dstPort MyCarrier+param2.value2 IP PORTNUM
yarp connect /srcPort /dstPort MyCarrier+param3.value3
```
The used carrier contains all three parameters: +param1.value1+param2.value2+param3.value3.
We decided that Network object does NOT any check on parameters: their verification will be done in the carrier.
=> Improve using of parameters in carriers

src/libYARP_name/src/BootstrapServer.cpp
If in config file there was a nonexistent IP address then the server started anyway.
Fixes #1404.
This patch should fix this problem: the application warns the user that it cannot start because the IP written in configuration file doesn't exist.
=> Fixed issue #1404 about 'yarp server --read command'

src/rtf-plugins/fixture-managers/yarpmanager/YarpFixManager.cpp, src/rtf-plugins/fixture-managers/yarpmanager/YarpFixManager.h
YarpFixManager has been splitted in two parts, in order to ensure the destruction of the manager class to happen before the destruction of the yarp::os::Network object.
this is because the manager class depend to it.
=> separation of inheritances in yarpFixManager

doc/release/v2_3_70_2.md, src/libYARP_dev/src/devices/ServerGrabber/ServerGrabber.cpp
RPC were not working when connectiong to the right image port, in case split is set to true.
=> ServerGrabberDual: fix error while handling RPC calls for right image

src/libYARP_OS/include/yarp/os/RFModule.h, src/libYARP_OS/include/yarp/os/RateThread.h, src/libYARP_OS/src/RFModule.cpp, src/libYARP_OS/src/RateThread.cpp, src/libYARP_OS/src/ThreadImpl.cpp, src/libYARP_OS/src/Time.cpp
After F2F chat with @lornat75 and @pattacini, it has been decided to introduce a patch to restore the same behavior as ACE.
ACE version of `sleep(0)` was forcing a `yield`.
With the introduction of C++11, `sleep(0)` does not force `yield` anymore.
This patch is to reintroduce old behavior and avoid thread starvation.
=> Patch for C++11 delay(0)

cmake/YarpOSXUtilities.cmake
@claudiofantacci can you check if this is working fine even with CMake 3.9 ?
=> Fix https://github.com/robotology/yarp/issues/1464

doc/release/v2_3_70_2.md, src/libYARP_OS/include/yarp/os/Network.h, src/libYARP_OS/src/Network.cpp, tests/libYARP_OS/NetworkTest.cpp
This PR add  the static method `NetworkBase::isValidPortName(...)` that checks that the port name:
- starts with `'/'`.
- doesn't end with `'/'`.
- doesn't contains spaces.
It fixes #1421 .
=> Add extra check during the connect

doc/release/v2_3_72.md, src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.cpp, src/libYARP_dev/src/devices/ServerGrabber/ServerGrabber.cpp, src/libYARP_sig/include/yarp/sig/Image.h, src/libYARP_sig/src/Image.cpp, src/libYARP_sig/src/Sound.cpp, src/libYARP_wire_rep_utils/WireImage.cpp, tests/libYARP_sig/ImageTest.cpp
fixes #1408
basically the pixelSize is a datum dependent on the pixel code and have to be always deduced from it, not set manually. we should deprecate the `setPixelSize` method
=> pixelsize bug fix

src/carriers/mjpeg_carrier/MjpegDecompression.cpp, src/carriers/mjpeg_carrier/MjpegStream.h, src/devices/ffmpeg/FfmpegWriter.h, src/devices/openni2/OpenNI2DeviceDriverServer.cpp, src/devices/openni2/OpenNI2SkeletonTracker.cpp, src/devices/portaudio/PortAudioDeviceDriver.cpp, src/devices/rpLidar2/rpLidar2.h
Affect components
- carriers
- devices
=> Coverity fixes - initializations_1

src/libYARP_OS/src/AuthHMAC.cpp, src/libYARP_OS/src/SharedLibraryFactory.cpp, src/libYARP_OS/src/SystemInfoSerializer.cpp, src/libYARP_dev/include/yarp/dev/RemoteFrameGrabber.h, src/libYARP_dev/src/devices/FrameTransformClient/FrameTransformClient.cpp, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlNetUtils.h, src/libYARP_dev/src/devices/RemoteControlBoard/RemoteControlBoard.cpp
Affect components
- libYARP_OS
- libYARP_dev
=> Coverity fixes - initializations_2

example/opencv/CMakeLists.txt
The test is not working due to a missing target of the libraries linkage and to a miswritten name of the OpenCV package.
=> Small adjustments to CMakeLists

doc/release/v2_3_72.md, src/libYARP_OS/include/yarp/os/RateThread.h, src/libYARP_OS/src/RateThread.cpp
OS/RateThread: Improvements
* Cleanup
* Avoid useless call
* Improve PIMPL implementation
* Remove useless private method
OS/RateThread: Protect methods that should not be public.
The following methods in `yarp::os::RateThread` are now `protected` instead
of `public`:
* `virtual bool threadInit();`
* `virtual void threadRelease();`
* `virtual void run() = 0;`
* `virtual void beforeStart();`
* `virtual void afterStart(bool success);`
Fixes #1481
=> Rate thread improvements

src/carriers/tcpros_carrier/TcpRosStream.h, src/libYARP_dev/src/devices/JoypadControlServer/JoypadControlNetUtils.h, src/libYARP_dev/src/devices/Rangefinder2DWrapper/Rangefinder2DWrapper.cpp, src/yarpbatterygui/display.cpp, src/yarpdatadumper/main.cpp, src/yarplogger/messageWidget.cpp, src/yarpmanager/src-manager/logwidget.cpp
Commits are grouped by component.
=> Coverity fixes - initializations_5

bindings/yarp.i
This PR adds `IPositionDirect` SWIG bindings, and extends some basic methods.
We have several use cases where we would like to have `IPositionDirect` in Python: A common setup is during simulations for Evolutionary Strategies and/or (Deep) Reinforcement Learning. We want instant movements and do not care about intermediate trajectories. The current hack is via `IPositionControl::setRefSpeed` > `IControlLimits2::setVelLimits`. However, the `IPositionDirect` interface seems much more appropriate.
Here is some code with which it has been tested (unfortunately requires https://github.com/roboticslab-uc3m/openrave-yarp-plugins; some day we will have a very complete FakeControlboard that implements all of these methods):
```python
import yarp
options = yarp.Property() …
```
=> add IPositionDirect binding, extend basic methods

doc/release/v2_3_72.md, src/libYARP_manager/include/yarp/manager/executable.h, src/libYARP_manager/include/yarp/manager/manager.h, src/libYARP_manager/src/executable.cpp, src/libYARP_manager/src/manager.cpp, src/yarpmanager/src-manager/applicationviewwidget.cpp
This PR introduces the possibility to switch broker for launching modules.
It makes possible to switch from `localhost` to `yarprun` and viceversa without the necessity to change the xml and reload the application.
It fixes #1471.
=> Broker switching in yarpmanager

src/yarpmanager-console/ymanager.cpp
Use the name `yarpmanager-console` consistently in the help message.
=> yarpmanager-console: display correct name in help

src/libYARP_dev/include/yarp/dev/CanBusInterface.h
P.S. No changelog file available in `doc/release/`.
=> Add missing <cstring> include in yarp/dev/CanBusInterface.h for std::memset

doc/release/v2_3_72.md, src/libYARP_OS/src/NameClient.cpp, src/libYARP_OS/src/Network.cpp
This patch should allow to open a port with an associated custom carrier different from tcp, if this carrier is available and it provides a custom implementation of `yarp::os::Face` that can replace default handshake.
Example:
```
yarp::os::Port p;
yarp::os::Contact c("/port", "carrier");
p.open(c);
```
=> Add support for carrier specification on registration

doc/release/v2_3_72.md, src/libYARP_dev/include/yarp/dev/CanBusInterface.h
Use case:
```c++
// implements yarp::dev::ICanBus::canWrite
bool MyClass::canWrite(const yarp::dev::CanBuffer &msgs, unsigned int size, unsigned int *sent, bool wait)
{
// ideally, we would like to avoid this:
//const yarp::dev::CanMessage &msg = const_cast<yarp::dev::CanBuffer &>(msgs)[0];
// ...and do this instead:
const yarp::dev::CanMessage &msg = msgs[0];
// send msg
}
```
=> Overload yarp::dev::CanMessage::operator[], add constness for getters

doc/release/v2_3_72.md, src/libYARP_dev/include/yarp/dev/IVirtualAnalogSensor.h, src/libYARP_dev/src/devices/VirtualAnalogWrapper/VirtualAnalogWrapper.h
Methods of `yarp::dev::IVirtualAnalogSensor` renamed in order to avoid conflicts with similar methods of `yarp::dev::IAnalogSensor`.
This change breaks some compatibility with icub-main and codyco, which need to be changed accordingly.
=> IVirtualAnalogSensor methods renamed.

extern/xmlrpcpp/CMakeLists.txt
Linking xmlrpcpp statically makes the binary for the xmlrpc carrier LGPL2.1+.
Linking it dynamically, it should stay BSD.
CC: @lornat75
=> CMake: Add YARP_priv_xmlrpcpp_TYPE to allow building xmlrpcpp as a shared library

cmake/YarpIDL.cmake, doc/release/v3_0_0.md, src/idls/rosmsg/src/RosType.cpp, src/idls/rosmsg/src/RosType.h, src/idls/rosmsg/src/main.cpp
If this option is enabled, it generates code only for the selected file, not for its dependencies.
The new `NO_RECURSE` argument is now accepted by `yarp_add_idl` and `yarp_idl_to_dir`
=> yarpidl_rosmsg: Add --no-recurse option

bindings/yarp.i
Rebased  PR #1521 as requested.
=> bug fix - typedReaderMissingCallback with Sound in python bindings (rebase of  #1521)

src/libYARP_OS/src/PlatformTime.cpp
@barbalberto Is there a reason why this one stayed like this after the changes to the clock?
Please notice that this change will break VS 2013, we don't support that anymore, but this is the first change actually breaking it.
=> OS: Use std::this_thread::sleep_for instead of ACE_OS::sleep/usleep in PlatformTime

src/libYARP_OS/include/yarp/os/Os.h, src/libYARP_OS/src/Os.cpp, src/libYARP_OS/src/ResourceFinder.cpp
This PR fixes the implementation of yarp::OS::getprogname() that is not working on Windows. 
Indeed, the method was just a wrapper for an ACE function that was ok on Linux, but was not implemented for Windows (it was just able to return a string previously set by yarp::OS::setprogname()).
The new implementations is now a wrapper around yarp::os::SystemInfo::getProcessInfo(), which is correctly implemented using a windows.h function call. I was tempted to remove yarp::OS::getprogname() completely, but I left it for backward compatibility.
Instead, I removed yarp::OS::setprogname() because it is neither useful nor meaningful to me.
To be tested on MAC_OS.
=> Fix yarp::OS::getprogname

src/libYARP_OS/include/yarp/os/PortReaderBufferBase.h
Compiler specific attributes support being placed also between the return type
and the name of the function, but the C++14 `[[deprecated]]` needs to be placed
before the return type of the function.
Fix (hopefully) https://github.com/robotology/yarp/issues/1531 .
=> Always place YARP_DEPRECATED before the return type of the function

doc/release/v3_0_0.md, src/libYARP_OS/include/yarp/os/Os.h, src/libYARP_OS/include/yarp/os/SystemInfo.h, src/libYARP_OS/src/LogForwarder.cpp, src/libYARP_OS/src/NetworkClock.cpp, src/libYARP_OS/src/Os.cpp, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/ResourceFinder.cpp, src/libYARP_OS/src/SystemInfo.cpp, tests/libYARP_OS/SystemInfoTest.cpp
This PR replaces #1606 
Deprecated yarp::os::setprogname()
Deprecated yarp::os::getprogname(), superseded by yarp::os::getprocessname()
Removed all occurrences of yarp::os::setprogname() in yarp
Replaced all occurrences of yarp::os::getprogname() in yarp with yarp::os::getprocessname()
=> getprogname replaced by SystemInfo::getProcessInfo

doc/release/v2_3_72_1.md, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp
Subdevice options did not show up on stdout when using `yarpdev --verbose`. A missing `Searchable::setMonitor` call prevented the monitor object from being passed on to any wrapped device. By the way, the *subdevice* generic name has been replaced so that the actual device name is picked by said monitor.
=> Actually pass monitor object to wrapped subdevices in CBW

doc/release/v2_3_72_1.md, src/libYARP_dev/src/devices/ControlBoardRemapper/ControlBoardRemapper.cpp
The method was actually returning encoder velocities
=> Fix bug in ControlBoardRemapper::getEncoderAccelerations method

CMakeLists.txt
Fix https://github.com/robotology/yarp/issues/1628
=> Set the PROJECT_DESCRIPTION CMake variable in way compatible with CMake <= 3.8

doc/release/v2_3_72_1.md, src/devices/depthCamera/CMakeLists.txt, src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.cpp, src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.h
This PR fixes the CMakelists of `depthCamera` and the compatibility of `RGBDSensorWrapper` with frameGrabberGui2.
=> Fix depthCamera and RGBDSensorWrapper

cmake/YarpOSXUtilities.cmake, doc/release/v2_3_72_1.md
This PR remove `IMPORTED_GLOBAL` property in `YarpOSXUtilities.cmake` 
This property has been introduced in `cmake 3.11`.
Error: 
```
IMPORTED_GLOBAL property can't be set on non-imported targets
```
CMake documentation : https://cmake.org/cmake/help/v3.11/prop_tgt/IMPORTED_GLOBAL.html
=> Fix macos guis compilation

src/devices/realsense2/realsense2Driver.cpp, src/devices/realsense2/realsense2Driver.h, src/libYARP_dev/src/devices/ServerGrabber/ServerGrabber.cpp
This PR introduces some enhancements to the `realsense2` device.
The most important:
- support for stereo stream (@randaz81)
- flag for eventually disable the alignment of the depth over the rgb.
Example of ini file to use the `realsense2` with the `grabberDual` 
```
device         grabberDual
subdevice   realsense2
capabilities  RAW
stereoMode true
[SETTINGS]
rgbResolution       (640 480)
depthResolution   (640 480)
framerate             30
enableEmitter       true
[HW_DESCRIPTION]
```
=> Improve realsense

src/libYARP_conf/include/yarp/conf/api.h.in
Fix https://github.com/robotology/yarp/issues/1614
=> Fix failure in compiling YARP headers in C++14 mode with GCC

src/libYARP_OS/include/yarp/os/impl/Logger.h, src/libYARP_OS/src/Logger.cpp
Currently we have 2 different implementations for the "deprecated" internal `yarp::os::impl::Logger` class (that at some point will be removed and replaced with the newer `yInfo`, `yDebug` etc. logging methods). One implementation uses "standard" c methods, and works on every platform since it does not require any non-portable library, the other one uses ACE adding a callback and it requires ACE initialization in `Network`. Both implementation have been used and we never had complains about the non-ACE version, I don't think the callback is actually used anywhere.
In this patch the ACE/callback implementation is removed, since I believe it is unused.
The defines were renamed, since otherwise they would conflict when including Logger.h in the same file with an ACE header.
@lornat75 Please …
=> os/impl/Logger: Remove ACE implementation

doc/release/v3_0_0.md, src/yarpdataplayer/src/worker.cpp
This PR aims to let `yarpdataplayer` deal with `ImageOf<PixelFloat>` also when OpenCV is used. Indeed, `cvLoadImage()` alone does not load any float image, actually.
Further, I've tried to streamline all the possible flows, saved an unnecessary copy, and made use of `unique_ptr<>` in order to facilitate memory deallocation.
Anyway, writing/reading a float image - which is done through `yarp::sig::file::write()/read()` - appears to be overly inefficient, at least with 640x480 images. Nevertheless, we could now encode handier ways to store/retrieve float images. To get an impression, just take a look at:
https://github.com/robotology/yarp/blob/b806be8c6c3c6e67190e8ec1e428cf3e9e1c2b64/src/libYARP_sig/src/ImageFile.cpp#L26-L115
I ran several tests with standard RGB images successfully. …
=> Let yarpdataplayer read ImageOf<PixelFloat> via OpenCV

doc/release/v3_0_0.md, src/libYARP_sig/include/yarp/sig/ImageFile.h, src/libYARP_sig/src/ImageFile.cpp
Read/write services over `ImageOf<PixelFloat>` do produce binary files now. We should definitely gain something in terms of performance.
=> Storing binary files for ImageOf<PixelFloat>

bindings/lua/tests/CMakeLists.txt, bindings/lua/tests/test_vocab.lua, bindings/yarp.i, doc/release/v2_3_72_1.md, src/libYARP_OS/include/yarp/os/PortInfo.h, src/libYARP_OS/include/yarp/os/Vocab.h, src/libYARP_dev/include/yarp/dev/IPidControl.h, src/libYARP_sig/include/yarp/sig/Image.h
- SWIG was generating compile errors on `VOCAB`s in `enums`s starting by 'b'/'c'/'d'.
- d7b4099 introduced a hack to avoid SWIG binding compilation errors by substituting `char`s by equivalent `int`s.
- A deep issue was buried :skull:: only `VOCAB`s with that hack were correctly formed.
- In reality, all other `VOCAB`s generated a **copy** of the first `char`, rather than the correct `int` (e.g. `VOCAB_PIXEL_ENCODING_BAYER_GBRG16=VOCAB4('g','b','1','6');` generated `'g'` rather than `909206119`).
- Note this only affected the `VOCAB` in `enum` with SWIG combination.
- TLDR: roboticslab-uc3m/kinematics-dynamics#150 [ where @PeterBowman proposed the `constexpr` solution]
- PR also removes obsolete hacks.
Updates:
- Related: https://github.com/swig/swig/issues/737
- Introduced …
=> Fix SWIG preprocessor issue with VOCABs in enums

doc/yarp_swig.dox
As of now, we've successfully tested `lua5.2` with yarp, plus the path where the binding gets saved is different from what stated in the present doc and thus needs a fix.
=> Updated/fixed LUA documentation

doc/yarp-doxygen-layout.xml
This drastically improves the readability in HTML output, especially for
classes (such as the device implementation) that expose a lot of methods/attributes.
Before: 
After:
Before: 
After:
=> Move doxygen detaileddescription section before memberdecl

doc/release/v2_3_72_1.md, src/libYARP_OS/include/yarp/os/impl/TcpConnector.h, src/libYARP_OS/src/SocketTwoWayStream.cpp, src/libYARP_OS/src/TcpConnector.cpp
This is an attempt to fix #1636.
If timeout is not not explicitly set, `select()` function remains blocking with a default timeout of ~1min maintaining behaviour of `TcpConnector::connect()` as before.
=> add timeout support for TcpConnector::connect()

src/libYARP_eigen/include/yarp/eigen/Eigen.h
This PR adds two missing headers in `Eigen.h`:
1. `#include <yarp/sig/Matrix.h>`
2. `#include <yarp/sig/Vector.h>`
Without these headers, `Eigen.h` cannot be compiled and users are required to have an implicit order in their header inclusion list.
=> Fix missing YARP Matrix and Vector headers

src/libYARP_OS/src/TcpConnector.cpp
After #1638 `yarp clean` stopped working with `SKIP_ACE=ON`.
This PR fixes this bug.
=> Fix tcp connector

src/libYARP_OS/src/TcpConnector.cpp
Fixes (another) bug introduced by #1638.
=> change TcpConnector print method to avoid problems with remote logging

doc/release/v2_3_72_1.md, src/libYARP_serversql/src/yarpserver.cpp
It fixes #722 .
This PR makes `xmlrpc` `rossrv` `tcpros` carriers mandatory for running `yarpserver --ros`.
=> Add check on carriers for yarpserver --ros

doc/release/v3_0_0.md, src/devices/fakeMotionControl/fakeMotionControl.cpp, src/libYARP_dev/include/yarp/dev/IControlLimits2Impl.h, src/libYARP_dev/include/yarp/dev/IInteractionModeImpl.h, src/libYARP_dev/include/yarp/dev/IPositionControl2Impl.h, src/libYARP_dev/include/yarp/dev/IPositionDirectImpl.h, src/libYARP_dev/include/yarp/dev/IVelocityControl2Impl.h, src/libYARP_dev/include/yarp/dev/ImplementControlMode2.h, src/libYARP_dev/include/yarp/dev/ImplementCurrentControl.h, src/libYARP_dev/include/yarp/dev/ImplementEncodersTimed.h, src/libYARP_dev/include/yarp/dev/ImplementMotor.h, src/libYARP_dev/include/yarp/dev/ImplementMotorEncoders.h, src/libYARP_dev/include/yarp/dev/ImplementTorqueControl.h, src/libYARP_dev/src/ControlMode2Impl.cpp, src/libYARP_dev/src/CurrentControlImpl.cpp, src/libYARP_dev/src/IControlLimit2sImpl.cpp, src/libYARP_dev/src/IEncodersTimedImpl.cpp, src/libYARP_dev/src/IInteractionModeImpl.cpp, src/libYARP_dev/src/IMotorEncodersImpl.cpp, src/libYARP_dev/src/IMotorImpl.cpp, src/libYARP_dev/src/IPositionControl2Impl.cpp, src/libYARP_dev/src/IPositionDirectImpl.cpp, src/libYARP_dev/src/IVelocityControl2Impl.cpp, src/libYARP_dev/src/PWMControlImpl.cpp, src/libYARP_dev/src/TorqueControlImpl.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.h, src/libYARP_dev/src/devices/ControlBoardWrapper/SubDevice.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/SubDevice.h
Currently, the functions for all joints of control board wrapper call the equivalent function"single joint" "of "impl" layer in a for-cycle on all joints, and it invokes the single joint function of device.
Instead, I needed that the ControlBoardWrapper calls functions for all joints of device in order to make  operational the improvement done in our motion control device "embObjMotionControl", that lets to reduce time for requests to firmware. Therefore, in this branch I modified functions for all joints so that they call the equivalent function for all joints of device. 
When I tested for the first time this branch this issue occurred: https://github.com/robotology/yarp/issues/1660
that I already fixed in this branch. see https://github.com/valegagge/yarp/commit/d3af731b7838f256203737a0c …
=> ControlBoardWrapper: functions for all joints invoke the equivalent device's function for all joints

bindings/yarp.i, doc/release/v3_0_0.md
This change adds bindings to the interface `IMotorEncoders`.
`IMotorEncoders` interface methods can be used to directly monitor the motor shaft position and speed or even to control the motor positions individually when estimating coupled motors friction parameters.
The change extends:
- the `yarp::dev::PolyDriver` class adding a wrapping of `viewIMotorEncoders()` which casts the device driver to the `yarp::dev::IMotorEncoders` interface
- the `yarp::dev::IMotorEncoders` interface to deal with parameters that are not correctly translated by **SWIG** (redefinition of `getMotorEncoder`, `getMotorEncoders`, `getMotorEncoderTimed`, `getMotorEncodersTimed`, `getMotorEncoderSpeed`, `getMotorEncoderSpeeds`)
=> Add bindings for Motor encoders interface

src/libYARP_OS/include/yarp/os/Carriers.h, src/libYARP_OS/include/yarp/os/impl/LogForwarder.h, src/libYARP_OS/src/Carriers.cpp, src/libYARP_OS/src/LogForwarder.cpp, src/libYARP_OS/src/Network.cpp, src/libYARP_OS/src/RFModule.cpp, src/libYARP_init/src/CustomInit.cpp, src/libYARP_manager/include/yarp/manager/utility.h, src/libYARP_manager/src/utility.cpp, src/yarpscope/plugin/plotmanager.cpp, src/yarpscope/plugin/plotmanager.h
This PR c++11-fy all(?) the singletons in `yarp`.
=> Cleanup singleton

doc/release/v3_0_0.md, src/libYARP_OS/include/yarp/os/impl/SocketTwoWayStream.h, src/libYARP_OS/src/BufferedConnectionWriter.cpp, src/libYARP_OS/src/NameClient.cpp, src/libYARP_OS/src/NameserCarrier.cpp, src/libYARP_OS/src/Protocol.cpp, src/libYARP_OS/src/SocketTwoWayStream.cpp
This patch increase the performance of `tcp` and `fast_tcp` carrier.
The performance has been measured in terms of latency between sender and receiver(on the same machine) and we improved it by a factor of **2**. 
Now the most used yarp carrier goes ~2 times faster than before :sunglasses:.
It is a small change but that can have a huge impact on yarp, for this reason we want to test it on the robot before merging.
To achieve it we used a magic combination of `TCP_NODELAY`, `TCP_CORK` :crystal_ball: 
For the curious: 
- [TCP protocol](https://en.wikipedia.org/wiki/Transmission_Control_Protocol)
- **TCP_CORK** (since Linux 2.2)
If set, don't send out partial frames. All queued partial frames are sent when the option is cleared again. This is useful for prepending headers before calling …
=> Tcp carrier performance improvement

doc/release/v3_0_0.md, src/libYARP_math/include/yarp/math/Math.h, src/libYARP_math/src/math.cpp
=> move math operators outside yarp::math namespace

src/libYARP_dev/src/devices/ServerSerial/ServerSerial.cpp
This is necessary to avoid the issue described in https://github.com/robotology/yarp/issues/1705 .
=> Declare serial as a wrapper of itself

example/dev/simple_motor_client.cpp, example/os/rateThreadTiming.cpp, example/portaudio/sound_sender_file_chunks.cpp, example/profiling/rateThreadTiming.cpp, example/profiling/thread_latency.cpp, src/devices/fakeLaser/fakeLaser.cpp, src/devices/laserFromDepth/laserFromDepth.cpp, src/devices/laserHokuyo/laserHokuyo.cpp, src/devices/rpLidar/rpLidar.cpp, src/devices/rpLidar2/rpLidar2.cpp, src/libYARP_OS/include/yarp/os/Time.h, src/libYARP_OS/include/yarp/os/impl/TimeImpl.h, src/libYARP_OS/src/Network.cpp, src/libYARP_OS/src/Time.cpp, src/yarpdatadumper/main.cpp, src/yarprobotinterface/main.cpp, tests/libYARP_OS/RateThreadTest.cpp
* Remove unneeded calls to Time::turboBoost() (already called in initMinimum())
* OS/Time: Deprecate turboBoost() (called automatically by Network)
* OS: Make Time a namespace (it was an useless instantiable class with just static methods)
* OS/Network: Remove Bottle and BottleImpl initialization (no longer necessary)
* OS/Network: Reset system timer resolution at the end of the execution. According to https://msdn.microsoft.com/en-us/library/vs/alm/dd757624(v=vs.85).aspx `timeBeginPeriod` (called in startTurboBoost`) affects a global Windows setting and should be matched with a call to  `timeEndPeriod` (called inendTurboBoost).
=> Friday night cleanup (Network, Time)

src/libYARP_dev/src/devices/FrameTransformClient/FrameTransformClient.cpp
TF where parent and child frame have the same name are rejected as invalid.
A TF like that caused the client to run into a infinite loop.
=> FrameTransformClient: add consistency check in setTranform

cmake/YarpPlugin.cmake
Commit 6b02ae4 assumes one would wrap plugin declarations between `yarp_begin_plugin_library()` and `yarp_end_plugin_library()`. However, these make no sense in a DL world, that is, when all we want are
dynamically loaded libraries. In fact, those macros lead to the creation of a dummy (i.e. 'empty', all it does is incrementing a static counter) *static* library with .so extension. Apart from that, a prefix is added to all CMake options associated with YARP plugins these macros encompass. Such prefix was not mandatory, but said commit was not prepared to handle an empty string for its value (and this happens when the aforementioned macros were not used).
TL;DR: regression fix
=> Don't add stray '_' char if bundle name is empty

cmake/template/YARPTargetsStatic.cmake.in
Regression, #1715 introduced one implicit `find_package()` call per (public or private) external dependency of each YARP component. In static builds, this issue hit some private deps such as Libedit and Eigen that couldn't be found on system while issuing a `find_package(YARP)` call. Internal Find&lt;pkg&gt;.cmake modules may be used in order to locate these packages on system.
From https://github.com/robotology/yarp/pull/1715#issuecomment-395065930:
> I'm unable to configure the OS examples (`example/os/`) while using statically linked YARP:
>
> ```
> ~/git/yarp/example/os/build (devel % u=)$ cmake .
> CMake Error at /usr/share/cmake-3.5/Modules/CMakeFindDependencyMacro.cmake:65 (find_package):
>   By not providing "FindLibedit.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake …
```
=> Register YARP's own module paths before loading components in static builds

doc/release/v3_0_0.md, src/libYARP_dev/src/devices/ControlBoardWrapper/StreamingMessagesParser.cpp
The use of [`setRefCurrents(const int n_joint, const int *joints, const double *refs)`](https://github.com/robotology/yarp/blob/master/src/libYARP_dev/src/devices/ControlBoardRemapper/ControlBoardRemapper.cpp#L4460) method in the `ControlBoardRemapper` was causing `SEGMENTATION FAULT` because of the message send by the [`RemoteControlBoard`](https://github.com/robotology/yarp/blob/master/src/libYARP_dev/src/devices/RemoteControlBoard/RemoteControlBoard.cpp#L3241) is not parsed correctly by the [StreamingMessagesParser](https://github.com/robotology/yarp/blob/master/src/libYARP_dev/src/devices/ControlBoardWrapper/StreamingMessagesParser.cpp#L140).
The message that is sent is: 
`[VOCAB_CURRENTCONTROL_INTERFACE VOCAB_CURRENT_REF_GROUP n_joint joinLUT]`
while the parser was reading n_joint …
=> Fix VOCAB_CURRENT_REF_GROUP message parser

cmake/FindI2C.cmake, cmake/YarpFindDependencies.cmake, doc/release/v3_1_0.md, src/devices/imuBosch_BNO055/CMakeLists.txt, src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp, src/devices/imuBosch_BNO055/imuBosch_BNO055.h
This PR add support for i2c in `imuBosh_BNO055`
In order to use it you need to install 
`$ sudo apt install libi2c-dev`
and in particular the `pc104` needs some custom kernel module to be compiled and loaded (`kempld-core.ko` and  `i2c-kempld.ko`)
=> Add support for i2c in imuBosh. 

doc/release/v3_0_1.md, src/libYARP_math/CMakeLists.txt
`set(<var> <value> PARENT_SCOPE)` defines `<var>` in the parent scope *only*, at least in CMake 3.5. There is a slight change in the behavior of this command in CMake 3.7, but should not affect the result, see docs for `set()`:
* https://cmake.org/cmake/help/v3.5/command/set.html#set-normal-variable
* https://cmake.org/cmake/help/v3.7/command/set.html#set-normal-variable
This is a regression introduced by #1715. On Xenial (CMake 3.5) with libeigen3-dev and YARP 3.0, configuring YARP **from scratch** (make sure to delete `CMakeCache.txt`) leads to errors like such:
```
[...]
-- Configuring done
CMake Error at cmake/YarpPlugin.cmake:524 (add_library):
Target "yarp_transformClient" links to target "YARP::YARP_math" but the
target was not found.  Perhaps a find_package() call is missing for …
```
=> Define YARP_HAS_MATH_LIB locally (libYARP_math), then export to parent scope

src/libYARP_OS/include/yarp/os/Contact.h, src/libYARP_OS/include/yarp/os/NestedContact.h, src/libYARP_OS/include/yarp/os/Route.h, src/libYARP_OS/src/Contact.cpp, src/libYARP_OS/src/NestedContact.cpp, src/libYARP_OS/src/Route.cpp
see http://www.codingstandard.com/rule/12-5-4-declare-noexcept-the-move-constructor-and-move-assignment-operator/
=> Add noexcept in move operators and constructor

bindings/yarp.i, doc/release/v3_1_0.md
I am opening a PR as suggested here: https://github.com/robotology/QA/issues/301
This PR adds to the yarp bindings the IInteractionMode interface and a couple of methods (IInteractionMode.getInteractionMode(int) and IImpedanceControl.getAxes())
I've tested the modification by compiling (and using) the yarp bindings for Python 2.7.
=> [yarp bindings] Added IInteractionMode interface and a couple of methods

cmake/template/YARPConfig.cmake.in, doc/release/v3_0_1.md
There is no way to make this work with `find_dependency()` since it passes caller's `REQUIRED` option to the underlying `find_package()` call. That is, no error should be raised if an optional component was not
found while issuing a `find_package(YARP REQUIRED ...)` command. See also this related discussion in the CMake's community mailing list: [ref](https://cmake.org/pipermail/cmake/2016-March/062941.html).
Example invocation (tested with YARP static and shared builds):
```cmake
find_package(YARP REQUIRED COMPONENTS OS dev
OPTIONAL_COMPONENTS math asdf)
```
CMake issues a diagnostic message for the missing `YARP_asdf` component:
`-- Could NOT find YARP_asdf (missing: YARP_asdf_DIR)`
This is a follow-up proposal to #1715. The CMake <3.9 fix was introduced in #1731.
=> Handle OPTIONAL_COMPONENTS in find_package(YARP)

doc/release/v3_0_1.md, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/devices/RemoteControlBoard/RemoteControlBoard.cpp, src/libYARP_dev/src/devices/RemoteControlBoard/stateExtendedReader.cpp
Fix the implementation of `getCurrent` and `getCurrents` methods in the `RemoteControlBoard` using the `stateExt:o` port.
The implementation has been modified also in the `ControlBoardWrapper` in order to use the `ICurrentControl` interface methods.
=> Fix get Current/get Currents using stateExt and iCurrentControl

doc/release/v3_0_1.md, src/libYARP_dev/include/yarp/dev/IJoypadController.h
=> Fix deprecated constructor in IJoypadEventDriven

src/libYARP_dev/include/yarp/dev/INavigation2D.h
We figured out that `ILocalization2D` is a subset of `INavigation2D`,
moreover they were defining the same vocabs that, since they are constexpr
now, it is illegal(#1764).
No changelog is required, since the user experience it isn't changed.
=> YARP_dev: make `INavigation2D` a derived interface of `ILocalization2D`.

extern/ycm/CMakeLists.txt
`YARP_MODULE_PATH` was used in place of `YCM_MODULE_PATH` and, as a consequence, CMake 3.8 ycm modules were not added in `CMAKE_MODULE_PATH`.
=> Fix extern/ycm CMakeLists

src/devices/ovrheadset/OVRHeadset.cpp
`ovrheadset.cpp` used deprecated methods/objects, doesn't compile with new YARP, hence the modifications.
This PR and corresponding fork handles the `yarp::math` and `rateThread` related errors when compiling the `ovrheadset.cpp` . It, one the other hand, doesn't address the breaking changes in the Oculus SDK from verions 1.17 onwards, it assumes you are using the 1.16 version (or older).
=> OVR compilation fix with yarp 3.0

.travis.yml, doc/release/v3_0_1.md, extern/rplidar/sdk/src/rplidar_driver.cpp, src/devices/rpLidar2/CMakeLists.txt
This static cast is necessary for the compilation because the return value of "wait(..)" is unsigned but EVENT_TIMEOUT = -1. We will keep it until they will fix the bug in the sdk.(fixes #1689)
Moreover add NOT APPLE as dependency of the device since some bugs in the sdk make it impossible to compile on macOs(see https://travis-ci.org/robotology/yarp/jobs/402720473 for example)
=> Fix rplidar2 compilation

doc/release/v3_0_1.md, src/devices/realsense2/realsense2Driver.cpp, src/devices/realsense2/realsense2Driver.h
This PR fixes the deadlock on macOS, see IntelRealSense/librealsense#1855
Actually to fix it on macOS, it is necessary also those changes -> IntelRealSense/librealsense#2022.
`librealsense 2.13.0` should include them.
cc @vtikha
=> Fix realsense deadlock on macOS

doc/release/v3_0_1.md, src/devices/multipleanalogsensorsremapper/MultipleAnalogSensorsRemapper.cpp
Fixes issue https://github.com/robotology/yarp/issues/1765. Please refer to that link for all the details on the analysis.
=> Fix the sensors name remapping in MultipleAnalogSensorsRemapper class

doc/release/v3_0_1.md, src/libYARP_OS/src/Network.cpp
Multinamespace is a c++11 singleton(since #1699)  and need to be initialized
before the first port that is opened and it has to exist until
the last port is closed.
This PR is a firs step for the documentation of the `Network` object see #1670
=> Fix multi namespace

bindings/matlab/vectors_fromTo_matlab.i, bindings/yarp.i, src/libYARP_dev/include/yarp/dev/all.h
The binding class yarp.Vector is missing some methods since `yarp::sig::Vector` was made a typedef of `yarp::sig::VectorOf<double>`, and the change https://github.com/robotology/yarp/commit/2417c7d5e50aebca2ca8532fb40e7084262d50e8 fixed the ruby bindings generation.
Refer to issue https://github.com/robotology/yarp/issues/1809.
**The Fix:** replace every instance of `yarp::sig::Vector` by `yarp::sig::VectorOf<double>` in yarp.i. and `matlab/vectors_fromTo_matlab.i`.
For further details on the analysis, refer to https://github.com/robotology/yarp/issues/1809#issuecomment-406811352.
=> Fixed the missing bindings in `yarp.Vector` class

COPYING, LICENSE, LICENSE.GPL-3, README.md, bindings/lua/tests/test_vocab.lua, scripts/admin/update-license, scripts/admin/update-license-single, src/carriers/depth_image_portmonitor/DepthImage.cpp, src/carriers/depth_image_portmonitor/DepthImage.h, src/carriers/zfp_portmonitor/zfpPortmonitor.cpp, src/carriers/zfp_portmonitor/zfpPortmonitor.h, src/devices/DynamixelAX12Ftdi/DynamixelAX12FtdiDriver.cpp, src/devices/DynamixelAX12Ftdi/DynamixelAX12FtdiDriver.h, src/devices/ffmpeg/FfmpegGrabber.cpp, src/devices/ffmpeg/FfmpegGrabber.h, src/devices/ffmpeg/FfmpegWriter.cpp, src/devices/ffmpeg/FfmpegWriter.h, src/devices/ffmpeg/README.TXT, src/devices/ffmpeg/avpreamble.h, src/devices/ffmpeg/ffmpeg_api.cpp, src/devices/ffmpeg/ffmpeg_api.h, src/rtf-plugins/fixture-managers/yarpmanager/YarpFixManager.cpp, src/rtf-plugins/fixture-managers/yarpmanager/YarpFixManager.h, src/rtf-plugins/fixture-managers/yarpplugin/YarpPluginFixture.cpp, src/rtf-plugins/fixture-managers/yarpplugin/YarpPluginFixture.h, src/rtf-plugins/fixture-managers/yarpserver/yarpserverfixture.cpp
Re-license the following components to BSD (all required permission were received):
* devices/DynamixelAX12Ftdi
* devices/ffmpeg
* carriers/depth_image_portmonitor
* carriers/zfp_portmonitor
* rtf-plugins
* test_vocab.lua
Fix and update copyright scripts and re-generate COPYING file.
=> More re-licensing/license cleanup

bindings/yarp.i
=> bindings: Disable extended analog sensor interfaces in java

bindings/macrosForMultipleAnalogSensors.i, bindings/yarp.i, doc/release/v3_1_1.md
This change fixes Python bindings generation which was broken due to the redefinition of `yarp::sig::Vector` (https://github.com/robotology/yarp/commit/2417c7d5e50aebca2ca8532fb40e7084262d50e8). For further information please refer to https://github.com/robotology/yarp/issues/1826.
This change also adds left over fixes on the Matlab bindings of Multiple Analog Sensors Interfaces using `yarp::sig::Vector` type input parameters. The fix https://github.com/robotology/yarp/pull/1811 had missed the following section https://github.com/robotology/yarp/blob/5aa3f580a75d9a356731cae4b232dfe8783de53b/bindings/macrosForMultipleAnalogSensors.i#L43-L51
=> Complement to fix on yarp::sig::Vector for Python and Matlab bindings

bindings/yarp.i, doc/release/v3_1_1.md
See https://github.com/robotology/yarp/issues/1770, same fix as in https://github.com/robotology/yarp/pull/1817 (which was for Java)
=> Bindings: Disable extended analog sensor interfaces in CSharp

bindings/yarp.i
Silly mistake of mine in https://github.com/robotology/yarp/pull/1830 (been programming Python recently ..).
The following error is resolved:
```
/usr/local/src/robot/install/yarp/share/yarp/bindings/yarp.i:1078: Warning 202: Could not evaluate expression '!defined(SWIGJAVA) and !defined(SWIGCSHARP)'
/usr/local/src/robot/install/yarp/share/yarp/bindings/yarp.i:1078: Warning 202: Error: 'Syntax error: expected operator'
```
Sorry for that.
=> Bindings: fix "and" to "&&" for preprocessor

doc/release/v3_1_1.md, src/libYARP_OS/include/yarp/os/BufferedPort-inl.h, tests/libYARP_OS/PortTest.cpp
This PR fixes #1834.
Moreover it add a test to check this fix.
`read()` worked after interrupt/resume because it checks `port.isOpen()`
=> Fix BufferedPort::write() after interrupt-resume

doc/release/v3_1_1.md, src/yarpdataplayer/src/worker.cpp
@claudiofantacci  noticed on Windows that yarpdataplayer while streaming continued allocating memory without freeing it.
It checked on Linux and I experienced the same issue see: 
Probably it was introduced by the changes necessary to stream `PixelFloat` images (#1650), but I'm not sure.
BTW the code now is more cleaner.
@pattacini or @claudiofantacci could you please check if this patch fix this leak also on windows?
For me now with this patch the memory usage is 23Kbyte fixed.
=> Fix yarpdataplayer memory leak.

doc/release/v3_1_1.md, src/libYARP_OS/include/yarp/os/impl/LogForwarder.h, src/libYARP_OS/src/Log.cpp, src/libYARP_OS/src/LogForwarder.cpp, src/libYARP_OS/src/Network.cpp
* Added shutdown method called in Network::finiMinimum (Fixes #1851)
* Use Port instead of BufferedPort
* Write in background and wait at shutdown
* Use fast_tcp instead of tcp
* Call addOutput instead of connect in order to avoid extra useless
queries
* Avoid duplicate code
* Cleanup
=> OS/impl/LogForwarder: Heavy refactoring

doc/release/v3_1_1.md, src/idls/thrift/src/t_yarp_generator.cc
This PR proposes an hotfix for https://github.com/robotology/yarp/issues/1802. For the time being I enabled the flag for handling nested objects in the value of the map. I fear that if the key is a nested object (side case though) we might face similar issues.
I didn't do any ad-hoc testing but I used this fix already for a couple of weeks with complex thrifts without any problem.
cc @drdanz @traversaro
=> Fix serialisation / deserialisation of maps in thrift idl

src/devices/ovrheadset/TextureBattery.cpp
To fix [#1859](https://github.com/robotology/yarp/issues/1859).
=> getRate to getPeriod for ovrheadset compilation

doc/release/v3_1_1.md, src/devices/realsense2/realsense2Driver.cpp, src/devices/realsense2/realsense2Driver.h, src/libYARP_dev/include/yarp/dev/IVisualParams.h, src/libYARP_dev/src/FrameGrabberControlImpl.cpp, src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.cpp
This PR:
- Fixes #1871
- Fixes #1875
- Fixes #1877 
Moreover it clarifies the documentation of (`set/getDepthAccuracy`).
Tests on real and fake device have been done.
=> Various fixes rgbd sensors/wrapper

src/libYARP_dev/include/yarp/dev/IRGBDSensor.h
* Remove spurious sentence in getDepthImage , probably due to a copy&paste from getRgbImage
* Added unit of measurement for the depth frame (as inferred by the `realsense2` driver)
* Clarified that the external timestamp can be a local variable, no need for the user to provide explicit memory allocation
=> Cleanup of getDepthImage docs

doc/release/v3_2_0.md, src/devices/realsense2/realsense2Driver.cpp, src/libYARP_dev/src/devices/ServerGrabber/ServerGrabber.cpp, src/libYARP_dev/src/devices/ServerGrabber/ServerGrabber.h, src/libYARP_sig/CMakeLists.txt, src/libYARP_sig/include/yarp/sig/ImageUtils.h, src/libYARP_sig/src/ImageUtils.cpp, tests/libYARP_sig/ImageTest.cpp
This PR add  `ImageUtils.h`, an header containing the following image utilities:
- `utils::vertSplit`
- `utils::horzSplit`
- `utils::vertConcat`
- `utils::horzConcat`
it fixes #1870 
=> Add ImageUtils

doc/release/v3_2_0.md, src/libYARP_manager/include/yarp/manager/xmlclusterloader.h, src/libYARP_manager/src/xmlclusterloader.cpp, src/yarpmanager/src-manager/clusterWidget.cpp, src/yarpmanager/src-manager/clusterWidget.h, src/yarpmanager/src-manager/clusterWidget.ui
Fix https://github.com/robotology/yarp/issues/1893
Maybe also the graphic should be modified, adding a column with the address. It would be even better if it could be modified from the GUI, but I don't really know what to touch.
=> Specify a different name for the node name and the yarprun server name in the yarpmanager

bindings/python/tests/test_vector.py, bindings/yarp.i, doc/release/v3_1_1.md, doc/release/v3_2_0.md, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/devices/RemoteControlBoard/RemoteControlBoard.cpp, src/libYARP_dev/src/devices/RemoteControlBoard/stateExtendedReader.cpp, src/libYARP_sig/include/yarp/sig/PointCloud.h, src/libYARP_sig/include/yarp/sig/Vector.h, tests/libYARP_sig/VectorOfTest.cpp, tests/libYARP_sig/VectorTest.cpp
This PR modernize *our* Vector.
It adds:
1. constructor with `initializer_list`: `Vector {1.0, 2.0, 3.0}`
2.  `reserve()` and `capacity()`
3. `push_back(&&)`
4. `emplace_back(_Args ..)`
5. `begin()`, `cbegin()`, `end()`, `cend()`
6. deprecate `getFirst()` in favour of begin() or data().
now begin() and data() are the same because the `VectorOf::iterator` is an alias of `T*`, but one day we could implement a proper `iterator` and they will diverge.
Implementing `begin()` and `end()` allow to use the yarp vector in the stl algorithm and use for range based (`for(auto el : v)`)
It fixes #1898
It fixes #1899 
Relatives tests have been added
=> Modernize vector

src/libYARP_OS/src/Carriers.cpp, src/libYARP_OS/src/Network.cpp, src/libYARP_OS/src/ResourceFinder.cpp
Current implementation of the `chooseCarrier` method is really confusing.
It accepts a pointer to a `const std::string` and a pointer to a `const yarp::os::Bytes` that can be null, but the method is called wither with the first parameter and the second equal to `nullptr`, or vice versa, therefore I split the method in 2 separate methods, and changed them to use const references instead of pointers.
Anyway, the real problem is that these lines are *really* confusing and hard to understand:
https://github.com/drdanz/yarp/blob/096b771f31599fd06bc5a6f68817be9db199b398/src/libYARP_OS/src/Carriers.cpp#L62-L71
I replaced them with `substr` and recursion.
---
Edit: Added a second commit that does very similar changes in Network.cpp
---
Edit 2: Added a third commit for ResourceFinder
=> OS: Refactor a few private methods

cmake/YarpInstallationHelpers.cmake
Partial revert of  https://github.com/robotology/yarp/pull/1841, fix https://github.com/robotology/yarp/issues/1866 .
The issue was tricky to spot, because even if the directory separator substitution was added for both the build and install manifest, it was not actually affecting the build manifest as it was done **after** the line `configure_file("${_in_file}" "${_build_file}" @ONLY).
It is still necessary to investigate why `path.d` manifests and plugin libraries manifest need different directory separators (the actual root behind https://github.com/robotology/yarp/pull/1841). I think this is probably related to how this two files are  **consumed**, rather than how they are **generated** but I think this can be done after we actually fix the serious bug …
=> Remove directory separator substitution in the <package>.ini plugin manifest

doc/release/v3_2_0.md, src/carriers/bayer_carrier/BayerCarrier.h, src/libYARP_OS/include/yarp/os/ConnectionReader.h, src/libYARP_OS/include/yarp/os/ConnectionWriter.h, src/libYARP_OS/include/yarp/os/InputStream.h, src/libYARP_OS/include/yarp/os/NullConnectionReader.h, src/libYARP_OS/include/yarp/os/NullConnectionWriter.h, src/libYARP_OS/include/yarp/os/impl/BufferedConnectionWriter.h, src/libYARP_OS/include/yarp/os/impl/ConnectionRecorder.h, src/libYARP_OS/include/yarp/os/impl/StreamConnectionReader.h, src/libYARP_OS/src/BufferedConnectionWriter.cpp, src/libYARP_OS/src/ConnectionRecorder.cpp, src/libYARP_OS/src/InputStream.cpp, src/libYARP_OS/src/NullConnectionReader.cpp, src/libYARP_OS/src/NullConnectionWriter.cpp, src/libYARP_OS/src/StreamConnectionReader.cpp
Change the signature of the following methods:
* `ConnectionReader::expectText()`
* `ConnectionWriter::appendString()`
* `InputStream::readLine()`
**WARNING**: Very small API break, but I sincerely hope that nobody ever used these methods with an int
=> OS: Pass terminating characters as const char instead of int

src/carriers/zfp_portmonitor/CMakeLists.txt
the command `target_include_directories` was used instead of `target_link_libraries`
[CI_SKIP]
=> Fix error in zfp CMakeList

doc/release/v3_2_0.md, doc/yarp_pointcloud.dox, src/devices/depthCamera/depthCameraDriver.cpp, src/devices/depthCamera/depthCameraDriver.h, src/devices/realsense2/realsense2Driver.cpp, src/libYARP_dev/include/yarp/dev/RGBDSensorParamParser.h, src/libYARP_dev/src/RGBDSensorParamParser.cpp, src/libYARP_sig/CMakeLists.txt, src/libYARP_sig/include/yarp/sig/IntrinsicParams.h, src/libYARP_sig/include/yarp/sig/PointCloud.h, src/libYARP_sig/include/yarp/sig/PointCloudUtils-inl.h, src/libYARP_sig/include/yarp/sig/PointCloudUtils.h, src/libYARP_sig/src/IntrinsicParams.cpp, src/libYARP_sig/src/PointCloudUtils.cpp, tests/libYARP_sig/PointCloudTest.cpp
Following the request of @claudiofantacci I implemented 2 functions to get `yarp::sig::PointCloud` from depth images given the intrinsic parameters.
These functions have been added in `YARP_math` because I would try to optimize the mathematical operations using eigen or something else, for now they are simple for loops.
In these functions I need the structure `IntrinsicParams` but it was in `YARP_dev` and since `math` cannot depend from `dev` I moved it in `YARP_sig` implementing it as `yarp::os::Portable`. I kept it anyways also in `YARP_dev` as deprecated typedef.
Finally I added the missing documentation for the `RGBDSensorParamParser` (Fixes #1863). 
TODO:
=> Add conversion depthImage->PointCloud

doc/release/v3_1_1.md, src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp, src/devices/imuBosch_BNO055/imuBosch_BNO055.h
Despite the serial, i2c does not put the ack in the first 2 bytes of the
response, so they are not to be discarded.
This device is not tested by CI
=> Fix imu bosh i2c

src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.cpp, src/libYARP_dev/src/devices/RGBDSensorWrapper/RGBDSensorWrapper.h
swapped the init strings of color and depth parameters in order to maintain their meaning
=> small fix in RGBDSensorWrapper

src/libYARP_sig/include/yarp/sig/Image.h
Since `Image.h` gets included within the user code, the type mismatch causes plenty of annoying warnings.
Don't know whether changing the returned type will cause other warnings in cascade though. If so, we could keep the returned type unchanged and then fix the line `38`.
=> Fixed annoying warnings caused by Image.h

cmake/template/Doxyfile.in, doc/release/v3_2_0.md, src/CMakeLists.txt, src/libYARP_cv/CMakeLists.txt, src/libYARP_cv/include/yarp/cv/Cv-inl.h, src/libYARP_cv/include/yarp/cv/Cv.h, src/libYARP_pcl/CMakeLists.txt, src/libYARP_sig/include/yarp/sig/Image.h, src/libYARP_sig/src/Image.cpp, src/yarpdatadumper/main.cpp, src/yarpdataplayer/CMakeLists.txt, src/yarpdataplayer/include/worker.h, src/yarpdataplayer/src/worker.cpp
In late 2018 we have finally a easy way that allow to get a `cv::Mat` from a `yarp::sig::ImageOf` :tada: 
Since there is no way to retrieve the Pixel code from the `cv::Mat` and the default coding is BGR, this library assumes that when converting to yarp image, the cv::Mat has to be BGR, and the cv::Mat obtained from the reversed conversion is BGR.
Converting from OpenCV to Yarp no copies are involved.
In the other direction is quite tricky to understand when OpenCV performs a copy and when not :confused: 
@drdanz and me found a sort of rule behind their choice to copy or not, but maybe it is not important.
The argument of `toCvMat()` is a `&&` a.k.a a right-reference, this means that after this function call the integrity of the data of the input yarp image is no longer guaranteed. Since …
=> Add opencv compatibility library

src/devices/localization2DServer/Localization2DServer.cpp
In the Localization2DServer.cpp file, the std::nan function is used. This function is defined in the cmath header ( https://en.cppreference.com/w/cpp/numeric/math/nan ).
Before this commit the math.h header (that only defines nan in the global namespace, not std::nan) was included instead of cmath.
This can create a compilation failure or not depending on the platform due to transitive inclusion of cmath in the other included headers.
=> Include cmath if std::nan is used

.travis.yml
This PR should fix macOs build on travis(`opencv 4.0.1`), but I'm afraid it will break the linux ones, I don't know which version of ubuntu and then OpenCV there is in our travis.
On `master` unfortunately it is quite tricky to fix since the new compatibility library `YARP_cv` to handle the `cv::Mat` is only on `devel` and `opencv 4` get rid of `IplImage* cvLoadImage()` in favour of `cv::Mat imread()`
Related to #1672 
=> Fix macOs build

doc/release/v3_2_0.md, src/libYARP_cv/include/yarp/cv/Cv-inl.h, src/libYARP_sig/include/yarp/sig/Image.h, src/libYARP_sig/src/Image.cpp
This PR add move semantic in `yarp::sig::Image`.
Moreover it fixes a alignment issue in the `YARP_cv` library.
=> Add move semantic in yarp image

doc/release/v3_2_0.md, example/game/game_server/main.cpp, src/libYARP_OS/include/yarp/os/ConnectionReader.h, src/libYARP_OS/include/yarp/os/ConnectionWriter.h, src/libYARP_OS/include/yarp/os/NullConnectionWriter.h, src/libYARP_OS/include/yarp/os/impl/BufferedConnectionWriter.h, src/libYARP_OS/include/yarp/os/impl/ConnectionRecorder.h, src/libYARP_OS/include/yarp/os/impl/StreamConnectionReader.h, src/libYARP_OS/src/BottleImpl.cpp, src/libYARP_OS/src/BufferedConnectionWriter.cpp, src/libYARP_OS/src/ConnectionRecorder.cpp, src/libYARP_OS/src/NameServer.cpp, src/libYARP_OS/src/NullConnectionWriter.cpp, src/libYARP_OS/src/PortCommand.cpp, src/libYARP_OS/src/Stamp.cpp, src/libYARP_OS/src/StreamConnectionReader.cpp, src/libYARP_OS/src/SystemInfoSerializer.cpp, src/libYARP_OS/src/WireWriter.cpp, src/libYARP_dev/src/Map2DArea.cpp, src/libYARP_dev/src/MapGrid2D.cpp, src/libYARP_name/include/yarp/name/NameServerConnectionHandler.h, src/libYARP_name/src/BootstrapServer.cpp, src/libYARP_wire_rep_utils/WireImage.h
* `ConnectionWriter::appendString()` is deprecated in favour of `appendText()`.
* `ConnectionWriter::appendRawString()` is deprecated in favour of  `appendString()`.
* Added `ConnectionReader::expectString()`.
Fixes #1953
=> Synchronize "Append" and "Expect" methods for strings

src/yarprobotinterface/Types.h
simple as the title said. at the moment the bug is blocking the compilation on visual studio 2019
=> include what you use fix on Types.h

src/libYARP_sig/src/Image.cpp
It fixes #1979 
The best should be add a test to reproduce the bug fixed, but til now I was not able to reproduce it without opencv.
=> YARP_sig: fix move operator of Image

doc/release/v3_1_1.md, src/libYARP_dev/include/yarp/dev/ImplementControlLimits2.h
This patch solves ~~two issues~~:
* Broken header inclusion in `ImplementControlLimits2.h`.
* ~~Missing `ImplementControlLimits2.h` in `ControlBoardInterfacesImpl.h`. This used to work prior to YARP 3.0, hence I'm identifying it as a regression. Moreover, I preferred to remove `ImplementControlMode.h` so that it's treated equally with everything else. Alternatively, use deprecation macros:~~
```c++
#ifndef YARP_NO_DEPRECATED
#include <yarp/dev/ImplementControlLimits2.h> // and so on
#else
#include <yarp/dev/ImplementControlLimits.h> // and so on
#endif
```
(I'm not sure whether it makes sense since those deprecated headers are being installed anyway. Dropping this idea in case it's worth investigating further.)
**Edit:** dropped from the final patchset …
=> Fix header inclusion (ImplementControlLimits.h)

src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp
Follows up https://github.com/robotology/yarp/pull/1691. Should be harmful, this patchset does nothing more than:
```c++
if (cond1)
{ /* use new interface methods */ }
else
{
if (cond1) // *** REMOVED, we never reach this branch ***
{ /* use old interface methods */ }
else
{ /* report error */ }
}
```
Also, some redundant/misleading/outdated comments have been deleted.
=> Remove dead code in CBW (old motor interface leftovers)

doc/release/v3_1_1.md, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp
Might have led to buggy behavior in case some subdevice did not implement an unrelated interface.
=> Fix interface checks in CBW prior to forwarding a method call

doc/release/v3_1_1.md, src/libYARP_dev/src/devices/RemoteControlBoard/RemoteControlBoard.cpp, src/libYARP_dev/src/devices/RemoteControlBoard/stateExtendedReader.cpp, src/libYARP_dev/src/devices/RemoteControlBoard/stateExtendedReader.h
This PR fixes #1833.
With @barbalberto we thought to add timeout check in all data kind streamed by `*\stateExt:o` ports not only for certain(e.g. `getEncoder`).
It is wip because it is more a proposal.
=> Move the timeout check from RemoteControlBoard to the stateExtendedReader

doc/release/v3_2_0.md, src/libYARP_OS/include/yarp/os/Property.h, src/libYARP_OS/src/Property.cpp, tests/libYARP_OS/PropertyTest.cpp
This PR add the `initializer_list` constructor for the property.
Now it is possible to easily initilialize the Property from the construction.
E.g. : 
```c++
Property p {{"one", Value(1)},
{"two", Value(2.0)},
{"string", Value("foo")}
};
```
It is an idea that came up with @aerydna 
=> Add initilizer_list constructor in Property

doc/release/v3_2_0.md, src/libYARP_OS/include/yarp/os/Bottle.h, src/libYARP_OS/src/Bottle.cpp, tests/libYARP_OS/BottleTest.cpp
This PR adds the `initializer_list` constructor in `Bottle`.
Example:
```c++
Bottle b { Value(1),
Value(2.0),
Value("foo")
};
```
=> Add initializer_list constructor in Bottle

doc/release/v3_2_0.md, src/libYARP_dev/src/devices/AnalogSensorClient/AnalogSensorClient.cpp, src/libYARP_dev/src/devices/AnalogWrapper/AnalogWrapper.cpp
Closes #1981. Also, remote calls to `calibrateSensor(const yarp::sig::Vector& value)` are now handled by the server device.
=> Correctly handle return codes in IAnalogSensor server/client device pair

src/devices/realsense2/realsense2Driver.cpp
Fixes https://github.com/robotology/yarp/issues/2009, please test on other RealSense models (@Nicogene).
Known `rs2::sensor` subclasses include, at time of writing: `rs2::depth_sensor` (checked against in current code), `rs2::pose_sensor`, `rs2::wheel_odometer` and `rs2::roi_sensor` (see [*rs_sensor.hpp*](https://github.com/IntelRealSense/librealsense/blob/9bdbfd98440b6516f8c864fbdfd6a9778b2c5715/include/librealsense2/hpp/rs_sensor.hpp)). I noticed that the color sensor in D435i is perceived by the SDK as a `rs2::roi_sensor` (`sensor.is<rs2::roi_sensor>() == true`). Since this might not be portable to other models, the solution described in https://github.com/IntelRealSense/librealsense/issues/1163#issuecomment-364733894 has been implemented here.
=> Correctly detect color sensor on D435i

doc/release/v3_2_0.md, src/idls/thrift/src/t_yarp_generator.cc
Read annotations for defining the import/export macro (e.g. `YARP_os_API`)
* `yarp.api.include` = the header file that contains the definition of
the import/export keyword
* `yarp.api.keyword` = the name of the keyword
Example:
```thrift
struct foo
{
1: i32 bar;
2: i32 baz;
} (
yarp.api.include = "yarp/dev/api.h"
yarp.api.keyword = "YARP_dev_API"
)
```
=> yarpidl_thrift: Allow to define import/export macros

doc/release/v3_2_0.md, src/libYARP_dev/include/yarp/dev/CanBusInterface.h
Users were forced to `const_cast<>` a `const yarp::dev::CanBuffer` instance in order to call `getPointer()`.
=> Add const counterpart of CanBuffer::getPointer()

src/libYARP_OS/include/yarp/os/RpcServer.h
The method write in RPCServer.h is overridden to disable it, but on the YARP documentation website it appears to be highlighted and working. The method documentation is then modified, as this can be misleading.
=> Documentation fix on RPCServer write function

src/libYARP_dev/include/yarp/dev/CanBusInterface.h
Pure template classes do not need any symbol-visibility attributes, as they define no symbols in the `libYARP_dev`  library. 
If there was  an explicit template instantiation in the library, then `YARP_dev_API` should be added to the template instantiation (see https://anteru.net/blog/2008/c-tricks-6-explicit-template-instantiation/).
Fix https://github.com/robotology/icub-main/issues/577 .
=> Remove YARP_dev_API attribute from yarp::dev::ImplementCanBufferFactory

doc/release/v3_2_0.md, src/devices/map2DClient/Map2DClient.cpp, src/devices/map2DClient/Map2DClient.h, src/devices/map2DServer/Map2DServer.cpp, src/libYARP_dev/include/yarp/dev/ILocalization2D.h, src/libYARP_dev/include/yarp/dev/IMap2D.h, tests/libYARP_dev/MapGrid2DTest.cpp
Added the following methods:
yarp::dev::IMap2D::renameLocation(std::string original_name, std::string new_name);
yarp::dev::IMap2D::renameArea(std::string original_name, std::string new_name);
=> Added method to rename areas and locations

doc/release/v3_2_0.md, src/libYARP_dev/CMakeLists.txt, src/libYARP_dev/include/yarp/dev/IVisualServoing.h, src/libYARP_dev/src/IVisualServoing.cpp
After https://github.com/robotology/yarp/pull/2011#pullrequestreview-232263751 this PR has been changed to provide an `IVisualServoing.cpp` file with an explicit call to the compiler default destructor implementation.
---
_Initial post_
This PR partially reverts https://github.com/robotology/yarp/commit/864c3f851d36ad28b5d5dded442ef857477ffcb6.
In particular, it removes `YARP_dev_API` from `IVisualServoing` interface header because, under Windows, nothing is exported into a dll and the keyword triggers a linker error when using `IVisualServoing` for implementing derived classes.
Out of sheer curiosity, why wasn't I automatically call in during #2006 review for this particular file?
=> Add IVisualServoing destructor implementation in cpp file

cmake/YarpIDL.cmake, cmake/template/placeGeneratedYarpIdlFiles.cmake.in, doc/release/v3_2_0.md, src/idls/thrift/src/t_yarp_generator.cc, src/libYARP_dev/CMakeLists.txt, src/libYARP_rosmsg/CMakeLists.txt, src/yarpdataplayer/CMakeLists.txt, src/yarprobotinterface/CMakeLists.txt, tests/yarpidl_rosmsg/demo/CMakeLists.txt, tests/yarpidl_thrift/demo/CMakeLists.txt
* Support passing multiple files to `yarp_idl_to_dir`
* Add optional parameters to `yarp_idl_to_dir`
* Use the namespace as subdirectory (can be disabled using the no_namespace_prefix option. For compatibility, this is disabled by default when using `yarp_idl_to_dir` with the old syntax)
* Cleanup
=> yarpidl_thrift/YarpIDL more refactor

src/devices/map2DServer/Map2DServer.cpp
Added some string commands via rpc to list/clear the available areas into the map server. The same commands were already available via Map2Client, so this is just a minor change, useful only when you want to check the status of the server storage via command line.
=> Map2dserver rpc

src/devices/DynamixelAX12Ftdi/DynamixelAX12FtdiDriver.cpp, src/devices/DynamixelAX12Ftdi/DynamixelAX12FtdiDriver.h, src/libYARP_dev/include/yarp/dev/IPositionControl.h, src/libYARP_dev/src/ImplementPositionControl.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp
This PR fixes issues reported in issue #2027 for files
* DynamixelAX12FtdiDriver.cpp
* ControlBoardWrapper.cpp
* ImplementPositionControl.cpp
The device `DynamixelAX12FtdiDriver.cpp` has been updated with multiple-joint version of functions, e.g.
`    bool positionMove(const int n_joint, const int *joints, const double *refs) override;`
They now are mandatory for a device driver.
_**Before merging this PR**_, we need to merge the PR fixing the implementation in iCub's `embobjMotionControl`
=> Fix checkMotionDone

src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp, src/devices/imuBosch_BNO055/imuBosch_BNO055.h
This commit implements requests from issue #1994, the PR is done on devel as requested.
HW read error is propagated to YARP call
While opening, a first read is done, if it fails the device is closed.
Please test the PR on a real device before merging, to verify it works as specification.
=> IMU bosh: read error propagated up to YARP call - issue #1994

src/libYARP_dev/include/yarp/dev/ImplementMotor.h, src/libYARP_dev/src/ImplementMotor.cpp, src/libYARP_dev/src/ImplementPositionControl.cpp
This fix has to be merged in devel because the bug is present only in devel and not in master.
This fixes also another error in `getTemperatures` function which was not doing the joint remapping.
Please @randaz81 can you double check?
=> Fix issue #1982

doc/release/v3_2_0.md, src/yarprobotinterface/Module.cpp, src/yarprobotinterface/RobotInterfaceDTD.cpp, src/yarprobotinterface/XMLReader.h, src/yarprobotinterface/XMLReaderVx.cpp
Parser for yarprobotinterface configuration files v1.0 is now deprecated. Only v3.0 is supported.
=> `yarprobotinterface` will not run anymore deprecated DTD format v1.0

src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp, src/libYARP_dev/src/devices/ControlBoardWrapper/ControlBoardWrapper.h, src/libYARP_dev/src/devices/ControlBoardWrapper/SubDevice.h, src/libYARP_dev/src/devices/TestMotor/TestMotor.h
TESTED ON ROBOT
This PR changes how the ControlBoardWrapper refreshes the data from the HW and send them via the output ports state:o and stateExt:o.
This is due to a corner case found, where the position data on the 2 ports were different.
Previous implementation was calling `getEncoders` for one port and `getEncodersTimed` for the other one.
In the low-level device one function was implemented and the other one was not.
Although it is legal for the wrapper to do so (and the bug is actually on the low-level device), it is quite a counter-intuitive and misleading behaviour for the wrapper, and it is better to have a more uniform one.
Since the wrapper during the attach phase enforces the requirement of the `IEncoderTimed` interface only, this is the only one used now.
Furthermore, in the …
=> Control board wrapper improvement

doc/cmd_yarpdatadumper.dox, doc/release/devel.md, src/yarpdatadumper/CMakeLists.txt, src/yarpdatadumper/main.cpp, src/yarpdataplayer/src/utils.cpp
This PR aims to extend `yarpdatadumper` so that:
- Images can be saved also in the PNG format; for that, just use the option `--type image_png`
- The format of the time stamps is provided from within the `info.log` file as in the following example:
```
Type: Bottle;
Stamp: [rx; | tx; | tx+rx;]
[local-timestamp] /yarp-port-name [connected]
[local-timestamp] /yarp-port-name [disconnected]
```
Preliminary tests show that the low-level YARP services devoted to deal with storing the PNG images are correctly called, even though I'm getting some PNG header errors on my machine. This behavior might be linked to my installation though, hence further verifications are required.
@vtikha I've modified the `yarpdataplayer` to let it read the new format of `info.log`. Please, have a look at it. …
=> yarpdatadumper to save PNG images

doc/release/master.md, src/carriers/mjpeg_carrier/MjpegCarrier.cpp
This PR fixes #2060.
`MONO`, `RGB` and `BGR` have been successfully tested
=> Fix mjpeg while using BGR images

src/devices/multipleanalogsensorsremapper/MultipleAnalogSensorsRemapper.cpp
Here
https://github.com/robotology/yarp/blob/3c157dc43783506b71fb03fe65ad9b201886aaaa/src/devices/multipleanalogsensorsremapper/MultipleAnalogSensorsRemapper.cpp#L509
the remapper creates dummy, a auxiliary vector of 1 element only, but then accesses to dummy[1], its second element.
This pr fixes this issue #2056
=> fix MultipleAnalogSensorsRemapper::getTemperatureSensorMeasure 

bindings/lua/examples/driver_qos.lua, bindings/lua/examples/example.lua, bindings/lua/examples/example2.lua
As of 2019-08-04 in yarp master branch, Lua bindings examples are failing with the following error:
```bash
./example.lua 
[...]
yarp: Port /lua active at tcp://10.0.3.10:10002/
Sending: count 1 of 100
/usr/bin/lua: ./example.lua:39: attempt to call field 'Time_delay' (a nil value)
stack traceback:
./example.lua:39: in main chunk
[C]: in ?
```
This PR fixes the call to `yarp.delay`, restoring the execution of the examples:
```bash
./example.lua 
[...]
yarp: Port /lua active at tcp://10.0.3.10:10002/
Sending: count 1 of 100
Sending: count 2 of 100
Sending: count 3 of 100
[...]
```
=> Fix delay function in Lua bindings examples

doc/release/devel/Property_refactor.md, src/libYARP_OS/include/yarp/os/Property.h, src/libYARP_OS/include/yarp/os/Searchable.h, src/libYARP_OS/src/Property.cpp
* Added move constructor and assignment operator.
* Minor refactor (always allocate the pimpl member, instead of calling 'summon()' everywhere). this will have a minor impact when creating an empty property that is never "summoned" (if that ever happened), but a tiny speedup (a function call and an if) whenever the property is used.
* Added move constructor and assignment operator.
* :warning: The `yarp::os::Property` constructor using `hash_size` was deprecated (it was
already unused since the internal structure was ported to use `std::map`).
=> yarp::os::Property: Small Refactor

src/libYARP_OS/include/yarp/os/impl/PortCore.h, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/PortCoreInputUnit.cpp
Split into tiny commits, since touching this part is very dangerous, and this will allow to debug it in case something goes wrong.
Also unrelated (maybe I'll move it in a separate PR before merging),  the `yarp::os::Property` constructor using 'hash_size' was deprecated (it was already unused since the internal structure was ported to use std::map).
=> PortCore refactor

CMakeLists.txt, doc/release/devel/AddOptionMASClient.md, src/devices/multipleanalogsensorsclient/MultipleAnalogSensorsClient.cpp, src/devices/multipleanalogsensorsclient/MultipleAnalogSensorsClient.h
TESTED
Please @traversaro check if I am missing something
=> MultiplAnalogSensorsClient: add --externalConnection option

doc/release/devel/TimerMutex.md, doc/release/devel/deprecate_Mutex.md, doc/release/devel/setCallBackLock.md, src/libYARP_OS/CMakeLists.txt, src/libYARP_OS/include/yarp/os/AbstractContactable.h, src/libYARP_OS/include/yarp/os/BufferedPort-inl.h, src/libYARP_OS/include/yarp/os/BufferedPort.h, src/libYARP_OS/include/yarp/os/Contactable.h, src/libYARP_OS/include/yarp/os/LockGuard.h, src/libYARP_OS/include/yarp/os/Mutex.h, src/libYARP_OS/include/yarp/os/Port.h, src/libYARP_OS/include/yarp/os/RecursiveMutex.h, src/libYARP_OS/include/yarp/os/Timer.h, src/libYARP_OS/include/yarp/os/all.h, src/libYARP_OS/include/yarp/os/impl/PortCore.h, src/libYARP_OS/include/yarp/os/impl/PortCoreAdapter.h, src/libYARP_OS/src/AbstractContactable.cpp, src/libYARP_OS/src/Mutex.cpp, src/libYARP_OS/src/Port.cpp, src/libYARP_OS/src/PortCore.cpp, src/libYARP_OS/src/PortCoreAdapter.cpp, src/libYARP_OS/src/RecursiveMutex.cpp, src/libYARP_OS/src/Timer.cpp
I'll just leave this here, waiting for a discussion in september, the patch is not just a lot more than just deprecating `yarp::os::Mutex` but the title should be able to catch some people eyes :laughing: 
The first part of the patch aims at supporting `std::mutex` in YARP classes. I see no reason not to have this
* `Contactable`, `AbstractContactable` `Port`, `BufferedPort`: Added `setCallbackLock` overrides to pass a `std::mutex` instead of a `yarp::os::Mutex`
* `Timer`: Added constructors that accept `std::mutex` instead of `yarp::os::Mutex`
The last part deprecates `yarp::os::Mutex` in favour of `std::mutex`. Since the yarp class adds nothing and `std::mutex` is in the standard since 2011, I see no reason to keep having a duplicated YARP class.
* All `yarp::os::Mutex` related classes …
=> Deprecate yarp::os::Mutex in favour of std::mutex

cmake/YarpIDL.cmake, doc/release/devel/YarpIDL_PLACEMENT.md, src/devices/multipleAnalogSensorsMsgs/CMakeLists.txt, src/idls/thrift/src/t_yarp_generator.cc, src/libYARP_rosmsg/CMakeLists.txt
The `yarp_idl_to_dir` command now accepts the `PLACEMENT` option:
* `MERGED`:        headers and sources in `<OUTPUT_DIR>/<namespace>`
* `SEPARATE`:      headers in `<OUTPUT_DIR>/include/<namespace>` sources in
`<OUTPUT_DIR>/src/<namespace>`
* `SEPARATE_EVEN`: Alias for `SEPARATE`
* `SEPARATE_ODD`:  headers in `<OUTPUT_DIR>/include/<namespace>` sources in
`<OUTPUT_DIR>/src`
For backwards compatibility the default value is `SEPARATE_ODD`.
yarpidl_thrift now places the source files according to the "separate"
layout.
After calling the `yarp_add_idl` method, the `YARP_ADD_IDL_INCLUDE_DIR`
variable contains the include directory for using the header files
=> yarpidl_thrift/YarpIDL.cmake: Allow "standard" file placements

doc/release/devel/alignRGBD.md, src/devices/realsense2/realsense2Driver.cpp, src/devices/realsense2/realsense2Driver.h, src/libYARP_dev/CMakeLists.txt, src/libYARP_dev/src/RGBDSensorParamParser.cpp
This PR add the possibility to align the frames of the realsense camera to the depth frame.
Before it was only possible to align the depth image over the rgb frame.
For doing so I add a new parameter called `alignmentFrame` and deprecated the old `needAlignment`.
The default behaviour has been maintaned, if not specified `alignmentFrame` is `RGB`.
The allowed values are `RGB`, `Depth` and `None`.
To be tested.
=> Add the possibility to align the frames of the realsense camera also to the depth frame

cmake/template/YARPConfig.cmake.in
It should fix the issue introduced by #2105 .
It is a quite easy fix, the answer is @drdanz why did you put `_yarp_component_path_is_deprecated` ?
Do you forgot to define the macro? Or it was a typo?
=> Fix YarpConfig

src/yarpmanager/src-manager/clusterWidget.ui
This fixes a wrong label in `yarpmanager clusterWidget` user interface
https://github.com/robotology/yarp/blob/e28da21babaace57aa55507fa8c291459a113737/src/yarpmanager/src-manager/clusterWidget.ui#L71
changing it to 
```<string>Cluster Management Window</string> ```.
fixes #2113
=> [yarpmanager] Fix wrong text label in clusterWidget

doc/release/devel/yarpdatadumper_dirname.md, src/yarpdatadumper/main.cpp
This PR addresses #2116 so that special chars (`:`, `*`, `|`...) in the name of the dirs created by `yarpdatadumper` get replaced with the underscore. The chars `/`, '\' can be still used as it will allow for creating nested dirs.
=> yarpdatadumper can handle dir name w/ special chars

src/libYARP_dev/src/yarp/dev/Wrapper.h
The YARP_COMPILER_WARNING macro is defined in yarp/conf/system.h, so it is needed to include it to use the macro.
=> Fix compilation when including Wrapper.h

doc/release/devel/Network_isConnected.md, src/libYARP_os/src/yarp/os/Network.cpp, src/libYARP_os/src/yarp/os/Network.h
* Cleanup of the signature of the following methods of `yarp::os::Network`:
```
static bool connect(const std::string& src, const std::string& dest, const ContactStyle& style);
static bool connect(const std::string& src, const std::string& dest, const std::string& carrier = "",  bool quiet = true);
static bool connect(const char* src, const char* dest, const char* carrier,  bool quiet = true);
static bool disconnect(const std::string& src, const std::string& dest, bool quiet);
static bool disconnect(const std::string& src, const std::string& dest, const ContactStyle& style);
static bool disconnect(const std::string& src, const std::string& dest, const std::string& carrier = "", bool quiet = true);
static bool disconnect(const char* src, const char* dest, const char* carrier, bool quiet = …
```
=> cleanup of the signature of several methods of yarp::os::Network

doc/release/devel/refactor_MessageStack.md, src/libYARP_os/src/yarp/os/MessageStack.cpp, src/libYARP_os/src/yarp/os/MessageStack.h
* Properly implement PIMPL.
* Use condition_variable instead of semaphore.
* Constructor now accepts the max number of thread as `size_t` instead of `int`.
* Copy and move constructors and operators are now explicitly deleted.
* Cleanup.
=> os/MessageStack: Refactor

cmake/YarpSystemCheck.cmake, src/libYARP_os/src/CMakeLists.txt, src/libYARP_os/src/yarp/os/Log.cpp, src/libYARP_os/src/yarp/os/impl/windows/WinConsole.c
Colored output by `yarp::os::Log`'s utilities is achieved via setting the `YARP_COLORED_OUTPUT` environment variable on UNIX systems. This patch enables said feature for the Windows 10 console.
Tested on 17134 (1803). Should work since 10586 (1511), although code authors were forced to enable colors programatically from 14393 (1607) onwards according to https://github.com/symfony/symfony/issues/19520#issuecomment-238815318.
Adapted from RL/UC3M code, see https://github.com/roboticslab-uc3m/color-debug/issues/5 for full rationale.
Sample test code:
```c++
cmake_minimum_required(VERSION 3.5 FATAL_ERROR)
project(yarp-logger-test LANGUAGES CXX)
find_package(YARP 3.1 REQUIRED COMPONENTS OS)
file(WRITE ${CMAKE_BINARY_DIR}/main.cpp
"
#include <yarp/os/LogStream.h>
int main()
{
yTrace() << …
```
=> Enable colored logger output on Windows 10

doc/release/devel/addFilesystem.md, src/libYARP_companion/src/yarp/companion/impl/Companion.cpp, src/libYARP_conf/src/CMakeLists.txt, src/libYARP_conf/src/yarp/conf/filesystem.h, src/libYARP_manager/src/yarp/manager/scriptbroker.cpp, src/libYARP_manager/src/yarp/manager/xmlapploader.cpp, src/libYARP_manager/src/yarp/manager/xmlmodloader.cpp, src/libYARP_manager/src/yarp/manager/xmlresloader.cpp, src/libYARP_manager/src/yarp/manager/xmltemploader.cpp, src/libYARP_os/src/yarp/os/Network.cpp, src/libYARP_os/src/yarp/os/Network.h, src/libYARP_os/src/yarp/os/ResourceFinder.cpp, src/libYARP_os/src/yarp/os/impl/NameConfig.cpp, src/libYARP_run/src/yarp/run/Run.cpp, src/yarpmanager-console/ymanager.cpp, src/yarpmanager/src-manager/entitiestreewidget.cpp, src/yarpmanager/src-manager/mainwindow.cpp, src/yarpmanager/src-manager/newapplicationwizard.cpp, src/yarprobotinterface/XMLReaderVx.cpp, tests/devices/harness_devices.cpp, tests/harness.cpp, tests/libYARP_os/ResourceFinderTest.cpp
It fixes #1855 .
The main feature brought by this PR is that it has been possible to remove the inclusion of `Network.h` in several places where the actual network or communication wasn't involved.
It is a draft since @drdanz has some plan to create a separate library and get rid of other stuff not concerning the network in `Network.h`
=> Add filesystem utilities

src/libYARP_os/src/yarp/os/Log.cpp
Follow-up of https://github.com/robotology/yarp/pull/2076 and https://github.com/robotology/yarp/pull/2137. This patch performs a runtime check so that Windows systems that do not support colors do not attempt to add color markers (i.e. print `[DEBUG]test` instead of `[DEBUG]\033[01;32mtest\033[00m`). Also, I moved this Windows-specific code into an anonymous namespace (the C++ way of declaring variables and functions with internal static linkage).
=> Conditionally enable colored logger output in runtime check (WIN10)

doc/release/devel/TransformClient.md, src/devices/transformClient/FrameTransformClient.cpp, src/devices/transformClient/FrameTransformClient.h, src/devices/transformServer/FrameTransformServer.cpp, src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/yarp/dev/IFrameTransformClientControl.cpp, src/libYARP_dev/src/yarp/dev/IFrameTransformClientControl.h
* Added new interface `yarp::dev::IFrameTranformClientControl`
* `yarp::dev::TransformClient` implements the new interface `yarp::dev::IFrameTranformClientControl`.
*  The rpc port of the `yarp::dev::TransformClient` allows to reconnect to the server.
* `yarp::dev::TransformServer` allows the use of wildcard to erase all the transforms between a specified source and *;
or between * and a specified destination.
* The rpc port of the `yarp::dev::TransformServer` allows to delete a given transform.
=> Transform client improvements

doc/release/yarp_3_3/fixYarpdataplayerPlayRpc.md, src/yarpdataplayer/src/mainwindow.cpp
It fixes #2144.
What I learnt is that if you call `resume()` on a `PeriodicThread` already running, causes deadlock.
Tested successfully on my laptop.
=> Fix yarpdataplayer play rpc

doc/release/yarp_3_3/missing-depr-header.md, src/libYARP_dev/src/yarp/dev/GenericSensorInterfaces.h, src/libYARP_dev/src/yarp/dev/PreciselyTimed.h, src/libYARP_dev/src/yarp/dev/SerialInterfaces.h
Follows up https://github.com/robotology/yarp/pull/2096.
=> Add missing header for deprecation warning macro

doc/release/master/featureYarpdataplayerGetSliderPercentage.md, doc/release/v3_3_0.md, src/yarpdataplayer/idl_generated_code/include/yarpdataplayer_IDL.h, src/yarpdataplayer/idl_generated_code/src/yarpdataplayer_IDL.cpp, src/yarpdataplayer/include/mainwindow.h, src/yarpdataplayer/src/mainwindow.cpp, src/yarpdataplayer/yarpdataplayer.thrift
This PR adds `getSliderPercentage()` method to yarpdataplayer rpc.
cc @Nicogene @vtikha 
Could you please confirm that committing the IDL generated code is also required?
=> [yarpdataplayer] add rpc method to get slider percentage

doc/release/master/featureIPositionSensors.md, src/devices/multipleAnalogSensorsMsgs/idl_generated_code/include/SensorRPCData.h, src/devices/multipleAnalogSensorsMsgs/idl_generated_code/include/SensorStreamingData.h, src/devices/multipleAnalogSensorsMsgs/idl_generated_code/src/MultipleAnalogSensorsMetadata.cpp, src/devices/multipleAnalogSensorsMsgs/idl_generated_code/src/SensorRPCData.cpp, src/devices/multipleAnalogSensorsMsgs/idl_generated_code/src/SensorStreamingData.cpp, src/devices/multipleAnalogSensorsMsgs/multipleAnalogSensorsSerializations.thrift, src/devices/multipleanalogsensorsclient/MultipleAnalogSensorsClient.cpp, src/devices/multipleanalogsensorsclient/MultipleAnalogSensorsClient.h, src/devices/multipleanalogsensorsremapper/MultipleAnalogSensorsRemapper.cpp, src/devices/multipleanalogsensorsremapper/MultipleAnalogSensorsRemapper.h, src/devices/multipleanalogsensorsserver/MultipleAnalogSensorsServer.cpp, src/devices/multipleanalogsensorsserver/MultipleAnalogSensorsServer.h, src/libYARP_dev/src/yarp/dev/MultipleAnalogSensorsInterfaces.h
Added a new interface `yarp::dev::IPositionSensors`, which can be used with localization sensors (e.g. UWB localization sensor) to broadcast a XYZ measurement of the device w.r.t. a fixed frame.
`MultipleAnalogSensorsServer` and `MultipleAnalogSensorsClient` have been modified accordingly.
=> positionSensors added to MultipleAnalogSensorsInterfaces

doc/release/master/featureRealsenseWithIMU.md, src/devices/realsense2/CMakeLists.txt, src/devices/realsense2/realsense2Driver.cpp, src/devices/realsense2/realsense2Driver.h, src/devices/realsense2/realsense2Tracking.cpp, src/devices/realsense2/realsense2Tracking.h, src/devices/realsense2/realsense2withIMUDriver.cpp, src/devices/realsense2/realsense2withIMUDriver.h, src/libYARP_dev/src/CMakeLists.txt
realsense2withIMUDriver extends class realsense2Driver, using realsense SDK to add **support for d435i and t265 devices**. 
These two devices are equipped with an **IMU sensor**, whose data are obtained through the interfaces included in **MultipleAnalogSensorsInterfaces.h**
=> RealsenseWithImu device driver

doc/release/master/makeVectorMovable.md, src/libYARP_os/src/yarp/os/ManagedBytes.cpp, src/libYARP_os/src/yarp/os/ManagedBytes.h, src/libYARP_sig/src/yarp/sig/Vector.h
This PR makes `ManagedBytes` and `VectorOf` movable.
It fixes #1965.
Please review the code.
=> Make MangedBytes and VectorOf movable

src/libYARP_robotinterface/src/yarp/robotinterface/XMLReader.h, src/libYARP_robotinterface/src/yarp/robotinterface/XMLReaderV1.cpp, src/libYARP_robotinterface/src/yarp/robotinterface/XMLReaderV3.cpp, src/libYARP_robotinterface/src/yarp/robotinterface/XMLReaderVx.cpp, src/libYARP_robotinterface/src/yarp/robotinterface/impl/RobotInterfaceDTD.h, src/libYARP_robotinterface/src/yarp/robotinterface/impl/XMLReaderFileVx.h
* Fix include guards  of RobotInterfaceDTD
* Make XMLReaderFileVx, XMLReaderFileV1 and XMLReaderFileV3 private classes
=> Cleanup headers of libYARP_robotinterface

src/libYARP_sig/src/yarp/sig/Vector.h, tests/libYARP_sig/VectorOfTest.cpp
This PR get rid of `yarp::os::ManagedBytes` in `yarp::sig::Vector`.
It is just a draft for starting a discussion
It compiles and the tests passes.
And it fixes #2192 . (hopefully, it has to be tested).
=> YARP_sig: add std::vector under the hood of yarp::sig::Vector

cmake/YarpFindDependencies.cmake, doc/release/master/oculusUpdate.md, src/devices/ovrheadset/InputCallback.cpp, src/devices/ovrheadset/OVRHeadset.cpp, src/devices/ovrheadset/OVRHeadset.h
* Port to the new rendering API and make it focus aware (SDK 1.19 is required).
* Fixed race condition causing randomly frame drops.
* Fixed behaviour of the `CTRL` button. Both `CTRL` buttons can now be pressed,
only `SHIFT` will decide which eye offsets should be modified.
* Add `P` command to print current settings.
* Fixed `--no-logo` option.
* Fixed `--userpose` option.
=> ovrheadset bugfixes and enhancements

doc/release/yarp_3_3/fix_batteryClient.md, src/devices/batteryClient/BatteryClient.cpp
* Fixed methods returning int instead of double:
* `getVoltage()`
* `getCurrent()`
* `getCharge()`
* `getTemperature()`
=> batteryClient: Fix methods returning integer instead of double

doc/release/yarp_3_3/fix_batteryClient2.md, src/devices/fakeBattery/fakeBattery.cpp
* Fixed `PeriodicThread` using 100% CPU
=> batteryClient: Fix PeriodicThread using 100% CPU

doc/release/yarp_3_3/fix_batteryWrapper.md, src/devices/batteryWrapper/BatteryWrapper.cpp
* Fixed parameters accepted by subdevice not printed with --verbose.
=> batteryWrapper: Fix parameters accepted by subdevice not printed with --verbose

doc/release/master/clamp.md, src/libYARP_conf/src/yarp/conf/numeric.h.in
This is a small utility available in c++17, that could make lots of code a lot easier to read in many different places.
* Added `yarp::conf::clamp`. Will be replaced by `std::clamp` as soon as c++17
is required in YARP.
=> conf: Add yarp::conf::clamp

doc/release/master/fakeBatteryImprovements.md, src/devices/fakeBattery/CMakeLists.txt, src/devices/fakeBattery/fakeBattery.cpp, src/devices/fakeBattery/fakeBattery.h, src/devices/fakeBattery/fakeBatteryService.thrift
* Added a new port `<name>/control/rpc:i` to change the values reported by the
fake battery.
* The battery is now charged/discharged depending on the sign of the current.
=> fakeBattery: Add RPC port to change the values returned

doc/release/master/fakeBatteryImprovements2.md, src/devices/fakeBattery/CMakeLists.txt, src/devices/fakeBattery/FakeBatteryService.thrift, src/devices/fakeBattery/fakeBattery.cpp, src/devices/fakeBattery/fakeBattery.h
* Rename service and remove `setBatteryStatus`
* The default values for voltage and current are now more realistic.
* It is now possible to change the values as device options.
=> fakeBattery more improvements

doc/release/yarp_3_3/fix_dev_math_dependency.md, src/libYARP_dev/src/CMakeLists.txt
* Fixed dependency from `YARP_math` that should be `PUBLIC`. A few headers
include `YARP_math` headers.
=> dev: Fix dependency from YARP_math that should be PUBLIC

src/libYARP_dev/src/CMakeLists.txt
This fix the regression introduced in https://github.com/robotology/yarp/pull/2216, where `YARP::YARP_math` was made a public dependency of `YARP::YARP_dev`, but this was not propagated at the CMake level.
Fix https://github.com/robotology/yarp/issues/2217 .
fyi @drdanz
=> dev: Fix dependency from YARP_math that should be PUBLIC at CMake package level

cmake/YarpFindDependencies.cmake, doc/release/master/upowerBattery.md, src/devices/CMakeLists.txt, src/devices/upowerBattery/CMakeLists.txt, src/devices/upowerBattery/upowerBattery.cpp, src/devices/upowerBattery/upowerBattery.h
* New device `upowerBattery` to view the battery of a linux laptop in YARP using
the `yarp::dev::IBattery` interface.
=> Add upowerBattery device

CMakeLists.txt, doc/release/master/mas-wrap-subdevice.md, src/devices/multipleanalogsensorsserver/CMakeLists.txt, src/devices/multipleanalogsensorsserver/MultipleAnalogSensorsServer.cpp, src/devices/multipleanalogsensorsserver/MultipleAnalogSensorsServer.h, tests/libYARP_dev/MultipleAnalogSensorsInterfacesTest.cpp
Besides the `attachAll` mechanism (also referred to as "deferred attach" in some other places across YARP's codebase), this patch enables the `multipleanalogsensorsserver` device to wrap a subdevice on initial configuration, i.e. via `DeviceDriver::open`. This implementation mirrors https://github.com/robotology/yarp/pull/1018.
Closes https://github.com/robotology/yarp/issues/2154.
=> Allow MAS to wrap subdevice via open() method

doc/release/yarp_3_3/timerfix.md, src/libYARP_os/src/yarp/os/Timer.cpp
fixed two issues found by @barbalberto .
- timer in monothread mode taking 100% of the cpu
- timers in separate threads not updating their settings
waiting @barbalberto to test it
=> Timer fixes

doc/cmd_yarpdataplayer.dox, doc/release/master/featureYarpDataPlayer_ROS.md, src/yarpdataplayer/CMakeLists.txt, src/yarpdataplayer/include/utils.h, src/yarpdataplayer/include/worker.h, src/yarpdataplayer/src/utils.cpp, src/yarpdataplayer/src/worker-impl.cpp, src/yarpdataplayer/src/worker.cpp
`yarpdataplayer` is now able to reproduce several ROS types, i.e.
```
sensor_msgs/LaserScan.
nav_msgs/Odometry
tf/tfMessage
tf2_msgs/tfMessage
geometry_msgs/Pose
geometry_msgs/Pose2D
```
Other types can be easily added just editing `utils.cpp` and `worker.cpp`. Only a couple of lines of code for message is needed! 
See also the documentation provided in the comment below.
_NOTE: (and more!) = all data types generated by yarp Thrift IDL_
=> yarpdataplayer is now able to reproduce ROS data types (and more!)

doc/release/yarp_3_3/fix_fromString_int64.md, src/libYARP_os/src/yarp/os/impl/BottleImpl.cpp
* Fixed fromString when reading a 64 bit integer.
=> os: Fix reading 64 bits integer

doc/release/master/copyPortable_const.md, src/libYARP_os/src/yarp/os/Portable.cpp, src/libYARP_os/src/yarp/os/Portable.h
* The first argument of `copyPortable` is now `const`. The new signature is:
```
bool copyPortable(const PortWriter& writer, PortReader& reader)
```
=> os/Portable: Make copyPortable first argument const

doc/release/yarp_3_3/fix_fromString_inf_nan.md, doc/release/yarp_3_3/fix_fromString_int64.md, src/libYARP_os/src/yarp/os/impl/BottleImpl.cpp, src/libYARP_os/src/yarp/os/impl/Storable.cpp
* Fixed toString and fromString when writing or reading infinity or nan.
=> os: Fix infinity and nan writing and reading

doc/release/yarp_3_3/fix_fromString_neg_inf.md, src/libYARP_os/src/yarp/os/impl/BottleImpl.cpp, src/libYARP_os/src/yarp/os/impl/Storable.cpp
* Fixed toString and fromString when writing or reading negative infinity.
=> os: Fix negative infinity writing and reading

doc/release/yarp_3_3/fix_float_precision.md, src/libYARP_os/src/yarp/os/impl/Storable.cpp
DBL_DIG is not enough to ensure that the number can be read back, a
better option would be to use DBL_DECIMAL_DIG, but this is available
only in C++17, hence we use DECIMAL_DIG.
* Fixed precision for floating point numbers, to ensure that they are read as
the original floating point written.
=> os: Increase the precision of printed floating point numbers

doc/release/master/yarpdev_quit.md, src/libYARP_dev/src/yarp/dev/Drivers.cpp
* The terminator port now tries to use the default value for `--name` accepted
by the device.
For example `yarpdev --device test_grabber` will open the port `/grabber/quit`
instead of `/test_grabber/quit`.
----
:warning: This is a very small breaking change
At the moment when yarpdev is started without passing the `--name` parameter, the terminator port is opened as `/<device>/quit`
For example `yarpdev --device test_grabber` opens the following ports:
* `/grabber`
* `/grabber/rpc`
* `/test_grabber/quit`
If instead a `--name /foo` option is passed, it opens the following ports:
* `/foo`
* `/foo/rpc`
* `/foo/quit`
With this change, if the name was not passed, the name used by default is searched inside the options searched by the device. Therefore in the first case the ports opened are:
* …
=> yarpdev: Try to find a better name for terminator port

doc/release/yarp_3_3/fix_yarpview_save_menu_checks.md, src/yarpview/plugin/VideoSurface.qml, src/yarpview/plugin/YARPViewMenu.qml, src/yarpview/src/qml/QtYARPView/main.qml
Now the "checked" state of the two checkable elements in the File menu
of "yarpview" (i.e. "Save single image..." and "Save a set of
images...") turns to false when the corresponding dialogs are closed.
=> yarpview: Checkable menu issue fixed

doc/release/master/yarprun_env_vars.md, src/libYARP_run/src/yarp/run/Run.cpp
* The following enviromnent variables are now set in the child processes:
* `YARP_IS_YARPRUN` is set to `1` for all child processes
* `YARPRUN_IS_FORWARDING_LOG` is set to `1` when yarprun is forwarding the
log and to `0` otherwise
=> yarprun: Let child processes that they are handled by yarprun

doc/release/master/featureMapGrid2DOrigin.md, src/libYARP_dev/src/yarp/dev/MapGrid2D.cpp, src/libYARP_dev/src/yarp/dev/MapGrid2D.h, src/libYARP_dev/src/yarp/dev/MapGrid2DInfo.cpp, src/libYARP_dev/src/yarp/dev/MapGrid2DInfo.h
* The format of .map file loaded by `MapGrid2D` has been changed. It can now include the parameters `resolution <double>` and 
`orientation <bottle>` to adjust the map reference frame.
* `MapGrid2DOrigin` can now handle a generic orientation. Previously only the trasnslational part was handled by methods `world2Cell` and `cell2World`
=> Improvements to Yarp .map files

doc/release/master/nettype_enh.md, src/libYARP_os/src/yarp/os/NetType.cpp, src/libYARP_os/src/yarp/os/NetType.h, src/libYARP_os/src/yarp/os/impl/Storable.cpp
* The following methods were added:
* `static std::string toString(yarp::conf::float32_t)`
* `static std::string toString(yarp::conf::float64_t)`
* `static yarp::conf::float32_t toFloat32(const std::string&)`
* `static yarp::conf::float64_t toFloat64(const std::string&)`
* `static yarp::conf::float32_t toFloat32(std::string&&)`
* `static yarp::conf::float64_t toFloat64(std::string&&)`
* `static std::string toHexString(long)`
* `static std::string toHexString(unsigned int)`
=> Add a few methods to yarp::os::NetType

doc/release/master/gethostname_string.md, src/libYARP_os/src/yarp/os/Os.cpp, src/libYARP_os/src/yarp/os/Os.h
* Add `gethostname()` overload to return a `std::string`
=> os: Add gethostname overload to return a std::string

doc/release/master/LogForwarder_path.md, src/libYARP_os/src/yarp/os/impl/LogForwarder.cpp, src/libYARP_run/src/yarp/run/Run.cpp
* The name of the port used to forward the output no longer contains the full
path, but only the executable name.
* The name of the port used to forward the output no longer contains the full
path, but only the executable name.
=> Remove executable path from port name from LogForwarder and yarprun

doc/release/master/feature_companion_qos_command.md, src/libYARP_companion/src/CMakeLists.txt, src/libYARP_companion/src/yarp/companion/impl/Companion.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.h, src/libYARP_companion/src/yarp/companion/impl/Companion.qos.cpp
* Two new commands have been added to the `yarp companion` related to the QOS of a given connection
* `priority-qos` That allows to set/get the packet priority value of both the<br/>source and the destination port
* `priority-sched` That allows to set/get the thread priority and policy values of both the<br/>source and the destination port
=> yarp companion: QOS related commands added

doc/release/master/log_refactor_Port.md, src/carriers/tcpros_carrier/RosSlave.h, src/libYARP_os/src/yarp/os/Port.cpp, src/libYARP_os/src/yarp/os/Port.h
* The methods `setVerbosity` and `getVerbosity` are deprecated in favour of Log Components.
=> os/Port: Port to the new logging system

doc/release/master/log_refactor_Network.md, src/libYARP_os/src/yarp/os/Network.cpp, src/libYARP_os/src/yarp/os/Network.h, src/libYARP_robottestingframework/src/yarp/robottestingframework/TestCase.cpp, src/robottestingframework-plugins/fixture-managers/yarpmanager/YarpFixManager.cpp, src/yarpmanager-console/yarpmanager.cpp, src/yarpmanager/src-manager/main.cpp, tests/devices/harness_devices.cpp, tests/harness.cpp
* The `setVerbosity` method is now deprecated in favor of Log Components.
=> os/Network: Port to the new logging system

doc/release/master/log_remove_trace.md, src/libYARP_os/src/yarp/os/Log.h, src/libYARP_os/src/yarp/os/LogComponent.h
* Trace should no longer generate code when building in release mode. When building with `-DYARP_NO_DEBUG_OUTPUT` debug should not generate any code as well. See https://godbolt.org/z/hSAC56
=> os/Log: Make trace generated code disappear when building in release mode

doc/release/master/log_refactor_Protocol.md, src/libYARP_os/src/yarp/os/ConnectionState.h, src/libYARP_os/src/yarp/os/impl/Protocol.cpp, src/libYARP_os/src/yarp/os/impl/Protocol.h
* The methods `getLog()` method was removed.
Depends on #2266
=> os/{ConnectionState,impl/Protocol}: Port to the new logging system

doc/release/master/log_refactor_YarpPlugin.md, src/carriers/portmonitor_carrier/dll/MonitorSharedLib.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cpp, src/libYARP_dev/src/yarp/dev/Drivers.cpp, src/libYARP_os/src/yarp/os/RFPlugin.cpp, src/libYARP_os/src/yarp/os/YarpPlugin.cpp, src/libYARP_os/src/yarp/os/YarpPluginSettings.h
* The method `setVerboseMode()` is now deprecated in favour of Log Components.
=> os/YarpPlugin: Port to the new logging system

doc/release/master/laserDevicesRefactored.md, src/devices/fakeLaser/fakeLaser.cpp, src/devices/fakeLaser/fakeLaser.h, src/devices/laserFromDepth/laserFromDepth.cpp, src/devices/laserFromDepth/laserFromDepth.h, src/devices/laserFromExternalPort/laserFromExternalPort.cpp, src/devices/laserFromExternalPort/laserFromExternalPort.h, src/devices/laserFromPointCloud/laserFromPointCloud.cpp, src/devices/laserFromPointCloud/laserFromPointCloud.h, src/libYARP_dev/src/yarp/dev/Lidar2DDeviceBase.cpp, src/libYARP_dev/src/yarp/dev/Lidar2DDeviceBase.h, src/yarplaserscannergui/main.cpp
- This PR  should be merged after https://github.com/robotology/yarp/pull/2199
* the following lidar devices in Yarp are now derived from Lidar2DDeviceTemplate. Marked items have been tested.
=> Lidar devices from template

src/libYARP_os/src/yarp/os/Log.cpp, src/libYARP_serversql/src/yarp/serversql/impl/LogComponent.cpp, src/libYARP_serversql/src/yarp/serversql/impl/LogComponent.h
In this PR, I fix a bug regarding the call of forward/print callback: the default component was created using the default-forward/default-print callback instead of the user defined one; in this way, the user callbacks were not invoked.
I fix this bug, creati g the default component with the user callbacks if they are defined.
To test this patch I defined a forward user callback in embobjMotionControl
```
static void testForwarderLog(yarp::os::Log::LogType t,
const char* msg,
const char* file,
const unsigned int line,
const char* func,
double systemtime,
double networktime,
const char* comp_name)
{
std::string type = "type:unknown" ;
switch(t)
{
case yarp::os::Log::LogType::TraceType: type = "type:Trace" ;
break;
case yarp::os::Log::LogType::DebugType: type = "type:Debug" ;
break;
case …
```
=> Fix bug of use forward/print callback user defined 

doc/release/master/feature_yarpview_color_picker.md, src/yarpview/plugin/VideoSurface.qml, src/yarpview/plugin/YARPViewMenu.qml, src/yarpview/plugin/YARPViewStatusBar.qml, src/yarpview/plugin/qtyarpview.cpp, src/yarpview/plugin/qtyarpview.h, src/yarpview/plugin/videoproducer.cpp, src/yarpview/plugin/videoproducer.h, src/yarpview/src/qml/QtYARPView/main.qml
* Added a checkable menu item that, if checked, shows an additional line in the `status bar` that display the color value of the pixel pointed by the mouse cursor.
The string has the following format 
```
Pixel("x","y") = "hexstring"
```
Where  `x` and `y` are the coordinates of the pixel and `hexstring` is the hexadecimal (in the ARGB format) string representing the pixel color
The additional line on the `status bar` contains also a little rectangle that will turn the same color of the currently selected pixel.
=> yarpview: Pixel rgb value in status bar

doc/release/master/companion_env.md, src/libYARP_companion/src/CMakeLists.txt, src/libYARP_companion/src/yarp/companion/impl/Companion.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.env.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.h
* Added new `env` subcommand to print one or the full list of environment variables.
This is could be useful, for example, for debugging the values of the environment variables for programs executed remotely using yarprun.
Depends on #2273
=> companion: Add yarp env command

doc/release/master/log_limiter.md, src/libYARP_os/src/yarp/os/Log.cpp, src/libYARP_os/src/yarp/os/Log.h, src/libYARP_os/src/yarp/os/LogComponent.h, src/libYARP_os/src/yarp/os/LogStream.h, tests/libYARP_os/CMakeLists.txt, tests/libYARP_os/LogStreamTest.cpp, tests/libYARP_os/LogTest.cpp
* Added the following new debug macros:
* `yDebugOnce`
* `yDebugThreadOnce`
* `yDebugThrottle`
* `yDebugThreadThrottle`
* Added the following new debug macros:
* `yCDebugOnce`
* `yCDebugThreadOnce`
* `yCDebugThrottle`
* `yCDebugThreadThrottle`
=> os/Log: Add limited debug methods

src/libYARP_robotinterface/src/yarp/robotinterface/Device.cpp, src/libYARP_robotinterface/src/yarp/robotinterface/XMLReader.h, src/libYARP_robotinterface/src/yarp/robotinterface/XMLReaderV1.cpp, src/libYARP_robotinterface/src/yarp/robotinterface/XMLReaderV3.cpp, src/libYARP_robotinterface/src/yarp/robotinterface/XMLReaderVx.cpp, src/libYARP_robotinterface/src/yarp/robotinterface/impl/XMLReaderFileVx.h, src/yarprobotinterface/Module.cpp, tests/libYARP_robotinterface/RobotinterfaceTest.cpp
This PR completes what was originally added in https://github.com/robotology/yarp/pull/2168, and finish the implementation of Part 1 of https://github.com/robotology/yarp/issues/2005 . 
In particular, the main difference w.r.t.  https://github.com/robotology/yarp/pull/2168 is that in that case, the API exposed was extremely complicated to use: as soon as there was an error in the input XML file, the whole process that called the `YARP_robotinterface` library was crashed. Clearly, this is not ideal for a library, and this PR modifies the library to ensure that the error is correctly propagated to the caller. Furthermore, to test this functionality this PR also restructure the parser to permit to load the XML configuration also from directly a string, and not from a file.
The public API …
=> Modify libYARP_robotinterface to enable proper error propagation

doc/release/master/fix_qos_invalid_dscp.md, src/libYARP_os/src/yarp/os/impl/PortCore.cpp, src/libYARP_os/src/yarp/os/impl/SocketTwoWayStream.cpp
Also improve debugging by adding a few debug messages
=> os/PortCore: Do not set TOS to 0 if DSCP is an unknown string

doc/release/master/fix_bug_MASRemapper.md, src/devices/multipleanalogsensorsremapper/MultipleAnalogSensorsRemapper.cpp
Notice: Sorry for spamming everyone. I pushed the rebased branch before changing the base, causing to add every other code-owners as reviewers.
The for loop in `parseOptions()` method was iterating in a way that it ignored to parse the options for PositionSensors interface.
This consequently resulted in an uninitialized buffer, causing segfaults while trying to attach PositionSensorInterfaces.
This PR updates the `MAS_NrOfSensorTypes` variable from 9 to 10 and modifies the static_assert condition that checks the consistency error between `MAS_NrOfSensorTypes` and `MAS_SensorType`.
=> Fix bug by updating MAS_NrOfSensorTypes in multipleanalogsensorsremapper to be inclusive of PositionSensors

doc/release/master/fakeBatteryImprovements3.md, src/devices/fakeBattery/FakeBatteryService.thrift, src/devices/fakeBattery/fakeBattery.cpp, src/devices/fakeBattery/fakeBattery.h, src/devices/fakeBattery/idl_generated_code/FakeBatteryService.cpp, src/devices/fakeBattery/idl_generated_code/FakeBatteryService.h
At the moment, the only way to get these info is through the server, which "speaks" a protocol that is very hard to use without the client.
This PR adds methods to the rpc interface to get these information
* Added new methods to the RPC port to get current values.
---
Also
* Do not use magic numbers
* Remove unused options (`[GENERAL]` group and `debug`)
* Port to the new logging system
=> Fake battery improvements

doc/release/yarp_3_3/fix_remoteCB_getInteractionModesGroup.md, src/devices/RemoteControlBoard/RemoteControlBoard.cpp
Typo fix. Prior to this, `getInteractionModes` was looking for control modes instead.
=> Fetch actual getInteractionModes data from stream

doc/release/yarp_3_3/fix_controlBoard_setGearboxRatio.md, src/devices/ControlBoardWrapper/RPCMessagesParser.cpp, src/devices/RemoteControlBoard/RemoteControlBoard.cpp, src/devices/RemoteControlBoard/RemoteControlBoard.h
This patch exposes [`yarp::dev::IMotor::setGearboxRatio`](http://www.yarp.it/classyarp_1_1dev_1_1IMotor.html#aacb74f2baff8e03481adb515edfe8d3e) from wrapped devices, previously was missing.
=> Add IMotor::setGearboxRatio in control board client-server pair

bindings/yarp.i, doc/release/master/bindings_addMissing.md
A bunch of methods pertaining to joint control interfaces, namely [motor interfaces](http://www.yarp.it/group__dev__iface__motor.html), needed to be properly extended in *yarp.i* for use in scripting languages. Most notably, every method that contains a pointer argument requires a simple workaround for translation into Python, Java, etc. This patch adds support for several previously omitted methods from already wrapped interfaces (with partial or even no prior support), and also exposes `IEncodersTimed` and `IMotor`.
Closes https://github.com/robotology/yarp/issues/1966.
=> Expose several missing methods from motor interfaces in language bindings

src/libYARP_dev/src/yarp/dev/ControlBoardHelper.h
Fixes a few -Wclass-memaccess warnings
=> dev/ControlBoardHelper: Do not clear memory for non-trivial types

doc/release/yarp_3_3/fix_bug_checkNearToLocation.md, src/devices/navigation2DClient/Navigation2DClient.cpp, tests/libYARP_dev/Navigation2DClientTest.cpp
The method `checkNearToLocation()` now correctly checks if two orientations are similar (below a certain threshold), also considering the critical points 0,180,360,-180,-360 etc.
=> fix_bug_checkNearToLocation

doc/release/master/addYarpRobotinterfaceLibrary.md, src/libYARP_robotinterface/src/yarp/robotinterface/Device.cpp, src/libYARP_robotinterface/src/yarp/robotinterface/Device.h, src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp, src/libYARP_robotinterface/src/yarp/robotinterface/Robot.h, tests/libYARP_robotinterface/RobotinterfaceTest.cpp
This feature can be used to instantiated a set of devices via the libYARP_robotinterface (for example a group of network wrappers), but making them attach to some devices that already exists and have been created independently from the libYARP_robotinterface.
An example of the use of such feature can  be found in the `"Check valid robot file with one device attaching to an external device"` section of the `RobotInterface` test, an abridged version is available in the following: 
~~~cxx
// Create a device externally
yarp::os::Property p;
p.put("device", "robotinterface_test_mock_device");
yarp::dev::PolyDriver physicalDevice;
physicalDevice.open(p);
// Add the device to the PolyDriverList with the appropriate name, 
// the name will then be used to refer to the device as part of "action" …
=> libYARP_robotinterface: Add a method to specify an external device list to be used as a target for actions of internal devices

doc/release/master/log_customTime.md, doc/yarp_logging.md, src/carriers/tcpros_carrier/yarpros.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cpp, src/libYARP_os/src/yarp/os/Log.cpp, src/libYARP_os/src/yarp/os/Log.h, src/libYARP_os/src/yarp/os/LogComponent.h, src/libYARP_os/src/yarp/os/LogStream.h, src/libYARP_os/src/yarp/os/impl/LogComponent.cpp, src/libYARP_os/src/yarp/os/impl/LogComponent.h, src/libYARP_serversql/src/yarp/serversql/impl/LogComponent.cpp, src/libYARP_serversql/src/yarp/serversql/impl/LogComponent.h, tests/libYARP_os/LogStreamTest.cpp, tests/libYARP_os/LogTest.cpp
In this pull request, we introduce a "customTime" term to the logger.
This will be used to include timestamps from "external" sources, e.g.: control boards.
We include also y*CustomTime functions (e.g.: yDebugCustomTime) that will be used to send these external timestamps to the logger.
=> Add custom time

doc/release/master/unix_socket.md, src/carriers/CMakeLists.txt, src/carriers/unix/CMakeLists.txt, src/carriers/unix/UnixSockTwoWayStream.cpp, src/carriers/unix/UnixSockTwoWayStream.h, src/carriers/unix/UnixSocketCarrier.cpp, src/carriers/unix/UnixSocketCarrier.h, src/carriers/unix/UnixSocketLogComponent.cpp, src/carriers/unix/UnixSocketLogComponent.h
* Added the new `unix_stream` and `unix_stream_ack` carriers to communicate with
a process on the same machine using a unix socket.
---
This PR includes the `unix_stream` and `unix_stream_ack` carriers, formerly developed separately, in YARP.
These carrier have been tested on Linux and on Windows using WSL, have proven to be very reliable and fast, and they were able to transfer up to 4K video (3840x2160) at 30fps (28.7fps the version with ack). Therefore we believe that, even if the release is very close, they deserve to be included in the next release, since this is a great improvement when transferring large data between processes on the same machine.
If you had the version developed externally installed, please remove it before installing this.
---
Credits and thanks to @Nicogene for …
=> Add unix_stream and unix_stream_ack carriers

doc/release/master/fix_Image_synchronize_function.md, src/libYARP_sig/src/yarp/sig/Image.cpp
* Fixed the `yarp::sig::Image::synchronize` method that missed the pixel type and the orientation settings needed to properly use the `move assignment operator`
* A `getTypeId` method has been added to `yarp::sig::ImageStore` to be able to read the <i>protected</i> value `type_id`
=> YARP sig: Fix yarp::sig::Image::synchronize method

src/carriers/unix/CMakeLists.txt, src/carriers/unix/UnixSocketCarrier.cpp, src/carriers/unix/UnixSocketCarrier.h
Instead of having a separate carrier for the ack version, it is a parameter of the carrier
Therefore, instead of using
```diff
-yarp connect /a /b unix_stream_ack
```
The ack version can be requested as
```diff
+yarp connect /a /b unix_stream+ack
```
This is what I understood:
Basically, the initiator side parses the "sender specifier" (`unix_stream+ack`) in the `configure` method (and for some reason, also the `configureFromProperty` seems to be involved in some way). If the `ack` option is found, `requireAckFlag` is set to true, and the carrier starts sending data using `UNIX_ACK` instead of `UNIX_STR`, and waiting for the ack after each data transmission.
On the recipients side, the `.ini` file is involved, the `code "UNIX_" (any) (any) (any)` should be matched in order to satisfy the …
=> carrier/unix_stream: Merge unix_stream and unix_stream_ack

doc/release/yarp_3_4/fix_realsense2Tracking_timestamp.md, src/devices/realsense2/realsense2Tracking.cpp, src/devices/realsense2/realsense2Tracking.h
Fixed missing timestamp for device `realsense2tracking`
added option `--timestamp yarp` : yarp timestamp will be used
added option `--timestamp realsense` : realsense timestamp will be used
default value is yarp timestamp.
=> Fixed realsense2tracking device timestamp

bindings/ruby/CMakeLists.txt, doc/release/yarp_3_4/cmake_3_18_ruby.md
Fixes Ruby bindings on CMake 3.18
=> bindings/ruby: Do not use deprecated CMake variables

doc/release/yarp_3_4/fix_typo_texture_buffer.md, src/devices/ovrheadset/TextureBuffer.cpp
When trying to compile on Windows with Visual Studio 16 2019 I had the following error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2059	syntax error: '<<' [C:\robotology-superbuild\build\robotology\YARP\src\devices\ovrheadset\yarp_ovrheadset.vcxproj]	YARP (ExternalProjectTargets\YARP\YARP)	C:\robotology-superbuild\robotology\YARP\src\devices\ovrheadset\TextureBuffer.cpp	260	
```
=> Fix typo on TextureBuffer.cpp

doc/release/master/frameTransform_displayTree.md, src/devices/transformServer/FrameTransformServer.cpp, src/devices/transformServer/FrameTransformServer.h, src/libYARP_math/src/yarp/math/FrameTransform.cpp, src/libYARP_math/src/yarp/math/FrameTransform.h
frameTransformServer: added a new rpc command 'generate_view' which generates via dot (graphviz) a `frames.pdf` file, containing a diagram of the transforms tree.
You can use a pdf viewer, i.e. `evince frames.pdf` to display the transforms tree and obtain a plot such as:
=> frameTransformServer: display transform tree 

doc/release/yarp_3_4/fix_FakeFrameGrabber.md, src/devices/fakeFrameGrabber/FakeFrameGrabber.cpp
The ball test is now displayed in the center of the image instead of the right-bottom corner. The bug was affecting windows only. The bug was introduced by a recent refactor in which some variables were modified from int to size_t
=> FakeFrameGrabber fix

doc/release/yarp_3_4/fix_yarpdatadumper_opencv2.md, src/yarpdatadumper/main.cpp
Per https://github.com/robotology/yarp/pull/2194#issuecomment-691230360:
> This change is not compatible with OpenCV 2.4.9.1 (latest `apt` package on Ubuntu 16.04). There is no `cv::VideoWriter::fourcc` function in OpenCV 2.x ([ref](https://docs.opencv.org/ref/2.4/dd/d9e/classcv_1_1VideoWriter.html), cf. [OpenCV 3.x](https://docs.opencv.org/3.4/dd/d9e/classcv_1_1VideoWriter.html)).
>
> ```
> /home/teo/repos/yarp/src/yarpdatadumper/main.cpp: In member function ‘virtual void DumpThread::run()’:
> /home/teo/repos/yarp/src/yarpdatadumper/main.cpp:489:69: error: ‘fourcc’ is not a member of ‘cv::VideoWriter’
>                  videoWriter.open(videoFile.c_str(),cv::VideoWriter::fourcc('H','F','Y','U'),
>                                                                      ^~~~~~
> ```
> (...) …
=> Fix compilation against OpenCV 2.x in yarpdatadumper

cmake/YarpFindDependencies.cmake, doc/cmd_yarpdatadumper.dox, doc/release/master/Zlib_depth.md, src/libYARP_sig/src/CMakeLists.txt, src/libYARP_sig/src/yarp/sig/ImageFile.cpp, src/libYARP_sig/src/yarp/sig/ImageFile.h, src/yarpdatadumper/main.cpp, src/yarpdataplayer/src/mainwindow.cpp, src/yarpdataplayer/src/utils.cpp, src/yarpdataplayer/src/worker.cpp
The purpose of this PR is to introduce a new data format to read/write **compressed** depth images on disk
* added optional **zlib dependency** to compress data
* added enum::image_fileformat::FORMAT_NUMERIC_COMPRESSED
* yarpdatadumper now is able to save depth and **depth_compressed** data types. Use --help to see the new options.
* yarpdatadumper documentation updated
* yarpdataplayer is now able to reproduce depth and **depth_compressed** data types
=> Zlib depth

doc/release/yarp_3_4/fix_1959.md, src/libYARP_sig/src/yarp/sig/PointCloudUtils-inl.h, tests/libYARP_sig/PointCloudTest.cpp
* Fixed `yarp::sig::utils::depthRgbToPC` for types without alpha channel (#1959).
=> sig/PointCloudUtils: Use SFINAE to avoid failure for types without alpha channel

doc/release/yarp_3_4/fix_stamp_max_count.md, src/libYARP_os/src/yarp/os/Stamp.cpp
It adds the usage of `std::numeric_limits` in `getMaxCount()`
=> Fix stamp max count

doc/release/yarp_3_4/fix_yarpmanager_tabs.md, src/yarpmanager/src-manager/mainwindow.cpp
This PR fixes the issue that disables side menubar buttons when changing tab.
It fixes #2355
=> Fix yarpmanager tabs/buttons issue

doc/release/master/RGBDSensorClient_refactor.md, src/devices/RGBDSensorClient/RGBDSensorClient.cpp, src/devices/RGBDSensorClient/RGBDSensorClient.h, src/devices/RGBDSensorClient/RGBDSensorClient_StreamingMsgParser.cpp, src/devices/RGBDSensorClient/RGBDSensorClient_StreamingMsgParser.h
* The device no longer crashes when no image was received yet (#2349).
* The timestamp is now correct.
----
Fixes #2349
=> Small refactor of the RGBDSensorClient device

doc/release/yarp_3_4/fix_check_network_local_with_timeout.md, src/libYARP_os/src/yarp/os/NameSpace.cpp
`NameSpace::checkNetwork(timeout)` was actually checking if a `yarpserver`  is running even if `NetworkBase::setLocalMode(true)` was caled, differently from `NameSpace::checkNetwork()` . This PR fixes  `NameSpace::checkNetwork(timeout)` so that it behaves like `NameSpace::checkNetwork()`  .
=> Fix NameSpace::checkNetwork(timeout) when NetworkBase::setLocalMode(true) is called

doc/release/yarp_3_4/log_component_color.md, src/libYARP_os/src/yarp/os/Log.cpp
This isn't actually a bugfix, but it is a tiny enhancement that helps **a lot** while debugging, therefore, unless someone is against this, I'd like to merge it in the stable branch.
(With `YARP_COMPACT_OUTPUT`):
=> os/Log: Print colored components when colors are enabled

doc/yarp_logging.md
Most importantly, a typo regarding the `yDebug` vs. `yCDebug` distinction is fixed. Also, I clarify which header stream macros actually need to work. A few more trivial typos and style fixes follow.
=> Fix typos and improve style in yarp_logging.md

src/libYARP_dev/src/yarp/dev/GazeControl.h
Actually, `od` stands for desired orientation (as per the Cartesian Control convention for example), whereas here we deal with feedback rather than setpoints, hence `o` is a better replacement.
I don't believe this tiny change is worth an entry point in the `doc/release` as signatures per se remain unchanged.
=> Minor fix of some names in GazeControl signatures

doc/release/master/feature_yarpview_right_click.md, src/yarpview/plugin/VideoSurface.qml, src/yarpview/plugin/YARPViewMenu.qml, src/yarpview/plugin/qtyarpview.cpp, src/yarpview/plugin/qtyarpview.h, src/yarpview/src/qml/QtYARPView/main.qml
* Added the possibility to intercept the mouse right button click event.
* As for the mouse left button click event, there are two possibilities:
* Single click (sends the current cursor coordinates to the specified output port)
* Press, drag, and release (sends the coordinates of the `press` point and of the `release` one to the specified output port)
* To enable this feature the user has to specify a name for the output port that will send the cursor coordinates to the YARP network using the `--rightout` option with the desired output port name, e.g.
```
yarpview --rightout /outRight
```
* If the ouput port has been specified, menu bar, under the voice `Image`, will have a new checkable menu item, i.e. `Intercept right click` (checked by default) that will allow the user to …
=> yarpview-feature: Added mouse button right click interception

src/devices/portaudio/CMakeLists.txt, src/devices/portaudioPlayer/CMakeLists.txt, src/devices/portaudioRecorder/CMakeLists.txt
The `FindPortAudio` CMake module from YCM ( https://github.com/robotology/ycm/blob/master/find-modules/FindPortAudio.cmake ) uses the `PortAudio_INCLUDE_DIRS` variable to contain the include directories, while YARP CMake was using `PortAudio_INCLUDE_DIR` that was empty. 
Related issue: https://github.com/robotology/yarp/issues/2117 .
=> devices: Fix include directories variable for PortAudio

doc/release/yarp_3_4/fix_ffmpeg_getAudio.md, src/devices/ffmpeg/FfmpegGrabber.cpp
* Corrected a minor error in `FfmpegGrabber.cpp` that caused a segmentation fault when using a video with audio track as a `source` for the device
* **N.B.** The device can now be used and do not crash but the actual audio grabbing has not been tested yet.
=> Fix ffmpeg get audio

doc/release/yarp_3_4/yarpbatterygui_fixes.md, src/yarpbatterygui/display.cpp, src/yarpbatterygui/display.ui, src/yarpbatterygui/main.cpp
* The window can no longer be resized.
* The window background can no longer be moved around.
* The window no longer stays on top automatically. A new `--keep-above` switch
is provided to restore this behavior.
Fixes #2207
=> yarpbatterygui fixes

doc/release/yarp_3_4/controlboardwrapper2_timeMutex.md, src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp
Fix access to the timestamp not protected by mutex (#2396).
---------------------------
Instead of repeatedly accessing the `time` variable, I saved it in while protected by the mutex, and used the same timestamp for the whole `run` function.
Fixes #2396
=> devices/controlboardwrapper2: Fix access to time not protected by mutex

doc/release/master/DummyConnector_reply_writer.md, src/libYARP_os/src/yarp/os/DummyConnector.cpp, src/libYARP_os/src/yarp/os/DummyConnector.h
* The `getReader` methods now accepts a `ConnectionWriter` as optional parameter. This writer is returned by `getWriter` is called on the `ConnectionReader` returned by the writer, and it is therefore used for the replies in `Portable`s and in a few other cases.
At the moment replies are written on the same writer that is used for writing the input for the `DummyConnector` this makes it impossible to receive a reply.
This is the first of a series of patch that will allow portmonitors to inspect RPC connections.
It's very similar to a bugfix, but unfortunately it requires some changes in the API, therefore it is on `master`
=> os/DummyConnector: Add optional replyWriter parameter

src/libYARP_os/src/yarp/os/Contactable.h, src/libYARP_os/src/yarp/os/impl/PortCore.cpp, src/libYARP_os/src/yarp/os/impl/PortCore.h
Replaced by a mutex + a condition_variable + a few atomic variables.
The semaphore was used both for synchronization and for protecting critical sections. It is now clear where the threads are syncronizing, and where the mutex is protecting some data from concurrent access.
(note: better select "Hide whitespace changes" while reviewing the patch)
=> os/impl/PortCore: Refactor state semaphore

bindings/yarp.i, doc/release/master/swig_vector_int.md
As per title this PR add supports for `yarp::sig::VectorOf<int>` in `bindings/yarp.i`.
Fixes #2411
=> Add support for yarp::sig::VectorOf<int> in bindings/yarp.i

doc/release/yarp_3_4/fix_pcl_toString.md, src/libYARP_sig/src/yarp/sig/PointCloudTypes.h
For instance, `printf("%c", red);` outputs the corresponding ASCII character. We should get numeric values instead.
=> Print RGBA values as ints in PointCloud data types

doc/release/yarp_3_4/fix_depthToPC_ROI.md, src/libYARP_sig/src/yarp/sig/PointCloudUtils.cpp, tests/libYARP_sig/PointCloudTest.cpp
Max and min values of both ROI and decimation steps are now clipped within reasonable limits.
=> Fix ROI clipping in yarp::sig::utils::depthToPC()

src/libYARP_sig/src/yarp/sig/PointCloudUtils.cpp
https://github.com/robotology/yarp/pull/2425 added the use of std::max and std::min, but adding as include cmath instead of algorithm . Without this change, I am experiencing compilation errors on Windows.
=> Fix wrong include in PointCloudUtils.cpp

doc/release/master/portmonitor_fix_reply_handler.md, src/carriers/portmonitor_carrier/PortMonitor.cpp
* The reply handler is now set correctly, it is therefore now possible to
monitor RPC connections.
----
This should be a bugfix, but it depends on #2385 therefore it cannot be fixed in the stable branch
=> carriers/portmonitor: Set the reply handler correctly

doc/release/yarp_3_4/fix_yarpviz_gridOnExport.md, extern/qgv/qgv/QGVCore/QGVScene.cpp, extern/qgv/qgv/QGVCore/QGVScene.h, src/yarpviz/src/MainWindow.cpp, src/yarpviz/src/MainWindow.h, src/yarpviz/src/MainWindow.ui
fix_yarpviz_gridOnExport {#yarp_3_4}
-------------------
* Since, due to how the `QGVScene::drawBackground` function has been reimplemented, everytime a scene is exported as an image from `yarpviz` a white grid is added on top of the background, whether the user likes it or not, I added to `QGVScene` a new **bool** property named `gridNeeded` in order to change this behavior. If the property is *true*, the grid will be drawn as it is now. Otherwise the grid won't be added to the resulting image.
* The initial value of the property can be passed to the class constructor as a parameter (the default value of this parameter is *true* for backward compatibility sake) and then it can be modified by using `QGVScen::enableBgGrid` and checked via `QGVScene::bgGridEnabled`.
* In `yarpviz`menu a new …
=> Fix yarpviz grid on export

doc/release/master/yarp_repeat.md, src/libYARP_companion/src/CMakeLists.txt, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdRepeat.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.h
Added new yarp companion command `yarp repeat`.
**Usage example:**
The picture below shows two machines connected through a wireless network. This network topology is **BAD** because each module uses its own connection, streaming data over the wireless twice.
Instead you can use the **yarp repeat** on the receiver side:
```
yarp repeat /repeater
yarp connect /grabber /repeater
yarp connect /repeater /port1 unix_stream
yarp connect /repeater /port2 unix_stream
```
In this way only one connection is used over the wifi. The two receiver modules run on the same machine, so they can use a `unix_stream` connection to efficiently receive data from the `/repeater` port.
=> yarp repeat

doc/release/master/yarp_trafficGen.md, src/libYARP_companion/src/CMakeLists.txt, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdTrafficGen.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.h
The companion tool `yarp trafficgen` sends generated data over a yarp port. The tool allows to test the communication and the available bandwidth over the network.
E.g.
```
yarp trafficgen /port --bandwidth [Mb/s]
yarp trafficgen /port --bandwidth [Mb/s] --duration [s]
yarp trafficgen /port --period [s] --size [MB]
yarp trafficgen /port --period [s] --size [MB] --duration [s]
```
=> Yarp trafficgen

doc/release/master/yarp_stats.md, src/libYARP_companion/src/CMakeLists.txt, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdStats.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.h
Added command `yarp stats` to yarp companion.
Example:
```
yarpdev --device test_grabber &
yarp stats /grabber --duration 5
```
will provide statistics on the data published on the port `/grabber`.
```
55.3104 Mb/s, 30 btl/s, 0.0333333 mean period (s)
55.3104 Mb/s, 30 btl/s, 0.0333333 mean period (s)
55.3104 Mb/s, 30 btl/s, 0.0333333 mean period (s)
55.3104 Mb/s, 30 btl/s, 0.0333333 mean period (s)
55.3104 Mb/s, 30 btl/s, 0.0333333 mean period (s)
34.569 total MB received,  150 total bottles received, 0.0333333 mean period (s)
```
=> Yarp stats

doc/release/yarp_3_4/fix_yarpviz_text.md, src/yarpviz/src/MainWindow.cpp
* To solve the unaesthetic text crop for subgraphs, nodes and connections labels, the `MainWindow::drawGraph` function now adds a number of white spaces proportional to the text length at the beginning and the end of labels texts. With this simple adjustments labels are now fully readable regardless of their length.
* Unfortunately, connections arrows labels, if too long can be partially hidden by the destination port ellipse. To correct this, a modification of the `YARP_priv_qgvcore` will probably be required.
=> Fix yarpviz unwanted labels text crop

doc/release/yarp_3_4/fix_deprecate-old-networks-format.md, src/devices/ControlBoardWrapper/ControlBoardWrapper.h
This PR addresses the proposal detailed in https://github.com/robotology/robots-configuration/issues/222#issuecomment-744507821 for the official deprecation of the "old" format of the keyword `networks`.
Configuration files have been updated consistently in https://github.com/robotology/robots-configuration/pull/227, thus `yCError` can be adopted gracefully.
cc @traversaro @S-Dafarra
=> Deprecate old networks format

cmake/YarpFindDependencies.cmake, doc/release/yarp_3_4/fix_interface_lib_deps.md, src/libYARP_cv/CMakeLists.txt, src/libYARP_cv/src/CMakeLists.txt, src/libYARP_pcl/CMakeLists.txt, src/libYARP_pcl/src/CMakeLists.txt
* Dependencies for the `INTERFACE` libraries (YARP_cv and YARP_pcl)
are now properly set (#2438).
* PCL is now required to build the YARP_pcl library.
* OpenCV is now required to build the YARP_cv library.
Fixes #2438
=> Properly set dependencies for the  libraries

src/devices/RGBDSensorWrapper/rgbdSensor_nws_ros.h
Since this is now a ROS-only device, it does not make sense to prefix all parameters with `ROS_`
=> devices/rgbdSensor_nws_ros: Remove "ROS_" from all parameters

doc/release/yarp_3_4/robotinterface_attach.md, src/libYARP_robotinterface/src/yarp/robotinterface/experimental/Device.cpp
* Fixed handling of `attach` action for `IWrapper` devices.
=> Fix handling of attach action for IWrapper devices

doc/release/yarp_3_4/cbw_fix_getTorque_twice.md, src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp
* `getTorque` is no longer called twice.
---
See:
https://github.com/robotology/yarp/blob/b9da15361d4d8c18fc1fd8eb1cc5a1fcfe3899ef/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp#L891
and
https://github.com/robotology/yarp/blob/b9da15361d4d8c18fc1fd8eb1cc5a1fcfe3899ef/src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp#L924-L925
=> devices/ControlBoardWrapper: Do not get torque data twice

doc/release/yarp_3_4/fix_virtualanalogwrapper_parser.md, src/devices/VirtualAnalogWrapper/VirtualAnalogWrapper.cpp
Following up on #2446, this PR upgrades the parsing of conf files for the `virtualAnalogWrapper` device in order to make it behave as `ControlBoardWrapper`.
Essentially, the use of parentheses is enforced and the old way is now deprecated although still accepted.
This PR fixes the problem spotted in https://github.com/robotology/robots-configuration/issues/233.
cc @xEnVrE
=> [virtualanalogwrapper] fixed parsing

doc/release/yarp_3_4/yarpmotorgui_fix_dark_mode.md, src/yarpmotorgui/jointitem.cpp, src/yarpmotorgui/jointitem.ui, src/yarpmotorgui/mainwindow.cpp, src/yarpmotorgui/piddlg.ui, src/yarpmotorgui/sequencewindow.ui
* Fixed colors on dark mode desktop (#2466).
---
I'd appreciate if someone with a light theme could give me some feedback.
Fixes #2466
=> yarpmotorgui: Fix colors on dark mode desktop

src/libYARP_sig/src/yarp/sig/Vector.h
Default ones are just fine (rule of zero)
CC: @Nicogene
CC-Issue: #2432
=> sig/VectorOf: Do not explicitly implement copy/move ctors and assignment operators

doc/release/master/robotinterface_attach_single_device.md, src/libYARP_robotinterface/src/yarp/robotinterface/experimental/Robot.cpp
* It is now possible to pass the `device` parameter to the `attach` action,
without defining `network` or `networks`. For example:
```.xml
<device name="foo_name" type="foo_type">
<action phase="startup" level="5" type="attach">
<param name="device"> bar_name </param>
</action>
<action phase="shutdown" level="5" type="detach" />
</device>
```
=> robotinterface: Allow to pass the "device" parameter without defining networks

doc/release/master/thrift_enhancement.md, src/idls/thrift/src/t_yarp_generator.cc, src/libYARP_os/src/yarp/os/idl/WireReader.cpp, tests/CMakeLists.txt, tests/yarpidl_rosmsg/CMakeLists.txt, tests/yarpidl_rosmsg/demo/CMakeLists.txt, tests/yarpidl_thrift/CMakeLists.txt, tests/yarpidl_thrift/demo/CMakeLists.txt, tests/yarpidl_thrift/demo/main.cpp
* Vocabs are now accepted in readI32
* Types annotated with "yarp.type" are no longer serialized as nested.
This improves the compatibility with existing services returning Bottle
or other YARP types, and makes it possible to write a thrift file for
existing protocols.
On the other hand, this breaks compatibility with thrift services
returning Bottles or other annotated types, generated before this
commit. This is a breaking change, but should impact only a very
limited number of cases, and it can be easily fixed by regenerating the
files.
* Added support for vocabs in structs (#2476).
Vocabs can be defined in this way:
```cpp
typedef i32 ( yarp.type = "yarp::conf::vocab32_t" ) vocab
struct FooStruct
{
1: vocab foo;
}
```
* Added "yarp.nested" annotation for struct fields
When defined = …
=> Thrift enhancements

doc/release/master/yarp-read_trim.md, src/libYARP_companion/src/yarp/companion/impl/BottleReader.h, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdRead.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.h
* The `read` subcommand now accepts the `trim` argument to reduce the number of
characters printed for each message received.
=> yarp-read: Add `trim` argument to reduce the number of characters printed

doc/release/yarp_3_4/fakeFrameGrabber_fixes.md, src/devices/fakeFrameGrabber/FakeFrameGrabber.cpp, src/devices/fakeFrameGrabber/FakeFrameGrabber.h
* The `rand` mode was fixed.
* The timestamp is now correct.
* The image is no longer initialized when all the pixels are overwritten.
=> fakeFrameGrabber fixes

.github/workflows/ci.yml, data/yarpmanager/tests/xml/modules/fakeFrameGrabber.xml, doc/device_invocation/fakeFrameGrabber_basic.dox, doc/release/master/fakeFrameGrabber_enh.md, src/devices/fakeFrameGrabber/FakeFrameGrabber.cpp, src/devices/fakeFrameGrabber/FakeFrameGrabber.h
* Added `--timestamp` option to write the timestamp in the first bytes of the
image. This was previously automatically enabled in `line` mode, but it can
now be used in all modes.
* Add `nois` (noise) mode. This can be used alone to generate a white noise,
image, or while passing `--src` to add some noise to the image.
The `--snr` option can be pass to specify the signal noise ratio (default 0.5).
* Double buffering is now used to produce the image on a separate thread. This
should improve performances when generating large images.
Depends on #2504
=> fakeFrameGrabber enhancements

doc/release/yarp_3_4/detect_clock_reset.md, src/libYARP_os/src/yarp/os/NetworkClock.cpp
This PR implements the suggestions of @traversaro (see https://github.com/robotology/yarp/issues/800#issuecomment-775112896) to handle the time reset. 
This fix should avoid the phenomena of threads stopping and resuming after the time at which the clock was previously reset has passed.
=> NetworkClock: unblock all waiting threads if a network reset is detected

doc/release/master/os_Header.md, src/libYARP_os/src/CMakeLists.txt, src/libYARP_os/src/yarp/os/Header.cpp, src/libYARP_os/src/yarp/os/Header.h, src/libYARP_os/src/yarp/os/Stamp.cpp, tests/libYARP_os/CMakeLists.txt, tests/libYARP_os/HeaderTest.cpp
* Introduced the `yarp::os::Header` class, intended to gradually replace the `yarp::os::Stamp` class to handle envelopes, maintaining backwards compatibility.
The differences with the `Stamp` class:
* `Header` has an extra field to handle the frame id, making it comparable with ROS [`std_msgs/Header`](http://docs.ros.org/en/api/std_msgs/html/msg/Header.html) message.
* The counter uses unsigned int instead of int.
* `Stamp::getMaxCount()` is replaced with `Header::npos`
* `Stamp::getCount()` is replaced with `Header::count()`
* `Stamp::getTime()` is replaced with `Header::timeStamp()`
=> os: Add Header class, intended to gradually replace the Stamp class

doc/release/master/mp3Sound_portmonitor.md, src/carriers/CMakeLists.txt, src/carriers/mp3Sound_portmonitor/CMakeLists.txt, src/carriers/mp3Sound_portmonitor/Mp3Sound.cpp, src/carriers/mp3Sound_portmonitor/Mp3Sound.h
Added new portmonitor `mp3Sound` to decompress a mp3 bytestream to `yarp::sig::Sound`
=> mp3Sound portmonitor

bindings/python/CMakeLists.txt, doc/release/yarp_3_4/fix_cmake_install_python.md
As mentioned in https://github.com/robotology/yarp/issues/2511#issuecomment-787429494 , the `CMAKE_INSTALL_PYTHON3DIR` variable was defined but never used. This PR does not change the default behaviour (as `CMAKE_INSTALL_PYTHON3DIR` default value is `${Python3_INSTDIR}`), but it permits users to specify the location where to install the Python bindings.
=> Fix installation path of Python bindings

bindings/python/CMakeLists.txt, doc/release/yarp_3_4/fix_python_bindings_windows.md
Without this fix, the compilation of Python bindings is failing with error:
~~~
2021-03-22T08:34:49.9037393Z   -- Found Python3: C:/Miniconda/envs/test/python.exe (found version "3.9.2") found components: Interpreter Development Development.Module Development.Embed 
2021-03-22T08:34:49.9045986Z   CMake Error at bindings/python/CMakeLists.txt:17 (get_filename_component):
2021-03-22T08:34:49.9047185Z     get_filename_component called with incorrect number of arguments
2021-03-22T08:34:49.9047925Z   
2021-03-22T08:34:49.9079080Z   -- Configuring incomplete, errors occurred!
~~~
The reason is that for the modern `FindPython3` CMake module `Python3_LIBRARY` is not an output, so the code does not work. However, the whole logic seems not to be necessary anymore with modern CMake and modern …
=> Fix compilation of Python Bindings on Windows

.ci/initial-cache.gh.linux.cmake, cmake/FindFFMPEG.cmake, cmake/YarpFindDependencies.cmake, src/carriers/libffmpeg_portmonitor/CMakeLists.txt, src/carriers/mp3Sound_portmonitor/CMakeLists.txt, src/devices/ffmpeg/CMakeLists.txt, src/libYARP_sig/src/CMakeLists.txt, tests/misc/check_license_skip.txt
Import the latest FindFFMPEG.cmake from VTK, and use the targets from
this module.
WARNING: This file should be imported in YCM, but it requires a bit of
caution, since it breaks the calls to `find_package(FFMPEG)` without
`COMPONENTS`.
Fixes #2529
=> Fix issues with FFMPEG libraries

doc/release/yarp_3_4/fix_race_condition_scan_plugin.md, src/libYARP_os/src/yarp/os/YarpPlugin.cpp
added a static mutex in order to avoid multiple concurrent accesses to singleton instance (ResourceFinder::getResourceFinderSingleton())
=> fixed bug in YarpPluginSelector::scan()

src/libYARP_conf/src/yarp/conf/numeric.h.in
This is a follow-up to https://github.com/robotology/yarp/pull/2506. Affects downstream projects, not YARP itself: apparently, there is a `Bool` defined somewhere in `<X11/Xlib.h>` that leads to a name clash within `<yarp/conf/numeric.h>`. [Failed build logs](https://github.com/roboticslab-uc3m/yarp-devices/runs/2266991160?check_suite_focus=true#step:20:265):
```
[ 67%] Building CXX object libraries/YarpPlugins/SpaceNavigator/CMakeFiles/SpaceNavigator.dir/SpaceNavigator.cpp.o
In file included from /usr/include/spnav.h:33:0,
from /home/runner/work/yarp-devices/yarp-devices/libraries/YarpPlugins/SpaceNavigator/SpaceNavigator.hpp:6,
from /home/runner/work/yarp-devices/yarp-devices/libraries/YarpPlugins/SpaceNavigator/SpaceNavigator.cpp:3:
/usr/local/include/yarp/conf/numeric.h:126:20: error: …
```
=> Avoid potential name clashes in template params (numeric.h)

doc/release/master/fix_periodic_thread_drift.md, src/libYARP_os/src/yarp/os/PeriodicThread.cpp, src/libYARP_os/src/yarp/os/PeriodicThread.h, tests/libYARP_os/PeriodicThreadTest.cpp
Fixes https://github.com/robotology/yarp/issues/2488. Instead of a relative value obtained from the time elapsed on each step, which was prone to cause error accumulation over time, now I am using an absolute initial reference that helps getting the exact delay to prevent just that. This reference needs to be reset whenever the period is changed. In short, the new computed delay boils down to:
```cxx
delay = absolute_reference + period * iterations_since_absolute_reference - now;
```
In addition, I have added new checks to PeriodicThreadTest, which I'm not sure why weren't there, for testing the timer accuracy.
Please review. I have tested this on the code snippet attached in https://github.com/robotology/yarp/issues/2488 (using a system clock), and also on a similar example app with …
=> Avoid cumulative drift in PeriodicThread

src/libYARP_math/src/yarp/math/FrameTransform.cpp, src/libYARP_math/src/yarp/math/FrameTransform.h
Added serialization methods to `yarp/math/FrameTransform.cpp`
**NB: This is a temporary solution required to allow the development of other software.**
In the future the `yarp::math::FrameTransform` class will be revised and its derivation from `yarp::os::Portable` will be removed. The robotology team **discourages** the use of class `yarp::os::Portable` in libraries such as dev, math, etc.
=> FrameTransform is now Portable

doc/release/yarp_3_4/fix_yarplogger_clear.md, src/yarplogger/logmodel.cpp
Now yarplogger does not crash anymore when attempting to clear a
selected log with its log tab opened
=> fix_yarplogger_clear

doc/release/master/add_cropRect.md, src/devices/ServerFrameGrabberDual/ServerFrameGrabberDual.cpp, src/libYARP_sig/src/yarp/sig/ImageUtils.cpp, src/libYARP_sig/src/yarp/sig/ImageUtils.h, tests/libYARP_sig/ImageTest.cpp
`ServerGrabber` (a.k.a. `grabberDual`) features rectangular image cropping ([ref](https://github.com/robotology/yarp/blob/dca3a0cb57664042537bfcd7ff3f54ee6ad1bf9c/src/devices/ServerFrameGrabberDual/ServerFrameGrabberDual.cpp#L576-L589)). This patch proposes a refactorization and public exposure via a helper method in the `yarp::sig::utils` namespace, further extending it to any underlying pixel type (as long as input-output types match).
Proposed signature:
```cxx
bool yarp::sig::utils::cropRect(const yarp::sig::Image& inImg,
const std::pair<unsigned int, unsigned int>& vertex1,
const std::pair<unsigned int, unsigned int>& vertex2,
yarp::sig::Image& outImg)
```
If this addition is deemed useful, please double-check the logic behind the now-deleted `u_offset` variable in the NWS responder. …
=> Add `yarp::sig::utils::cropRect()`, adopt in grabberDual

bindings/yarp.i, doc/release/conf_dirs.md, doc/resource_finder_spec.dox, doc/yarp_env_variables.md, doc/yarp_plugins.dox, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdWrite.cpp, src/libYARP_conf/src/yarp/conf/dirs.h, src/libYARP_os/src/yarp/os/ResourceFinder.cpp, src/libYARP_os/src/yarp/os/ResourceFinder.h, src/libYARP_os/src/yarp/os/impl/NameConfig.cpp, src/yarp-config/yarpcontextutils.cpp, src/yarp-config/yarpcontextutils.h, tests/libYARP_conf/CMakeLists.txt, tests/libYARP_conf/dirs.cpp, tests/libYARP_os/ResourceFinderTest.cpp
Following #2506, this patch moves another bunch of functionalities from `yarp::os` (`ResourceFinder`) to `yarp::conf`, and adds several new utilities.
Again, this also implies deprecating a few utilities in `yarp::os`, in order to avoid having the same functionalities in different places.
----------
Deprecation and Behaviour Changes
---------------------------------
* A few default values for the environment variables used by yarp are now
different:
* Linux:
* `YARP_CONFIG_DIRS` defaults to `/etc/xdg/yarp` to be compliant with the
[XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
* Windows:
* `YARP_DATA_DIRS` defaults to `%%ALLUSERSPROFILE%%\yarp`
* `YARP_CONFIG_DIRS` defaults to `%%ALLUSERSPROFILE%%\yarp\config`
New Features …
=> Move directories specifications in yarp::conf

doc/release/master/yarpdataplayer_fix.md, src/libYARP_dataplayer/src/yarp/dataplayer/YarpDataplayer.cpp
This PR fixes [2558](https://github.com/robotology/yarp/issues/2558), by interpreting correctly the timestamp propagated, dealing with locale issues.
=> [YarpDataplayer] fixed timestamp propagation

bindings/matlab/vectors_fromTo_matlab.i
The [`mexErrMsgIdAndTxt`](https://www.mathworks.com/help/matlab/apiref/mexerrmsgidandtxt.html) MATLAB C API function requires the first argument to be an errorID. The format for the errorID is given in https://www.mathworks.com/help/matlab/ref/mexception.html : 
> The error identifier includes one or more component fields and a mnemonic field. Fields must be separated with colon. For example, an error identifier with a component field component and a mnemonic field mnemonic is specified as 'component:mnemonic'.
The fields should be separated by a column, but in YARP they were separated by two colons. This probably was working fine with old MATLAB version, but in recent MATLAB versions it generated an error, see https://github.com/robotology/yarp-matlab-bindings/issues/62 . 
I did not …
=> MATLAB: Fix errorID format in mexErrMsgIdAndTxt

bindings/yarp.i, doc/release/master/FrameGrabberInterfacesRefactor4.md, src/devices/DevicePipe/DevicePipe.cpp, src/devices/ServerFrameGrabberDual/ServerFrameGrabberDual.cpp, src/devices/ServerFrameGrabberDual/ServerFrameGrabberDual.h, src/devices/fakeFrameGrabber/FakeFrameGrabber.h, src/devices/ffmpeg/FfmpegGrabber.h, src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/yarp/dev/AudioVisualInterfaces.h, src/libYARP_dev/src/yarp/dev/FrameGrabberControl2.h, src/libYARP_dev/src/yarp/dev/FrameGrabberInterfaces.h, src/libYARP_dev/src/yarp/dev/IFrameGrabberImage.h, src/libYARP_dev/src/yarp/dev/IFrameGrabberImageRaw.h, src/libYARP_dev/src/yarp/dev/all.h
* Properly mark the `yarp/dev/FrameGrabberControl2.h` header file as deprecated
(it should have been deprecated in YARP 3.0)
* The `yarp/dev/FrameGrabberInterfaces.h` header file was deprecated.
All interfaces were moved in the corresponding header.
Depends on #2569 and #2570
=> Deprecate the yarp/dev/FrameGrabberControl2.h and yarp/dev/FrameGrabberInterfaces.h files

doc/release/master/FrameGrabberInterfacesRefactor5.md, doc/yarp_code_examples.dox, example/dev/CMakeLists.txt, example/dev/grabber_crop/CMakeLists.txt, example/dev/grabber_crop/grabber_crop.cpp, src/libYARP_dev/src/yarp/dev/IFrameGrabberImage.cpp, src/libYARP_dev/src/yarp/dev/IFrameGrabberImage.h, src/libYARP_dev/src/yarp/dev/IFrameGrabberImageRaw.cpp, src/libYARP_dev/src/yarp/dev/IFrameGrabberImageRaw.h, tests/libYARP_dev/fakeFrameGrabberTest.cpp
* The `getImageCrop` method has now a working default implementation.
* The `getImageCrop` method has now a working default implementation.
Depends on #2571
=> dev/IFrameGrabberImage,IFrameGrabberImageRaw: Implement getImageCrop

src/devices/audioToFileDevice/audioToFileDevice.cpp, src/devices/fakeSpeaker/fakeSpeaker.cpp, src/devices/portaudioPlayer/PortAudioPlayerDeviceDriver.cpp, src/libYARP_dev/src/yarp/dev/AudioPlayerDeviceBase.cpp, src/libYARP_dev/src/yarp/dev/AudioPlayerDeviceBase.h
now using recursive_mutex to avoid deadlocks when a device re-initialization is required
=> fix for AudioPlayerDevices

bindings/yarp.i, doc/release/master/FrameGrabberInterfacesRefactor6.md, src/devices/usbCamera/common/USBcamera.cpp, src/devices/usbCamera/common/USBcamera.h, src/devices/usbCamera/linux/V4L_camera.cpp, src/devices/usbCamera/linux/V4L_camera.h, src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/yarp/dev/FrameGrabberInterfaces.h, src/libYARP_dev/src/yarp/dev/IFrameGrabber.cpp, src/libYARP_dev/src/yarp/dev/IFrameGrabber.h, src/libYARP_dev/src/yarp/dev/IFrameGrabberRgb.cpp, src/libYARP_dev/src/yarp/dev/IFrameGrabberRgb.h, src/libYARP_dev/src/yarp/dev/all.h
As discussed in #2576 and #1868, the `yarp::dev::IFrameGrabber` and `yarp::dev::IFrameGrabberRgb` interfaces are not used by anyone and are missing some very important information about the image, which makes the useless.
=> Deprecate yarp::dev::IFrameGrabber and yarp::dev::IFrameGrabberRgb interfaces

doc/release/master/IWrapper_helpers.md, src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/yarp/dev/WrapperMultiple.cpp, src/libYARP_dev/src/yarp/dev/WrapperMultiple.h, src/libYARP_dev/src/yarp/dev/WrapperSingle.cpp, src/libYARP_dev/src/yarp/dev/WrapperSingle.h
* Added the new `WrapperSingle` and `WrapperMultiple` helper classes, that inherit from both `IWrapper` and `IMultipleWrapper` but require to implement only one of these interfaces.
CC-Discussion #2489
=> dev: Add WrapperSingle and WrapperMultiple helpers

doc/release/yarp_3_4/yarpros_YARP_COMPILE_EXECUTABLES.md, src/carriers/tcpros_carrier/CMakeLists.txt
* The `yarpros` tool is no longer compiled when `YARP_COMPILE_EXECUTABLES` is
disabled
=> Do not compile yarpros when YARP_COMPILE_EXECUTABLES is disabled

doc/release/master/localization2D_nws.md, src/devices/localization2DServer/CMakeLists.txt, src/devices/localization2DServer/localization2D_nws_ros.cpp, src/devices/localization2DServer/localization2D_nws_ros.h, src/devices/localization2DServer/localization2D_nws_yarp.cpp, src/devices/localization2DServer/localization2D_nws_yarp.h
In this PR the following new devices have been implemented:
* `localization2D_nws_yarp`
* `localization2D_nws_ros`
These devices replace the old all-in-one device `localization2DServer`, in order to provide grater flexibility and decouple the logic from the wrapper(s)
=> localization2D_nws

src/libYARP_dev/src/yarp/dev/ControlBoardInterfacesImpl.h
The `ControlBoardInterfacesImpl.h` should include the `ImplementPositionControl.h` and `ImplementVelocityControl.h` headers that define the `yarp::dev::ImplementPositionControl`  and `yarp::dev::ImplementVelocityControl`, but those were removed in https://github.com/robotology/yarp/pull/2596 .  This PR restores them. 
Fix part of https://github.com/robotology/robotology-superbuild/issues/794 .
=> Add missing includes to ControlBoardInterfacesImpl.h file

doc/release/master/fix_topIsLow.md, src/devices/ServerFrameGrabberDual/ServerFrameGrabberDual.cpp, src/libYARP_sig/src/yarp/sig/Image.cpp, src/libYARP_sig/src/yarp/sig/Image.h, src/libYARP_sig/src/yarp/sig/ImageNetworkHeader.h, src/yarpview/plugin/ImagePort.cpp
This patch introduces a few fixes in the `topIsLow` flag handling in `yarp::sig::Image`.
This flag represent the scanline direction (top to bottom if true, bottom to top if false) of the image.
This is, in our use case, normally top to bottom, but there are a very limited number of exceptions (for example the [ovrheadset device](https://github.com/robotology/yarp-device-ovrheadset/blob/b310d7c8588ed0c74d2d167ea41c7d804d10aa18/src/devices/ovrheadset/OVRHeadset.cpp#L1134-L1136) is able to handle both cases), and there are a few cases when it is useful to have the origin in the bottom left corner (for example when working with opengl)
At the moment, whenever an image is sent through the network, it is copied to a top-left-origin image, therefore flipping any bottom-left-origin image, and …
=> sig/Image: Fix topIsLow handling

doc/release/yarp_3_4/fix_topIsLow_yarp-3.4.md, src/libYARP_sig/src/yarp/sig/Image.cpp, src/libYARP_sig/src/yarp/sig/ImageNetworkHeader.h, src/yarpview/plugin/ImagePort.cpp
As explained in #2609 and #2587, this patch restores compatibility in the protocol, when an image with `topIsLow==false` is sent by YARP 3.5.
---
* Fixed compatibility with images with topIsLow==false sent by YARP 3.5.
* Fixed upside down image when topIsLow is false (Qt >= 5.3.2 only).
=> sig/Image: Fix topIsLow handling in YARP 3.4

doc/release/master/image_move_swap.md, src/libYARP_sig/src/yarp/sig/Image.cpp, src/libYARP_sig/src/yarp/sig/Image.h, tests/libYARP_sig/ImageTest.cpp
These 2 methods allow to swap or move 2 images of different type (like [`copy()`](https://yarp.it/git-master/classyarp_1_1sig_1_1Image.html#a7792cdf9c1192dabd7f8ad2332895897))
------
* Added `move()` and `swap()` methods.
=> sig/Image: Add move() and swap() methods

doc/release/master/thrift_const_method.md, src/libYARP_os/src/yarp/os/Wire.h, src/libYARP_os/src/yarp/os/WireLink.cpp, src/libYARP_os/src/yarp/os/WireLink.h, src/yarpidl_thrift/src/t_yarp_generator.cc, tests/yarpidl_thrift/demo/demo.thrift, tests/yarpidl_thrift/demo/main.cpp
* Added `yarp()` const overload
* The write method is now const. The signature is now:
```c++
bool write(const PortWriter& writer, PortReader& reader) const
```
* It is now possible to specify a "const" qualifier to service methods using the
`yarp.qualifier` annotation. For example, this code:
```
service Foo {
bool const_method() (yarp.qualifier = "const");
}
```
will generate a service `Foo` with this method:
```c++
bool const_method() const
```
---
Depends on #2615
=> Thrift const service method

src/devices/frameTransformClient/CMakeLists.txt, src/devices/frameTransformClient/frameTransformClient.cpp, src/devices/frameTransformClient/robotinterface_xml/ftc_full_ros.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_local_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_pub_ros.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_pub_yarp_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_ros.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_sub_ros.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_sub_yarp_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_yarp_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_yarp_only_single_client.xml
Added support for CMakeRC library in YARP. Tests with
frameTransformClient. Everything seems to work as expected.
=> CMakeRC integration first test

src/libYARP_dev/src/yarp/dev/DeviceDriver.cpp
YARP 3.4 backport of https://github.com/robotology/yarp/commit/d02db0521aae86537aa5ada8bc17ce661d2cb3e3 . 
Fix https://github.com/robotology/yarp/issues/2630 .
=> dev/DeviceResponder: Change debug line to trace

doc/release/master/deprecated_internal.md, src/libYARP_os/src/yarp/os/Bottle.h, src/libYARP_os/src/yarp/os/ConnectionReader.h, src/libYARP_os/src/yarp/os/ConnectionWriter.h, src/libYARP_os/src/yarp/os/Value.h
These methods have been deprecated internally since YARP 3.0, and their use has been discouraged since then.
These are quite used, and that's the reason why I was asked not to deprecate them at the time, but since these methods will disappear in YARP 4, I think it is is better to have them deprecated for some time, rather than having an error when migrating from YARP 3 to YARP 4.
CC @traversaro, @pattacini, @vtikha, @Nicogene 
---
* `BOTTLE_TAG_INT` is deprecated in favour of `BOTTLE_TAG_INT32`
* `BOTTLE_TAG_DOUBLE` is deprecated in favour of `BOTTLE_TAG_FLOAT64`
* `BOTTLE_TAG_VOCAB` is deprecated in favour of `BOTTLE_TAG_VOCAB32`
* `addInt` is deprecated in favour of `addInt32`
* `addDouble` is deprecated in favour of `addFloat64`
* `expectInt` is deprecated in favour of `expectInt32`
* …
=> Deprecate *Int and *Double methods in favour of *Int32 and *Float64

.github/workflows/python.yml
Small but relevant copy-paste mistake from #2573
=> Fix branch name in Python workflow

cmake/CMakeRC.cmake, src/devices/frameTransformClient/CMakeLists.txt, tests/misc/check_license_skip.txt
As discussed in #2637, linking the `STATIC` library will not work on `STATIC` builds unless it is installed, and the generated library is supposed to be used privately, and not installed.
The `CMakeRC` module was modified and imported in https://github.com/robotology/ycm/pull/383, but I'm importing it here as well, until YCM 0.13 is released (very soon)
CC @PeterBowman
=> frameTransformClient: Produce OBJECT library instead of STATIC

doc/release/master/deprecated_devices_warnings.md, src/devices/ControlBoardWrapper/ControlBoardWrapper.cpp, src/devices/RGBDSensorWrapper/RGBDSensorWrapper.cpp, src/devices/Rangefinder2DWrapper/Rangefinder2DWrapper.cpp, src/devices/ServerFrameGrabberDual/ServerFrameGrabberDual.cpp, src/devices/ServerInertial/ServerInertial.cpp, src/devices/fakeFrameGrabber/CMakeLists.txt, src/devices/fakeFrameGrabber/FakeFrameGrabber.cpp, src/devices/fakeFrameGrabber/FakeFrameGrabber.h, src/devices/fakeMotor/CMakeLists.txt, src/devices/fakebot/CMakeLists.txt, src/devices/fakebot/FakeBot.h, src/devices/localization2DServer/Localization2DServer.cpp, src/devices/map2DServer/Map2DServer.cpp, src/devices/transformClient/transformClient.cpp, src/devices/transformServer/transformServer.cpp, src/libYARP_dev/src/yarp/dev/DeviceDriver.h
* The following devices are now deprecated:
* `test_grabber`
* `fakeMotor`
* `test_motor`
* `fakebot`
* The following devices will be replaced by NWS/NWC in the next release, and
print a warning when opened:
* `controlboardwrapper2` (replaced by `controlboardremapper` + `controlBoard_nws_yarp`)
* `RGBDSensorWrapper` (replaced by `rgbdSensor_nws_yarp`)
* `Rangefinder2DWrapper` (replaced by `rangefinder2D_nws_yarp`)
* `grabberDual` (replaced by `frameGrabber_nws_yarp`, and eventually `frameGrabberCropper`)
* `inertial` (replaced by `multipleanalogsensorsremapper` + `multipleanalogsensorsserver` + `IMURosPublisher`)
* `localization2DServer` (replaced by `localization2D_nws_yarp`)
* `map2DServer` (replaced by `map2D_nws_yarp`)
* `transformClient` (replaced by `frameTransformClient`)
* …
=> Deprecated devices warnings

doc/dev_all.dox, src/devices/ControlBoardWrapper/ControlBoard_nws_ros.h, src/devices/ControlBoardWrapper/ControlBoard_nws_yarp.h, src/devices/RGBDSensorWrapper/RgbdSensor_nws_ros.h, src/devices/RGBDSensorWrapper/RgbdSensor_nws_yarp.h, src/devices/RGBDToPointCloudSensorWrapper/CMakeLists.txt, src/devices/RGBDToPointCloudSensorWrapper/RGBDToPointCloudSensor_nws_ros.h, src/devices/Rangefinder2DWrapper/Rangefinder2D_nws_ros.h, src/devices/Rangefinder2DWrapper/Rangefinder2D_nws_yarp.h, src/devices/RemoteFrameGrabber/FrameGrabber_nwc_yarp.h, src/devices/ServerFrameGrabberDual/FrameGrabber_nws_ros.h, src/devices/ServerFrameGrabberDual/FrameGrabber_nws_yarp.h, src/devices/frameTransformClient/FrameTransformClient.h, src/devices/frameTransformGet/FrameTransformGet_nwc_ros.h, src/devices/frameTransformGet/FrameTransformGet_nwc_yarp.h, src/devices/frameTransformGet/FrameTransformGet_nws_yarp.h, src/devices/frameTransformSet/FrameTransformSet_nwc_ros.h, src/devices/frameTransformSet/FrameTransformSet_nwc_yarp.h, src/devices/frameTransformSet/FrameTransformSet_nws_yarp.h, src/devices/frameTransformStorage/FrameTransformStorage.h, src/devices/frameTransformUtils/FrameTransformContainer.h, src/devices/localization2DServer/Localization2D_nws_ros.h, src/devices/localization2DServer/Localization2D_nws_yarp.h, src/devices/map2DServer/Map2D_nws_ros.h, src/devices/map2DServer/Map2D_nws_yarp.h
Four new sections in the doxygen library have been added for NWS and NWC (both YARP and ROS). Missing `\brief` sections have been added to the documentation of a set of yarp devices
=> Added brief tag and nws-nwc sections

doc/release/yarp_3_5/audioFromFile_fix.md, src/devices/audioFromFileDevice/audioFromFileDevice.cpp
fixed module audioFromFileDevice when channels are > 1
=> audioFromFileDevice bugfix

doc/release/yarp_3_5/audio_gain.md, src/libYARP_dev/src/yarp/dev/AudioPlayerDeviceBase.cpp, src/libYARP_dev/src/yarp/dev/AudioRecorderDeviceBase.cpp
fixed parsing of parameters `hw_gain` and `sw_gain` in the two classes `AudioPlayerDeviceBase` and `AudioRecorderDeviceBase`
=> Audio gain fix

cmake/FindSOXR.cmake, cmake/YarpFindDependencies.cmake, doc/release/master/soundFilters.md, src/libYARP_sig/src/CMakeLists.txt, src/libYARP_sig/src/yarp/sig/SoundFilters.cpp, src/libYARP_sig/src/yarp/sig/SoundFilters.h
* added new files `yarp::sig::SoundFilters.h`, `yarp::sig::SoundFilters.cpp`
* added new method `yarp::sig::soundfilters::resample()`
* requires libsoxr.  `cmake/FindSOXR.cmake` temporary added. The file will be removed when ycm 0.14 is released.
=> Sound filters

doc/nws_and_nwc_architecture.md
As the documentation will be used also in the future, and in the past in 2023 will have a different meaning then now.
=> Do not use "in the past" in docs

doc/release/yarp_3_5/ResourceFinder_fix.md, src/libYARP_os/src/yarp/os/ResourceFinder.cpp
This PR fixes #2676.
I've tested it successfully ✔️ 
I'm proposing this change back to yarp-3.4 to then easily port it forward as for Distro 2021.08 we would likely need to rely on a fixed `yarp-3.4.6`.
I've tried to fill in the mandatory fields for describing the fix by taking inspiration from supporting files done for other old mods.
Tell me if I'm required to do anything else.
=> Use `mkdir_p` instead of `mkdir` w/ `getHomeContextPath` and `getHomeRobotPath`

doc/release/yarp_3_5/refactor_frameTransformComponents.md, src/devices/frameTransformClient/FrameTransformClient.h, src/devices/frameTransformClient/robotinterface_xml/ftc_full_ros.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_pub_yarp_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_sub_yarp_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_yarp_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_yarp_only_single_client.xml, src/devices/frameTransformGet/FrameTransformGet_nwc_yarp.cpp, src/devices/frameTransformGet/FrameTransformGet_nwc_yarp.h, src/devices/frameTransformGet/FrameTransformGet_nws_yarp.cpp, src/devices/frameTransformGet/FrameTransformGet_nws_yarp.h, src/devices/frameTransformServer/FrameTransformServer.h, src/devices/frameTransformServer/robotinterface_xml/fts_full_ros.xml, src/devices/frameTransformServer/robotinterface_xml/fts_yarp_only.xml, src/devices/frameTransformSet/FrameTransformSet_nwc_yarp.cpp, src/devices/frameTransformSet/FrameTransformSet_nwc_yarp.h, src/devices/frameTransformSet/FrameTransformSet_nws_yarp.cpp, src/devices/frameTransformSet/FrameTransformSet_nws_yarp.h
The following components have been refactored in order to easily manage ports names and avoid errors in doing so:
* frameTransformSet_nwc_yarp
* frameTransformSet_nws_yarp
* frameTransformGet_nwc_yarp
* frameTransformSet_nws_yarp
The xml files containing the configurations for the `frameTransformClient` and the `frameTransformServer` have been updated
accordingly.
=> FrameTransform architecture components refactoring

doc/release/yarp_3_5/yarprun_env_fix.md, src/libYARP_run/src/yarp/run/Run.cpp
Fixed handling of multiple environment variables with yarprun on win32
=> yarprun fix

doc/release/yarp_3_5/fix_frameTransformStorage_start.md, src/devices/frameTransformStorage/FrameTransformStorage.cpp
* Fixed bug in `frameTransformStorage`. The device did not call its `start` method after successfully attaching to a `yarp::dev::IFrameTransformStorageGet` interface. Therefore the device was not able to update its `FrameTransformContainer` storage by querying the device it was attached to.
=> Fixed bug in frameTransformStorage

doc/release/master/yarp_log_label.md, doc/yarp_env_variables.md, doc/yarp_logging.md, src/libYARP_os/src/yarp/os/impl/LogForwarder.cpp, src/libYARP_run/src/yarp/run/Run.cpp
You can now use the new environment variable `YARP_LOG_PROCESS_LABEL` to set an extra label which helps in identifying the name of the process which is performing the log
=> Yarp log label

doc/release/master/Map2DArea_description.md, src/devices/map2DStorage/map2DStorage.cpp, src/devices/map2DStorage/map2DStorage.h, src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/idl/Map2DAreaData.thrift, src/libYARP_dev/src/idl/Map2DLocationData.thrift, src/libYARP_dev/src/idl/Map2DPathData.thrift, src/libYARP_dev/src/idl_generated_code/Map2DAreaData_index.txt, src/libYARP_dev/src/idl_generated_code/yarp/dev/Map2DAreaData.cpp, src/libYARP_dev/src/idl_generated_code/yarp/dev/Map2DAreaData.h, src/libYARP_dev/src/idl_generated_code/yarp/dev/Map2DLocationData.cpp, src/libYARP_dev/src/idl_generated_code/yarp/dev/Map2DLocationData.h, src/libYARP_dev/src/yarp/dev/Map2DArea.cpp, src/libYARP_dev/src/yarp/dev/Map2DArea.h, src/libYARP_dev/src/yarp/dev/Map2DLocation.h, src/libYARP_dev/src/yarp/dev/Map2DPath.cpp, src/libYARP_dev/src/yarp/dev/Map2DPath.h, tests/libYARP_dev/Navigation2DClientTest.cpp
* `Map2DArea` has been refactored: it now inherits from the thrift defined type Map2DAreaData.thrift
* `Map2DArea`, `Map2DLocation`, `Map2DPath` now include a `description` field which can be filled by the user for generic purposes
* The documentation of the thrift types: `Map2DAreaData`, `Map2DLocationData`, `Map2DPathData` has been updated.
* Updated `map2DStorage` device to support the new v3 file format, which includes the description for Locations, Areas and Paths. 
Example of file locations.ini:
```
Version:
3
Locations:
living_room testMap 2 0 0 test1
office testMap 0 0 0 test2
Areas:
area1 testMap 3 1 1 2 1 2 2 test3
area2 testMap 4 -1 -1 -2 -1 -2 -2 -3 -3 test4
Paths:
path1 (testMap 0 0 0) (testMap 1 1 1) test5
```
=> Map2dArea description

doc/release/yarp_3_5/fix_joint_states_topic.md, src/devices/ControlBoardWrapper/ControlBoard_nws_ros.cpp
* `/joint_states` is no longer appended to the topic name.
=> devices/controlBoard_nws_ros: Do not append /joint_states to the topic name

doc/release/yarp_3_5/fix_WireReader_readString.md, src/libYARP_os/src/yarp/os/idl/WireReader.cpp
* Fixed reading empty string as latest argument.
=> os/idl/WireReader: Fix reading an empty string as last argument

src/libYARP_os/src/yarp/os/Log.cpp, src/libYARP_os/src/yarp/os/impl/LogComponent.cpp, src/libYARP_os/src/yarp/os/impl/LogComponent.h
After 9a16a9a056469779f5c7ea9e00a13f7e000575e9 the custom print callback is no longer called when running under yarprun
=> Fix log under yarprun always verbose 

.github/workflows/python.yml, doc/release/yarp_3_5/yarp_math_in_wheel.md, scripts/pip/setup.py
Eigen was missing in the debian container used to build the PEP600 wheels, and `libYARP_math` automatically disabled by CMake. This PR adds the target to the process, hopefully fixing https://github.com/dic-iit/bipedal-locomotion-framework/pull/296#issuecomment-911429287.
=> Enable compilation of `libYARP_math` in the Python wheels

doc/release/master/bottle_compression_zlib.md, src/portmonitors/CMakeLists.txt, src/portmonitors/bottle_compression_zlib/BottleZlibPortmonitor.cpp, src/portmonitors/bottle_compression_zlib/BottleZlibPortmonitor.h, src/portmonitors/bottle_compression_zlib/CMakeLists.txt, src/portmonitors/bottle_compression_zlib/README.md, src/portmonitors/depthimage_compression_zlib/DepthImageZlibPortmonitor.cpp, src/portmonitors/depthimage_compression_zlib/DepthImageZlibPortmonitor.h
added new portmonitor `bottle_compression_zlib` to compress bottles (or other yarp data types which can be automatically casted to bottle)
=> new portmonitor bottle_compression_zilib

doc/release/master/testdata_filename.md, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdLatencyTest.cpp
Added option `testdata_filename` to latency-test companion.
It allows to load a file that will be transmitted over the network as a benchmark.
Different files can be used to test latency when using a compression portmonitor (the compression factor will depend on the entropy of the file )
=> added option `testdata_filename` to latency-test companion

doc/release/master/carrier_option.md, src/devices/RGBDSensorClient/RGBDSensorClient.cpp, src/devices/Rangefinder2DClient/Rangefinder2DClient.cpp, src/devices/Rangefinder2DClient/Rangefinder2DClient.h, src/devices/batteryClient/BatteryClient.cpp, src/devices/batteryClient/BatteryClient.h, src/devices/localization2DClient/Localization2DClient.cpp, src/devices/localization2DClient/Localization2DClient.h, src/devices/map2DClient/Map2DClient.cpp, src/devices/map2DClient/Map2DClient.h, src/devices/map2DClient/Map2D_nwc_yarp.cpp, src/devices/map2DClient/Map2D_nwc_yarp.h, src/devices/mobileBaseVelocityControl/MobileBaseVelocityControl_nwc_yarp.cpp, src/devices/mobileBaseVelocityControl/MobileBaseVelocityControl_nwc_yarp.h, src/devices/multipleanalogsensorsclient/MultipleAnalogSensorsClient.cpp, src/devices/multipleanalogsensorsclient/MultipleAnalogSensorsClient.h, src/devices/navigation2DClient/Navigation2DClient.cpp, src/devices/navigation2DClient/Navigation2DClient.h, src/yarplaserscannergui/main.cpp
* Most of the clients/nwcs now implement options to set the carrier for the connection with the server
Minor:
* yarplaserscannergui now implements the `carrier` option to control the connection type of the internal Rangefinder2DClient
=> New carrier option for yarp clients connections

cmake/YarpFindDependencies.cmake, doc/release/yarp_3_5/fix_ffmpeg.md, src/devices/ffmpeg/CMakeLists.txt, src/portmonitors/image_compression_ffmpeg/CMakeLists.txt
* Fixed symbol lookup runtime error.
* Fixed symbol lookup runtime error.
* Fixed symbol lookup runtime error.
=> Fix Fixed symbol lookup runtime error in plugins using FFMPEG

doc/release/master/fix_frameTransformSet_nwc_ros.md, src/devices/frameTransformClient/FrameTransformClient.cpp, src/devices/frameTransformClient/FrameTransformClient.h, src/devices/frameTransformServer/FrameTransformServer.cpp, src/devices/frameTransformServer/FrameTransformServer.h
* Added the option to use an extern xml file (by providing its absolute path) to configure the `frameTransformServer` and the `frameTransformClient` devices.
* **NB:** this function is intended for TEST ONLY
=> Feature: frameTransform custom config

doc/release/yarp_3_5/opencv_no_copy.md, src/devices/opencv/OpenCVGrabber.cpp, src/devices/opencv/OpenCVGrabber.h
Resolves #2161. In contrast to the suggested solution, I am converting a `yarp::sig::Image` to a `cv::Mat` so that final allocation occurs at the YARP caller side (doing it on a local `cv::Mat` would produce memory corruption as soon as the execution flow exits `getImage`) without using YARP_cv at all since color conversion must take place after the frame is grabbed. As a side note, I noticed in-place `cv::cvtColor` produces bogus results (frames flash between BGR and RGB representations), hence the auxiliary `bgr` variable.
Disclaimer: copying still happens whenever frame transposition or resizing is requested.
In addition, I have enabled `--flip_x`, `--flip_y` and `--transpose` for data streams originating from a file on disk (using `--movie`), which also helped me test these changes.
=> Avoid copies between `cv::Mat` and `yarp::sig::Image` in opencv_grabber

doc/release/master/streaming_MobileBaseVelocityControl_nws_yarp.md, src/devices/mobileBaseVelocityControl/CMakeLists.txt, src/devices/mobileBaseVelocityControl/MobileBaseVelocityControl_nws_ros.cpp, src/devices/mobileBaseVelocityControl/MobileBaseVelocityControl_nws_ros.h, src/devices/mobileBaseVelocityControl/MobileBaseVelocityControl_nws_yarp.cpp, src/devices/mobileBaseVelocityControl/MobileBaseVelocityControl_nws_yarp.h
* Added input streaming port as an alternative to rpc command `applyVelocityCommandRPC()`
* Added `subdevice` option.
* Added the possibility to view the device through the interface `yarp::dev::Nav2D::INavigation2DVelocityActions`
=> mobileBaseVelocityControl_nws_yarp/ros improvements

doc/release/yarp_3_5/fix_delete_transformClient.md, src/devices/transformClient/transformClient.cpp, tests/libYARP_dev/IFrameTransformTest.cpp, tests/libYARP_dev/TransformClientTest.cpp
* fixed method delete in `transformClient`, now avoiding race conditions during server/client update via streaming port
* improved harness_dev test (IFrameTransformTest.cpp) for `transformClient` device.
=> Fixed method delete() for transformClient device

doc/release/yarp_3_5/fix_frameTransformSet_nws_ros_timestamp_value.md, src/devices/frameTransformSet/FrameTransformSet_nwc_ros.cpp
* Fixed bug in `frameTransformSet_nws_ros::yarpTransformToROSTransform`. The time stamps of the static transforms were wrongly set to yarp::os::Time::now()
=> Fixed time stamp in static transforms

doc/release/yarp_3_5/fix_frameTransformClient_part2.md, src/devices/frameTransformClient/FrameTransformClient.cpp, src/devices/frameTransformGet/FrameTransformGetMultiplexer.h, src/devices/frameTransformSet/FrameTransformSetMultiplexer.cpp, src/devices/frameTransformSet/FrameTransformSetMultiplexer.h, src/devices/frameTransformStorage/FrameTransformStorage.cpp, src/devices/frameTransformStorage/FrameTransformStorage.h, src/devices/frameTransformUtils/FrameTransformContainer.cpp, src/devices/frameTransformUtils/FrameTransformContainer.h, src/devices/transformClient/transformClient.cpp, src/libYARP_dev/src/yarp/dev/IFrameTransformStorage.h, src/libYARP_math/src/yarp/math/FrameTransform.cpp, src/libYARP_math/src/yarp/math/FrameTransform.h, src/libYARP_math/src/yarp/math/Quaternion.cpp, src/libYARP_math/src/yarp/math/Quaternion.h, tests/libYARP_dev/FrameTransformClientTest.cpp
* timestamp is now set also for static_transforms
* fixed race condition issue in `deleteTransform()` method.
* fixed race condition issue: added extra mutex to protect the periodicThread from set/get/delete operations
* the periodic thread can be now stopped/started on request by
methods `IFrameTransformStorageUtils::stopStorageThread` and `IFrameTransformStorageUtils::startStorageThread`.
* added new iterator class. It iterates only on valid transforms.
* when a transform is deleted, it is marked as invalid. The transform is then removed
during the next iteration of the checkAndRemoveExpired()
* added methods `startStorageThread()` and `stopStorageThread()` to interface `yarp::dev::IFrameTransformStorageUtils`
* added method `yarp::math::Quaternion::isValid()`
* added method …
=> Fix for frameTransformClient part2

doc/release/yarp_3_5/fix_yarpmanager_white_spaces_and_colors_port_names.md, src/libYARP_manager/src/yarp/manager/manager.cpp, src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/applicationviewwidget.h
* Targeted issue: port names containing trailing or leading white spaces not targeted as `non-existing` but throwing an error
when trying to connect.
* Now `yarpmanager` shows an error message in its `Message` text box when a port name listed in the `Connection list` widget contains white spaces. For simplicity's sake the error is thrown for spaces in any position, not only leading or trailing
* This has been done by adding a check in the [Manager::existPortFrom](https://github.com/robotology/yarp/blob/2aeab6c8e4babe651febc2ea755a5409f4cfeda7/src/libYARP_manager/src/yarp/manager/manager.cpp#L731) and [Manager::existPortTo](https://github.com/robotology/yarp/blob/2aeab6c8e4babe651febc2ea755a5409f4cfeda7/src/libYARP_manager/src/yarp/manager/manager.cpp#L745) functions
* Also, fixed the …
=> Fix yarpmanager white spaces check in ports names and ports names color

doc/release/master/robotinterface_dryrun.md, src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp, src/libYARP_robotinterface/src/yarp/robotinterface/Robot.h, src/libYARP_robotinterface/src/yarp/robotinterface/impl/XMLReaderFileV1.h, src/libYARP_robotinterface/src/yarp/robotinterface/impl/XMLReaderFileV3.cpp, src/libYARP_robotinterface/src/yarp/robotinterface/impl/XMLReaderFileV3.h, src/libYARP_robotinterface/src/yarp/robotinterface/impl/XMLReaderFileVx.h, src/yarprobotinterface/Module.cpp, src/yarprobotinterface/tests/fakeFrameGrabber/fakeFrameGrabber.xml, src/yarprobotinterface/tests/fakeFrameGrabber/grabber.xml
* Added `--dryrun` option to test the xml file without actually opening devices.
* Added `reverse-shutdown-action-order` attribute for the `robot` tag.
This reverses the order of actions in shutdown and interrupt phase, making it
easier to write the actions when multiple attach and detach are involved.
* All `robot` tag parameters are now passed to all devices.
=> Robotinterface dryrun and reverse shutdown action order

doc/release/master/robotinterface_dryrun.md, src/libYARP_robotinterface/src/yarp/robotinterface/Robot.cpp, src/libYARP_robotinterface/src/yarp/robotinterface/impl/XMLReaderFileV3.cpp
Revert the changes in ed063f3f4325f32b0abb6b4f2be2694831aa2993 that was doing the same thing for the `robot` tag, since this was used in other places, and some tags should not have been passed to the devices.
=> robotinterface: Pass all parames inside a `devices` tag to all `device` inside that tag

bindings/python/CMakeLists.txt, doc/release/yarp_3_5/fix_python3_bionic
On Bionic with VTK 6.3, Python 2.7 headers are added to the search path by `find_package` and given more precedence than Python 3 headers as provided by FindPython3.
Fixes https://github.com/robotology/yarp/issues/2725.
=> Give Python3 headers more precedence over 3rd-party transitive deps

doc/release/master/logstream_containers.md, src/libYARP_os/src/yarp/os/LogStream.h, tests/libYARP_os/LogStreamTest.cpp
I have always found the ability to chain `std::vector` to LogStream a great shortcut. This patch expands it to most standard containers (specifically tested with `array`, `deque`, `forward_list`, `list`, `set`, `unordered_set`), including key-value associations via `std::pair` (hence it also supports `map` and `unordered_map`), as well as old C-style arrays and even `std::tuple`.
To illustrate this quickly, the following tuple:
```cxx
std::tuple<int, std::set<int>, std::vector<std::map<double, char>>> t;
t = {5, {7, 6}, {{{1.1, 'g'}, {5.5, 'f'}}, {{9.0, 'h'}}}};
```
is rendered by `yInfo() << t;` as `[INFO] {5, [6, 7], [[{1.1, g}, {5.5, f}], [{9, h}]]}`.
=> Chain most std containers, C-style arrays and tuples in LogStream

bindings/yarp.i, doc/release/master/yarpmotogui_hwfault.md, src/devices/ControlBoardRemapper/ControlBoardRemapper.cpp, src/devices/ControlBoardRemapper/ControlBoardRemapper.h, src/devices/ControlBoardRemapper/ControlBoardRemapperHelpers.cpp, src/devices/ControlBoardRemapper/ControlBoardRemapperHelpers.h, src/devices/ControlBoardWrapper/ControlBoard_nws_yarp.cpp, src/devices/ControlBoardWrapper/ControlBoard_nws_yarp.h, src/devices/ControlBoardWrapper/RPCMessagesParser.cpp, src/devices/ControlBoardWrapper/RPCMessagesParser.h, src/devices/RemoteControlBoard/RemoteControlBoard.cpp, src/devices/RemoteControlBoard/RemoteControlBoard.h, src/devices/fakeMotionControl/fakeMotionControl.cpp, src/devices/fakeMotionControl/fakeMotionControl.h, src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/yarp/dev/ControlBoardInterfaces.h, src/libYARP_dev/src/yarp/dev/IJointFault.h, src/libYARP_dev/src/yarp/dev/ImplementJointFault.cpp, src/libYARP_dev/src/yarp/dev/ImplementJointFault.h, src/yarpmotorgui/jointitem.cpp, src/yarpmotorgui/jointitem.h, src/yarpmotorgui/jointitem.ui, src/yarpmotorgui/partitem.cpp, src/yarpmotorgui/partitem.h
See discussion: https://github.com/robotology/community/discussions/561
* Modified yarpmotorgui to support a new page "Hardware Fault" which displays the internal hardware error
* Added new interface IJointFault with method: IJointFault::getLastJointFault(int j, int& fault, std::string& message)
* IJointFault is now implemented by RemoteControlBoard and ControlBoard_nws_yarp
* fakeMotionControl.cpp now simulates an hardware fault when it receives a TorqueCommand > 1Nm
=> Yarpmotorgui with displayed hardware faults messages 

src/devices/fakeBattery/FakeBatteryService.thrift, src/devices/fakeBattery/fakeBattery.cpp, src/devices/fakeBattery/fakeBattery.h, src/devices/fakeBattery/idl_generated_code/FakeBatteryService.cpp, src/devices/fakeBattery/idl_generated_code/FakeBatteryService.h
This is useful to test enum serialization in thrift
=> devices/fakeBattery: Add setBatteryStatus/getBatteryStatus/getBatteryStatusString rpc methods

src/yarpidl_thrift/src/t_yarp_generator.cc, tests/yarpidl_thrift/demo/demo.thrift, tests/yarpidl_thrift/demo/main.cpp
=> yarpidl_thrift: Fix malformed files when comments contain double quotes

tests/libYARP_os/LogStreamTest.cpp
Illegal cast caught by MSVC (error C4576). Follows up https://github.com/robotology/yarp/commit/0394d6967991bd25bde2a314110d949293fa387a.
=> Fix C-style array initialization in LogStreamTest

src/devices/Rangefinder2DClient/Rangefinder2DClient.cpp, src/devices/Rangefinder2DClient/Rangefinder2DClient.h, src/devices/Rangefinder2DWrapper/Rangefinder2D_nws_ros.cpp, src/devices/Rangefinder2DWrapper/Rangefinder2D_nws_yarp.cpp, src/devices/laserHokuyo/laserHokuyo.cpp, src/devices/laserHokuyo/laserHokuyo.h, src/devices/rpLidar/rpLidar.cpp, src/devices/rpLidar/rpLidar.h, src/libYARP_dev/src/yarp/dev/IRangefinder2D.h, src/libYARP_dev/src/yarp/dev/Lidar2DDeviceBase.cpp, src/libYARP_dev/src/yarp/dev/Lidar2DDeviceBase.h
added timestamp to the following IRangefinder2D methods:
``` getLaserMeasurement(std::vector<LaserMeasurementData> &data, double* timestamp = nullptr) ```
```getRawData(yarp::sig::Vector &data, double* timestamp = nullptr) ```
=> Timestamp for IRangefinder2D

doc/release/master/thrift_vocab_arg.md, src/devices/ILocalization2DMsgs/idl_generated_code/ILocalization2DMsgs.cpp, src/devices/IMap2DMsgs/idl_generated_code/IMap2DMsgs.cpp, src/devices/INavigation2DMsgs/idl_generated_code/INavigation2DMsgs.cpp, src/devices/fakeBattery/idl_generated_code/FakeBatteryService.cpp, src/devices/frameTransformStorageMsgs/idl_generated_code/FrameTransformStorageGetRPC.cpp, src/devices/frameTransformStorageMsgs/idl_generated_code/FrameTransformStorageSetRPC.cpp, src/devices/mobileBaseVelocityControlMsgs/idl_generated_code/MobileBaseVelocityControlRPC.cpp, src/devices/multipleAnalogSensorsMsgs/idl_generated_code/MultipleAnalogSensorsMetadata.cpp, src/libYARP_os/src/yarp/os/idl/WireReader.cpp, src/libYARP_os/src/yarp/os/idl/WireReader.h, src/yarpdataplayer-console/idl_generated_code/yarpdataplayer_console_IDL.cpp, src/yarpdataplayer/idl_generated_code/yarpdataplayer_IDL.cpp, src/yarpidl_thrift/src/t_yarp_generator.cc, src/yarprobotinterface/idl_generated_code/yarprobotinterfaceRpc.cpp
WARNING: This makes it impossible to have a service function that starts
with the same name as a different function.
=> yarpidl_thrift: Fix services when the first argument is a vocab

doc/release/master.md, src/libYARP_sig/src/yarp/sig/Vector.h
This method was not returning anything contrary to what was stated in the documentation. Actually, it would have made sense to return `void` due to the signature of `std::vector<T>::emplace_back` in previous standards. In C++17 and later (hence I wouldn't think of backporting this as-is to yarp-3.5), it does return a reference instead: [cppreference.com](https://en.cppreference.com/w/cpp/container/vector/emplace_back).
Affects YARP 3.4.0+: https://github.com/robotology/yarp/pull/2195.
=> Actually return a reference in `VectorOf<T>::emplace_back`

doc/release/master/improved_frameTransformClientTest.md, src/devices/frameTransformClient/FrameTransformClient.cpp, src/devices/frameTransformClient/robotinterface_xml/ftc_full_ros.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_local_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_pub_ros.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_pub_yarp_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_ros.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_sub_ros.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_sub_yarp_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_yarp_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_yarp_only_single_client.xml, src/devices/frameTransformServer/FrameTransformServer.cpp, src/devices/frameTransformServer/robotinterface_xml/fts_full_ros.xml, src/devices/frameTransformServer/robotinterface_xml/fts_yarp_only.xml, src/devices/frameTransformStorage/FrameTransformStorage.cpp, src/devices/frameTransformUtils/FrameTransformContainer.cpp, src/devices/frameTransformUtils/FrameTransformContainer.h, tests/libYARP_dev/FrameTransformClientTest.cpp, tests/libYARP_dev/IFrameTransformTest.cpp
* improved frameTransformClientTest for better understanding issues in CI: now using new param FrameTransform_verbose_debug=1
* FrameTransformStorage, FrameTransformContainer show advanced debug info when FrameTransform_verbose_debug=1
* all xml files now expose the parameter FrameTransform_verbose_debug (default = 0)
=> Improved tests and debug messages for frameTransformClient/Server

src/yarpmotorgui/partitem.cpp
This regression was added with https://github.com/robotology/yarp/pull/2774/commits/d28d58e647995c2eff4043404d05fa4f016e8547. I forgot to add a proper initialization for the raw vector, so the corresponding delete could have caused a crash.
This is happening when a [art fails to open.
cc @randaz81 @drdanz
=> Fixed regression in yarpmotorgui when part is not available.

.ci/initial-cache.gh.linux.cmake, .ci/initial-cache.gh.macos.cmake, .ci/initial-cache.gh.windows.cmake, doc/release/master/sensorMeas_to_vec.md, src/devices/CMakeLists.txt, src/devices/fakePositionSensor/CMakeLists.txt, src/devices/fakePositionSensor/fakePositionSensor.cpp, src/devices/fakePositionSensor/fakePositionSensor.h, src/portmonitors/CMakeLists.txt, src/portmonitors/sensorMeasurements_to_vector/CMakeLists.txt, src/portmonitors/sensorMeasurements_to_vector/README.md, src/portmonitors/sensorMeasurements_to_vector/SM_to_vec.cpp, src/portmonitors/sensorMeasurements_to_vector/SM_to_vec.h
added new portmonitor `sensorMeasurements_to_vector` which converts a 6D Pose from a `SensorStreamingData` data type to a `yarp::sig::Vector` data type. The port monitor can be extended (writing simple additional code) to support different use cases.
Usage Example:
`yarp connect /tracking/measures:o /in tcp+recv.portmonitor+type.dll+file.sensorMeasurements_to_vector`
=> sensorMeasurements_to_vector portmonitor

doc/yarp_logging.md
There was a ` instead of a ' that create problems in visualization.
=> Fix typo in YARP_LOG_PROCESS_LABEL documentation

src/devices/RemoteControlBoard/RemoteControlBoard.h
The options are supported in the code (see https://github.com/robotology/yarp/blob/v3.6.0/src/devices/RemoteControlBoard/RemoteControlBoard.cpp#L236) but they were not documented.
=> Add documentation on carrier option supported in remote_controlboard device

src/yarpmotorgui/CMakeLists.txt, src/yarpmotorgui/jointitem.cpp, src/yarpmotorgui/jointitem.h, src/yarpmotorgui/mainwindow.cpp, src/yarpmotorgui/mainwindow.h, src/yarpmotorgui/mainwindow.ui, src/yarpmotorgui/modestreemanager.cpp, src/yarpmotorgui/modestreemanager.h, src/yarpmotorgui/partitem.cpp, src/yarpmotorgui/partitem.h
This depends on #2774 
This mainly isolates the code related to the tree mode in a separate class. This will ease the work for implementing what mentioned in https://github.com/robotology/yarp/pull/2773#issuecomment-987853393
It also adds the joint name in the tree
=> Refactoring of the tree mode in yarpmotorgui

CMakeLists.txt, doc/release/master/friction_parameters.md, src/devices/ControlBoardWrapper/RPCMessagesParser.cpp, src/devices/RemoteControlBoard/RemoteControlBoard.cpp, src/devices/fakeMotionControl/fakeMotionControl.cpp, src/devices/fakeMotionControl/fakeMotionControl.h, src/libYARP_dev/src/yarp/dev/ControlBoardHelper.cpp, src/libYARP_dev/src/yarp/dev/ControlBoardHelper.h, src/libYARP_dev/src/yarp/dev/ITorqueControl.h, src/libYARP_dev/src/yarp/dev/ImplementTorqueControl.cpp, src/yarpmotorgui/piddlg.cpp, src/yarpmotorgui/piddlg.ui, tests/libYARP_dev/CMakeLists.txt, tests/libYARP_dev/TorqueControlTest.cpp
What's new in this PR:
- In [ITorqueControl.h][1] have been added 4 new friction parameters: `viscousUp`, `viscousDown`, `coulombUp`, `coulombDown`.
- the definitions of all the `get/set` functions have been updated accordingly.
- A new ControlTorqueTest source has been added to the test folder in order to validate the implementation of the new parameters
**Notes:**
- The implementation has been tested successfully with the new test provided with this PR.
[1]: (https://github.com/robotology/yarp/compare/master...sgiraz:master#diff-a6d521af362a51d273c0ced3cd303cf4d7eaf66795f7514c6b33f471ea962254)
=> Add implementation for friction parameters

cmake/YarpMacOSUtilities.cmake, doc/release/yarp_3_6/fixrobsup_1090.md
This fixes compatibility with CMake 3.23.1 
Fix https://github.com/robotology/robotology-superbuild/issues/1090
=> yarp_macos_duplicate_and_add_bundle: Do not try to set properties that contain HEADER_SETS in the name

doc/release/master/safe_yarpread.md, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdRead.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdWrite.cpp
added check to prevent `yarp read` stealing ports already in use.
=> safe yarp read and write

doc/release/master/read_just_once.md, src/libYARP_companion/src/yarp/companion/impl/BottleReader.h, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdRead.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdReadWrite.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.h
added `once` option to companion command `yarp read`.
The `yarp read` terminates after the first received bottle.
=> yarp read once

doc/cmd_yarprobotinterface.dox, doc/release/master/robotinterface_portprefix.md, doc/robotinterface_all.dox, doc/yarp_robotinterface_xml_config_files.dox, src/libYARP_robotinterface/src/yarp/robotinterface/XMLReader.h, src/libYARP_robotinterface/src/yarp/robotinterface/impl/XMLReaderFileV3.cpp, src/yarprobotinterface/Module.cpp, tests/libYARP_robotinterface/RobotinterfaceTest.cpp
Fix half of https://github.com/robotology/yarp/issues/2492 by actually making use of the `portprefix` attribute.
For example, this can be used as in the following example XML example:
~~~xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE robot PUBLIC "-//YARP//DTD yarprobotinterface 3.0//EN" "http://www.yarp.it/DTD/yarprobotinterfaceV3.0.dtd">
<robot name="robotinterfaceExample" portprefix="/icub" build="0" xmlns:xi="http://www.w3.org/2001/XInclude">
<devices>
<device name="fake_motor_device" type="fakeMotionControl">
<group name="GENERAL">
<param name="Joints">            3         </param>
</group>
</device>
<device name="fake_motor_nws_yarp" type="controlBoard_nws_yarp">
<param name="name"> ${portprefix}/body </param>
<param name="period"> 0.01 </param>
<action phase="startup" …
=> Modify libYARP_robotinterface and yarprobotinterface to support passing using ${portprefix} in parameters

doc/release/yarp_3_6/fix_yarpmotorgui_setPointBox.md, src/yarpmotorgui/sliderWithTarget.cpp
* The target box for the joints sliders now lands where expected (see [#issue2824](https://github.com/robotology/yarp/issues/2824) for further details).
The the `target` value for the slider was not being multiplied by the `sliderStep` value when computing the new X value for the `target box` rectangle.
=> Joint item slider Target box position fixed

doc/release/yarp_3_7/fixgraphviz3.md, extern/qgv/CMakeLists.txt
Since version 3, Graphviz requires downstream users to define `GVDLL`  to link correctly on Windows when using a Graphviz shared library. This change (together with upcoming YCM release 0.14.2: https://github.com/robotology/ycm/pull/414) fixes the compilation of YARP against graphviz 3. 
If an older YCM version is used, nothing happens (so there is no need to bump the required YCM version).
=> Fix compilation against graphviz 3 on Windows

doc/release/yarp_3_7/fixodometryTimestamp.md, src/devices/fakeOdometry/FakeOdometry.cpp, src/devices/fakeOdometry/FakeOdometry.h, src/devices/odometry2D_nws_ros/Odometry2D_nws_ros.cpp, src/devices/odometry2D_nws_ros/Odometry2D_nws_ros.h, src/devices/odometry2D_nws_yarp/Odometry2D_nws_yarp.cpp, src/devices/odometry2D_nws_yarp/Odometry2D_nws_yarp.h, src/libYARP_dev/src/yarp/dev/IOdometry2D.h, src/libYARP_dev/src/yarp/dev/IRangefinder2D.h
added timestamp to IOdometry2D::getOdometry() method
=> Fix IOdometry2D added missing timestamp

doc/release/yarp_3_7/fix_yarpmotorgui_customPosition_error_on_missingParts.md, src/yarpmotorgui/mainwindow.cpp
* This pr solves the problem reported in issue [#issue2839](https://github.com/robotology/yarp/issues/2839). Now `yarpmotorgui` does not show the error dialog when setting only a subset of the
available robot parts to a custom position
=> Simple fix of onHomeAllPartsToCustomPoistion

.ci/initial-cache.gh.macos.cmake, extern/CMakeLists.txt
There were two points where https://github.com/robotology/yarp/pull/2852 did not changed from `SQLite`  to `SQLite3`.
Fix https://github.com/robotology/yarp/issues/2859 .
fyi @randaz81 @pattacini
=> Fix regression in https://github.com/robotology/yarp/pull/2852 that created problem if no system SQLite was installed

doc/release/yarp_3_7/cbw_consistency_timestamps.md, src/devices/ControlBoardWrapper/ControlBoard_nws_yarp.cpp
This bugfix is a follow-up to https://github.com/robotology/yarp/pull/2841 (cc @randaz81). The `run` loop is stuck on the consistency check after raising an error since there is no way to refresh the `times` vector again, thus rendering the state ports unusable from that point onwards. Our robot is capable of recovery on comms failure (which happens quite often) on any joint, therefore patch https://github.com/robotology/yarp/pull/2841 forces us to restart the control board. This didn't happen prior to YARP 3.7.
I might suggest later a way to disable or configure this consistency checker differently. Anyway, I believe this patch targets a bug and should be addressed first.
=> Refresh timestamps on consistency check failure

doc/release/yarp_3_7.md, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdConf.cpp, src/libYARP_os/src/yarp/os/impl/NameClient.cpp, src/libYARP_os/src/yarp/os/impl/NameConfig.cpp
Yarp now displays an error message if it is unable to save its configuration file.
Fixes: https://github.com/robotology/yarp/issues/2662
=> Added error message for conf file

doc/release/yarp_3_7/adddebugremap.md, src/devices/multipleanalogsensorsremapper/MultipleAnalogSensorsRemapper.cpp
When the `multipleanalogsensorsremapper` complains that the name is not found, it is important to also print the available names, to make sure that the users have a precise idea of why the provided name is not ok. 
This was quite useful when debugging https://github.com/robotology/gazebo-yarp-plugins/pull/633 .
=> multipleanalogsensorsremapper: Add more verbosity when sensor name is not found

doc/release/yarp_3_7/fix_companion_cmdWrite.md, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdWrite.cpp
* `Yarp companion` command `write` was throwing segmentation fault when `argc` was less than 2. The problem is now fixed.
=> Fixed yarp write segfault

doc/release/master/protected_control_interfaces.md, src/devices/ControlBoardWrapper/RPCMessagesParser.cpp, src/devices/fakeMotionControl/fakeMotionControl.cpp
RPCMessagesParser several calls to various motor control interfaces have been protected so that if an interface is not available in the hardware device (i.e. the view() fails), the controlboardwrapper/yarprobotinterface does not segfaults.
=> protected RPCMessagesParser 

doc/release/master/000_master.md, src/libYARP_sig/src/yarp/sig/Vector.h, tests/libYARP_os/LogStreamTest.cpp
Follow-up to https://github.com/robotology/yarp/pull/2758. Similarly to STL containers, C arrays, pairs and tuples, now `yarp::sig::VectorOf<T>` is also chainable to stream logging macros, e.g.:
```cxx
yarp::sig::Vector v {1.23, 5.0};
yInfo() << v;
```
(Disclaimer: one can obviously call `v.toString()` instead; this patch harmonizes YARP and STL vectors, though.)
=> Allow chaining `yarp::sig::VectorOf<T>` to LogStream

doc/release/yarp_3_7/fixffmpegwin.md, src/devices/ffmpeg/CMakeLists.txt, src/portmonitors/image_compression_ffmpeg/CMakeLists.txt
Without this patch, compilation against ffmpeg 4 on Windows is failing with error:
~~~
ffmpegPortmonitor.obj : error LNK2019: unresolved external symbol av_freep referenced in function "protected: int __cdecl FfmpegMonitorObject::compress(class yarp
::sig::Image *,struct AVPacket *)" (?compress@FfmpegMonitorObject@@IEAAHPEAVImage@sig@yarp@@PEAUAVPacket@@@Z) [C:\src\yarp\builddev\src\portmonitors\image_compres
sion_ffmpeg\yarp_pm_image_compression_ffmpeg.vcxproj]
ffmpegPortmonitor.obj : error LNK2019: unresolved external symbol av_buffer_create referenced in function "public: virtual class yarp::os::Things & __cdecl Ffmpeg
MonitorObject::update(class yarp::os::Things &)" (?update@FfmpegMonitorObject@@UEAAAEAVThings@os@yarp@@AEAV234@@Z) [C:\src\yarp\builddev\src\portmonitors\image_co …
=> ffmpeg_grabber: Fix linking errors on Windows

doc/module_executables/cmd_yarprobotinterface.dox, doc/module_yarprobotinterface/yarp_robotinterface_xml_config_files.dox, doc/release/master/yarprobotinterface_enable_tags.md, src/libYARP_robotinterface/src/yarp/robotinterface/impl/XMLReaderFileV3.cpp
`yarprobotinterface`: is now able to interactively enable/disable sections of the xml configuration files included through the xi:include tag. See attached yarprobotinterface `Doxygen` documentation.
=> yarprobotinterface with `enabled_by` and `disabled_by` xml attributes

doc/release/master/refactor_audioWrappers_multiWrapperToSingleWrapper.md, src/devices/audioPlayerWrapper/AudioPlayerWrapper.cpp, src/devices/audioPlayerWrapper/AudioPlayerWrapper.h, src/devices/audioRecorderWrapper/AudioRecorderWrapper.cpp, src/devices/audioRecorderWrapper/AudioRecorderWrapper.h
The two wrappers have been modified in order to be compatible with `yarprobotinterface` without losing the
compatibility with `yarpdev` and the `subdevice` option
Now the two objects do not inherit from `yarp::dev::IMultipleWrapper` but from `yarp::dev::WrapperSingle`
This modification has been done in order to allow the two wrappers to implement both the `IWrapper` and the `IMultipleWrapper` interfaces
=> Refactor audioPlayer and audioRecorder wrappers for yarprobotinterface compatibility

doc/release/master/feature_yarpview_titleOption.md, src/yarpview/plugin/VideoSurface.qml, src/yarpview/plugin/qtyarpview.cpp, src/yarpview/plugin/qtyarpview.h, src/yarpview/src/qml/QtYARPView/main.qml, src/yarpview/src/qml/QtYARPView/mainCompact.qml
* Added the possibility to set a custom title for `yarpview` by passing `--title` + *custom title* to the executable
* If the `title` argument is not passed `yarpview` window title will be assigned as it has been until now
---
* This PR is linked to issue [#2894](https://github.com/robotology/yarp/issues/2894)
=> Added --title option to yarpview

doc/release/master/improved_thrift_gen.md, src/yarpidl_thrift/src/t_yarp_generator.cc
Improved thrift generator in order to handle default values of the variables declared inside a .thrift file.
For instance, it is now possible to parse the following thrift file:
```
struct my_struct
{
/** before, the default value was ignored and set to zero. Now it is ok */
1: double       my_value=7.0;
}
```
=> Default values for thrift files

doc/module_executables/cmd_yarpscope.dox, doc/release/master/companion_split.md, src/libYARP_companion/src/CMakeLists.txt, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdSplit.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.h
Added companion command `yarp split`. The command splits a heterogeneous nested bottle received from a port into multiple ports.
=> New companion command `yarp split`

doc/release/master/extern_sqlite3_fix.md, extern/sqlite/CMakeLists.txt
Migration from sqlite to sqlite3. Fixed issue preventing extern/sqlite3 (i.e. YARP_priv_SQLite3) to be correctly found
as a dependency by other projects. Thanks @traversaro for finding the issue.
=> YARP_priv_SQLite3 fix

tests/harness.cpp, tests/harness.h
`yarp_tests_skipped` variable is now hidden inside `harness.cpp` and accessible only using `increment_tests_skipped()` function.
This allows easier export of library symbols.
=> yarp_tests_skipped incapsulation

doc/release/master/fix_FrameTransformClient_interfaces_check.md, src/devices/frameTransformClient/FrameTransformClient.cpp
* Now, if the selected configuration xml file does not include a certain interface, the device is still correctly initialized but that interface won't be available. If a method that involves the missing interface is called, an error will be returned.
=> Fix: frameTransformClient interfaces check

doc/release/yarp_3_7/cbw_remote_vars.md, src/devices/ControlBoardWrapper/RPCMessagesParser.cpp
Bugfix: a wrong pointer check could prevent from parsing remote `IRemoteVariables` commands.
=> Fix handling of `IRemoteVariables` messages via RPC

src/yarprobotinterface/Module.cpp
Commit https://github.com/robotology/yarp/commit/bb16484dbf26026906ef7b7b44169ca15dca201ba added some code that does not work fine on arm architectures. It seems that the same code also does not work on ppc architectures, so let's the appropriate checks to avoid to compile the code on ppc.
See https://github.com/conda-forge/ogre-next-feedstock/pull/13#issuecomment-1327923352 for why the `__PPC__` define has been used for the check.
=> Fix compilation on ppc architectures

src/libYARP_os/src/yarp/os/Os.cpp, src/libYARP_os/src/yarp/os/impl/NameConfig.cpp, src/libYARP_os/src/yarp/os/impl/SocketTwoWayStream.cpp, src/libYARP_os/src/yarp/os/impl/TcpAcceptor.h, src/libYARP_os/src/yarp/os/impl/TcpConnector.h, src/libYARP_os/src/yarp/os/impl/TcpStream.h, src/libYARP_os/src/yarp/os/impl/ThreadImpl.cpp, src/yarpidl_rosmsg/src/RosType.cpp
The `SKIP_ACE=ON`  option was currently broken in macOS as macOS, while providing a POSIX API, does not define the `__unix__`  preprocessor. 
The PR does not change in any way normal builds of macOS when `SKIP_ACE`  is set to `OFF`  (its default value).
=> Fix SKIP_ACE=ON option for macOS

doc/release/master/portmoinitor_imagerotation.md, src/portmonitors/CMakeLists.txt, src/portmonitors/image_rotation/CMakeLists.txt, src/portmonitors/image_rotation/imageRotation.cpp, src/portmonitors/image_rotation/imageRotation.h
added new portmonitor `image_rotation`
e.g.
`yarp connect /grabber/depth:o /yarpview/img:i tcp+recv.portmonitor+type.dll+file.image_rotation+options_rotate.rotate_ccw`
=> portmonitor `image_rotation`

bindings/yarp.i, doc/release/yarp_3_7/py_bind_gazectrl.md
The version of the method exposed to Python now returns the ID as output and takes no input, instead of expecting a pointer. A negative value (-1) represents an error in retrieving the ID.
=> Fixed python binding of IGazeControl storeContext()

tests/CMakeLists.txt
Tests are no longer placed in /build/tests folder.
Instead, they are now placed into /build folder.
This is required to fix some CI issues, i.e. the tests placed into /build/tests were not able to find some yarp libraries without appending the /build folder to path (in Win32)
Discussed with @traversaro
=> Change build path for yarp tests

bindings/yarp.i, doc/release/master/yarp_python_bindings_update.md
Fixes bug described in https://github.com/robotology/yarp/issues/2889.
Thanks @PeterBowman for the hint!
=> [ISSUE-2889] SWIG leak on yarp::os::Type

src/devices/ControlBoardRemapper/ControlBoardRemapper.cpp
This PR fixes a bug that arises when a user tries to get the gearbox ratio when a part uses the remapper. 
For example, let two sets of joints of a specific part have the following parameters:
```
set_1:
joint indices (0 1 2)
gear ratios (10 20 30)
set_2:
joint indices (3 4 5)
gear ratios (30 40 50)
remapper:
set_1 (0 2 0 2)
set_2 (3 5 0 2)
```
Without the fix, trying to get the gearbox ratio of all the robot part returns: `(10 10 10 40 40 40)`, because the index of the subcontrolboard is used. 
Instead, with the fix it should of course be: `(10 20 30 40 50 60)`.
The fix was successfully tested on iCub3.
Targeting yarp 3.7 as it's a bugfix, not sure if it's the correct branch.
cc @pattacini
=> Fix retrieval of gearbox ratio in controlBoardRemapper

doc/release/master/yarpmotorgui_improved_labels.md, src/devices/fakeMotionControl/fakeMotionControl.cpp, src/yarpmotorgui/jointitem.cpp, src/yarpmotorgui/jointitem.h, src/yarpmotorgui/mainwindow.cpp, src/yarpmotorgui/mainwindow.h, src/yarpmotorgui/partitem.cpp, src/yarpmotorgui/partitem.h, src/yarpmotorgui/sliderOptions.cpp, src/yarpmotorgui/sliderOptions.h, src/yarpmotorgui/sliderOptions.ui, src/yarpmotorgui/sliderWithTarget.cpp, src/yarpmotorgui/sliderWithTarget.h
* improved sliders labels alignment
* added a new option to set the number of decimal digits of the slider
* FakeMotionControl added LIMITS::Max and LIMITS::Min options
=> Improved yarpmotorgui labels

src/devices/multipleanalogsensorsclient/MultipleAnalogSensorsClient.cpp, src/devices/multipleanalogsensorsclient/MultipleAnalogSensorsClient.h
The previous one was `0.01` but since almost all our sensors has a period ~ `0.01` this made  trigger a lot of timeout errors
cc @traversaro @pattacini @davidetome
=> MultipleAnalogSensorsClient: Increase default timeout parameter to 0.02 seconds

src/libYARP_dataplayer/src/yarp/dataplayer/YarpDataplayer.cpp, src/libYARP_dataplayer/src/yarp/dataplayer/YarpDataplayer.h, src/yarpdataplayer/src/worker.cpp
This pull request applies a bug-fix and an update for high-frequency to `yarpdataplayer`.
`src/libYARP_dataplayer/src/yarp/dataplayer/YarpDataplayer.cpp#L653`
The function `sendBottle(part, frame)` sends the envelope as a `Bottle(timestamp)` which is inconsistent with `yarpdatadumper` which saves the envelope as a `yarp::os::Stamp` - i.e. sequence number and timestamp. This causes invalid envelopes when reading the envelopes sent by `yarpdatadumper` as a `Stamp`.
The function is changed to `sendGenericData<Bottle>(part, frame)` as it sends the envelope as a `Stamp` by default. In the comments of the code it suggests that the functions are "identical" and therefore this was probably something overlooked, and not intentional.
This bug completely breaks all timestamps for EDPR when using …
=> yarpdataplayer high-rate fix

doc/release/yarp_3_8/master.md, src/devices/multipleanalogsensorsserver/MultipleAnalogSensorsServer.cpp, src/devices/multipleanalogsensorsserver/MultipleAnalogSensorsServer.h, src/libYARP_dev/src/yarp/dev/MultipleAnalogSensorsInterfaces.h
The bug occured once one of the device that was wrapped by multipleanalogsensorsserver did not resize the measure vector passed in the `get<...>Measure` call, for example because no sensor measurements were available.
The problem is solved by properly resizing the buffers before populating them, without relying on the wrapped device to do the necessary resizing.
=> Fix segmentation fault bug in multipleanalogsensorsserver YARP device

src/yarpdataplayer/src/mainwindow.cpp, src/yarpdataplayer/src/worker.cpp
There seems to be a race condition in the `yarpdataplayer` GUI that causes the GUI to lock-up sometimes when pressing the stop button. I found it is the case when the worker thread is asked to `stop()` and is waiting to `join()`, that the thread is also often still waiting to return from an `updateGuiThread()`, which for some reason never happens. The race condition probably occurs more often after the GUI updates at a fast rate #2946 
To mitigate this 
- `updateGUIThread()` is only called if the worker thread is still running (`worker.cpp`)
- the worker thread is stopped before other operations that modify the GUI preventing both threads from attempting to update the GUI simultaneously (`mainwindow.cpp`)
=> mitigating yarpdataplayer GUI race condition

src/devices/opencv/OpenCVGrabber.cpp, src/devices/opencv/OpenCVGrabber.h
I was testing compilation of YARP against an opencv without highgui, and the compilation failed even if highgui is not actually used in `opencv_grabber`.
=> opencv_grabber: Remove use of highgui include

doc/release/yarp_3_8/yarpmotorgui_cpu.md, src/yarpmotorgui/sliderWithTarget.cpp
Fixes https://github.com/robotology/yarp/issues/2955. Apparently, CPU usage skyrockets when these commands are split, and also the application segfaults on exit. I merged them following [the API docs](https://doc.qt.io/qt-5/qt.html#AlignmentFlag-enum) and verified that `Qt::AlignLeft` and `Qt::AlignVCenter` cope well together (had to check View > View Position Target Value).
cc @xEnVrE please give it a try on your end
cc @randaz81 regarding https://github.com/robotology/yarp/commit/54c1a6f2151984985a227ee9083aecf89402fcbb (https://github.com/robotology/yarp/pull/2947).
=> Merge `setAlignment` commands in yarpmotorgui

data/yarpdataplayer/scripts/yarpdatadumper.xml.template, data/yarpdataplayer/scripts/yarpdatadumperExample.xml, data/yarpdataplayer/scripts/yarpdataplayer.xml.template, data/yarpdataplayer/scripts/yarpdataplayerExample.xml, doc/release/yarp_3_8/yarpdataplayer_cleanup_inertial_portnames.md
~~This patch follows up on https://github.com/orgs/robotology/discussions/638#discussioncomment-6248267 and aims to update the names of the inertial ports in the `yarpdataplayer` example application.~~
---
> **Note**
Actually, the `yarpdataplayer` is unable to deal with the MAS client, hence we cleaned up those ports.
See https://github.com/robotology/yarp/pull/2979#issuecomment-1602476624.
=> [yarpdataplayer] Remove inertial ports for robot and iCubGui from the example app

src/devices/multipleanalogsensorsserver/MultipleAnalogSensorsServer.cpp, src/devices/multipleanalogsensorsserver/MultipleAnalogSensorsServer.h
Before, only a sensor name was printed, now also the sensor type and the non-OK status that resulted in an error.
=> multipleanalogsensorsserver: Improve message in case a sensor is not published due to non-OK status

doc/module_yarp_dev/module_yarpdev.dox, doc/release/yarp_3_8/refactor_doc_libYARP_dev.md, src/libYARP_dev/src/yarp/dev/IAmplifierControl.h, src/libYARP_dev/src/yarp/dev/IAudioRender.h, src/libYARP_dev/src/yarp/dev/IAxisInfo.h, src/libYARP_dev/src/yarp/dev/ICalibrator.h, src/libYARP_dev/src/yarp/dev/IControlCalibration.h, src/libYARP_dev/src/yarp/dev/IControlLimits.h, src/libYARP_dev/src/yarp/dev/IControlMode.h, src/libYARP_dev/src/yarp/dev/ICurrentControl.h, src/libYARP_dev/src/yarp/dev/IEncoders.h, src/libYARP_dev/src/yarp/dev/IEncodersTimed.h, src/libYARP_dev/src/yarp/dev/IFrameGrabberControlsDC1394.h, src/libYARP_dev/src/yarp/dev/IFrameGrabberImage.h, src/libYARP_dev/src/yarp/dev/IHapticDevice.h, src/libYARP_dev/src/yarp/dev/IInteractionMode.h, src/libYARP_dev/src/yarp/dev/IJointFault.h, src/libYARP_dev/src/yarp/dev/IMotor.h, src/libYARP_dev/src/yarp/dev/IMotorEncoders.h, src/libYARP_dev/src/yarp/dev/IPWMControl.h, src/libYARP_dev/src/yarp/dev/IPidControl.h, src/libYARP_dev/src/yarp/dev/IPositionControl.h, src/libYARP_dev/src/yarp/dev/IPositionDirect.h, src/libYARP_dev/src/yarp/dev/IRemoteCalibrator.h, src/libYARP_dev/src/yarp/dev/IRemoteVariables.h, src/libYARP_dev/src/yarp/dev/ITorqueControl.h, src/libYARP_dev/src/yarp/dev/IVelocityControl.h, src/libYARP_dev/src/yarp/dev/IVirtualAnalogSensor.h, src/libYARP_dev/src/yarp/dev/IVisualServoing.h
- Added missing doxygen tags to:
- IAudioRender (`dev_iface_media`)
- ICalibrator (`dev_iface_motor`)
- IFrameGrabberControlsDC1394 (`dev_iface_media`)
- IFrameGrabberOf (`dev_iface_media`)
- IHapticDevice (`dev_iface_other`)
- IRemoteCalibrator (`dev_iface_motor`)
- IVisualServoing (`dev_iface_other`)
- Created new `raw` tag inside `dev_iface_motor` and `dev_iface_other` to separate raw interfaces from the others.
- Interfaces affected by this change (for some of them the tag was added since it was missing and for the other ones it was changes to the `raw` *sub-tag*):
- IAmplifierControlRaw (`dev_iface_motor_raw` - added)
- IAxisInfoRaw (`dev_iface_motor_raw` - added)
- IControlCalibrationRaw (`dev_iface_motor_raw` - added)
- IControlLimitsRaw (`dev_iface_motor_raw` - added)
- …
=> Categories refactoring for yapr::dev: interfaces documentation

doc/release/yarp_3_8/fix_frameGrabber_nwc_RPC_port_bug.md, src/devices/frameGrabber_nwc_yarp/FrameGrabber_nwc_yarp.cpp
Together with @traversaro and @HosameldinMohamed, we found out that the `frameGrabber_nwc_yarp` is using an RPC port to get the image of a camera because `m_streamerReceiver` is not defined; we added the function `setStreamReceiver` and in this way, the object `m_streamerReceiver` is defined and we avoid continuously calling the function [getImage](https://github.com/robotology/yarp/blob/99f5a8a2c728b50300d02bada44fe8fc85df5636/src/devices/frameGrabber_nwc_yarp/FrameGrabber_nwc_yarp.cpp#L145C115-L145C115) which uses an RPC port to receive the image and it slows the process.
=> FrameGrabber_nwc_yarp: fix bug that forces images to be sent through RPC calls

src/devices/JoypadControlServer/tests/joypadControlServer_test.cpp, src/devices/battery_nws_yarp/tests/battery_nws_yarp_test.cpp, src/devices/frameGrabber_nwc_yarp/FrameGrabber_nwc_yarp.cpp, src/devices/frameGrabber_nwc_yarp/FrameGrabber_nwc_yarp.h, src/devices/frameGrabber_nwc_yarp/tests/frameGrabber_nwc_yarp_test.cpp, src/libYARP_dev/src/yarp/dev/IFrameGrabberImage-inl.h
This PR is triggered by https://github.com/robotology/yarp/pull/2990. The fix on the image stream made visible a severe memory error on the method `getImageCropped()` which was not detected when the method was called in RPC mode. The issue is under investigation.
@davidegorbani
=> improved frameGrabber_nwc test / fix for method getImageCropped()

doc/release/yarp_3_8/yarprun_stdio_fix.md, src/libYARP_run/src/yarp/run/Run.cpp
Opened in #2966. This line prevents /stdin port to write info messages thus polluting the stdin of the cmd run by yarprun --cmd <cmd> --stdio.
=> [2966] Bugfix for yarprun stdio

src/carriers/h264_carrier/CMakeLists.txt, src/carriers/h264_carrier/H264Stream.cpp, src/carriers/h264_carrier/H264Stream.h, src/carriers/websocket/CMakeLists.txt
YARP_wire_rep_utils unnecessary dependency removed from h264 and websocket carriers.
No functional changes.
=> wire_rep_utils cleanup

doc/release/yarp_3_9_master/added_velocityThres.md, src/devices/RemoteControlBoard/RemoteControlBoard.cpp, src/devices/controlBoard_nws_yarp/RPCMessagesParser.cpp, src/devices/fakeMotionControl/fakeMotionControl.cpp, src/devices/fakeMotionControl/fakeMotionControl.h, src/libYARP_dev/src/yarp/dev/ControlBoardHelper.cpp, src/libYARP_dev/src/yarp/dev/ControlBoardHelper.h, src/libYARP_dev/src/yarp/dev/ITorqueControl.h, src/libYARP_dev/src/yarp/dev/ImplementTorqueControl.cpp, src/libYARP_dev/src/yarp/dev/tests/ITorqueControlTest.h, src/yarpmotorgui/piddlg.cpp, src/yarpmotorgui/piddlg.ui
**What's new:**
- Add a new `velocityThres` parameter used during torque control for friction compensation. This parameter is used to enable the new torque control law and fine-tune the friction compensation based on velocity feedback at FW level.
> **Note**
> - Tested on a single joint setup
=> Add velocityThres param for torque control

cmake/YarpFindDependencies.cmake, doc/release/yarp_3_9_master/master.md, src/CMakeLists.txt, src/devices/LLM_nws_yarp/CMakeLists.txt, src/devices/LLM_nws_yarp/ILLMServerImpl.cpp, src/devices/LLM_nws_yarp/ILLMServerImpl.h, src/devices/LLM_nws_yarp/LLM_nws_yarp.cpp, src/devices/LLM_nws_yarp/LLM_nws_yarp.h, src/devices/fakeLLMDevice/fakeLLMDevice.cpp, src/yarpllmgui/CMakeLists.txt, src/yarpllmgui/ConfigurePopup.qml, src/yarpllmgui/ConversationCallback.cpp, src/yarpllmgui/ConversationCallback.h, src/yarpllmgui/ConversationModel.cpp, src/yarpllmgui/ConversationModel.h, src/yarpllmgui/main.cpp, src/yarpllmgui/main.qml, src/yarpllmgui/res.qrc
This PR adds a minimal gui for the LLMDevices.
- The gui can be used both passively - following a conversation happening via nws - or actively.
- fakeDevice now can't modify the prompt after a conversation has started. This means that once the first question has been asked, if the user wants to change the prompt he/she also has to start a new conversation.
- Added a streaming port in the nws that serves to notify the gui of changes happening in the conversation. This makes it possible to use the gui to passively follow a conversation happening in the nws.
=> Yarpllmgui

src/libYARP_serversql/src/yarp/serversql/impl/ConnectThread.h
`ConnectThread` is using `std::string` , but `<string>` was not used. See https://github.com/robotology/idyntree/pull/1103#issuecomment-1706468411 .
=> ConnectThread: Include what you use

src/devices/audioRecorder_nws_yarp/AudioRecorder_nws_yarp.cpp
- Adding the configuration for the parameter `send_sound_on_stop` which was always set to true before.
- Fixing the condition to match the warning message (and the expected behaviour)
=> audioRecorder_nws fixes

src/devices/frameTransformClient/FrameTransformClient.h
The ``frameTransformClient`` opens a utility RPC port named ``/ftClient/rpc`` independently from the ``ft_client_prefix``. This can raise a name conflict problem in case there is more than one client in the network.
The problem can be avoided by specifying the ``local_rpc`` option, but this was not documented. The commit adds the parameter in the documentation.
cc @elandini84 @randaz81
=> Add documentation about local_rpc in frameTransformClient device

src/yarpmotorgui/piddlg.ui
**What's new:**
- when the `PID` button is clicked now it works as expected without crash.
**Note:**
- Tested on `five-small-joint` setup
cc @pattacini @pattacini @AntonioConsilvio @isorrentino
=> yarpmotorgui bugfix

doc/release/yarp_3_9_master/fix_frameTransform_tf_refresh_timeout.md, src/devices/frameTransformClient/robotinterface_xml/ftc_full_ros.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_local_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_ros.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_sub_ros.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_sub_yarp_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_yarp_only.xml, src/devices/frameTransformClient/robotinterface_xml/ftc_yarp_only_single_client.xml, src/devices/frameTransformServer/robotinterface_xml/fts_full_ros.xml, src/devices/frameTransformServer/robotinterface_xml/fts_yarp_only.xml, src/devices/frameTransformStorage/FrameTransformStorage.cpp
* Added a timeout related parameter (`FrameTransform_container_timeout`) to change the refresh interval for old timed frame transforms.
* The parameter has also been added to the `frameTransformClient` and `frameTransformServer` configuration files. The `extern-name` for this parameter is:
* `ftc_storage_timeout` for `frameTransformClient` files
* `fts_storage_timeout` for `frameTransformServer` files
=> FrameTransformStorage - Timed tf refresh timeout parameter

.github/workflows/ci.yml
Updating sonar-scanner version to use java-11 before deprecation, as recommended in https://community.sonarsource.com/t/java-11-is-deprecated-as-a-runtime-env-to-scan-your-projects/96597.
=> [sonarcloud/coverage] Updated sonar scanner version.

src/libYARP_os/src/yarp/os/SystemClock.cpp
`yarp::os::SystemClock::nowSystem()` now maps to `std::chrono::system_clock` instead of `std::chrono::high_resolution_clock`.
This makes yarp timestamps comparable between windows and linux machines. See issue: https://github.com/robotology/yarp/issues/3038
=> windows<->linux timestamps sync fix

cmake/YarpSystemCheck.cmake, extern/catch2/CMakeLists.txt, src/devices/VirtualAnalogWrapper/VirtualAnalogWrapper.h, src/libYARP_os/src/yarp/os/Log.h
Yarp now requires cpp 20 standard
=> C++20 support

doc/release/yarp_3_8/throttle_consistency_checker.md, src/devices/controlBoard_nws_yarp/ControlBoard_nws_yarp.cpp
As a follow-up to https://github.com/robotology/yarp/pull/2862, this patch throttles the error message printed whenever an inconsistency in encoder timestamps is detected. The "Encoder timestamps are not consistent! Data will not be published." is logged every few milliseconds and bloats the terminal. I'm using an arbitrary throttle of one second to mitigate this.
@randaz81 I think the nws_ros{.h,.cpp} files at src/devices/ControlBoardWrapper have been accidentally left out after https://github.com/robotology/yarp/pull/2845.  Perhaps you want to delete them first, then I can rebase this patch accordingly. As a side note, the consistency check patch from https://github.com/robotology/yarp/pull/2841 was applied to both nws_yarp and nws_ros in the ControlBoardWrapper directory, but the …
=> Throttle error message on inconsistent encoder timestamps

cmake/YarpInstallationHelpers.cmake, doc/release/yarp_3_9/yarpidl_thrift_windows_longpath.md, src/yarpidl_thrift/CMakeLists.txt
The `yarp_add_idl`  and `yarp_idl_to_dir` macros can be called in deeply nested folders in downstream projects, and the `yarpidl_thrift` invoked by them also create really long paths when creating the temporary folders it creates. For this reason, it can happen that the paths on which `yarpidl_thrift`  operates violates the 260 maximum character limit on Windows. To use the support for longer paths, as documented in https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation it is necessary to add  a specific manifest to the executable. 
This PR adds support to `yarpidl_thrift` to deal with path longer than 260 characters on Windows.
=> Add support for long paths on Windows for yarpidl_thrift

doc/release/yarp_3_9/yarpviz_graphviz9.md, extern/qgv/CMakeLists.txt, extern/qgv/qgv/QGVCore/private/QGVCore.h
Fix https://github.com/robotology/robotology-superbuild/issues/1537 .
=> yarpviz: Support compilation with graphviz >= 9

example/cmake/with_opencv/CMakeLists.txt, example/opencv/CMakeLists.txt, src/devices/opencv/CMakeLists.txt, src/devices/usbCamera/CMakeLists.txt, src/libYARP_cv/CMakeLists.txt, src/libYARP_cv/src/CMakeLists.txt, src/portmonitors/image_rotation/CMakeLists.txt, src/yarpdatadumper/CMakeLists.txt, src/yarpdataplayer/CMakeLists.txt, src/yarplaserscannergui/CMakeLists.txt
`OpenCV_LIBS` is the variable documented in official OpenCV docs (https://docs.opencv.org/4.x/db/df5/tutorial_linux_gcc_cmake.html). `OpenCV_LIBRARIES` was a YCM extension, that is going to be deprecated (see https://github.com/robotology/ycm/pull/434).
=> CMake: Use OpenCV_LIBS instead of OpenCV_LIBRARIES as documented in official OpenCV docs

src/devices/controlBoardRemapper/ControlBoardRemapper.cpp, src/devices/fake/fakeLaserWithMotor/robotinterface_xml/ros.xml, src/devices/fake/fakeLaserWithMotor/robotinterface_xml/ros2.xml, src/devices/fake/fakeLaserWithMotor/robotinterface_xml/ros2b.xml, src/devices/fake/fakeLaserWithMotor/robotinterface_xml/yarp.xml, src/devices/fake/fakeMotionControl/fakeMotionControl.h, src/devices/fake/fakeMotionControlMicro/fakeMotionControlMicro.h, src/devices/frameGrabberCropper/frameGrabberCropper.cpp, src/devices/frameGrabberCropper/frameGrabberCropper.h, src/devices/networkWrappers/AnalogWrapper/AnalogWrapper.cpp, src/devices/networkWrappers/AnalogWrapper/AnalogWrapper.h, src/devices/networkWrappers/JoypadControlServer/JoypadControlServer.cpp, src/devices/networkWrappers/JoypadControlServer/JoypadControlServer.h, src/devices/networkWrappers/RGBDSensor_nws_yarp/RgbdSensor_nws_yarp.cpp, src/devices/networkWrappers/RGBDSensor_nws_yarp/RgbdSensor_nws_yarp.h, src/devices/networkWrappers/Rangefinder2D_nws_yarp/Rangefinder2D_nws_yarp.cpp, src/devices/networkWrappers/Rangefinder2D_nws_yarp/Rangefinder2D_nws_yarp.h, src/devices/networkWrappers/audioPlayerWrapper/AudioPlayerWrapper.cpp, src/devices/networkWrappers/audioPlayerWrapper/AudioPlayerWrapper.h, src/devices/networkWrappers/audioRecorderWrapper/AudioRecorderWrapper.cpp, src/devices/networkWrappers/audioRecorderWrapper/AudioRecorderWrapper.h, src/devices/networkWrappers/controlBoard_nws_yarp/ControlBoard_nws_yarp.cpp, src/devices/networkWrappers/controlBoard_nws_yarp/ControlBoard_nws_yarp.h, src/devices/networkWrappers/frameGrabber_nws_yarp/FrameGrabber_nws_yarp.cpp, src/devices/networkWrappers/frameGrabber_nws_yarp/FrameGrabber_nws_yarp.h, src/devices/networkWrappers/mobileBaseVelocityControl_nws_yarp/MobileBaseVelocityControl_nws_yarp.cpp, src/devices/networkWrappers/mobileBaseVelocityControl_nws_yarp/MobileBaseVelocityControl_nws_yarp.h, src/devices/networkWrappers/multipleanalogsensorsserver/MultipleAnalogSensorsServer.cpp, src/devices/networkWrappers/multipleanalogsensorsserver/MultipleAnalogSensorsServer.h
The individual implementations of the parameter `subdevice` have been removed from all yarp wrapper devices.
Depends on #3079
Discussed in details in https://github.com/robotology/yarp/discussions/3078
=> Removed subdevice parameter in device wrappers implementations

bindings/yarp.i, doc/release/master.md, src/devices/fake/fakeLLMDevice/fakeLLMDevice.cpp, src/devices/fake/fakeLLMDevice/fakeLLMDevice.h, src/devices/messages/ILLMMsgs/ILLMMsgs.thrift, src/devices/messages/ILLMMsgs/idl_generated_code/ILLMMsgs_index.txt, src/devices/messages/ILLMMsgs/idl_generated_code/yarp/dev/llm/return_ask.cpp, src/devices/messages/ILLMMsgs/idl_generated_code/yarp/dev/llm/return_ask.h, src/devices/messages/ILLMMsgs/idl_generated_code/yarp/dev/llm/return_getConversation.cpp, src/devices/messages/ILLMMsgs/idl_generated_code/yarp/dev/llm/return_getConversation.h, src/devices/networkWrappers/LLM_nwc_yarp/LLM_nwc_yarp.cpp, src/devices/networkWrappers/LLM_nwc_yarp/LLM_nwc_yarp.h, src/devices/networkWrappers/LLM_nws_yarp/ILLMServerImpl.cpp, src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/idl/LLM_Message.thrift, src/libYARP_dev/src/idl_generated_code/LLM_Message_index.txt, src/libYARP_dev/src/idl_generated_code/yarp/dev/LLM_Message.cpp, src/libYARP_dev/src/idl_generated_code/yarp/dev/LLM_Message.h, src/libYARP_dev/src/yarp/dev/ILLM.h, src/libYARP_dev/src/yarp/dev/tests/ILLMTest.h, src/yarpllmgui/ConversationModel.cpp, src/yarpllmgui/ConversationModel.h
In this PR:
- Added a new data type [LLM_Message](src/libYARP_dev/src/idl/LLM_Message.thrift) to propagate the answer given by the LLM to our query 
- Necessary plumbing to make nws,nwc, fake device working
=> Added support for GPT "Functions"

doc/release/master.md, src/portmonitors/image_compression_ffmpeg/README.md, src/portmonitors/image_compression_ffmpeg/constants.h, src/portmonitors/image_compression_ffmpeg/ffmpegPortmonitor.cpp, src/portmonitors/image_compression_ffmpeg/ffmpegPortmonitor.h
With this PR it is possible to select all the encoders and decoders available with ``ffmpeg``. In order to do so, I had to allow specifying custom pixel formats, listing also all those available for each encoder/decoder. 
Moreover, I managed to fix a crash occurring when launching two port monitor instances.
I also added a utility to print the estimated bandwidth requested (it is a lower bound) and I made it work also in conjunction with ``yarp repeat``.
We are currently using it with the NVIDIA ``hevc`` codecs in both Windows and Linux.
cc @mebbaid @GiulioRomualdi @traversaro
=> Improvements on the `ffmpeg` port monitor to allow using different couples of coders/decodes

src/libYARP_os/tests/CMakeLists.txt, src/libYARP_os/tests/NetworkClockTest.cpp
I wanted to work on https://github.com/robotology/yarp/issues/3096, but I was unable to reproduce the problem. Anyhow, the test I setup to debug is nevertheless useful.
=> Add test for NetworkClock

src/libYARP_sig/src/yarp/sig/Sound.cpp, src/libYARP_sig/tests/SoundTest.cpp
fixed text serialization and copyPortable() of yarp::sig::Sound when using yarp read
=> yarp::sig:::Sound fix

doc/release/master.md, src/libYARP_sig/src/yarp/sig/SoundFileMp3.cpp, src/portmonitors/image_compression_ffmpeg/ffmpegPortmonitor.cpp
I based my modifications on the modifications done in `decode_audio` and `encode_audio` examples in ffmpeg, see the modifications in https://github.com/FFmpeg/FFmpeg/commit/f5ef91e02080316f50d606f5b0b03333bb627ed7 .
Note that `LIBAVCODEC_VERSION_MAJOR==61` corresponds to ffmpeg 7, see https://github.com/FFmpeg/FFmpeg/blob/n7.0/libavcodec/version_major.h#L28 .
=> SoundFileMp3 and ffmpegPortmonitor: Fix compatibility with ffmpeg 7

doc/release/master.md, src/carriers/portmonitor_carrier/CMakeLists.txt
Without this fix, the compilation with a custom non-system swig is failing. See https://github.com/Kitware/CMake/blob/v3.29.2/Modules/UseSWIG.cmake#L725 for similar code inside CMake. 
This is important for compatibility with Ubuntu 24.04 when using apt dependencies, as the swig that ships with Ubuntu 24.04 is swig 4.2.0, that is not compatible with YARP.
=> Do not ignore ${SWIG_DIR} when invoking ${SWIG_EXECUTABLE}

doc/001_installation/3_install.dox, doc/001_installation/3_install_conda.md, doc/001_installation/3_install_linux.md
This repository will be soon be offline, see https://github.com/orgs/robotology/discussions/653 .
See also:
* https://github.com/orgs/robotology/discussions/612
* https://github.com/icub-tech-iit/documentation/issues/261
=> Do not refer anymore to deb binary packages from icub.eu anymore

src/libYARP_serversql/src/yarp/serversql/impl/NameServerContainer.cpp
The message "Database needs to be reset, IP or port number set." is printed every time the `--ip` or `--socket` is passed, so it does not make sense to print as an error as it is printed even if everything is working as intended. This PR changes it from `yCError` to `yCInfo` .
This seems a regression from https://github.com/robotology/yarp/commit/d97ab7f6269b16b94b7187269918e41746eee5c8#diff-be8b39c3c66ca00e0f5ace04995b0d08fc83edaaff870d6d8d87dc349d7cc8a8R104 . Before that commit, the message was just printed on `stderr`, but not printed as an error.
=> NameServerContainer: do not print "database needs to be reset" message

doc/release/master.md, src/libYARP_sig/src/yarp/sig/Vector.cpp, src/libYARP_sig/tests/VectorOfTest.cpp
Before this PR, sending an empty yarp::sig::Vector on port in Debug mode resulted in a crash of the application attempting to do that:
~~~
(yarpdev) traversaro@IITBMP014LW012:~/pixiws/yarpdev/yarp/build$ ctest -R VectorOf -VV
UpdateCTestConfiguration  from :/home/traversaro/pixiws/yarpdev/yarp/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/traversaro/pixiws/yarpdev/yarp/build/DartConfiguration.tcl
Test project /home/traversaro/pixiws/yarpdev/yarp/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 73
Start 73: sig::VectorOfTest
73: Test command: /home/traversaro/pixiws/yarpdev/yarp/build/bin/harness_sig …
=> Fix sending empty yarp::sig::Vector when building in Debug

src/devices/fakeDepthCamera/CMakeLists.txt
The fakeDepthCamera had the old `RGBDCameraWrapper` instead of the `rgbdSensor_nws_yarp`, as such running `yarpdev --device fakeDepthCamera` resulted in an error.
=> Fix fakeDepthCamera wrapper

doc/release/master.md, extern/qgv/qgv/QGVCore/QGVScene.cpp, extern/qgv/qgv/QGVCore/QGVSubGraph.cpp
See:
* https://github.com/Gepetto/qgv/commit/b3dea28cc39e6fd07c142c2bee8b4376500f89ea
* https://github.com/gazebosim/gazebo-classic/pull/3373
for similar fixes.
=> Fix build with graphviz 10

src/libYARP_manager/src/yarp/manager/broker.h, src/libYARP_manager/src/yarp/manager/execstate.cpp, src/libYARP_manager/src/yarp/manager/executable.cpp, src/libYARP_manager/src/yarp/manager/localbroker.cpp, src/libYARP_manager/src/yarp/manager/localbroker.h, src/libYARP_manager/src/yarp/manager/scriptbroker.cpp, src/libYARP_manager/src/yarp/manager/scriptbroker.h, src/libYARP_manager/src/yarp/manager/yarpbroker.cpp, src/libYARP_manager/src/yarp/manager/yarpbroker.h, src/yarpmanager/src-manager/applicationviewwidget.cpp, src/yarpmanager/src-manager/mainwindow.cpp
Fix for: https://github.com/robotology/yarp/issues/3105
I'm aware that std::string is not a plain char*. 
..but do we need to stick to this oooooold '99 style in libyarpmanager? I think not.  
BTW, strings are used elsewhere in the same lib.
=> fixed dangling pointer using std::string

src/libYARP_os/src/yarp/os/impl/ThreadImpl.cpp
The printed error was always `Cannot set priority without ACE`, even if the reason was the error was actually something else.
=> Fix setPriority error messages

doc/release/master.md, src/devices/fake/fakeNavigationDevice/FakeNavigation.cpp, src/devices/fake/fakeNavigationDevice/FakeNavigation.h, src/devices/messages/INavigation2DMsgs/INavigation2DMsgs.thrift, src/devices/messages/INavigation2DMsgs/idl_generated_code/INavigation2DMsgs.cpp, src/devices/messages/INavigation2DMsgs/idl_generated_code/INavigation2DMsgs.h, src/devices/networkWrappers/navigation2D_nwc_yarp/Navigation2D_nwc_yarp.cpp, src/devices/networkWrappers/navigation2D_nwc_yarp/Navigation2D_nwc_yarp.h, src/devices/networkWrappers/navigation2D_nwc_yarp/Navigation2D_nwc_yarp_iNav2DTarget.cpp, src/devices/networkWrappers/navigation2D_nws_yarp/INavigation2DServerImpl.cpp, src/devices/networkWrappers/navigation2D_nws_yarp/INavigation2DServerImpl.h, src/libYARP_dev/src/yarp/dev/INavigation2D.h
This PR introduces the interfaces to navigate by using the name of a predefined path specified in locations.ini file. There is a related PR in navigation to provide an implementation of the interface using nav2 https://github.com/robotology/navigation/pull/77
- followPath interface to Navigation2D
- gotoTargetByLocationName also navigates to path
=> Navigation through path

src/libYARP_dev/src/CMakeLists.txt, src/libYARP_sig/src/CMakeLists.txt
Added install of header files generated by thtift in yarp_sig
=> Fixed installation of yarp_sig header files

doc/release/master.md, src/devices/CMakeLists.txt, src/devices/portaudio/DEPRECATION_NOTICE.TXT, src/devices/portaudio/PortAudioBuffer.h, src/devices/portaudio/PortAudioDeviceDriver.cpp, src/devices/portaudio/PortAudioDeviceDriver.h
Portaudio device, previously marked as deprecated, has been definitely removed from devices' CMakeLists.txt
=> removed deprecated device Portaudio

src/devices/portaudioPlayer/PortAudioPlayerDeviceDriver.cpp, src/devices/portaudioPlayer/PortAudioPlayerDeviceDriver_ParamsParser.cpp, src/devices/portaudioPlayer/PortAudioPlayerDeviceDriver_ParamsParser.h, src/devices/portaudioPlayer/PortAudioPlayerDeviceDriver_params.md, src/devices/portaudioRecorder/PortAudioRecorderDeviceDriver.cpp, src/devices/portaudioRecorder/PortAudioRecorderDeviceDriver_ParamsParser.cpp, src/devices/portaudioRecorder/PortAudioRecorderDeviceDriver_ParamsParser.h, src/devices/portaudioRecorder/PortAudioRecorderDeviceDriver_params.md
Replaced parameter "id" in portaudioPlayer, portaudioRecorder with "a…udio_device_id" because "id" and "device_id" are keywords reserved by yarprobotinterface.
Additionally a new print now shows the name of the selected interface.
=> Fix for portaudioRecorder, portaudioPlayer device ID selection

bindings/python/CMakeLists.txt, bindings/yarp.i, doc/release/master.md
Since Python 3.8, Python ignores the `PATH` env variable when trying to load the DLL of compiled Python extensions. 
We kind ignored the problem until now as if you install in `%CONDA_PREFIX%\Library\bin` in conda environment everything works out of the box, but the problem is present when bipedal-locomotion-framework is installed in an arbitrary install prefix and the Python bindings are found via `PYTHONPATH` env variable, see https://github.com/robotology/robotology-superbuild/issues/1268 .
This PR fixes the problem by adding some automatically generated code in the `__init__.py` file that automatically calls `os.add_dll_directory` as necessary.
As the Python code is generated by CMake it may be a bit cryptic, the actual rendered code is:
~~~py
import os
library_dll_path = …
=> Fix loading of Python bindings on Windows when installed in arbitrary directory

src/devices/fake/fakeFrameGrabber/FakeFrameGrabber.cpp, src/devices/fake/fakeFrameGrabber/FakeFrameGrabber_ParamsParser.cpp, src/devices/fake/fakeFrameGrabber/FakeFrameGrabber_ParamsParser.h, src/devices/fake/fakeFrameGrabber/FakeFrameGrabber_params.md, src/libYARP_sig/src/yarp/sig/Image.cpp, src/libYARP_sig/src/yarp/sig/Image.h, src/libYARP_sig/src/yarp/sig/ImageNetworkHeader.h, src/libYARP_sig/tests/ImageTest.cpp, src/yarpview/plugin/ImagePort.cpp
The following methods:
```
bool topIsLowIndex() const
void setTopIsLowIndex(bool flag);
```
have been removed from yarp::sig::Image
=> Removed topIsLow in yarp image

doc/release/master.md, src/carriers/shmem_carrier/ShmemInputStream.cpp, src/carriers/shmem_carrier/ShmemInputStream.h, src/devices/networkWrappers/multipleanalogsensorsclient/MultipleAnalogSensorsClient.cpp
In the context of walking, inside the `ergocub-torso` we are interested in establishing connection that continue to run even if the network interface over which they are established temporary goes down. The rationale for this is that at the moment in most demos we run the `yarpserver` in the operator laptop and the walking and the robot robotinterface inside the `ergocub-torso` board embedded in the robot, and while walking the robot could loose the connection with the operator laptop where the yarpserver is running.
To do so, we experimented with using `shmem` and `unix_stream` carriers, experiencing the following problems:
* For `shmem`, sometimes there was a segfault on one of the two sides of the connection when the shmem connection was disconnected.
* For `unix_stream`, it was not …
=> Fix use of shmem and unix_stream carriers in remote_controlboard and multipleanalogsensorclient network wrapper clients

bindings/CMakeLists.txt, bindings/yarp.i
In https://github.com/robotology/yarp/pull/3146 there was a regression, as a new file `swig_python_windows_preable.i` was included in the `yarp.i` and it was generated by CMake in its binary directory. However, that file is not supposed to be included (and it is not even availble in the include path) when a downstream project (like `icub-main`) includes the file in its own `.i` swig binding file.
This PR fixes the issue by only including the file when `yarp.i` is used to generate the yarp bindings, and not when the `yarp.i` is included in a downstream project, by checking if the `SWIG_GENERATING_YARP_BINDINGS` preprocessor macro (that is only defined in the CMake build of YARP bindings) is defined.
Fix https://github.com/robotology/icub-main/issues/992 .
=> Fix compilation of downstream bindings that include yarp.i

example/dev/RGBD/README.md, example/dev/RGBD/RGBD_test_1b_server.cpp, src/devices/openNI2DepthCamera/depthCameraDriver.h
The `RGBDSensorWrapper` device was deprecated in YARP 3.5 and removed in YARP 3.8 (see https://github.com/robotology/yarp/commit/4da405c7fb077b4604029fd87e4e51a633e2d7eb) and it has been substituted by `rgbdSensor_nws_yarp`. Note that the corresponding network wrapper client (`nwc`) device that reads the rgbd data from a YARP port is called `RGBDSensorClient`.
However, there was still docs that was referring to `RGBDSensorWrapper`, this PR fixes those occurrences.
fyi @nicktrem @davidegorbani
=> Change references from RGBDSensorWrapper to rgbdSensor_nws_yarp

src/devices/fake/fakeMotionControl/FakeMotionControl.cpp, src/devices/fake/fakeMotionControl/FakeMotionControl.h
added valid timestamp to FakeMotionControl encoders
=> FakeMotionControl encoders timestamps

src/libYARP_companion/src/yarp/companion/impl/BottleReader.h, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdRead.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.cmdReadWrite.cpp, src/libYARP_companion/src/yarp/companion/impl/Companion.h
the command `yarp read ... /port envelope` now displays the envelope inline with the data, while the command `yarp read ... /port envelope2` displays the envelope and the data on two different lines
=> yarp read and envelope display

doc/release/master.md, src/libYARP_sig/src/CMakeLists.txt, src/libYARP_sig/src/yarp/sig/Image.cpp, src/libYARP_sig/src/yarp/sig/ImageNetworkHeader.h, src/libYARP_sig/src/yarp/sig/ImageUtils.cpp, src/libYARP_sig/src/yarp/sig/ImageUtils.h, src/libYARP_sig/src/yarp/sig/LayeredImage.cpp, src/libYARP_sig/src/yarp/sig/LayeredImage.h, src/libYARP_sig/tests/CMakeLists.txt, src/libYARP_sig/tests/LayeredImageTest.cpp, src/yarpopencvdisplay/main.cpp
- added new datatype `yarp::sig::LayeredImage` with test
- modified yarpopencvdisplay to support `yarp::sig::LayeredImage` 
- added `yarp::sig::utils::sum()` to transform a`yarp::sig::LayeredImage` to `yarp::sig::Image`
=> Layered Image

src/libYARP_sig/src/yarp/sig/Vector.h, src/libYARP_sig/tests/VectorTest.cpp
Added erase() method to yarp::sig::Vector
=> yarp::sig::Vector::erase()

.github/workflows/ci.yml, bindings/yarp.i
SWIG_STD_VECTOR_SPECIALIZE_MINIMUM is not more used with swig 4.2.1
=> fix for c# with swig version 4.2.1

src/devices/networkWrappers/multipleanalogsensorsserver/MultipleAnalogSensorsServer.cpp, src/devices/networkWrappers/multipleanalogsensorsserver/MultipleAnalogSensorsServer.h
MultipleAnalogSensorServer now derives yarp::dev::WrapperSingle instead of yarp::dev::IMultipleWrapper
https://github.com/robotology/yarp/issues/3152
=> MultipleAnalogSensorServer fix

src/devices/frameTransformClient/FrameTransformClient.cpp, src/devices/frameTransformClient/FrameTransformClient.h, src/devices/frameTransformGet/FrameTransformGetMultiplexer.cpp, src/devices/frameTransformGet/FrameTransformGetMultiplexer.h, src/devices/frameTransformGet/FrameTransformGet_nwc_yarp.cpp, src/devices/frameTransformGet/FrameTransformGet_nwc_yarp.h, src/devices/frameTransformGet/FrameTransformGet_nws_yarp.cpp, src/devices/frameTransformSet/FrameTransformSetMultiplexer.cpp, src/devices/frameTransformSet/FrameTransformSetMultiplexer.h, src/devices/frameTransformSet/FrameTransformSet_nwc_yarp.cpp, src/devices/frameTransformSet/FrameTransformSet_nwc_yarp.h, src/devices/frameTransformSet/FrameTransformSet_nws_yarp.cpp, src/devices/frameTransformSet/FrameTransformSet_nws_yarp.h, src/devices/frameTransformStorage/FrameTransformStorage.cpp, src/devices/frameTransformStorage/FrameTransformStorage.h, src/devices/messages/frameTransformStorageMsgs/CMakeLists.txt, src/devices/messages/frameTransformStorageMsgs/frameTransformStorageMsgs.thrift, src/devices/messages/frameTransformStorageMsgs/idl_generated_code/FrameTransformStorageSetRPC.cpp, src/devices/messages/frameTransformStorageMsgs/idl_generated_code/FrameTransformStorageSetRPC.h, src/devices/messages/frameTransformStorageMsgs/idl_generated_code/return_getAllTransforms.cpp, src/devices/messages/frameTransformStorageMsgs/idl_generated_code/return_getAllTransforms.h, src/libYARP_dev/src/yarp/dev/FrameTransformContainer.cpp, src/libYARP_dev/src/yarp/dev/FrameTransformContainer.h, src/libYARP_dev/src/yarp/dev/IFrameTransform.h, src/libYARP_dev/src/yarp/dev/IFrameTransformStorage.h, src/libYARP_dev/src/yarp/dev/ReturnValue.cpp, src/libYARP_dev/src/yarp/dev/ReturnValue.h, src/libYARP_dev/src/yarp/dev/tests/IFrameTransformTest.h
sequel of https://github.com/robotology/yarp/pull/3167.
All frameTransform interfaces/devices have been updated to use yarp::dev::ReturnValue
=> New class for return values of interface methods PART3

doc/release/master.md
See discussion in https://github.com/robotology/yarp/pull/3169#issuecomment-2627626286 .
=> Document breaking changes to IFrameTransform methods in YARP 3.11.0

doc/release/master.md, src/guis/yarpmanager/src-manager/clusterWidget.cpp, src/guis/yarpmanager/src-manager/clusterWidget.h, src/guis/yarpmanager/src-manager/main.cpp, src/guis/yarpmanager/src-manager/mainwindow.cpp, src/libYARP_manager/src/yarp/manager/utility.cpp, src/libYARP_manager/src/yarp/manager/utility.h, src/yarpmanager-console/ymanager.cpp
* Added time info to `libYARP_manager` logger and to `yarpmanager` GUI.
* The time info can be displayed as the current time (obtained from `std::chrono::system_clock::now()`) or as time elapsed since yarpmanager GUI launch
This PR aims to address this particular issue: #3120
=> Feature: `yarpmanager` log messages time stamp

CMakeLists.txt, doc/release/yarp_3_11/000_yarp_3_11.md, src/libYARP_companion/src/CMakeLists.txt, src/libYARP_conf/src/CMakeLists.txt, src/libYARP_cv/src/CMakeLists.txt, src/libYARP_dataplayer/src/CMakeLists.txt, src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/yarp/dev/ReturnValue.h, src/libYARP_eigen/src/CMakeLists.txt, src/libYARP_gsl/src/CMakeLists.txt, src/libYARP_init/src/CMakeLists.txt, src/libYARP_logger/src/CMakeLists.txt, src/libYARP_manager/src/CMakeLists.txt, src/libYARP_math/src/CMakeLists.txt, src/libYARP_name/src/CMakeLists.txt, src/libYARP_os/src/CMakeLists.txt, src/libYARP_pcl/src/CMakeLists.txt, src/libYARP_profiler/src/CMakeLists.txt, src/libYARP_robotinterface/src/CMakeLists.txt, src/libYARP_robottestingframework/src/CMakeLists.txt, src/libYARP_run/src/CMakeLists.txt, src/libYARP_serversql/src/CMakeLists.txt, src/libYARP_sig/src/CMakeLists.txt, tests/CMakeLists.txt, tests/header_smoke_test/CMakeLists.txt, tests/header_smoke_test/header_smoke_test.cpp
As discussed in a meeting with @randaz81, @elandini84  and @Nicogene, in the short term to avoid downstream problems it is convenient to keep at least the header of YARP compatible with C++ 17 . 
This is not a long term decision, and in future the minimum C++ version required to compile headers could be increased again.
=>  Restore compatibility with C++17 in public headers 

extern/tinyxml/CMakeLists.txt
For TinyXML (1), the CMake project/package name that we use is `TinyXML`, for example also in ycm-cmake-modules there is a `FindTinyXML.cmake` file. This is different from tinyxml2 (that ideally at some point we should migrate to), where the CMake project/package name is `tinyxml2`. So it make sense that also the vendored CMake package is called `YARP_priv_TinyXML`, not `YARP_priv_tinyxml`.
Fix https://github.com/robotology/yarp/issues/3197 .
Fix https://github.com/robotology/yarp/issues/2512 .
@vmartinlac can you check if this change works for you? Thanks! This PR is targeting `yarp-3.11`, but this file was not changed in years, so I think the patch should apply in a clean way to older releases.
=> Rename vendored TinyXML cmake project and package from YARP_priv_tinyxml to YARP_priv_TinyXML

src/libYARP_init/src/CMakeLists.txt
The `CustomInit.cpp` file was renamed in https://github.com/robotology/yarp/commit/3eb97000f57d388bc746e7304eb46de1c2c0e1b0#diff-e26e6136eee05544fca0d9360616145d09f0910dff53c12cbd8c046c0790fb5a (part of https://github.com/robotology/yarp/pull/2123, a ~1000 files modified PR that apparently I approved :D ) but the CMake code that referred to it was not modified. In this PR, we fix this and avoid to define the name of the file in multiple places.
=> Fix set_property of non-existant CustomInit.cpp file

doc/release/yarp_3_11/000_yarp_3_11.md, src/devices/fake/fakeLaserWithMotor/FakeLaserWithMotor.cpp, src/devices/laserFromExternalPort/laserFromExternalPort.cpp, src/devices/laserFromExternalPort/laserFromExternalPort.h, src/devices/networkWrappers/AnalogSensorClient/AnalogSensorClient.cpp, src/devices/networkWrappers/AnalogSensorClient/AnalogSensorClient.h, src/devices/networkWrappers/Rangefinder2D_nwc_yarp/Rangefinder2D_nwc_yarp.cpp, src/devices/networkWrappers/Rangefinder2D_nwc_yarp/Rangefinder2D_nwc_yarp.h, src/devices/networkWrappers/audioRecorder_nwc_yarp/AudioRecorder_nwc_yarp.cpp, src/devices/networkWrappers/audioRecorder_nwc_yarp/AudioRecorder_nwc_yarp.h, src/devices/networkWrappers/audioRecorder_nws_yarp/AudioRecorder_nws_yarp.cpp, src/devices/networkWrappers/audioRecorder_nws_yarp/AudioRecorder_nws_yarp.h, src/devices/networkWrappers/battery_nwc_yarp/Battery_nwc_yarp.cpp, src/devices/networkWrappers/battery_nwc_yarp/Battery_nwc_yarp.h, src/devices/networkWrappers/chatBot_nws_yarp/ChatBot_nws_yarp.cpp, src/devices/networkWrappers/chatBot_nws_yarp/ChatBot_nws_yarp.h, src/devices/networkWrappers/mobileBaseVelocityControl_nws_yarp/MobileBaseVelocityControl_nws_yarp.cpp, src/devices/networkWrappers/mobileBaseVelocityControl_nws_yarp/MobileBaseVelocityControl_nws_yarp.h, src/devices/networkWrappers/serialPort_nws_yarp/SerialPort_nws_yarp.cpp, src/devices/networkWrappers/serialPort_nws_yarp/SerialPort_nws_yarp.h, src/devices/networkWrappers/speechSynthesizer_nws_yarp/SpeechSynthesizer_nws_yarp.cpp, src/devices/networkWrappers/speechSynthesizer_nws_yarp/SpeechSynthesizer_nws_yarp.h, src/devices/networkWrappers/speechTranscription_nws_yarp/SpeechTranscription_nws_yarp.cpp, src/devices/networkWrappers/speechTranscription_nws_yarp/SpeechTranscription_nws_yarp.h, src/portmonitors/bottle_compression_zlib/BottleZlibPortmonitor.cpp, src/portmonitors/image_compression_ffmpeg/ffmpegPortmonitor.cpp, src/portmonitors/image_rotation/imageRotation.cpp, src/portmonitors/sound_marker/Sound_marker.cpp, src/portmonitors/soundfilter_resample/SoundFilter_resample.cpp
Fixed the generation of the plugins static library.
Renamed symbols with the same name used by different devices/portmonitors
=> Fix for static builds: avoiding multiple symbols definitions

bindings/yarp.i
After https://github.com/robotology/yarp/pull/3169 these two methods could not be used anymore in the python bindings since they edit an input parameter by reference
=> Added methods canTransform and frameExists in bindings.

doc/release/yarp_3_11/000_yarp_3_11.md, src/libYARP_sig/src/yarp/sig/Sound.cpp
Since `m_frequency` is an integer, dividing the unit by this number was always yielding zero. Either the unit or this variable must be converted to a floating point type to get the correct result.
=> Fix `Sound::getDuration()` always returning zero

doc/release/yarp_3_11/000_yarp_3_11.md, src/libYARP_dev/src/yarp/dev/ReturnValue.cpp
Fixed `yarp::dev::ReturnValue` serialization when used from command line (e.g. yarp rpc /xxx)
=> ReturnValue fix

src/libYARP_robotinterface/src/yarp/robotinterface/Device.cpp
robotinterface logs are always full of messages "is not an IWrapper. Trying IMultipleWrapper"
~~~
[INFO] Executing attach action, level 5 on device left_arm-mc_remapper with parameters [("networks" = "(left_arm_joints1)"), ("left_arm_joints1" = "left_arm_hardware_device")]
[INFO] left_arm-mc_remapper is not an IWrapper. Trying IMultipleWrapper
[INFO] Executing attach action, level 5 on device right_arm-mc_remapper with parameters [("networks" = "(right_arm_joints1)"), ("right_arm_joints1" = "right_arm_hardware_device")]
[INFO] right_arm-mc_remapper is not an IWrapper. Trying IMultipleWrapper
[INFO] Executing attach action, level 5 on device left_leg-mc_remapper with parameters [("networks" = "(left_leg_joints1)"), ("left_leg_joints1" = "left_leg_hardware_device")]
[INFO] …
=> robotinterface: Do not print a message if a device does not derive from IWrapper

doc/release/master.md, src/devices/networkWrappers/LLM_nwc_yarp/LLM_nwc_yarp.cpp, src/devices/networkWrappers/audioRecorder_nwc_yarp/AudioRecorder_nwc_yarp.cpp, src/devices/networkWrappers/battery_nwc_yarp/Battery_nwc_yarp.cpp, src/devices/networkWrappers/chatBot_nwc_yarp/ChatBot_nwc_yarp.cpp, src/devices/networkWrappers/frameGrabber_nwc_yarp/FrameGrabber_nwc_yarp.cpp, src/devices/networkWrappers/frameTransformGet_nwc_yarp/FrameTransformGet_nwc_yarp.cpp, src/devices/networkWrappers/frameTransformSet_nwc_yarp/FrameTransformSet_nwc_yarp.cpp, src/devices/networkWrappers/localization2D_nwc_yarp/Localization2D_nwc_yarp.cpp, src/devices/networkWrappers/map2D_nwc_yarp/Map2D_nwc_yarp.cpp, src/devices/networkWrappers/mobileBaseVelocityControl_nwc_yarp/MobileBaseVelocityControl_nwc_yarp.cpp, src/devices/networkWrappers/navigation2D_nwc_yarp/Navigation2D_nwc_yarp.cpp, src/devices/networkWrappers/odometry2D_nwc_yarp/Odometry2D_nwc_yarp.cpp, src/devices/networkWrappers/rangefinder2D_nwc_yarp/Rangefinder2D_nwc_yarp.cpp, src/devices/networkWrappers/robotDescription_nwc_yarp/RobotDescription_nwc_yarp.cpp, src/devices/networkWrappers/serialPort_nwc_yarp/SerialPort_nwc_yarp.cpp, src/devices/networkWrappers/speechSynthesizer_nwc_yarp/SpeechSynthesizer_nwc_yarp.cpp, src/devices/networkWrappers/speechTranscription_nwc_yarp/SpeechTranscription_nwc_yarp.cpp
This PR will break compatibility with NWS belonging to YARP versions < 4
Requires https://github.com/robotology/yarp/pull/3219
=> NWCs with protocol check

src/devices/networkWrappers/RemoteControlBoard/RemoteControlBoard.cpp, src/devices/networkWrappers/RemoteControlBoard/stateExtendedReader.cpp, src/devices/networkWrappers/controlBoard_nws_yarp/ControlBoard_nws_yarp.cpp, src/devices/networkWrappers/controlBoard_nws_yarp/ControlBoard_nws_yarp.h, src/libYARP_dev/src/idl/stateExt.thrift, src/libYARP_dev/src/idl_generated_code/yarp/dev/impl/jointData.cpp, src/libYARP_dev/src/idl_generated_code/yarp/dev/impl/jointData.h, src/libYARP_sig/src/yarp/sig/Vector.cpp, src/libYARP_sig/src/yarp/sig/Vector.h
After a discussion with @randaz81 and @traversaro, we decided to add motor temperature data to `stateExt`, streamed as a vector of floats. To avoid increasing the message size, we also decided to convert the PWM data from a vector of doubles to a vector of floats.  
This pull request introduces several changes to the `RemoteControlBoard` and related components to support temperature data. The modifications affect data structures, methods, and interfaces to handle temperature readings properly.  
The PR consists of two commits:  
- https://github.com/robotology/yarp/commit/e889527bc308ef3636dc727a414619af80399c2b: Modifies the message to add temperature data and converts the PWM vector to float.  
- https://github.com/robotology/yarp/commit/a435ecd640f4324df705e75c08a6a2ef568e596d: Adds …
=> Add Motor Temperature to stateExt and Convert PWM to Float

doc/release/master.md, src/libYARP_sig/src/yarp/sig/Image.copyPixels.cpp, src/libYARP_sig/src/yarp/sig/Image.cpp, src/libYARP_sig/src/yarp/sig/Image.h, src/libYARP_sig/src/yarp/sig/ImageNetworkHeader.h, src/libYARP_sig/src/yarp/sig/impl/IplImage.cpp, src/libYARP_sig/src/yarp/sig/impl/IplImage.h
Removed field `topIsLow` from `yarp::sig::Image`
=> Image cleanup

bindings/python/CMakeLists.txt
Follow-up to https://github.com/robotology/yarp/pull/3247 (cc @PasMarra). I noticed this warning during the CMake configuration step:
```
CMake Warning:
Value of CMAKE_INSTALL_PYTHON3DIR contained a newline; truncating
```
This means that the output of:
https://github.com/robotology/yarp/blob/d046789b8ffceb85292957ef0a2881a2b72de692/bindings/python/CMakeLists.txt#L49-L50
contains a trailing newline. I replicated this code on a different project, hit the same warning, and observed the following glitch on `cmake --install` ([CI run](https://github.com/roboticslab-uc3m/vision/actions/runs/16393021350)):
```
-- Installing: /usr/local/lib/python3.12/dist-packages
/roboticslab_vision.py
-- Installing: /usr/local/lib/python3.12/dist-packages
/_roboticslab_vision.so
```
Due to the presence of …
=> Strip trailing newline from `CMAKE_INSTALL_PYTHON3DIR`

bindings/yarp.i, src/libYARP_dev/src/yarp/dev/ReturnValue.h
This avoids "swig/python detected a memory leak of type 'yarp::dev::ReturnValue *', no destructor found." when using interfaces that have been migrated to [`yarp::dev::ReturnValue`](https://github.com/robotology/yarp/blob/ce8ff4c8c1c5245a9242196bc3a17eebde05d69d/src/libYARP_dev/src/yarp/dev/ReturnValue.h) (https://github.com/robotology/yarp/discussions/3168). Parts that did not compile successfully have been enclosed in `SWIG_PREPROCESSOR_SHOULD_SKIP_THIS` guards.
=> Register bindings for `yarp::dev::ReturnValue`

bindings/yarp.i
This patch also enables invoking `yarp::dev::ILLM::getConversation` through the new `LLMVector` specialization of `std::vector<yarp::dev::LLM_Message>`.
Python usage:
```py
llm = device.viewILLM()
question = 'What is 2 + 2?';
answer = yarp.LLM_Message()
print(f'Asking: {question}')
if llm.ask(question, answer):
print('Answer:')
print(f'* type: {answer.type}')
print(f'* content: {answer.content}')
print(f'* parameters: {list(answer.parameters)}')
print(f'* arguments: {list(answer.arguments)}')
conversation = yarp.LLMVector()
if llm.getConversation(conversation):
for msg in conversation:
print(msg.toString_c())
```
Besides, it was no longer necessary to extend `yarp::dev::ILLM::ask`, so I removed that.
=> Add bindings for `yarp::dev::LLM_Message`

src/libYARP_logger/CMakeLists.txt, src/libYARP_logger/src/yarp/logger/YarpLogger.cpp, src/libYARP_logger/tests/CMakeLists.txt, src/libYARP_logger/tests/LogForwarderTest.cpp, src/libYARP_os/src/yarp/os/impl/LogForwarder.cpp, src/libYARP_os/src/yarp/os/impl/LogForwarder.h, src/portmonitors/CMakeLists.txt, src/portmonitors/depthimage_to_mono/CMakeLists.txt, src/portmonitors/depthimage_to_rgb/CMakeLists.txt, src/portmonitors/depthimage_to_vector/CMakeLists.txt, src/portmonitors/segmentationimage_to_rgb/CMakeLists.txt, src/portmonitors/sensorMeasurements_to_vector/CMakeLists.txt, src/portmonitors/simulated_network_delay/CMakeLists.txt, src/portmonitors/simulated_network_delay/README.md, src/portmonitors/simulated_network_delay/Simulated_network_delay.cpp, src/portmonitors/simulated_network_delay/Simulated_network_delay.h
Added new test LogForwarderTest to check that all forwarded messages are caught by the logger engine.
Added new portmonitor 'simulated_network_delay' to test the logger under various network delay conditions
NB: CI is supposed to fail after this commit (it will be fixed by PR https://github.com/robotology/yarp/pull/2789)
=> Logforwarder test + simulated_network_delay portmonitor

src/devices/controlBoardRemapper/tests/controlBoardRemapper_t2_test.cpp, src/devices/fake/fakeMotionControl/FakeMotionControl.cpp, src/devices/fake/fakeMotionControl/FakeMotionControl.h, src/devices/fake/fakeMotionControl/tests/fakeMotionControl_test.cpp, src/devices/networkWrappers/RemoteControlBoard/tests/RemoteControlBoard_test.cpp, src/guis/yarpmotorgui/partitem.cpp, src/guis/yarpmotorgui/partitem.h, src/guis/yarpmotorgui/piddlg.cpp, src/guis/yarpmotorgui/piddlg.h, src/libYARP_dev/src/yarp/dev/tests/CMakeLists.txt, src/libYARP_dev/src/yarp/dev/tests/IImpedanceControlTest.cpp, src/libYARP_dev/src/yarp/dev/tests/IImpedanceControlTest.h
Added new tests to check IImpedanceControl interface.
Improved yarpmotorgui to handle forceOffset of IImpedanceControl interface: the value is sent only if the value in the table is changed.
Fixes: https://github.com/robotology/yarp/issues/3119
=> Improvements to IImpendaceControl interface

src/libYARP_dev/src/CMakeLists.txt, src/libYARP_dev/src/yarp/dev/IJacobianCoupling.cpp, src/libYARP_dev/src/yarp/dev/IJacobianCoupling.h
It needs the destructor definition in the .cpp. It fixes #3278
=> IJacobianCoupling: fix linker error under windows
